import { SHOWCASE_STATIC_DEMO_RUN_ID } from "@/lib/showcase-static-demo";

/** Pathnames emitted in `app/sitemap.ts`. Prefix "/", no trailing slash. */
export const MARKETING_SITEMAP_PATHNAMES: readonly string[] = [
  "/welcome",
  "/pricing",
  "/why",
  "/see-it",
  "/trust",
  "/privacy",
  "/accessibility",
  "/security-trust",
  "/compliance-journey",
  "/signup",
  "/signup/verify",
  "/quick-start",
  "/get-started",
  "/example-roi-bulletin",
  `/showcase/${SHOWCASE_STATIC_DEMO_RUN_ID}`,
];

/**
 * Paths we ask generic crawlers to skip — operator shell, API-style routes, funnel auth, noindex previews.
 * Do not list "/" alone (RFC-style prefix rules would disallow the entire host).
 */
export const MARKETING_ROBOTS_DISALLOW_PREFIXES: readonly string[] = [
  "/auth/",
  "/api/",
  "/reviews/",
  "/runs/",
  "/manifests/",
  "/why-archlucid",
  "/compare",
  "/replay",
  "/executive/",
  "/alerts/",
  "/admin/",
  "/settings/",
  "/graph",
  "/governance/",
  "/governance-resolution/",
  "/onboard",
  "/onboarding/",
  "/planning/",
  "/policy-packs/",
  "/product-learning/",
  "/recommendation-learning/",
  "/digest-subscriptions/",
  "/advisory",
  "/advisory-scheduling",
  "/integrations/",
  "/help",
  "/search",
  "/scorecard",
  "/ask",
  "/demo/",
  "/getting-started",
  "/evolution-review",
  "/audit",
  "/value-report",
  "/digests",
  "/workspace",
  "/v1",
  "/v2",
  "/health",
  "/openapi/",
  "/swagger/",
  "/scalar/",
  "/metrics",
  "/live-demo",
];
