import type { ProductLineId } from "@/lib/product-line/product-line-id";

export const PRODUCT_LINE_DISPLAY_NAME: Record<ProductLineId, string> = {
  architecture: "ArchLucid",
  security: "SecureNow",
};

export function productLineDisplayName(productLineId: ProductLineId): string {
  return PRODUCT_LINE_DISPLAY_NAME[productLineId];
}

/** SecureNow is text-only — do not render the ArchLucid SVG mark in that shell. */
export function productLineShowsArchLucidMark(productLineId: ProductLineId): boolean {
  return productLineId !== "security";
}

export function productLinePoweredByLine(productLineId: ProductLineId): string {
  return `Powered by ${productLineDisplayName(productLineId)}`;
}

export function productLineWordmarkAriaLabel(productLineId: ProductLineId): string {
  return `${productLineDisplayName(productLineId)} — go to workspace overview`;
}

export function productLineAuthWelcomeAriaLabel(productLineId: ProductLineId): string {
  return `${productLineDisplayName(productLineId)} — welcome`;
}

export function productLineDocumentTitle(productLineId: ProductLineId): string {
  return `${productLineDisplayName(productLineId)} workspace`;
}

export function productLineTitleTemplate(productLineId: ProductLineId): string {
  return `%s · ${productLineDisplayName(productLineId)}`;
}

export function productLineTransientFailureTimeoutTitle(productLineId: ProductLineId): string {
  return `${productLineDisplayName(productLineId)} is taking longer than expected`;
}

export function productLineTransientFailureUnavailableTitle(productLineId: ProductLineId): string {
  return `${productLineDisplayName(productLineId)} is temporarily unavailable`;
}

export function productLineTransientFailureFooter(
  productLineId: ProductLineId,
  statusLabel: "TIMEOUT" | "UNAVAILABLE",
): string {
  return `${productLineDisplayName(productLineId)} · ${statusLabel}`;
}

export function accessDeniedHeading(productLineId: ProductLineId): string {
  return `You don't have access to ${productLineDisplayName(productLineId)} yet`;
}

export function accessDeniedBody(productLineId: ProductLineId): string {
  const displayName = productLineDisplayName(productLineId);

  return `You're signed in, but your account has not been assigned a ${displayName} app role for this tenant. Ask your administrator to assign access, then sign in again.`;
}

export function accessDeniedSupplementCopy(
  productLineId: ProductLineId,
  message: "missing-role" | "wrong-tenant",
): string {
  const displayName = productLineDisplayName(productLineId);

  if (message === "missing-role") {
    return `No ${displayName} app role was found for this account.`;
  }

  return "This account is not authorized for the selected tenant.";
}

export function accessDeniedMailtoSubject(productLineId: ProductLineId): string {
  return `${productLineDisplayName(productLineId)} access request`;
}

export function productLinePasswordlessExplanation(productLineId: ProductLineId): string {
  const displayName = productLineDisplayName(productLineId);

  return `${displayName} does not use a product password. Sign in with a work or school account or a one-time email code.`;
}

export function productLineEvaluationSignupLead(productLineId: ProductLineId): string {
  return `New to ${productLineDisplayName(productLineId)}?`;
}

export function productLineGeneratedByLine(productLineId: ProductLineId): string {
  return `Generated by ${productLineDisplayName(productLineId)}`;
}
