import { describe, expect, it } from "vitest";

import {
  PRODUCT_LINE_DISPLAY_NAME,
  accessDeniedBody,
  accessDeniedHeading,
  accessDeniedMailtoSubject,
  accessDeniedSupplementCopy,
  localizeProductCopy,
  productLineAuthWelcomeAriaLabel,
  productLineDisplayName,
  productLineDocumentTitle,
  productLineEvaluationSignupLead,
  productLineGeneratedByLine,
  howProductWorksTitle,
  usingProductTitle,
  productLineManagedIdentityObjectIdLabel,
  productLinePasswordlessExplanation,
  productLinePoweredByLine,
  productLineTenantIdLabel,
  productLineTitleTemplate,
  productLineTransientFailureFooter,
  productLineTransientFailureTimeoutTitle,
  productLineTransientFailureUnavailableTitle,
  productLineWordmarkAriaLabel,
} from "@/lib/product-line/product-line-display-name";

describe("productLineDisplayName", () => {
  it("maps architecture to ArchLucid and security to SecureNow", () => {
    expect(PRODUCT_LINE_DISPLAY_NAME.architecture).toBe("ArchLucid");
    expect(PRODUCT_LINE_DISPLAY_NAME.security).toBe("SecureNow");
    expect(productLineDisplayName("architecture")).toBe("ArchLucid");
    expect(productLineDisplayName("security")).toBe("SecureNow");
  });
});

describe("product line chrome copy", () => {
  it("builds architecture chrome strings", () => {
    expect(productLineWordmarkAriaLabel("architecture")).toBe("ArchLucid — go to workspace overview");
    expect(productLineAuthWelcomeAriaLabel("architecture")).toBe("ArchLucid — welcome");
    expect(productLineDocumentTitle("architecture")).toBe("ArchLucid workspace");
    expect(productLineTitleTemplate("architecture")).toBe("%s · ArchLucid");
    expect(productLinePoweredByLine("architecture")).toBe("Powered by ArchLucid");
    expect(productLineGeneratedByLine("architecture")).toBe("Generated by ArchLucid");
  });

  it("builds security chrome strings", () => {
    expect(productLineWordmarkAriaLabel("security")).toBe("SecureNow — go to workspace overview");
    expect(productLineAuthWelcomeAriaLabel("security")).toBe("SecureNow — welcome");
    expect(productLineDocumentTitle("security")).toBe("SecureNow workspace");
    expect(productLineTitleTemplate("security")).toBe("%s · SecureNow");
    expect(productLinePoweredByLine("security")).toBe("Powered by SecureNow");
    expect(productLineGeneratedByLine("security")).toBe("Generated by SecureNow");
    expect(howProductWorksTitle("security")).toBe("How SecureNow works");
    expect(usingProductTitle("security")).toBe("Using SecureNow");
  });

  it("builds architecture help hub titles", () => {
    expect(howProductWorksTitle("architecture")).toBe("How ArchLucid works");
    expect(usingProductTitle("architecture")).toBe("Using ArchLucid");
  });
});

describe("product line recovery copy", () => {
  it("names ArchLucid in architecture outage surfaces", () => {
    expect(productLineTransientFailureTimeoutTitle("architecture")).toBe(
      "ArchLucid is taking longer than expected",
    );
    expect(productLineTransientFailureUnavailableTitle("architecture")).toBe(
      "ArchLucid is temporarily unavailable",
    );
    expect(productLineTransientFailureFooter("architecture", "TIMEOUT")).toBe("ArchLucid · TIMEOUT");
    expect(accessDeniedHeading("architecture")).toBe("You don't have access to ArchLucid yet");
    expect(accessDeniedBody("architecture")).toContain("ArchLucid app role");
    expect(accessDeniedSupplementCopy("architecture", "missing-role")).toBe(
      "No ArchLucid app role was found for this account.",
    );
    expect(accessDeniedMailtoSubject("architecture")).toBe("ArchLucid access request");
    expect(productLinePasswordlessExplanation("architecture")).toContain("ArchLucid does not use");
    expect(productLineEvaluationSignupLead("architecture")).toBe("New to ArchLucid?");
  });

  it("names SecureNow in security outage surfaces", () => {
    expect(productLineTransientFailureTimeoutTitle("security")).toBe(
      "SecureNow is taking longer than expected",
    );
    expect(productLineTransientFailureUnavailableTitle("security")).toBe(
      "SecureNow is temporarily unavailable",
    );
    expect(productLineTransientFailureFooter("security", "UNAVAILABLE")).toBe("SecureNow · UNAVAILABLE");
    expect(accessDeniedHeading("security")).toBe("You don't have access to SecureNow yet");
    expect(accessDeniedBody("security")).toContain("SecureNow app role");
    expect(accessDeniedSupplementCopy("security", "missing-role")).toBe(
      "No SecureNow app role was found for this account.",
    );
    expect(accessDeniedMailtoSubject("security")).toBe("SecureNow access request");
    expect(productLinePasswordlessExplanation("security")).toContain("SecureNow does not use");
    expect(productLineEvaluationSignupLead("security")).toBe("New to SecureNow?");
  });
});

describe("localizeProductCopy", () => {
  it("preserves script placeholder tokens while renaming the product", () => {
    const template = "Replace {ArchLucid tenant ID} and {ArchLucid managed identity object ID} for ArchLucid federation.";

    expect(localizeProductCopy("security", template)).toBe(
      "Replace {ArchLucid tenant ID} and {ArchLucid managed identity object ID} for SecureNow federation.",
    );
  });

  it("exposes SecureNow federation field labels", () => {
    expect(productLineTenantIdLabel("security")).toBe("SecureNow tenant ID");
    expect(productLineManagedIdentityObjectIdLabel("security")).toBe("SecureNow managed identity object ID");
  });
});
