using ArchLucid.ArtifactSynthesis.Layout;

using FluentAssertions;

namespace ArchLucid.ArtifactSynthesis.Tests;

public sealed class DiagramInventoryAutoGeneratedResourceNameTests
{
    [Theory]
    [InlineData("vnet-aep-hi-test-wus-001")]
    [InlineData("vm-0123456789abcdef0123456789abcdef")]
    [InlineData("nic-a1b2c3d4-e5f6-7890-abcd-ef1234567890")]
    public void LooksAutoGenerated_returns_true_for_azure_style_names(string resourceName)
    {
        DiagramInventoryAutoGeneratedResourceName.LooksAutoGenerated(resourceName).Should().BeTrue();
    }

    [Theory]
    [InlineData("vnet-eastus")]
    [InlineData("Claims API")]
    [InlineData("sqldb-app")]
    public void LooksAutoGenerated_returns_false_for_short_human_names(string resourceName)
    {
        DiagramInventoryAutoGeneratedResourceName.LooksAutoGenerated(resourceName).Should().BeFalse();
    }
}
