import type { Dispatch, SetStateAction } from "react";

import type { ApiLoadFailureState } from "@/lib/api-load-failure";
import type { TeamsIntegrationConnectionStatus } from "@/lib/teams-integration-page-copy";
import type { TeamsSecretValidationResult } from "@/lib/teams-integration-secret-validation";
import type { TeamsIncomingWebhookConnectionResponse } from "@/types/teams-incoming-webhook-connection";

export type TeamsNotificationsIntegrationPageViewModel = {
  readonly isDemo: boolean;
  readonly canMutate: boolean;
  readonly loading: boolean;
  readonly saving: boolean;
  readonly validating: boolean;
  readonly testing: boolean;
  readonly failure: ApiLoadFailureState | null;
  readonly conn: TeamsIncomingWebhookConnectionResponse | null;
  readonly connectionStatus: TeamsIntegrationConnectionStatus;
  readonly secretName: string;
  readonly setSecretName: Dispatch<SetStateAction<string>>;
  readonly label: string;
  readonly setLabel: Dispatch<SetStateAction<string>>;
  readonly catalog: string[];
  readonly enabledTriggers: ReadonlySet<string>;
  readonly secretValidation: TeamsSecretValidationResult | null;
  readonly testMessage: string | null;
  readonly testKind: "success" | "error" | null;
  readonly lastTestMessage: string | null;
  readonly showTriggerValidationError: boolean;
  readonly mutationSuccessMessage: string | null;
  readonly setMutationSuccessMessage: Dispatch<SetStateAction<string | null>>;
  readonly canSendTest: boolean;
  readonly toggleTrigger: (eventType: string, checked: boolean) => void;
  readonly onSelectRecommended: () => void;
  readonly onSelectAll: () => void;
  readonly onClearAll: () => void;
  readonly onValidateSecret: () => Promise<void>;
  readonly onSendTest: () => Promise<void>;
  readonly onSave: () => Promise<void>;
  readonly pendingRemoveConfirm: boolean;
  readonly requestRemove: () => void;
  readonly cancelRemove: () => void;
  readonly confirmRemove: () => Promise<void>;
};
