using ArchLucid.Contracts.Findings;

namespace ArchLucid.Application.Findings;

/// <inheritdoc cref="IFindingTrustLabelMapper" />
public sealed class FindingTrustLabelMapper : IFindingTrustLabelMapper
{
    /// <summary>EvaluationConfidenceScore threshold at or above which a finding is considered high-confidence.</summary>
    private const int HighConfidenceScoreThreshold = 70;

    /// <inheritdoc />
    public FindingTrustSummary Map(ArchitectureFinding finding, AgentTrustContext context)
    {
        ArgumentNullException.ThrowIfNull(finding);
        ArgumentNullException.ThrowIfNull(context);

        if (context.IsDegraded)
            return new FindingTrustSummary(FindingTrustLabel.Degraded, "Output was degraded; verify independently.");

        if (context.IsSimulatorDerived)
            return new FindingTrustSummary(FindingTrustLabel.SimulatorDerived, "Generated by the simulator — not a live model result.");

        bool hasEvidenceRefs = finding.EvidenceRefs.Count > 0;

        if (hasEvidenceRefs)
            return MapEvidenceBacked(finding, context);

        return MapNoEvidence(finding);
    }

    private static FindingTrustSummary MapEvidenceBacked(ArchitectureFinding finding, AgentTrustContext context)
    {
        bool isHighConfidence = finding.EvaluationConfidenceScore >= HighConfidenceScoreThreshold
            || finding.ConfidenceLevel is FindingConfidenceLevel.High or FindingConfidenceLevel.Medium;

        if (isHighConfidence)
        {
            FindingTrustLabel label = context.IsRealModel ? FindingTrustLabel.RealModel : FindingTrustLabel.EvidenceBacked;
            return new FindingTrustSummary(label, "Supported by retrieved evidence.");
        }

        return new FindingTrustSummary(FindingTrustLabel.Estimated, "Evidence available; confidence is limited.");
    }

    private static FindingTrustSummary MapNoEvidence(ArchitectureFinding finding)
    {
        if (finding.ConfidenceLevel == FindingConfidenceLevel.Low)
            return new FindingTrustSummary(FindingTrustLabel.Heuristic, "Based on heuristic reasoning; not directly evidenced.");

        return new FindingTrustSummary(FindingTrustLabel.MissingCitation, "No evidence reference available for this finding.");
    }
}
