using ArchLucid.Contracts.Findings;

namespace ArchLucid.Application.Findings;

/// <inheritdoc cref="IFindingTrustLabelMapper" />
public sealed class FindingTrustLabelMapper : IFindingTrustLabelMapper
{
    /// <summary>EvaluationConfidenceScore threshold at or above which a finding is considered high-confidence.</summary>
    private const int HighConfidenceScoreThreshold = 70;

    /// <inheritdoc />
    public FindingTrustSummary Map(ArchitectureFinding finding, AgentTrustContext context)
    {
        ArgumentNullException.ThrowIfNull(finding);
        ArgumentNullException.ThrowIfNull(context);

        // Precedence: simulator > deterministic rule > LLM-failure fallback > default evidence/heuristic paths.
        if (context.IsSimulatorDerived)
            return new FindingTrustSummary(FindingTrustLabel.SimulatorDerived, "Generated by the simulator — not a live model result.");

        if (!string.IsNullOrWhiteSpace(finding.PolicyRuleId))
        {
            string reason = context.IsDegraded
                ? "Deterministic policy rule; run output was degraded but this rule result is still authoritative."
                : "A deterministic policy rule fired; rationale comes from the rule definition.";

            return new FindingTrustSummary(FindingTrustLabel.DeterministicRule, reason);
        }

        if (context.IsDegraded)
            return new FindingTrustSummary(
                FindingTrustLabel.DeterministicFallback,
                "LLM path failed; this finding uses a deterministic fallback — verify independently.");

        bool hasEvidenceRefs = finding.EvidenceRefs.Count > 0;

        if (hasEvidenceRefs)
            return MapEvidenceBacked(finding, context);

        return MapNoEvidence(finding);
    }

    private static FindingTrustSummary MapEvidenceBacked(ArchitectureFinding finding, AgentTrustContext context)
    {
        bool isHighConfidence = finding.EvaluationConfidenceScore >= HighConfidenceScoreThreshold
            || finding.ConfidenceLevel is FindingConfidenceLevel.High or FindingConfidenceLevel.Medium;

        if (isHighConfidence)
        {
            FindingTrustLabel label = context.IsRealModel ? FindingTrustLabel.RealModel : FindingTrustLabel.EvidenceBacked;
            return new FindingTrustSummary(label, "Supported by retrieved evidence.");
        }

        return new FindingTrustSummary(FindingTrustLabel.Estimated, "Evidence available; confidence is limited.");
    }

    private static FindingTrustSummary MapNoEvidence(ArchitectureFinding finding)
    {
        if (finding.ConfidenceLevel == FindingConfidenceLevel.Low)
            return new FindingTrustSummary(FindingTrustLabel.Heuristic, "Based on heuristic reasoning; not directly evidenced.");

        return new FindingTrustSummary(FindingTrustLabel.MissingCitation, "No evidence reference available for this finding.");
    }
}
