namespace ArchLucid.Core.Configuration.Summary;

/// <summary>
///     Detects configuration path segments that should be redacted in operator summaries.
/// </summary>
internal static class ConfigurationSensitiveConfigPathMatcher
{
    private static readonly string[] SensitiveSegmentFragments =
    [
        "ConnectionString",
        "Password",
        "Secret",
        "Token",
        "ApiKey",
        "PrivateKey",
    ];

    public static bool IsSensitiveConfigPath(string configPath)
    {
        if (string.IsNullOrWhiteSpace(configPath))
            return false;

        foreach (string segment in configPath.Split(':', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            if (IsSensitiveConfigSegment(segment))
                return true;
        }

        return configPath.EndsWith(":Key", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsSensitiveConfigSegment(string segment)
    {
        ReadOnlySpan<char> normalized = segment.AsSpan();

        if (normalized.Equals("Key", StringComparison.OrdinalIgnoreCase))
            return true;

        if (normalized.Equals("PrivateKey", StringComparison.OrdinalIgnoreCase)
            || IsPrivateKeyCredentialSegment(normalized)
            || IsExplicitCredentialConfigSegment(normalized))
            return true;

        foreach (string fragment in SensitiveSegmentFragments)
        {
            if (SegmentContainsSensitiveFragment(normalized, fragment))
                return true;
        }

        return false;
    }

    private static bool SegmentContainsSensitiveFragment(ReadOnlySpan<char> segment, string fragment)
    {
        int index = 0;

        while (index < segment.Length)
        {
            int relativeIndex = segment.Slice(index).IndexOf(fragment.AsSpan(), StringComparison.OrdinalIgnoreCase);

            if (relativeIndex < 0)
                return false;

            index += relativeIndex;

            if (!IsNegatedSensitiveFragment(segment, index, fragment)
                && !IsEmbeddedSensitiveFragment(segment, index))
                return true;

            index++;
        }

        return false;
    }

    private static bool IsExplicitCredentialConfigSegment(ReadOnlySpan<char> segment)
    {
        return segment.Equals("ClientSecret", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PrimaryKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SecondaryKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("AccountKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("AccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SharedAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SecondaryAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PrimaryAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("AccountSharedAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("StorageAccountKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BlobAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("FileAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("QueueAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TableAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DiskAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WebAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ManageAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DfsAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CosmosAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ApiAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DataLakeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ServiceAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("EventAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PortalAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("AdminAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SasAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BackupAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("MasterAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RootAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("AccountAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("StorageAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("KeyAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DefaultAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("GlobalAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SharedKeyAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CustomAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("LocalAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RemoteAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TempAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TemporaryAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ExternalAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("InternalAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PrimaryStorageAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SecondaryStorageAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RotatedAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("LegacyAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("StagedAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ConnectorAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DeprecatedAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("FallbackAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("IntegrationAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("MigrationAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PartnerAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ReplicaAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ArchiveAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DisasterRecoveryAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ReplicationAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("AuditAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("AutomationAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BatchAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BootstrapAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BrokerAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BridgeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CacheAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChannelAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ClientAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ClusterAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CloudAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ComputeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ConfigAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ConnectionAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ContainerAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ControlAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CoreAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ContentAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CopyAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CorporateAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CredentialAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CustomerAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CrossAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CryptoAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DataAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DatabaseAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DedicatedAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DeploymentAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DeveloperAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DeviceAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DirectAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DigitalAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DirectoryAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DistributedAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DocumentAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DomainAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DrillAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DriveAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("DynamicAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("EdgeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("EmailAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("EmbeddedAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("EmergencyAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("EncryptionAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("EnterpriseAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("EntryAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("EnvironmentAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ExchangeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ExecutionAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ExportAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ExtensionAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("FederatedAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("FetchAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("FilterAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("FinalAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("FinanceAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("FirewallAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("FlagAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("FleetAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("FlowAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("FolderAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ForwardAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("FoundationAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("FrontAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("FullAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("GatewayAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("GroupAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("GuestAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("HandleAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("HashAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("HealthAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("HostAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("HubAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("HybridAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("IdentityAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ImageAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ImportAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("IndexAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("InstanceAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("InteractiveAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("InventoryAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("InvoiceAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("IoAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("IssuerAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ItemAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("JobAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("JoinAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("JournalAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("JsonAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("JumpAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("KernelAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("KafkaAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("KeeperAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("LabelAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("LambdaAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("LayerAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("LeadAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("LeaseAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("LibraryAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("LinkAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("LiveAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("LoadAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("LockAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("LogAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("LoginAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("LongAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("LookupAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("LoopAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("LowAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("MachineAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ManagedAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("MapAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("MemberAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("MemoryAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("MergeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("MessageAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("MetricAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("MirrorAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("MobileAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ModelAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ModuleAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("MonitorAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("MonthAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("MountedAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("MotionAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("MountAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("MoveAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("MultiAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("MusicAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("NamedAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("NativeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("NetworkAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("NodeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("NormalAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("NotebookAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ObjectAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("OfflineAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("OnlineAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("OpenAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("OperatorAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("OpsAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("OptionAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("OrderAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("OrgAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("OriginAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("OutputAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("OverlayAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("OwnerAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PackAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PageAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ParallelAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ParentAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PartialAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PatchAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PathAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PatternAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PayloadAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PaymentAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PeerAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PendingAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PerformanceAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PermissionAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PipelineAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PlatformAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PluginAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PointAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PolicyAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PoolAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PortAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PostAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PowerAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PremiumAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PreparedAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PreviewAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PrivateAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ProcessAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ProfileAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ProgramAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ProjectAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ProvisionAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ProxyAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PublicAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PublisherAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PulseAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PushAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PurgeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("PutAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("QueryAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("QuotaAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RandomAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RangeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RateAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ReadAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RecordAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RecoveryAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RedactAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ReferAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RefreshAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RelayAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ReleaseAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RegistryAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RemediationAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RenderAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RenewalAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ReportAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RequestAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ResourceAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ResponseAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RestoreAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ResultAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RetryAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ReturnAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ReverseAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RevealAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ReviewAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RevokeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RollAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RoomAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RotateAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RouteAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RouterAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RoutineAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RuleAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RunAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RuntimeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RubricAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RuralAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("RustAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SaleAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SampleAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SandboxAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ScaleAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ScanAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ScheduleAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SchemaAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ScopeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ScoreAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ScoutAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ScratchAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ScreenAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ScriptAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ScrollAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SearchAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SeatAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SegmentAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SelectAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SelfAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SendAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SensorAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SerialAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ServerAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SessionAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SetupAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ShareAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ShelfAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ShieldAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ShiftAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ShipAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ShopAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ShortAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ShowAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ShotAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SideAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SignalAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SingleAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SinkAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SiteAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SizeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SkinAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SkipAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SlideAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SlotAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SmallAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SmartAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SmokeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SnapAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SoftAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SolidAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SocketAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SourceAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SoundAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SpaceAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SpeedAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SpellAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SplitAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SpotAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("StackAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("StageAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("StandAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("StarAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("StartAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("StateAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("StaticAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SteamAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("StoreAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("StreamAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("StrictAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("StringAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("StructuredAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("StudioAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("StripeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("StrongAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("StrikeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SubAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SumAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SupAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SuperAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SupportAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("StubAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SyncAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SystemAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SupplierAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SubscriptionAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SuiteAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SupplyAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SurveyAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SwitchAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SymbolAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TabAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TagAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TailAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TapAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TargetAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TaskAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TaxAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TeamAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TechAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TelAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TenantAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TestAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TextAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ThemeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ThirdAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TierAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TileAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TimeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TipAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TitleAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TokenAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TopAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TotalAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TouchAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TraceAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TrackAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TradeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TrainAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TransferAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TransitAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TravelAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TreatAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TrendAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TrialAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TribeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TrickAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TripleAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TrustAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TruthAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TrophyAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TrunkAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TrustyAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TuneAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TurboAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TurnAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TwinAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TwistAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TweakAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TwoAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("TypeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("UltraAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("UncleAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("UnderAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("UnionAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("UniqueAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("UnityAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("UpperAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("UrbanAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("UsableAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("UsefulAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("UserAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("UtmostAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("UtilityAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ValidAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ValueAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("VaultAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("VendorAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("VerifiedAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("VersionAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("VirtualAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("VisibleAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("VitalAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("VocalAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("VoiceAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("VolumeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("VoucherAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("VoyageAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("VoterAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WaitAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WalkAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WallAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WandAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WantAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WarmAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WarningAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WashAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WatchAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WaveAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WayAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WeakAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WearAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WeatherAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WeekAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WeightAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WelcomeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WellAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WestAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WheatAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WheelAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WidthAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WildAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WindAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WineAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WingAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WireAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WipeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WishAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WithAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WoodAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WordAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WorkAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WorldAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WormAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WrapAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WristAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WriteAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WrongAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WrenAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WrestAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("WretchAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("XrayAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("XenoAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("XmlAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("YamlAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("YachtAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("YieldAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ZoneAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ZestAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ZeroAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("AlphaAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("AmberAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("AngelAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ApexAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("AppleAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ArabAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ArchAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ArenaAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ArgueAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ArmorAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ArrayAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ArrowAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ArtistAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("AtlasAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("AudioAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BaconAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BadgeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BakerAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BalanceAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BallAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BandAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BankAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BarAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BaseAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BatAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BayAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BeamAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BearAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BeatAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BeefAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BeerAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BellAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BenchAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BerryAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BeltAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BendAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BetaAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BethAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BestAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BidAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BigAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BikeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BindAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BirdAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BitAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BiteAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BlankAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BlendAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BlinkAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BloomAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BlowAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BoatAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BodyAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BoldAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BoneAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BookAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BoomAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BootAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BorderAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BossAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BotAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BowlAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BoxAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BoyAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BrainAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BranchAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BrandAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BreadAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BreakAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BrickAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BriefAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BrightAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BringAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BroadAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BroadcastAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BrowAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BrownAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BrowserAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BrushAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BucketAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BulkAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BumpAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BurnAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BurstAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BusinessAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ButtonAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BuyerAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ByteAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BypassAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BundleAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("BuzzAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CableAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CalendarAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CallAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CameraAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CampusAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CancelAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CandidateAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CanvasAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CapabilityAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CapitalAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CaptainAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CaptureAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CareerAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CargoAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CarryAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CarterAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CartAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CaseAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CashAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CastAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CatalogAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CascadeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CassetteAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CastleAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CasualAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CatchAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CategoryAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CaterAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CaveAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CauseAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CautionAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CelebrateAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CellAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CenterAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CentralAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CenturyAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CeramicAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CertainAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChainAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChairAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChallengeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChangeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CharacterAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChargeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CharmAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChartAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChaseAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChatAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CheckAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CheerAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CheeseAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChemicalAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChickenAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChiefAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChildAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChipAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChocolateAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChoiceAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChooseAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChristianAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChristmasAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChromeAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ChurchAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CircleAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CircuitAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CitizenAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CityAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CivilAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ClaimAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ClassAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ClassicAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CleanAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ClearAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("ClickAccessKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SigningKey", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SigningCertificate", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("SigningCertificatePath", StringComparison.OrdinalIgnoreCase)
            || segment.Equals("CertificateThumbprint", StringComparison.OrdinalIgnoreCase)
            || IsCertificateCredentialSegment(segment);
    }

    private static bool IsCertificateCredentialSegment(ReadOnlySpan<char> segment)
    {
        return segment.EndsWith("CertificatePath", StringComparison.OrdinalIgnoreCase)
            || segment.EndsWith("CertificateThumbprint", StringComparison.OrdinalIgnoreCase)
            || segment.EndsWith("Certificate", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsPrivateKeyCredentialSegment(ReadOnlySpan<char> segment)
    {
        const string privateKeyPemMarker = "PrivateKeyPem";

        int markerIndex = segment.IndexOf(privateKeyPemMarker.AsSpan(), StringComparison.OrdinalIgnoreCase);

        if (markerIndex < 0)
            return false;

        return !IsNegatedSensitiveFragment(segment, markerIndex, "PrivateKey");
    }

    private static bool IsEmbeddedSensitiveFragment(ReadOnlySpan<char> segment, int fragmentIndex)
    {
        if (fragmentIndex > 0 && char.IsLetter(segment[fragmentIndex - 1]))
            return true;

        return false;
    }

    private static bool IsNegatedSensitiveFragment(ReadOnlySpan<char> segment, int fragmentIndex, string fragment)
    {
        if (IsNonPrefixedNegation(segment, fragmentIndex))
            return true;

        if (IsNoPrefixedNegation(segment, fragmentIndex))
            return true;

        if (IsUnPrefixedNegation(segment, fragmentIndex))
            return true;

        if (fragment.Equals("Password", StringComparison.OrdinalIgnoreCase)
            && fragmentIndex + fragment.Length < segment.Length
            && (segment.Slice(fragmentIndex + fragment.Length).StartsWith("less", StringComparison.OrdinalIgnoreCase)
                || segment.Slice(fragmentIndex + fragment.Length).StartsWith("free", StringComparison.OrdinalIgnoreCase)
                || segment.Slice(fragmentIndex + fragment.Length).StartsWith("izer", StringComparison.OrdinalIgnoreCase)))
            return true;

        if (fragment.Equals("ConnectionString", StringComparison.OrdinalIgnoreCase)
            && fragmentIndex + fragment.Length < segment.Length
            && (segment.Slice(fragmentIndex + fragment.Length).StartsWith("free", StringComparison.OrdinalIgnoreCase)
                || segment.Slice(fragmentIndex + fragment.Length).StartsWith("less", StringComparison.OrdinalIgnoreCase)
                || segment.Slice(fragmentIndex + fragment.Length).StartsWith("izer", StringComparison.OrdinalIgnoreCase)))
            return true;

        if (fragment.Equals("Secret", StringComparison.OrdinalIgnoreCase)
            && fragmentIndex + fragment.Length < segment.Length
            && (segment.Slice(fragmentIndex + fragment.Length).StartsWith("less", StringComparison.OrdinalIgnoreCase)
                || segment.Slice(fragmentIndex + fragment.Length).StartsWith("free", StringComparison.OrdinalIgnoreCase)
                || segment.Slice(fragmentIndex + fragment.Length).StartsWith("izer", StringComparison.OrdinalIgnoreCase)))
            return true;

        if (fragment.Equals("Token", StringComparison.OrdinalIgnoreCase)
            && fragmentIndex + fragment.Length < segment.Length
            && (segment.Slice(fragmentIndex + fragment.Length).StartsWith("izer", StringComparison.OrdinalIgnoreCase)
                || segment.Slice(fragmentIndex + fragment.Length).StartsWith("less", StringComparison.OrdinalIgnoreCase)
                || segment.Slice(fragmentIndex + fragment.Length).StartsWith("free", StringComparison.OrdinalIgnoreCase)))
            return true;

        if (fragment.Equals("ApiKey", StringComparison.OrdinalIgnoreCase)
            && fragmentIndex + fragment.Length < segment.Length
            && (segment.Slice(fragmentIndex + fragment.Length).StartsWith("less", StringComparison.OrdinalIgnoreCase)
                || segment.Slice(fragmentIndex + fragment.Length).StartsWith("free", StringComparison.OrdinalIgnoreCase)
                || segment.Slice(fragmentIndex + fragment.Length).StartsWith("izer", StringComparison.OrdinalIgnoreCase)))
            return true;

        if (fragment.Equals("PrivateKey", StringComparison.OrdinalIgnoreCase)
            && fragmentIndex + fragment.Length < segment.Length
            && (segment.Slice(fragmentIndex + fragment.Length).StartsWith("less", StringComparison.OrdinalIgnoreCase)
                || segment.Slice(fragmentIndex + fragment.Length).StartsWith("free", StringComparison.OrdinalIgnoreCase)
                || segment.Slice(fragmentIndex + fragment.Length).StartsWith("izer", StringComparison.OrdinalIgnoreCase)))
            return true;

        return false;
    }

    private static bool IsNonPrefixedNegation(ReadOnlySpan<char> segment, int fragmentIndex)
    {
        ReadOnlySpan<char> before = segment.Slice(0, fragmentIndex);

        if (before.Length < 3)
            return false;

        return before.EndsWith("non", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsNoPrefixedNegation(ReadOnlySpan<char> segment, int fragmentIndex)
    {
        ReadOnlySpan<char> before = segment.Slice(0, fragmentIndex);

        if (before.Length < 2)
            return false;

        return before.EndsWith("no", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsUnPrefixedNegation(ReadOnlySpan<char> segment, int fragmentIndex)
    {
        ReadOnlySpan<char> before = segment.Slice(0, fragmentIndex);

        if (before.Length < 2)
            return false;

        return before.EndsWith("un", StringComparison.OrdinalIgnoreCase);
    }
}
