import type { components } from "@/lib/openapi-schemas";
type LearningThemeResponseSchema = components["schemas"]["LearningThemeResponse"];
export type LearningThemeResponse = LearningThemeResponseSchema & Required<Pick<LearningThemeResponseSchema, "themeId" | "themeKey" | "title" | "summary" | "affectedArtifactTypeOrWorkflowArea" | "severityBand" | "evidenceSignalCount" | "distinctRunCount" | "derivationRuleVersion" | "status" | "createdUtc">>;
type LearningThemesListResponseSchema = components["schemas"]["LearningThemesListResponse"];
export type LearningThemesListResponse = LearningThemesListResponseSchema & Required<Pick<LearningThemesListResponseSchema, "generatedUtc" | "themes">>;
type LearningPlanListItemResponseSchema = components["schemas"]["LearningPlanListItemResponse"];
export type LearningPlanListItemResponse = LearningPlanListItemResponseSchema & Required<Pick<LearningPlanListItemResponseSchema, "planId" | "themeId" | "title" | "summary" | "priorityScore" | "status" | "createdUtc">>;
type LearningPlansListResponseSchema = components["schemas"]["LearningPlansListResponse"];
export type LearningPlansListResponse = LearningPlansListResponseSchema & Required<Pick<LearningPlansListResponseSchema, "generatedUtc" | "plans">>;
type LearningSummaryResponseSchema = components["schemas"]["LearningSummaryResponse"];
export type LearningSummaryResponse = LearningSummaryResponseSchema & Required<Pick<LearningSummaryResponseSchema, "generatedUtc" | "themeCount" | "planCount" | "totalThemeEvidenceSignals" | "totalLinkedSignalsAcrossPlans">>;
type LearningPlanStepResponseSchema = components["schemas"]["LearningPlanStepResponse"];
export type LearningPlanStepResponse = LearningPlanStepResponseSchema & Required<Pick<LearningPlanStepResponseSchema, "ordinal" | "actionType" | "description">>;
type LearningPlanEvidenceCountsResponseSchema = components["schemas"]["LearningPlanEvidenceCountsResponse"];
export type LearningPlanEvidenceCountsResponse = LearningPlanEvidenceCountsResponseSchema & Required<Pick<LearningPlanEvidenceCountsResponseSchema, "linkedSignalCount" | "linkedArtifactCount" | "linkedArchitectureRunCount">>;
type LearningPlanDetailResponseSchema = components["schemas"]["LearningPlanDetailResponse"];
export type LearningPlanDetailResponse = LearningPlanDetailResponseSchema & Required<Pick<LearningPlanDetailResponseSchema, "planId" | "themeId" | "title" | "summary" | "priorityScore" | "status" | "createdUtc" | "actionSteps" | "evidenceCounts">>;
