using ArchLucid.Core.Costing;

using FluentAssertions;

namespace ArchLucid.Core.Tests.Costing;

[Trait("Category", "Unit")]
public sealed class AzureRetailPricesSkuMatchersWeekMeterTests
{
    public static TheoryData<string> WeekUnitOfMeasureSynonyms =>
    [
        "w",
        "wk",
        "/w",
        "wks",
        "/wk",
        "/wks",
        "10 W",
        "10wk",
        "10 w",
        "week",
        "10wks",
        "10wek",
        "weeks",
        "1/wks",
        "10 wk",
        "10wel",
        "10wels",
        "1/week",
        "10 / w",
        "/weeks",
        "10week",
        "10weks",
        "10 wks",
        "10 wek",
        "10weel",
        "10 wels",
        "10weekk",
        "10weeks",
        "10wekks",
        "10 weel",
        "1/weeks",
        "10 weks",
        "10weels",
        "10 weels",
        "10 / wel",
        "10weekkk",
        "10weekes",
        "10 / wek",
        "10weekkkk",
        "10 weekes",
        "10weekkkkk",
        "10 / weekk",
        "10weekkkkkk",
        "10 / weekkkk",
        "10weekkkkkkk",
        "10weekkkkkkkk",
        "10 / weekkkkk",
        "10 / weekkkkkk",
        "10weekkkkkkkkk",
        "10 / weekkkkkkk",
        "10weekkkkkkkkkk",
        "10 / weekkkkkkkk",
        "10weekkkkkkkkkkk",
        "10weekkkkkkkkkkkk",
        "10 / weekkkkkkkkk",
        "10weekkkkkkkkkkkkk",
        "10 / weekkkkkkkkkk",
        "10 / weekkkkkkkkkkk",
        "10weekkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10weekkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
        "10 / weekkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
    ];

    [Theory]
    [MemberData(nameof(WeekUnitOfMeasureSynonyms))]
    public void LooksLikeConsumptionUsd_accepts_week_unit_of_measure_synonyms(string unitOfMeasure)
    {
        AzureRetailPricesCatalogClient.RetailPriceDto dto = new()
        {
            CurrencyCode = "USD",
            Type = "Consumption",
            UnitOfMeasure = unitOfMeasure,
            UnitPrice = 1m,
        };

        AzureRetailPricesCatalogClient.LooksLikeConsumptionUsd(dto).Should().BeTrue();
    }
}
