<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ArchLucid.Integrations.AzureExtractor.Tests</RootNamespace>
    <AssemblyName>ArchLucid.Integrations.AzureExtractor.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ArchLucid.Integrations.AzureExtractor\ArchLucid.Integrations.AzureExtractor.csproj" />
    <ProjectReference Include="..\ArchLucid.Application\ArchLucid.Application.csproj" />
    <ProjectReference Include="..\ArchLucid.Persistence\ArchLucid.Persistence.csproj" />
  </ItemGroup>

</Project>
