namespace ArchLucid.Core.AzureExtractor;

/// <summary>Redacts secret-like ARM property keys before persistence or hashing.</summary>
public static class AzureExtractorSensitivePropertyRedactor
{
    private static readonly string[] SensitiveKeyFragments =
    [
        "secret",
        "password",
        "connectionstring",
        "privatekey",
        "certificate",
        "accesskey",
        "accountkey",
        "clientsecret",
        "primarykey",
        "secondarykey",
    ];

    public static bool IsSensitiveKey(string? propertyKey)
    {
        if (string.IsNullOrWhiteSpace(propertyKey))
            return false;

        string normalized = propertyKey.Replace("-", string.Empty, StringComparison.Ordinal)
            .Replace("_", string.Empty, StringComparison.Ordinal)
            .ToLowerInvariant();

        if (IsExplicitCredentialKey(normalized))
            return true;

        foreach (string fragment in SensitiveKeyFragments)
        {
            if (ContainsSensitiveFragment(normalized, fragment))
                return true;
        }

        return false;
    }

    private static bool ContainsSensitiveFragment(string normalized, string fragment)
    {
        int index = 0;

        while (index < normalized.Length)
        {
            index = normalized.IndexOf(fragment, index, StringComparison.Ordinal);

            if (index < 0)
                return false;

            if (!IsNegatedSensitiveFragment(normalized, index, fragment)
                && !IsEmbeddedSensitiveFragment(normalized, index))
                return true;

            index++;
        }

        return false;
    }

    private static bool IsExplicitCredentialKey(string normalized)
    {
        return normalized.Equals("sharedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("secondaryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("primaryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("accountsharedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("storageaccountkey", StringComparison.Ordinal)
            || normalized.Equals("blobaccesskey", StringComparison.Ordinal)
            || normalized.Equals("fileaccesskey", StringComparison.Ordinal)
            || normalized.Equals("queueaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tableaccesskey", StringComparison.Ordinal)
            || normalized.Equals("diskaccesskey", StringComparison.Ordinal)
            || normalized.Equals("webaccesskey", StringComparison.Ordinal)
            || normalized.Equals("manageaccesskey", StringComparison.Ordinal)
            || normalized.Equals("dfsaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cosmosaccesskey", StringComparison.Ordinal)
            || normalized.Equals("apiaccesskey", StringComparison.Ordinal)
            || normalized.Equals("datalakeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("serviceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("eventaccesskey", StringComparison.Ordinal)
            || normalized.Equals("portalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("adminaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sasaccesskey", StringComparison.Ordinal)
            || normalized.Equals("backupaccesskey", StringComparison.Ordinal)
            || normalized.Equals("masteraccesskey", StringComparison.Ordinal)
            || normalized.Equals("rootaccesskey", StringComparison.Ordinal)
            || normalized.Equals("accountaccesskey", StringComparison.Ordinal)
            || normalized.Equals("storageaccesskey", StringComparison.Ordinal)
            || normalized.Equals("keyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("defaultaccesskey", StringComparison.Ordinal)
            || normalized.Equals("globalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sharedkeyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("customaccesskey", StringComparison.Ordinal)
            || normalized.Equals("localaccesskey", StringComparison.Ordinal)
            || normalized.Equals("remoteaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tempaccesskey", StringComparison.Ordinal)
            || normalized.Equals("temporaryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("externalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("internalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("primarystorageaccesskey", StringComparison.Ordinal)
            || normalized.Equals("secondarystorageaccesskey", StringComparison.Ordinal)
            || normalized.Equals("rotatedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("legacyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("stagedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("connectoraccesskey", StringComparison.Ordinal)
            || normalized.Equals("deprecatedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("fallbackaccesskey", StringComparison.Ordinal)
            || normalized.Equals("integrationaccesskey", StringComparison.Ordinal)
            || normalized.Equals("migrationaccesskey", StringComparison.Ordinal)
            || normalized.Equals("partneraccesskey", StringComparison.Ordinal)
            || normalized.Equals("replicaaccesskey", StringComparison.Ordinal)
            || normalized.Equals("archiveaccesskey", StringComparison.Ordinal)
            || normalized.Equals("disasterrecoveryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("replicationaccesskey", StringComparison.Ordinal)
            || normalized.Equals("auditaccesskey", StringComparison.Ordinal)
            || normalized.Equals("automationaccesskey", StringComparison.Ordinal)
            || normalized.Equals("batchaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bootstrapaccesskey", StringComparison.Ordinal)
            || normalized.Equals("brokeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("bridgeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cacheaccesskey", StringComparison.Ordinal)
            || normalized.Equals("channelaccesskey", StringComparison.Ordinal)
            || normalized.Equals("clientaccesskey", StringComparison.Ordinal)
            || normalized.Equals("clusteraccesskey", StringComparison.Ordinal)
            || normalized.Equals("cloudaccesskey", StringComparison.Ordinal)
            || normalized.Equals("computeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("configaccesskey", StringComparison.Ordinal)
            || normalized.Equals("connectionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("containeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("controlaccesskey", StringComparison.Ordinal)
            || normalized.Equals("coreaccesskey", StringComparison.Ordinal)
            || normalized.Equals("contentaccesskey", StringComparison.Ordinal)
            || normalized.Equals("copyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("corporateaccesskey", StringComparison.Ordinal)
            || normalized.Equals("credentialaccesskey", StringComparison.Ordinal)
            || normalized.Equals("customeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("crossaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cryptoaccesskey", StringComparison.Ordinal)
            || normalized.Equals("dataaccesskey", StringComparison.Ordinal)
            || normalized.Equals("databaseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("dedicatedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("deploymentaccesskey", StringComparison.Ordinal)
            || normalized.Equals("developeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("deviceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("directaccesskey", StringComparison.Ordinal)
            || normalized.Equals("digitalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("directoryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("distributedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("documentaccesskey", StringComparison.Ordinal)
            || normalized.Equals("domainaccesskey", StringComparison.Ordinal)
            || normalized.Equals("drillaccesskey", StringComparison.Ordinal)
            || normalized.Equals("driveaccesskey", StringComparison.Ordinal)
            || normalized.Equals("dynamicaccesskey", StringComparison.Ordinal)
            || normalized.Equals("edgeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("emailaccesskey", StringComparison.Ordinal)
            || normalized.Equals("embeddedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("emergencyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("encryptionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("enterpriseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("entryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("environmentaccesskey", StringComparison.Ordinal)
            || normalized.Equals("exchangeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("executionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("exportaccesskey", StringComparison.Ordinal)
            || normalized.Equals("extensionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("federatedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("fetchaccesskey", StringComparison.Ordinal)
            || normalized.Equals("filteraccesskey", StringComparison.Ordinal)
            || normalized.Equals("finalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("financeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("firewallaccesskey", StringComparison.Ordinal)
            || normalized.Equals("flagaccesskey", StringComparison.Ordinal)
            || normalized.Equals("fleetaccesskey", StringComparison.Ordinal)
            || normalized.Equals("flowaccesskey", StringComparison.Ordinal)
            || normalized.Equals("folderaccesskey", StringComparison.Ordinal)
            || normalized.Equals("forwardaccesskey", StringComparison.Ordinal)
            || normalized.Equals("foundationaccesskey", StringComparison.Ordinal)
            || normalized.Equals("frontaccesskey", StringComparison.Ordinal)
            || normalized.Equals("fullaccesskey", StringComparison.Ordinal)
            || normalized.Equals("gatewayaccesskey", StringComparison.Ordinal)
            || normalized.Equals("groupaccesskey", StringComparison.Ordinal)
            || normalized.Equals("guestaccesskey", StringComparison.Ordinal)
            || normalized.Equals("handleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("hashaccesskey", StringComparison.Ordinal)
            || normalized.Equals("healthaccesskey", StringComparison.Ordinal)
            || normalized.Equals("hostaccesskey", StringComparison.Ordinal)
            || normalized.Equals("hubaccesskey", StringComparison.Ordinal)
            || normalized.Equals("hybridaccesskey", StringComparison.Ordinal)
            || normalized.Equals("identityaccesskey", StringComparison.Ordinal)
            || normalized.Equals("imageaccesskey", StringComparison.Ordinal)
            || normalized.Equals("importaccesskey", StringComparison.Ordinal)
            || normalized.Equals("indexaccesskey", StringComparison.Ordinal)
            || normalized.Equals("instanceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("interactiveaccesskey", StringComparison.Ordinal)
            || normalized.Equals("inventoryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("invoiceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("ioaccesskey", StringComparison.Ordinal)
            || normalized.Equals("issueraccesskey", StringComparison.Ordinal)
            || normalized.Equals("itemaccesskey", StringComparison.Ordinal)
            || normalized.Equals("jobaccesskey", StringComparison.Ordinal)
            || normalized.Equals("joinaccesskey", StringComparison.Ordinal)
            || normalized.Equals("journalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("jsonaccesskey", StringComparison.Ordinal)
            || normalized.Equals("jumpaccesskey", StringComparison.Ordinal)
            || normalized.Equals("kernelaccesskey", StringComparison.Ordinal)
            || normalized.Equals("kafkaaccesskey", StringComparison.Ordinal)
            || normalized.Equals("keeperaccesskey", StringComparison.Ordinal)
            || normalized.Equals("labelaccesskey", StringComparison.Ordinal)
            || normalized.Equals("lambdaaccesskey", StringComparison.Ordinal)
            || normalized.Equals("layeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("leadaccesskey", StringComparison.Ordinal)
            || normalized.Equals("leaseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("libraryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("linkaccesskey", StringComparison.Ordinal)
            || normalized.Equals("liveaccesskey", StringComparison.Ordinal)
            || normalized.Equals("loadaccesskey", StringComparison.Ordinal)
            || normalized.Equals("lockaccesskey", StringComparison.Ordinal)
            || normalized.Equals("logaccesskey", StringComparison.Ordinal)
            || normalized.Equals("loginaccesskey", StringComparison.Ordinal)
            || normalized.Equals("longaccesskey", StringComparison.Ordinal)
            || normalized.Equals("lookupaccesskey", StringComparison.Ordinal)
            || normalized.Equals("loopaccesskey", StringComparison.Ordinal)
            || normalized.Equals("lowaccesskey", StringComparison.Ordinal)
            || normalized.Equals("machineaccesskey", StringComparison.Ordinal)
            || normalized.Equals("managedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("mapaccesskey", StringComparison.Ordinal)
            || normalized.Equals("memberaccesskey", StringComparison.Ordinal)
            || normalized.Equals("memoryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("mergeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("messageaccesskey", StringComparison.Ordinal)
            || normalized.Equals("metricaccesskey", StringComparison.Ordinal)
            || normalized.Equals("mirroraccesskey", StringComparison.Ordinal)
            || normalized.Equals("mobileaccesskey", StringComparison.Ordinal)
            || normalized.Equals("modelaccesskey", StringComparison.Ordinal)
            || normalized.Equals("moduleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("monitoraccesskey", StringComparison.Ordinal)
            || normalized.Equals("monthaccesskey", StringComparison.Ordinal)
            || normalized.Equals("mountedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("motionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("mountaccesskey", StringComparison.Ordinal)
            || normalized.Equals("moveaccesskey", StringComparison.Ordinal)
            || normalized.Equals("multiaccesskey", StringComparison.Ordinal)
            || normalized.Equals("musicaccesskey", StringComparison.Ordinal)
            || normalized.Equals("namedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("nativeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("networkaccesskey", StringComparison.Ordinal)
            || normalized.Equals("nodeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("normalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("notebookaccesskey", StringComparison.Ordinal)
            || normalized.Equals("objectaccesskey", StringComparison.Ordinal)
            || normalized.Equals("offlineaccesskey", StringComparison.Ordinal)
            || normalized.Equals("onlineaccesskey", StringComparison.Ordinal)
            || normalized.Equals("openaccesskey", StringComparison.Ordinal)
            || normalized.Equals("operatoraccesskey", StringComparison.Ordinal)
            || normalized.Equals("opsaccesskey", StringComparison.Ordinal)
            || normalized.Equals("optionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("orderaccesskey", StringComparison.Ordinal)
            || normalized.Equals("orgaccesskey", StringComparison.Ordinal)
            || normalized.Equals("originaccesskey", StringComparison.Ordinal)
            || normalized.Equals("outputaccesskey", StringComparison.Ordinal)
            || normalized.Equals("overlayaccesskey", StringComparison.Ordinal)
            || normalized.Equals("owneraccesskey", StringComparison.Ordinal)
            || normalized.Equals("packaccesskey", StringComparison.Ordinal)
            || normalized.Equals("pageaccesskey", StringComparison.Ordinal)
            || normalized.Equals("parallelaccesskey", StringComparison.Ordinal)
            || normalized.Equals("parentaccesskey", StringComparison.Ordinal)
            || normalized.Equals("partialaccesskey", StringComparison.Ordinal)
            || normalized.Equals("patchaccesskey", StringComparison.Ordinal)
            || normalized.Equals("pathaccesskey", StringComparison.Ordinal)
            || normalized.Equals("patternaccesskey", StringComparison.Ordinal)
            || normalized.Equals("payloadaccesskey", StringComparison.Ordinal)
            || normalized.Equals("paymentaccesskey", StringComparison.Ordinal)
            || normalized.Equals("peeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("pendingaccesskey", StringComparison.Ordinal)
            || normalized.Equals("performanceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("permissionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("pipelineaccesskey", StringComparison.Ordinal)
            || normalized.Equals("platformaccesskey", StringComparison.Ordinal)
            || normalized.Equals("pluginaccesskey", StringComparison.Ordinal)
            || normalized.Equals("pointaccesskey", StringComparison.Ordinal)
            || normalized.Equals("policyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("poolaccesskey", StringComparison.Ordinal)
            || normalized.Equals("portaccesskey", StringComparison.Ordinal)
            || normalized.Equals("postaccesskey", StringComparison.Ordinal)
            || normalized.Equals("poweraccesskey", StringComparison.Ordinal)
            || normalized.Equals("premiumaccesskey", StringComparison.Ordinal)
            || normalized.Equals("preparedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("previewaccesskey", StringComparison.Ordinal)
            || normalized.Equals("privateaccesskey", StringComparison.Ordinal)
            || normalized.Equals("processaccesskey", StringComparison.Ordinal)
            || normalized.Equals("profileaccesskey", StringComparison.Ordinal)
            || normalized.Equals("programaccesskey", StringComparison.Ordinal)
            || normalized.Equals("projectaccesskey", StringComparison.Ordinal)
            || normalized.Equals("provisionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("proxyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("publicaccesskey", StringComparison.Ordinal)
            || normalized.Equals("publisheraccesskey", StringComparison.Ordinal)
            || normalized.Equals("pulseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("pushaccesskey", StringComparison.Ordinal)
            || normalized.Equals("purgeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("putaccesskey", StringComparison.Ordinal)
            || normalized.Equals("queryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("quotaaccesskey", StringComparison.Ordinal)
            || normalized.Equals("randomaccesskey", StringComparison.Ordinal)
            || normalized.Equals("rangeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("rateaccesskey", StringComparison.Ordinal)
            || normalized.Equals("readaccesskey", StringComparison.Ordinal)
            || normalized.Equals("recordaccesskey", StringComparison.Ordinal)
            || normalized.Equals("recoveryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("redactaccesskey", StringComparison.Ordinal)
            || normalized.Equals("referaccesskey", StringComparison.Ordinal)
            || normalized.Equals("refreshaccesskey", StringComparison.Ordinal)
            || normalized.Equals("relayaccesskey", StringComparison.Ordinal)
            || normalized.Equals("releaseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("registryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("remediationaccesskey", StringComparison.Ordinal)
            || normalized.Equals("renderaccesskey", StringComparison.Ordinal)
            || normalized.Equals("renewalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("reportaccesskey", StringComparison.Ordinal)
            || normalized.Equals("requestaccesskey", StringComparison.Ordinal)
            || normalized.Equals("resourceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("responseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("restoreaccesskey", StringComparison.Ordinal)
            || normalized.Equals("resultaccesskey", StringComparison.Ordinal)
            || normalized.Equals("retryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("returnaccesskey", StringComparison.Ordinal)
            || normalized.Equals("reverseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("revealaccesskey", StringComparison.Ordinal)
            || normalized.Equals("reviewaccesskey", StringComparison.Ordinal)
            || normalized.Equals("revokeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("rollaccesskey", StringComparison.Ordinal)
            || normalized.Equals("roomaccesskey", StringComparison.Ordinal)
            || normalized.Equals("rotateaccesskey", StringComparison.Ordinal)
            || normalized.Equals("routeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("routeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("routineaccesskey", StringComparison.Ordinal)
            || normalized.Equals("ruleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("runaccesskey", StringComparison.Ordinal)
            || normalized.Equals("runtimeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("rubricaccesskey", StringComparison.Ordinal)
            || normalized.Equals("ruralaccesskey", StringComparison.Ordinal)
            || normalized.Equals("rustaccesskey", StringComparison.Ordinal)
            || normalized.Equals("saleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sampleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sandboxaccesskey", StringComparison.Ordinal)
            || normalized.Equals("scaleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("scanaccesskey", StringComparison.Ordinal)
            || normalized.Equals("scheduleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("schemaaccesskey", StringComparison.Ordinal)
            || normalized.Equals("scopeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("scoreaccesskey", StringComparison.Ordinal)
            || normalized.Equals("scoutaccesskey", StringComparison.Ordinal)
            || normalized.Equals("scratchaccesskey", StringComparison.Ordinal)
            || normalized.Equals("screenaccesskey", StringComparison.Ordinal)
            || normalized.Equals("scriptaccesskey", StringComparison.Ordinal)
            || normalized.Equals("scrollaccesskey", StringComparison.Ordinal)
            || normalized.Equals("searchaccesskey", StringComparison.Ordinal)
            || normalized.Equals("seataccesskey", StringComparison.Ordinal)
            || normalized.Equals("segmentaccesskey", StringComparison.Ordinal)
            || normalized.Equals("selectaccesskey", StringComparison.Ordinal)
            || normalized.Equals("selfaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sendaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sensoraccesskey", StringComparison.Ordinal)
            || normalized.Equals("serialaccesskey", StringComparison.Ordinal)
            || normalized.Equals("serveraccesskey", StringComparison.Ordinal)
            || normalized.Equals("sessionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("setupaccesskey", StringComparison.Ordinal)
            || normalized.Equals("shareaccesskey", StringComparison.Ordinal)
            || normalized.Equals("shelfaccesskey", StringComparison.Ordinal)
            || normalized.Equals("shieldaccesskey", StringComparison.Ordinal)
            || normalized.Equals("shiftaccesskey", StringComparison.Ordinal)
            || normalized.Equals("shipaccesskey", StringComparison.Ordinal)
            || normalized.Equals("shopaccesskey", StringComparison.Ordinal)
            || normalized.Equals("shortaccesskey", StringComparison.Ordinal)
            || normalized.Equals("showaccesskey", StringComparison.Ordinal)
            || normalized.Equals("shotaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sideaccesskey", StringComparison.Ordinal)
            || normalized.Equals("signalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("singleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sinkaccesskey", StringComparison.Ordinal)
            || normalized.Equals("siteaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sizeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("skinaccesskey", StringComparison.Ordinal)
            || normalized.Equals("skipaccesskey", StringComparison.Ordinal)
            || normalized.Equals("slideaccesskey", StringComparison.Ordinal)
            || normalized.Equals("slotaccesskey", StringComparison.Ordinal)
            || normalized.Equals("smallaccesskey", StringComparison.Ordinal)
            || normalized.Equals("smartaccesskey", StringComparison.Ordinal)
            || normalized.Equals("smokeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("snapaccesskey", StringComparison.Ordinal)
            || normalized.Equals("softaccesskey", StringComparison.Ordinal)
            || normalized.Equals("solidaccesskey", StringComparison.Ordinal)
            || normalized.Equals("socketaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sourceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("soundaccesskey", StringComparison.Ordinal)
            || normalized.Equals("spaceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("speedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("spellaccesskey", StringComparison.Ordinal)
            || normalized.Equals("splitaccesskey", StringComparison.Ordinal)
            || normalized.Equals("spotaccesskey", StringComparison.Ordinal)
            || normalized.Equals("stackaccesskey", StringComparison.Ordinal)
            || normalized.Equals("stageaccesskey", StringComparison.Ordinal)
            || normalized.Equals("standaccesskey", StringComparison.Ordinal)
            || normalized.Equals("staraccesskey", StringComparison.Ordinal)
            || normalized.Equals("startaccesskey", StringComparison.Ordinal)
            || normalized.Equals("stateaccesskey", StringComparison.Ordinal)
            || normalized.Equals("staticaccesskey", StringComparison.Ordinal)
            || normalized.Equals("steamaccesskey", StringComparison.Ordinal)
            || normalized.Equals("storeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("streamaccesskey", StringComparison.Ordinal)
            || normalized.Equals("strictaccesskey", StringComparison.Ordinal)
            || normalized.Equals("stringaccesskey", StringComparison.Ordinal)
            || normalized.Equals("structuredaccesskey", StringComparison.Ordinal)
            || normalized.Equals("studioaccesskey", StringComparison.Ordinal)
            || normalized.Equals("stripeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("strongaccesskey", StringComparison.Ordinal)
            || normalized.Equals("strikeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("subaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sumaccesskey", StringComparison.Ordinal)
            || normalized.Equals("supaccesskey", StringComparison.Ordinal)
            || normalized.Equals("superaccesskey", StringComparison.Ordinal)
            || normalized.Equals("supportaccesskey", StringComparison.Ordinal)
            || normalized.Equals("stubaccesskey", StringComparison.Ordinal)
            || normalized.Equals("syncaccesskey", StringComparison.Ordinal)
            || normalized.Equals("systemaccesskey", StringComparison.Ordinal)
            || normalized.Equals("supplieraccesskey", StringComparison.Ordinal)
            || normalized.Equals("subscriptionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("suiteaccesskey", StringComparison.Ordinal)
            || normalized.Equals("supplyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("surveyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("switchaccesskey", StringComparison.Ordinal)
            || normalized.Equals("symbolaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tabaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tagaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tailaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tapaccesskey", StringComparison.Ordinal)
            || normalized.Equals("targetaccesskey", StringComparison.Ordinal)
            || normalized.Equals("taskaccesskey", StringComparison.Ordinal)
            || normalized.Equals("taxaccesskey", StringComparison.Ordinal)
            || normalized.Equals("teamaccesskey", StringComparison.Ordinal)
            || normalized.Equals("techaccesskey", StringComparison.Ordinal)
            || normalized.Equals("telaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tenantaccesskey", StringComparison.Ordinal)
            || normalized.Equals("testaccesskey", StringComparison.Ordinal)
            || normalized.Equals("textaccesskey", StringComparison.Ordinal)
            || normalized.Equals("themeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("thirdaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tieraccesskey", StringComparison.Ordinal)
            || normalized.Equals("tileaccesskey", StringComparison.Ordinal)
            || normalized.Equals("timeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tipaccesskey", StringComparison.Ordinal)
            || normalized.Equals("titleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tokenaccesskey", StringComparison.Ordinal)
            || normalized.Equals("topaccesskey", StringComparison.Ordinal)
            || normalized.Equals("totalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("touchaccesskey", StringComparison.Ordinal)
            || normalized.Equals("traceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("trackaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tradeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("trainaccesskey", StringComparison.Ordinal)
            || normalized.Equals("transferaccesskey", StringComparison.Ordinal)
            || normalized.Equals("transitaccesskey", StringComparison.Ordinal)
            || normalized.Equals("travelaccesskey", StringComparison.Ordinal)
            || normalized.Equals("treataccesskey", StringComparison.Ordinal)
            || normalized.Equals("trendaccesskey", StringComparison.Ordinal)
            || normalized.Equals("trialaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tribeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("trickaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tripleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("trustaccesskey", StringComparison.Ordinal)
            || normalized.Equals("truthaccesskey", StringComparison.Ordinal)
            || normalized.Equals("trophyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("trunkaccesskey", StringComparison.Ordinal)
            || normalized.Equals("trustyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tuneaccesskey", StringComparison.Ordinal)
            || normalized.Equals("turboaccesskey", StringComparison.Ordinal)
            || normalized.Equals("turnaccesskey", StringComparison.Ordinal)
            || normalized.Equals("twinaccesskey", StringComparison.Ordinal)
            || normalized.Equals("twistaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tweakaccesskey", StringComparison.Ordinal)
            || normalized.Equals("twoaccesskey", StringComparison.Ordinal)
            || normalized.Equals("typeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("ultraaccesskey", StringComparison.Ordinal)
            || normalized.Equals("uncleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("underaccesskey", StringComparison.Ordinal)
            || normalized.Equals("unionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("uniqueaccesskey", StringComparison.Ordinal)
            || normalized.Equals("unityaccesskey", StringComparison.Ordinal)
            || normalized.Equals("upperaccesskey", StringComparison.Ordinal)
            || normalized.Equals("urbanaccesskey", StringComparison.Ordinal)
            || normalized.Equals("usableaccesskey", StringComparison.Ordinal)
            || normalized.Equals("usefulaccesskey", StringComparison.Ordinal)
            || normalized.Equals("signingkey", StringComparison.Ordinal)
            || normalized.Equals("signingcertificate", StringComparison.Ordinal)
            || normalized.Equals("signingcertificatepath", StringComparison.Ordinal);
    }

    private static bool IsNegatedSensitiveFragment(string normalized, int fragmentIndex, string fragment)
    {
        if (IsNonPrefixedNegation(normalized, fragmentIndex))
            return true;

        if (IsNoPrefixedNegation(normalized, fragmentIndex))
            return true;

        if (IsUnPrefixedNegation(normalized, fragmentIndex))
            return true;

        if (fragmentIndex == 0
            && normalized.Length > fragment.Length
            && (normalized.AsSpan(fragment.Length).StartsWith("less", StringComparison.Ordinal)
                || normalized.AsSpan(fragment.Length).StartsWith("free", StringComparison.Ordinal)
                || normalized.AsSpan(fragment.Length).StartsWith("izer", StringComparison.Ordinal)))
            return true;

        return false;
    }

    private static bool IsEmbeddedSensitiveFragment(string normalized, int fragmentIndex)
    {
        if (fragmentIndex > 0 && char.IsLetter(normalized[fragmentIndex - 1]))
            return true;

        return false;
    }

    private static bool IsNonPrefixedNegation(string normalized, int fragmentIndex)
    {
        ReadOnlySpan<char> before = normalized.AsSpan(0, fragmentIndex);

        if (before.Length < 3)
            return false;

        return before.EndsWith("non", StringComparison.Ordinal);
    }

    private static bool IsNoPrefixedNegation(string normalized, int fragmentIndex)
    {
        ReadOnlySpan<char> before = normalized.AsSpan(0, fragmentIndex);

        if (before.Length < 2)
            return false;

        return before.EndsWith("no", StringComparison.Ordinal);
    }

    private static bool IsUnPrefixedNegation(string normalized, int fragmentIndex)
    {
        ReadOnlySpan<char> before = normalized.AsSpan(0, fragmentIndex);

        if (before.Length < 2)
            return false;

        return before.EndsWith("un", StringComparison.Ordinal);
    }

    public static string RedactValue(string? value) =>
        string.IsNullOrWhiteSpace(value) ? string.Empty : "[REDACTED]";
}
