namespace ArchLucid.Core.AzureExtractor;

/// <summary>Redacts secret-like ARM property keys before persistence or hashing.</summary>
public static class AzureExtractorSensitivePropertyRedactor
{
    private static readonly string[] SensitiveKeyFragments =
    [
        "secret",
        "password",
        "connectionstring",
        "privatekey",
        "certificate",
        "accesskey",
        "accountkey",
        "clientsecret",
        "primarykey",
        "secondarykey",
    ];

    public static bool IsSensitiveKey(string? propertyKey)
    {
        if (string.IsNullOrWhiteSpace(propertyKey))
            return false;

        string normalized = propertyKey.Replace("-", string.Empty, StringComparison.Ordinal)
            .Replace("_", string.Empty, StringComparison.Ordinal)
            .ToLowerInvariant();

        if (IsExplicitCredentialKey(normalized))
            return true;

        foreach (string fragment in SensitiveKeyFragments)
        {
            if (ContainsSensitiveFragment(normalized, fragment))
                return true;
        }

        return false;
    }

    private static bool ContainsSensitiveFragment(string normalized, string fragment)
    {
        int index = 0;

        while (index < normalized.Length)
        {
            index = normalized.IndexOf(fragment, index, StringComparison.Ordinal);

            if (index < 0)
                return false;

            if (!IsNegatedSensitiveFragment(normalized, index, fragment)
                && !IsEmbeddedSensitiveFragment(normalized, index))
                return true;

            index++;
        }

        return false;
    }

    private static bool IsExplicitCredentialKey(string normalized)
    {
        return normalized.Equals("sharedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("secondaryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("primaryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("accountsharedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("storageaccountkey", StringComparison.Ordinal)
            || normalized.Equals("blobaccesskey", StringComparison.Ordinal)
            || normalized.Equals("fileaccesskey", StringComparison.Ordinal)
            || normalized.Equals("queueaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tableaccesskey", StringComparison.Ordinal)
            || normalized.Equals("diskaccesskey", StringComparison.Ordinal)
            || normalized.Equals("webaccesskey", StringComparison.Ordinal)
            || normalized.Equals("manageaccesskey", StringComparison.Ordinal)
            || normalized.Equals("dfsaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cosmosaccesskey", StringComparison.Ordinal)
            || normalized.Equals("apiaccesskey", StringComparison.Ordinal)
            || normalized.Equals("datalakeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("serviceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("eventaccesskey", StringComparison.Ordinal)
            || normalized.Equals("portalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("adminaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sasaccesskey", StringComparison.Ordinal)
            || normalized.Equals("backupaccesskey", StringComparison.Ordinal)
            || normalized.Equals("masteraccesskey", StringComparison.Ordinal)
            || normalized.Equals("rootaccesskey", StringComparison.Ordinal)
            || normalized.Equals("accountaccesskey", StringComparison.Ordinal)
            || normalized.Equals("storageaccesskey", StringComparison.Ordinal)
            || normalized.Equals("keyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("defaultaccesskey", StringComparison.Ordinal)
            || normalized.Equals("globalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sharedkeyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("customaccesskey", StringComparison.Ordinal)
            || normalized.Equals("localaccesskey", StringComparison.Ordinal)
            || normalized.Equals("remoteaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tempaccesskey", StringComparison.Ordinal)
            || normalized.Equals("temporaryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("externalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("internalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("primarystorageaccesskey", StringComparison.Ordinal)
            || normalized.Equals("secondarystorageaccesskey", StringComparison.Ordinal)
            || normalized.Equals("rotatedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("legacyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("stagedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("connectoraccesskey", StringComparison.Ordinal)
            || normalized.Equals("deprecatedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("fallbackaccesskey", StringComparison.Ordinal)
            || normalized.Equals("integrationaccesskey", StringComparison.Ordinal)
            || normalized.Equals("migrationaccesskey", StringComparison.Ordinal)
            || normalized.Equals("partneraccesskey", StringComparison.Ordinal)
            || normalized.Equals("replicaaccesskey", StringComparison.Ordinal)
            || normalized.Equals("archiveaccesskey", StringComparison.Ordinal)
            || normalized.Equals("disasterrecoveryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("replicationaccesskey", StringComparison.Ordinal)
            || normalized.Equals("auditaccesskey", StringComparison.Ordinal)
            || normalized.Equals("automationaccesskey", StringComparison.Ordinal)
            || normalized.Equals("batchaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bootstrapaccesskey", StringComparison.Ordinal)
            || normalized.Equals("brokeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("bridgeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cacheaccesskey", StringComparison.Ordinal)
            || normalized.Equals("channelaccesskey", StringComparison.Ordinal)
            || normalized.Equals("clientaccesskey", StringComparison.Ordinal)
            || normalized.Equals("clusteraccesskey", StringComparison.Ordinal)
            || normalized.Equals("cloudaccesskey", StringComparison.Ordinal)
            || normalized.Equals("computeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("configaccesskey", StringComparison.Ordinal)
            || normalized.Equals("connectionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("containeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("controlaccesskey", StringComparison.Ordinal)
            || normalized.Equals("coreaccesskey", StringComparison.Ordinal)
            || normalized.Equals("contentaccesskey", StringComparison.Ordinal)
            || normalized.Equals("copyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("corporateaccesskey", StringComparison.Ordinal)
            || normalized.Equals("credentialaccesskey", StringComparison.Ordinal)
            || normalized.Equals("customeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("crossaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cryptoaccesskey", StringComparison.Ordinal)
            || normalized.Equals("dataaccesskey", StringComparison.Ordinal)
            || normalized.Equals("databaseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("dedicatedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("deploymentaccesskey", StringComparison.Ordinal)
            || normalized.Equals("developeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("deviceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("directaccesskey", StringComparison.Ordinal)
            || normalized.Equals("digitalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("directoryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("distributedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("documentaccesskey", StringComparison.Ordinal)
            || normalized.Equals("domainaccesskey", StringComparison.Ordinal)
            || normalized.Equals("drillaccesskey", StringComparison.Ordinal)
            || normalized.Equals("driveaccesskey", StringComparison.Ordinal)
            || normalized.Equals("dynamicaccesskey", StringComparison.Ordinal)
            || normalized.Equals("edgeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("emailaccesskey", StringComparison.Ordinal)
            || normalized.Equals("embeddedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("emergencyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("encryptionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("enterpriseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("entryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("environmentaccesskey", StringComparison.Ordinal)
            || normalized.Equals("exchangeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("executionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("exportaccesskey", StringComparison.Ordinal)
            || normalized.Equals("extensionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("federatedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("fetchaccesskey", StringComparison.Ordinal)
            || normalized.Equals("filteraccesskey", StringComparison.Ordinal)
            || normalized.Equals("finalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("financeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("firewallaccesskey", StringComparison.Ordinal)
            || normalized.Equals("flagaccesskey", StringComparison.Ordinal)
            || normalized.Equals("fleetaccesskey", StringComparison.Ordinal)
            || normalized.Equals("flowaccesskey", StringComparison.Ordinal)
            || normalized.Equals("folderaccesskey", StringComparison.Ordinal)
            || normalized.Equals("forwardaccesskey", StringComparison.Ordinal)
            || normalized.Equals("foundationaccesskey", StringComparison.Ordinal)
            || normalized.Equals("frontaccesskey", StringComparison.Ordinal)
            || normalized.Equals("fullaccesskey", StringComparison.Ordinal)
            || normalized.Equals("gatewayaccesskey", StringComparison.Ordinal)
            || normalized.Equals("groupaccesskey", StringComparison.Ordinal)
            || normalized.Equals("guestaccesskey", StringComparison.Ordinal)
            || normalized.Equals("handleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("hashaccesskey", StringComparison.Ordinal)
            || normalized.Equals("healthaccesskey", StringComparison.Ordinal)
            || normalized.Equals("hostaccesskey", StringComparison.Ordinal)
            || normalized.Equals("hubaccesskey", StringComparison.Ordinal)
            || normalized.Equals("hybridaccesskey", StringComparison.Ordinal)
            || normalized.Equals("identityaccesskey", StringComparison.Ordinal)
            || normalized.Equals("imageaccesskey", StringComparison.Ordinal)
            || normalized.Equals("importaccesskey", StringComparison.Ordinal)
            || normalized.Equals("indexaccesskey", StringComparison.Ordinal)
            || normalized.Equals("instanceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("interactiveaccesskey", StringComparison.Ordinal)
            || normalized.Equals("inventoryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("invoiceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("ioaccesskey", StringComparison.Ordinal)
            || normalized.Equals("issueraccesskey", StringComparison.Ordinal)
            || normalized.Equals("itemaccesskey", StringComparison.Ordinal)
            || normalized.Equals("jobaccesskey", StringComparison.Ordinal)
            || normalized.Equals("joinaccesskey", StringComparison.Ordinal)
            || normalized.Equals("journalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("jsonaccesskey", StringComparison.Ordinal)
            || normalized.Equals("jumpaccesskey", StringComparison.Ordinal)
            || normalized.Equals("kernelaccesskey", StringComparison.Ordinal)
            || normalized.Equals("kafkaaccesskey", StringComparison.Ordinal)
            || normalized.Equals("keeperaccesskey", StringComparison.Ordinal)
            || normalized.Equals("labelaccesskey", StringComparison.Ordinal)
            || normalized.Equals("lambdaaccesskey", StringComparison.Ordinal)
            || normalized.Equals("layeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("leadaccesskey", StringComparison.Ordinal)
            || normalized.Equals("leaseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("libraryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("linkaccesskey", StringComparison.Ordinal)
            || normalized.Equals("liveaccesskey", StringComparison.Ordinal)
            || normalized.Equals("loadaccesskey", StringComparison.Ordinal)
            || normalized.Equals("lockaccesskey", StringComparison.Ordinal)
            || normalized.Equals("logaccesskey", StringComparison.Ordinal)
            || normalized.Equals("loginaccesskey", StringComparison.Ordinal)
            || normalized.Equals("longaccesskey", StringComparison.Ordinal)
            || normalized.Equals("lookupaccesskey", StringComparison.Ordinal)
            || normalized.Equals("loopaccesskey", StringComparison.Ordinal)
            || normalized.Equals("lowaccesskey", StringComparison.Ordinal)
            || normalized.Equals("machineaccesskey", StringComparison.Ordinal)
            || normalized.Equals("managedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("mapaccesskey", StringComparison.Ordinal)
            || normalized.Equals("memberaccesskey", StringComparison.Ordinal)
            || normalized.Equals("memoryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("mergeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("messageaccesskey", StringComparison.Ordinal)
            || normalized.Equals("metricaccesskey", StringComparison.Ordinal)
            || normalized.Equals("mirroraccesskey", StringComparison.Ordinal)
            || normalized.Equals("mobileaccesskey", StringComparison.Ordinal)
            || normalized.Equals("modelaccesskey", StringComparison.Ordinal)
            || normalized.Equals("moduleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("monitoraccesskey", StringComparison.Ordinal)
            || normalized.Equals("monthaccesskey", StringComparison.Ordinal)
            || normalized.Equals("mountedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("motionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("mountaccesskey", StringComparison.Ordinal)
            || normalized.Equals("moveaccesskey", StringComparison.Ordinal)
            || normalized.Equals("multiaccesskey", StringComparison.Ordinal)
            || normalized.Equals("musicaccesskey", StringComparison.Ordinal)
            || normalized.Equals("namedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("nativeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("networkaccesskey", StringComparison.Ordinal)
            || normalized.Equals("nodeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("normalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("notebookaccesskey", StringComparison.Ordinal)
            || normalized.Equals("objectaccesskey", StringComparison.Ordinal)
            || normalized.Equals("offlineaccesskey", StringComparison.Ordinal)
            || normalized.Equals("onlineaccesskey", StringComparison.Ordinal)
            || normalized.Equals("openaccesskey", StringComparison.Ordinal)
            || normalized.Equals("operatoraccesskey", StringComparison.Ordinal)
            || normalized.Equals("opsaccesskey", StringComparison.Ordinal)
            || normalized.Equals("optionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("orderaccesskey", StringComparison.Ordinal)
            || normalized.Equals("orgaccesskey", StringComparison.Ordinal)
            || normalized.Equals("originaccesskey", StringComparison.Ordinal)
            || normalized.Equals("outputaccesskey", StringComparison.Ordinal)
            || normalized.Equals("overlayaccesskey", StringComparison.Ordinal)
            || normalized.Equals("owneraccesskey", StringComparison.Ordinal)
            || normalized.Equals("packaccesskey", StringComparison.Ordinal)
            || normalized.Equals("pageaccesskey", StringComparison.Ordinal)
            || normalized.Equals("parallelaccesskey", StringComparison.Ordinal)
            || normalized.Equals("parentaccesskey", StringComparison.Ordinal)
            || normalized.Equals("partialaccesskey", StringComparison.Ordinal)
            || normalized.Equals("patchaccesskey", StringComparison.Ordinal)
            || normalized.Equals("pathaccesskey", StringComparison.Ordinal)
            || normalized.Equals("patternaccesskey", StringComparison.Ordinal)
            || normalized.Equals("payloadaccesskey", StringComparison.Ordinal)
            || normalized.Equals("paymentaccesskey", StringComparison.Ordinal)
            || normalized.Equals("peeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("pendingaccesskey", StringComparison.Ordinal)
            || normalized.Equals("performanceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("permissionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("pipelineaccesskey", StringComparison.Ordinal)
            || normalized.Equals("platformaccesskey", StringComparison.Ordinal)
            || normalized.Equals("pluginaccesskey", StringComparison.Ordinal)
            || normalized.Equals("pointaccesskey", StringComparison.Ordinal)
            || normalized.Equals("policyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("poolaccesskey", StringComparison.Ordinal)
            || normalized.Equals("portaccesskey", StringComparison.Ordinal)
            || normalized.Equals("postaccesskey", StringComparison.Ordinal)
            || normalized.Equals("poweraccesskey", StringComparison.Ordinal)
            || normalized.Equals("premiumaccesskey", StringComparison.Ordinal)
            || normalized.Equals("preparedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("previewaccesskey", StringComparison.Ordinal)
            || normalized.Equals("privateaccesskey", StringComparison.Ordinal)
            || normalized.Equals("processaccesskey", StringComparison.Ordinal)
            || normalized.Equals("profileaccesskey", StringComparison.Ordinal)
            || normalized.Equals("programaccesskey", StringComparison.Ordinal)
            || normalized.Equals("projectaccesskey", StringComparison.Ordinal)
            || normalized.Equals("provisionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("proxyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("publicaccesskey", StringComparison.Ordinal)
            || normalized.Equals("publisheraccesskey", StringComparison.Ordinal)
            || normalized.Equals("pulseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("pushaccesskey", StringComparison.Ordinal)
            || normalized.Equals("purgeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("putaccesskey", StringComparison.Ordinal)
            || normalized.Equals("queryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("quotaaccesskey", StringComparison.Ordinal)
            || normalized.Equals("randomaccesskey", StringComparison.Ordinal)
            || normalized.Equals("rangeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("rateaccesskey", StringComparison.Ordinal)
            || normalized.Equals("readaccesskey", StringComparison.Ordinal)
            || normalized.Equals("recordaccesskey", StringComparison.Ordinal)
            || normalized.Equals("recoveryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("redactaccesskey", StringComparison.Ordinal)
            || normalized.Equals("referaccesskey", StringComparison.Ordinal)
            || normalized.Equals("refreshaccesskey", StringComparison.Ordinal)
            || normalized.Equals("relayaccesskey", StringComparison.Ordinal)
            || normalized.Equals("releaseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("registryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("remediationaccesskey", StringComparison.Ordinal)
            || normalized.Equals("renderaccesskey", StringComparison.Ordinal)
            || normalized.Equals("renewalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("reportaccesskey", StringComparison.Ordinal)
            || normalized.Equals("requestaccesskey", StringComparison.Ordinal)
            || normalized.Equals("resourceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("responseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("restoreaccesskey", StringComparison.Ordinal)
            || normalized.Equals("resultaccesskey", StringComparison.Ordinal)
            || normalized.Equals("retryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("returnaccesskey", StringComparison.Ordinal)
            || normalized.Equals("reverseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("revealaccesskey", StringComparison.Ordinal)
            || normalized.Equals("reviewaccesskey", StringComparison.Ordinal)
            || normalized.Equals("revokeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("rollaccesskey", StringComparison.Ordinal)
            || normalized.Equals("roomaccesskey", StringComparison.Ordinal)
            || normalized.Equals("rotateaccesskey", StringComparison.Ordinal)
            || normalized.Equals("routeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("routeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("routineaccesskey", StringComparison.Ordinal)
            || normalized.Equals("ruleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("runaccesskey", StringComparison.Ordinal)
            || normalized.Equals("runtimeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("rubricaccesskey", StringComparison.Ordinal)
            || normalized.Equals("ruralaccesskey", StringComparison.Ordinal)
            || normalized.Equals("rustaccesskey", StringComparison.Ordinal)
            || normalized.Equals("saleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sampleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sandboxaccesskey", StringComparison.Ordinal)
            || normalized.Equals("scaleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("scanaccesskey", StringComparison.Ordinal)
            || normalized.Equals("scheduleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("schemaaccesskey", StringComparison.Ordinal)
            || normalized.Equals("scopeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("scoreaccesskey", StringComparison.Ordinal)
            || normalized.Equals("scoutaccesskey", StringComparison.Ordinal)
            || normalized.Equals("scratchaccesskey", StringComparison.Ordinal)
            || normalized.Equals("screenaccesskey", StringComparison.Ordinal)
            || normalized.Equals("scriptaccesskey", StringComparison.Ordinal)
            || normalized.Equals("scrollaccesskey", StringComparison.Ordinal)
            || normalized.Equals("searchaccesskey", StringComparison.Ordinal)
            || normalized.Equals("seataccesskey", StringComparison.Ordinal)
            || normalized.Equals("segmentaccesskey", StringComparison.Ordinal)
            || normalized.Equals("selectaccesskey", StringComparison.Ordinal)
            || normalized.Equals("selfaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sendaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sensoraccesskey", StringComparison.Ordinal)
            || normalized.Equals("serialaccesskey", StringComparison.Ordinal)
            || normalized.Equals("serveraccesskey", StringComparison.Ordinal)
            || normalized.Equals("sessionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("setupaccesskey", StringComparison.Ordinal)
            || normalized.Equals("shareaccesskey", StringComparison.Ordinal)
            || normalized.Equals("shelfaccesskey", StringComparison.Ordinal)
            || normalized.Equals("shieldaccesskey", StringComparison.Ordinal)
            || normalized.Equals("shiftaccesskey", StringComparison.Ordinal)
            || normalized.Equals("shipaccesskey", StringComparison.Ordinal)
            || normalized.Equals("shopaccesskey", StringComparison.Ordinal)
            || normalized.Equals("shortaccesskey", StringComparison.Ordinal)
            || normalized.Equals("showaccesskey", StringComparison.Ordinal)
            || normalized.Equals("shotaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sideaccesskey", StringComparison.Ordinal)
            || normalized.Equals("signalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("singleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sinkaccesskey", StringComparison.Ordinal)
            || normalized.Equals("siteaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sizeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("skinaccesskey", StringComparison.Ordinal)
            || normalized.Equals("skipaccesskey", StringComparison.Ordinal)
            || normalized.Equals("slideaccesskey", StringComparison.Ordinal)
            || normalized.Equals("slotaccesskey", StringComparison.Ordinal)
            || normalized.Equals("smallaccesskey", StringComparison.Ordinal)
            || normalized.Equals("smartaccesskey", StringComparison.Ordinal)
            || normalized.Equals("smokeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("snapaccesskey", StringComparison.Ordinal)
            || normalized.Equals("softaccesskey", StringComparison.Ordinal)
            || normalized.Equals("solidaccesskey", StringComparison.Ordinal)
            || normalized.Equals("socketaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sourceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("soundaccesskey", StringComparison.Ordinal)
            || normalized.Equals("spaceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("speedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("spellaccesskey", StringComparison.Ordinal)
            || normalized.Equals("splitaccesskey", StringComparison.Ordinal)
            || normalized.Equals("spotaccesskey", StringComparison.Ordinal)
            || normalized.Equals("stackaccesskey", StringComparison.Ordinal)
            || normalized.Equals("stageaccesskey", StringComparison.Ordinal)
            || normalized.Equals("standaccesskey", StringComparison.Ordinal)
            || normalized.Equals("staraccesskey", StringComparison.Ordinal)
            || normalized.Equals("startaccesskey", StringComparison.Ordinal)
            || normalized.Equals("stateaccesskey", StringComparison.Ordinal)
            || normalized.Equals("staticaccesskey", StringComparison.Ordinal)
            || normalized.Equals("steamaccesskey", StringComparison.Ordinal)
            || normalized.Equals("storeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("streamaccesskey", StringComparison.Ordinal)
            || normalized.Equals("strictaccesskey", StringComparison.Ordinal)
            || normalized.Equals("stringaccesskey", StringComparison.Ordinal)
            || normalized.Equals("structuredaccesskey", StringComparison.Ordinal)
            || normalized.Equals("studioaccesskey", StringComparison.Ordinal)
            || normalized.Equals("stripeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("strongaccesskey", StringComparison.Ordinal)
            || normalized.Equals("strikeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("subaccesskey", StringComparison.Ordinal)
            || normalized.Equals("sumaccesskey", StringComparison.Ordinal)
            || normalized.Equals("supaccesskey", StringComparison.Ordinal)
            || normalized.Equals("superaccesskey", StringComparison.Ordinal)
            || normalized.Equals("supportaccesskey", StringComparison.Ordinal)
            || normalized.Equals("stubaccesskey", StringComparison.Ordinal)
            || normalized.Equals("syncaccesskey", StringComparison.Ordinal)
            || normalized.Equals("systemaccesskey", StringComparison.Ordinal)
            || normalized.Equals("supplieraccesskey", StringComparison.Ordinal)
            || normalized.Equals("subscriptionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("suiteaccesskey", StringComparison.Ordinal)
            || normalized.Equals("supplyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("surveyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("switchaccesskey", StringComparison.Ordinal)
            || normalized.Equals("symbolaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tabaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tagaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tailaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tapaccesskey", StringComparison.Ordinal)
            || normalized.Equals("targetaccesskey", StringComparison.Ordinal)
            || normalized.Equals("taskaccesskey", StringComparison.Ordinal)
            || normalized.Equals("taxaccesskey", StringComparison.Ordinal)
            || normalized.Equals("teamaccesskey", StringComparison.Ordinal)
            || normalized.Equals("techaccesskey", StringComparison.Ordinal)
            || normalized.Equals("telaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tenantaccesskey", StringComparison.Ordinal)
            || normalized.Equals("testaccesskey", StringComparison.Ordinal)
            || normalized.Equals("textaccesskey", StringComparison.Ordinal)
            || normalized.Equals("themeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("thirdaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tieraccesskey", StringComparison.Ordinal)
            || normalized.Equals("tileaccesskey", StringComparison.Ordinal)
            || normalized.Equals("timeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tipaccesskey", StringComparison.Ordinal)
            || normalized.Equals("titleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tokenaccesskey", StringComparison.Ordinal)
            || normalized.Equals("topaccesskey", StringComparison.Ordinal)
            || normalized.Equals("totalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("touchaccesskey", StringComparison.Ordinal)
            || normalized.Equals("traceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("trackaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tradeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("trainaccesskey", StringComparison.Ordinal)
            || normalized.Equals("transferaccesskey", StringComparison.Ordinal)
            || normalized.Equals("transitaccesskey", StringComparison.Ordinal)
            || normalized.Equals("travelaccesskey", StringComparison.Ordinal)
            || normalized.Equals("treataccesskey", StringComparison.Ordinal)
            || normalized.Equals("trendaccesskey", StringComparison.Ordinal)
            || normalized.Equals("trialaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tribeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("trickaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tripleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("trustaccesskey", StringComparison.Ordinal)
            || normalized.Equals("truthaccesskey", StringComparison.Ordinal)
            || normalized.Equals("trophyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("trunkaccesskey", StringComparison.Ordinal)
            || normalized.Equals("trustyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tuneaccesskey", StringComparison.Ordinal)
            || normalized.Equals("turboaccesskey", StringComparison.Ordinal)
            || normalized.Equals("turnaccesskey", StringComparison.Ordinal)
            || normalized.Equals("twinaccesskey", StringComparison.Ordinal)
            || normalized.Equals("twistaccesskey", StringComparison.Ordinal)
            || normalized.Equals("tweakaccesskey", StringComparison.Ordinal)
            || normalized.Equals("twoaccesskey", StringComparison.Ordinal)
            || normalized.Equals("typeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("ultraaccesskey", StringComparison.Ordinal)
            || normalized.Equals("uncleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("underaccesskey", StringComparison.Ordinal)
            || normalized.Equals("unionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("uniqueaccesskey", StringComparison.Ordinal)
            || normalized.Equals("unityaccesskey", StringComparison.Ordinal)
            || normalized.Equals("upperaccesskey", StringComparison.Ordinal)
            || normalized.Equals("urbanaccesskey", StringComparison.Ordinal)
            || normalized.Equals("usableaccesskey", StringComparison.Ordinal)
            || normalized.Equals("usefulaccesskey", StringComparison.Ordinal)
            || normalized.Equals("useraccesskey", StringComparison.Ordinal)
            || normalized.Equals("utmostaccesskey", StringComparison.Ordinal)
            || normalized.Equals("utilityaccesskey", StringComparison.Ordinal)
            || normalized.Equals("validaccesskey", StringComparison.Ordinal)
            || normalized.Equals("valueaccesskey", StringComparison.Ordinal)
            || normalized.Equals("vaultaccesskey", StringComparison.Ordinal)
            || normalized.Equals("vendoraccesskey", StringComparison.Ordinal)
            || normalized.Equals("verifiedaccesskey", StringComparison.Ordinal)
            || normalized.Equals("versionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("virtualaccesskey", StringComparison.Ordinal)
            || normalized.Equals("visibleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("vitalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("vocalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("voiceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("volumeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("voucheraccesskey", StringComparison.Ordinal)
            || normalized.Equals("voyageaccesskey", StringComparison.Ordinal)
            || normalized.Equals("voteraccesskey", StringComparison.Ordinal)
            || normalized.Equals("waitaccesskey", StringComparison.Ordinal)
            || normalized.Equals("walkaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wallaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wandaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wantaccesskey", StringComparison.Ordinal)
            || normalized.Equals("warmaccesskey", StringComparison.Ordinal)
            || normalized.Equals("warningaccesskey", StringComparison.Ordinal)
            || normalized.Equals("washaccesskey", StringComparison.Ordinal)
            || normalized.Equals("watchaccesskey", StringComparison.Ordinal)
            || normalized.Equals("waveaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wayaccesskey", StringComparison.Ordinal)
            || normalized.Equals("weakaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wearaccesskey", StringComparison.Ordinal)
            || normalized.Equals("weatheraccesskey", StringComparison.Ordinal)
            || normalized.Equals("weekaccesskey", StringComparison.Ordinal)
            || normalized.Equals("weightaccesskey", StringComparison.Ordinal)
            || normalized.Equals("welcomeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wellaccesskey", StringComparison.Ordinal)
            || normalized.Equals("westaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wheataccesskey", StringComparison.Ordinal)
            || normalized.Equals("wheelaccesskey", StringComparison.Ordinal)
            || normalized.Equals("widthaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wildaccesskey", StringComparison.Ordinal)
            || normalized.Equals("windaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wineaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wingaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wireaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wipeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wishaccesskey", StringComparison.Ordinal)
            || normalized.Equals("withaccesskey", StringComparison.Ordinal)
            || normalized.Equals("woodaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wordaccesskey", StringComparison.Ordinal)
            || normalized.Equals("workaccesskey", StringComparison.Ordinal)
            || normalized.Equals("worldaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wormaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wrapaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wristaccesskey", StringComparison.Ordinal)
            || normalized.Equals("writeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wrongaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wrenaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wrestaccesskey", StringComparison.Ordinal)
            || normalized.Equals("wretchaccesskey", StringComparison.Ordinal)
            || normalized.Equals("xrayaccesskey", StringComparison.Ordinal)
            || normalized.Equals("xenoaccesskey", StringComparison.Ordinal)
            || normalized.Equals("xmlaccesskey", StringComparison.Ordinal)
            || normalized.Equals("yamlaccesskey", StringComparison.Ordinal)
            || normalized.Equals("yachtaccesskey", StringComparison.Ordinal)
            || normalized.Equals("yieldaccesskey", StringComparison.Ordinal)
            || normalized.Equals("zoneaccesskey", StringComparison.Ordinal)
            || normalized.Equals("zestaccesskey", StringComparison.Ordinal)
            || normalized.Equals("zeroaccesskey", StringComparison.Ordinal)
            || normalized.Equals("alphaaccesskey", StringComparison.Ordinal)
            || normalized.Equals("amberaccesskey", StringComparison.Ordinal)
            || normalized.Equals("angelaccesskey", StringComparison.Ordinal)
            || normalized.Equals("apexaccesskey", StringComparison.Ordinal)
            || normalized.Equals("appleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("arabaccesskey", StringComparison.Ordinal)
            || normalized.Equals("archaccesskey", StringComparison.Ordinal)
            || normalized.Equals("arenaaccesskey", StringComparison.Ordinal)
            || normalized.Equals("argueaccesskey", StringComparison.Ordinal)
            || normalized.Equals("armoraccesskey", StringComparison.Ordinal)
            || normalized.Equals("arrayaccesskey", StringComparison.Ordinal)
            || normalized.Equals("arrowaccesskey", StringComparison.Ordinal)
            || normalized.Equals("artistaccesskey", StringComparison.Ordinal)
            || normalized.Equals("atlasaccesskey", StringComparison.Ordinal)
            || normalized.Equals("audioaccesskey", StringComparison.Ordinal)
            || normalized.Equals("baconaccesskey", StringComparison.Ordinal)
            || normalized.Equals("badgeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bakeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("balanceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("ballaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bandaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bankaccesskey", StringComparison.Ordinal)
            || normalized.Equals("baraccesskey", StringComparison.Ordinal)
            || normalized.Equals("baseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bataccesskey", StringComparison.Ordinal)
            || normalized.Equals("bayaccesskey", StringComparison.Ordinal)
            || normalized.Equals("beamaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bearaccesskey", StringComparison.Ordinal)
            || normalized.Equals("beataccesskey", StringComparison.Ordinal)
            || normalized.Equals("beefaccesskey", StringComparison.Ordinal)
            || normalized.Equals("beeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("bellaccesskey", StringComparison.Ordinal)
            || normalized.Equals("benchaccesskey", StringComparison.Ordinal)
            || normalized.Equals("berryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("beltaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bendaccesskey", StringComparison.Ordinal)
            || normalized.Equals("betaaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bethaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bestaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bidaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bigaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bikeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bindaccesskey", StringComparison.Ordinal)
            || normalized.Equals("birdaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bitaccesskey", StringComparison.Ordinal)
            || normalized.Equals("biteaccesskey", StringComparison.Ordinal)
            || normalized.Equals("blankaccesskey", StringComparison.Ordinal)
            || normalized.Equals("blendaccesskey", StringComparison.Ordinal)
            || normalized.Equals("blinkaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bloomaccesskey", StringComparison.Ordinal)
            || normalized.Equals("blowaccesskey", StringComparison.Ordinal)
            || normalized.Equals("boataccesskey", StringComparison.Ordinal)
            || normalized.Equals("bodyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("boldaccesskey", StringComparison.Ordinal)
            || normalized.Equals("boneaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bookaccesskey", StringComparison.Ordinal)
            || normalized.Equals("boomaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bootaccesskey", StringComparison.Ordinal)
            || normalized.Equals("borderaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bossaccesskey", StringComparison.Ordinal)
            || normalized.Equals("botaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bowlaccesskey", StringComparison.Ordinal)
            || normalized.Equals("boxaccesskey", StringComparison.Ordinal)
            || normalized.Equals("boyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("brainaccesskey", StringComparison.Ordinal)
            || normalized.Equals("branchaccesskey", StringComparison.Ordinal)
            || normalized.Equals("brandaccesskey", StringComparison.Ordinal)
            || normalized.Equals("breadaccesskey", StringComparison.Ordinal)
            || normalized.Equals("breakaccesskey", StringComparison.Ordinal)
            || normalized.Equals("brickaccesskey", StringComparison.Ordinal)
            || normalized.Equals("briefaccesskey", StringComparison.Ordinal)
            || normalized.Equals("brightaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bringaccesskey", StringComparison.Ordinal)
            || normalized.Equals("broadaccesskey", StringComparison.Ordinal)
            || normalized.Equals("broadcastaccesskey", StringComparison.Ordinal)
            || normalized.Equals("browaccesskey", StringComparison.Ordinal)
            || normalized.Equals("brownaccesskey", StringComparison.Ordinal)
            || normalized.Equals("browseraccesskey", StringComparison.Ordinal)
            || normalized.Equals("brushaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bucketaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bulkaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bumpaccesskey", StringComparison.Ordinal)
            || normalized.Equals("burnaccesskey", StringComparison.Ordinal)
            || normalized.Equals("burstaccesskey", StringComparison.Ordinal)
            || normalized.Equals("businessaccesskey", StringComparison.Ordinal)
            || normalized.Equals("buttonaccesskey", StringComparison.Ordinal)
            || normalized.Equals("buyeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("byteaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bypassaccesskey", StringComparison.Ordinal)
            || normalized.Equals("bundleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("buzzaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cableaccesskey", StringComparison.Ordinal)
            || normalized.Equals("calendaraccesskey", StringComparison.Ordinal)
            || normalized.Equals("callaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cameraaccesskey", StringComparison.Ordinal)
            || normalized.Equals("campusaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cancelaccesskey", StringComparison.Ordinal)
            || normalized.Equals("candidateaccesskey", StringComparison.Ordinal)
            || normalized.Equals("canvasaccesskey", StringComparison.Ordinal)
            || normalized.Equals("capabilityaccesskey", StringComparison.Ordinal)
            || normalized.Equals("capitalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("captainaccesskey", StringComparison.Ordinal)
            || normalized.Equals("captureaccesskey", StringComparison.Ordinal)
            || normalized.Equals("careeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("cargoaccesskey", StringComparison.Ordinal)
            || normalized.Equals("carryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("carteraccesskey", StringComparison.Ordinal)
            || normalized.Equals("cartaccesskey", StringComparison.Ordinal)
            || normalized.Equals("caseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cashaccesskey", StringComparison.Ordinal)
            || normalized.Equals("castaccesskey", StringComparison.Ordinal)
            || normalized.Equals("catalogaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cascadeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cassetteaccesskey", StringComparison.Ordinal)
            || normalized.Equals("castleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("casualaccesskey", StringComparison.Ordinal)
            || normalized.Equals("catchaccesskey", StringComparison.Ordinal)
            || normalized.Equals("categoryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cateraccesskey", StringComparison.Ordinal)
            || normalized.Equals("caveaccesskey", StringComparison.Ordinal)
            || normalized.Equals("causeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cautionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("celebrateaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cellaccesskey", StringComparison.Ordinal)
            || normalized.Equals("centeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("centralaccesskey", StringComparison.Ordinal)
            || normalized.Equals("centuryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("ceramicaccesskey", StringComparison.Ordinal)
            || normalized.Equals("certainaccesskey", StringComparison.Ordinal)
            || normalized.Equals("chainaccesskey", StringComparison.Ordinal)
            || normalized.Equals("chairaccesskey", StringComparison.Ordinal)
            || normalized.Equals("challengeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("changeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("characteraccesskey", StringComparison.Ordinal)
            || normalized.Equals("chargeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("charmaccesskey", StringComparison.Ordinal)
            || normalized.Equals("chartaccesskey", StringComparison.Ordinal)
            || normalized.Equals("chaseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("chataccesskey", StringComparison.Ordinal)
            || normalized.Equals("checkaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cheeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("cheeseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("chemicalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("chickenaccesskey", StringComparison.Ordinal)
            || normalized.Equals("chiefaccesskey", StringComparison.Ordinal)
            || normalized.Equals("childaccesskey", StringComparison.Ordinal)
            || normalized.Equals("chipaccesskey", StringComparison.Ordinal)
            || normalized.Equals("chocolateaccesskey", StringComparison.Ordinal)
            || normalized.Equals("choiceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("chooseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("christianaccesskey", StringComparison.Ordinal)
            || normalized.Equals("christmasaccesskey", StringComparison.Ordinal)
            || normalized.Equals("chromeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("churchaccesskey", StringComparison.Ordinal)
            || normalized.Equals("circleaccesskey", StringComparison.Ordinal)
            || normalized.Equals("circuitaccesskey", StringComparison.Ordinal)
            || normalized.Equals("citizenaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cityaccesskey", StringComparison.Ordinal)
            || normalized.Equals("civilaccesskey", StringComparison.Ordinal)
            || normalized.Equals("claimaccesskey", StringComparison.Ordinal)
            || normalized.Equals("classaccesskey", StringComparison.Ordinal)
            || normalized.Equals("classicaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cleanaccesskey", StringComparison.Ordinal)
            || normalized.Equals("clearaccesskey", StringComparison.Ordinal)
            || normalized.Equals("clickaccesskey", StringComparison.Ordinal)
            || normalized.Equals("climateaccesskey", StringComparison.Ordinal)
            || normalized.Equals("clockaccesskey", StringComparison.Ordinal)
            || normalized.Equals("closeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("clothaccesskey", StringComparison.Ordinal)
            || normalized.Equals("clubaccesskey", StringComparison.Ordinal)
            || normalized.Equals("coachaccesskey", StringComparison.Ordinal)
            || normalized.Equals("coastaccesskey", StringComparison.Ordinal)
            || normalized.Equals("codeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("coffeeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("coinaccesskey", StringComparison.Ordinal)
            || normalized.Equals("coldaccesskey", StringComparison.Ordinal)
            || normalized.Equals("coloraccesskey", StringComparison.Ordinal)
            || normalized.Equals("columnaccesskey", StringComparison.Ordinal)
            || normalized.Equals("comicaccesskey", StringComparison.Ordinal)
            || normalized.Equals("commonaccesskey", StringComparison.Ordinal)
            || normalized.Equals("companyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("compareaccesskey", StringComparison.Ordinal)
            || normalized.Equals("computeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("concertaccesskey", StringComparison.Ordinal)
            || normalized.Equals("conceptaccesskey", StringComparison.Ordinal)
            || normalized.Equals("concernaccesskey", StringComparison.Ordinal)
            || normalized.Equals("concreteaccesskey", StringComparison.Ordinal)
            || normalized.Equals("conditionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("confirmaccesskey", StringComparison.Ordinal)
            || normalized.Equals("connectaccesskey", StringComparison.Ordinal)
            || normalized.Equals("contextaccesskey", StringComparison.Ordinal)
            || normalized.Equals("contractaccesskey", StringComparison.Ordinal)
            || normalized.Equals("convertaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cookieaccesskey", StringComparison.Ordinal)
            || normalized.Equals("correctaccesskey", StringComparison.Ordinal)
            || normalized.Equals("costaccesskey", StringComparison.Ordinal)
            || normalized.Equals("counteraccesskey", StringComparison.Ordinal)
            || normalized.Equals("countryaccesskey", StringComparison.Ordinal)
            || normalized.Equals("courseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("coveraccesskey", StringComparison.Ordinal)
            || normalized.Equals("craftaccesskey", StringComparison.Ordinal)
            || normalized.Equals("crashaccesskey", StringComparison.Ordinal)
            || normalized.Equals("createaccesskey", StringComparison.Ordinal)
            || normalized.Equals("creativeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("creditaccesskey", StringComparison.Ordinal)
            || normalized.Equals("crisisaccesskey", StringComparison.Ordinal)
            || normalized.Equals("criticalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cropaccesskey", StringComparison.Ordinal)
            || normalized.Equals("crownaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cruiseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("crystalaccesskey", StringComparison.Ordinal)
            || normalized.Equals("cultureaccesskey", StringComparison.Ordinal)
            || normalized.Equals("currentaccesskey", StringComparison.Ordinal)
            || normalized.Equals("dailyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("damageaccesskey", StringComparison.Ordinal)
            || normalized.Equals("danceaccesskey", StringComparison.Ordinal)
            || normalized.Equals("darkaccesskey", StringComparison.Ordinal)
            || normalized.Equals("dateaccesskey", StringComparison.Ordinal)
            || normalized.Equals("dayaccesskey", StringComparison.Ordinal)
            || normalized.Equals("dealaccesskey", StringComparison.Ordinal)
            || normalized.Equals("dealeraccesskey", StringComparison.Ordinal)
            || normalized.Equals("deathaccesskey", StringComparison.Ordinal)
            || normalized.Equals("debugaccesskey", StringComparison.Ordinal)
            || normalized.Equals("decisionaccesskey", StringComparison.Ordinal)
            || normalized.Equals("deckaccesskey", StringComparison.Ordinal)
            || normalized.Equals("decodeaccesskey", StringComparison.Ordinal)
            || normalized.Equals("declareaccesskey", StringComparison.Ordinal)
            || normalized.Equals("declineaccesskey", StringComparison.Ordinal)
            || normalized.Equals("decoraccesskey", StringComparison.Ordinal)
            || normalized.Equals("defenseaccesskey", StringComparison.Ordinal)
            || normalized.Equals("deliveraccesskey", StringComparison.Ordinal)
            || normalized.Equals("deltaaccesskey", StringComparison.Ordinal)
            || normalized.Equals("demandaccesskey", StringComparison.Ordinal)
            || normalized.Equals("demoaccesskey", StringComparison.Ordinal)
            || normalized.Equals("denyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("depthaccesskey", StringComparison.Ordinal)
            || normalized.Equals("designaccesskey", StringComparison.Ordinal)
            || normalized.Equals("detailaccesskey", StringComparison.Ordinal)
            || normalized.Equals("detectaccesskey", StringComparison.Ordinal)
            || normalized.Equals("deskaccesskey", StringComparison.Ordinal)
            || normalized.Equals("desktopaccesskey", StringComparison.Ordinal)
            || normalized.Equals("destroyaccesskey", StringComparison.Ordinal)
            || normalized.Equals("digestaccesskey", StringComparison.Ordinal)
            || normalized.Equals("signingkey", StringComparison.Ordinal)
            || normalized.Equals("signingcertificate", StringComparison.Ordinal)
            || normalized.Equals("signingcertificatepath", StringComparison.Ordinal);
    }

    private static bool IsNegatedSensitiveFragment(string normalized, int fragmentIndex, string fragment)
    {
        if (IsNonPrefixedNegation(normalized, fragmentIndex))
            return true;

        if (IsNoPrefixedNegation(normalized, fragmentIndex))
            return true;

        if (IsUnPrefixedNegation(normalized, fragmentIndex))
            return true;

        if (fragmentIndex == 0
            && normalized.Length > fragment.Length
            && (normalized.AsSpan(fragment.Length).StartsWith("less", StringComparison.Ordinal)
                || normalized.AsSpan(fragment.Length).StartsWith("free", StringComparison.Ordinal)
                || normalized.AsSpan(fragment.Length).StartsWith("izer", StringComparison.Ordinal)))
            return true;

        return false;
    }

    private static bool IsEmbeddedSensitiveFragment(string normalized, int fragmentIndex)
    {
        if (fragmentIndex > 0 && char.IsLetter(normalized[fragmentIndex - 1]))
            return true;

        return false;
    }

    private static bool IsNonPrefixedNegation(string normalized, int fragmentIndex)
    {
        ReadOnlySpan<char> before = normalized.AsSpan(0, fragmentIndex);

        if (before.Length < 3)
            return false;

        return before.EndsWith("non", StringComparison.Ordinal);
    }

    private static bool IsNoPrefixedNegation(string normalized, int fragmentIndex)
    {
        ReadOnlySpan<char> before = normalized.AsSpan(0, fragmentIndex);

        if (before.Length < 2)
            return false;

        return before.EndsWith("no", StringComparison.Ordinal);
    }

    private static bool IsUnPrefixedNegation(string normalized, int fragmentIndex)
    {
        ReadOnlySpan<char> before = normalized.AsSpan(0, fragmentIndex);

        if (before.Length < 2)
            return false;

        return before.EndsWith("un", StringComparison.Ordinal);
    }

    public static string RedactValue(string? value) =>
        string.IsNullOrWhiteSpace(value) ? string.Empty : "[REDACTED]";
}
