import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import { GeneratedByModelAliasDisclosure } from "@/components/GeneratedByModelAliasDisclosure";

describe("GeneratedByModelAliasDisclosure", () => {
  it("renders nothing when alias is absent", () => {
    const { container } = render(<GeneratedByModelAliasDisclosure modelAlias={null} />);

    expect(container).toBeEmptyDOMElement();
  });

  it("shows governed alias in disclosure summary", () => {
    render(<GeneratedByModelAliasDisclosure modelAlias="balanced-default" />);

    expect(screen.getByTestId("generated-by-model-alias-disclosure")).toHaveTextContent(
      "Generated by balanced-default",
    );
  });
});
