import { cn } from "@/lib/utils";
import { OPERATOR_TYPOGRAPHY } from "@/lib/design-tokens";

type Props = {
  readonly modelAlias: string | null | undefined;
  readonly className?: string;
};

function trimmedAlias(value: string | null | undefined): string {
  return typeof value === "string" ? value.trim() : "";
}

/**
 * Buyer-facing disclosure for approved model alias (TB-871). Never shows raw deployment names.
 */
export function GeneratedByModelAliasDisclosure(props: Props) {
  const alias = trimmedAlias(props.modelAlias);

  if (alias.length === 0) {
    return null;
  }

  return (
    <details
      className={cn(
        "rounded-md border border-neutral-200 bg-white/60 p-2 text-neutral-700 dark:border-neutral-700 dark:bg-neutral-950/40 dark:text-neutral-300",
        OPERATOR_TYPOGRAPHY.helper,
        props.className,
      )}
      data-testid="generated-by-model-alias-disclosure"
    >
      <summary className="cursor-pointer font-medium text-neutral-800 dark:text-neutral-200">
        Generated by <span className="font-mono">{alias}</span>
      </summary>
      <p className="m-0 mt-2 leading-relaxed">
        This output used the approved model alias <span className="font-mono">{alias}</span> from your workspace model
        registry. Deployment names are not shown in buyer-facing surfaces.
      </p>
    </details>
  );
}
