using System.IO.Compression;
using System.Text;
using System.Text.Json;

namespace ArchLucid.Integrations.AzureExtractor;

/// <summary>
///     Builds schema v1 Azure extractor ZIP bytes matching the PowerShell collector layout.
/// </summary>
public static class HostedAzureExtractorZipBuilder
{
    private const int SchemaVersion = 1;

    private const string HostedScriptVersion = "hosted-1.0.0";

    private static readonly JsonSerializerOptions SerializerOptions =
        new()
        {
            WriteIndented = true
        };

    public static byte[] BuildZip(
        string subscriptionId,
        IReadOnlyList<HostedAzureArmResourceRecord> resources,
        bool includeCostRequested,
        DateTimeOffset collectionTimestampUtc)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(subscriptionId);

        string scope = $"/subscriptions/{subscriptionId.Trim()}";
        List<string> switchesUsed = [];

        if (includeCostRequested)
            switchesUsed.Add("IncludeCost");

        Dictionary<string, object?> manifest = new(StringComparer.Ordinal)
        {
            ["schemaVersion"] = SchemaVersion,
            ["scriptVersion"] = HostedScriptVersion,
            ["collectionTimestamp"] = collectionTimestampUtc.ToString("o"),
            ["subscriptionId"] = subscriptionId.Trim(),
            ["scope"] = scope,
            ["switchesUsed"] = switchesUsed,
            ["azModuleVersion"] = "hosted-extractor"
        };

        if (includeCostRequested)
        {
            // Cost Management query requires POST on management.azure.com — omitted on hosted GET-only path.
            manifest["actualCostSummary"] = null;
        }

        object[] resourceRows = resources
            .Select(static r => new
            {
                resourceType = r.ResourceType,
                resourceId = r.ResourceId,
                name = r.Name,
                location = r.Location,
                sku = r.Sku,
                tags = r.Tags,
                properties = r.Properties
            })
            .ToArray<object>();

        Dictionary<string, object?> policyCompliance = new(StringComparer.Ordinal)
        {
            ["schemaVersion"] = 1,
            ["collectionTimestampUtc"] = collectionTimestampUtc.ToString("o"),
            ["scope"] = scope,
            ["subscriptionId"] = subscriptionId.Trim(),
            ["policyStates"] = Array.Empty<object>(),
            ["note"] =
                "Hosted Tier 2 collector uses GET-only management.azure.com calls; policy states require POST and are not collected in this path."
        };

        const string readme = """
                              ArchLucid hosted Azure extractor package (Tier 2 — Workload Identity Federation).
                              Generated by ArchLucid's cloud-hosted read-only collector. No customer client secrets cross the boundary.
                              Upload via POST /v1/azure-extractor/upload or the hosted run endpoint.
                              """;

        using MemoryStream zipStream = new();

        using (ZipArchive archive = new(zipStream, ZipArchiveMode.Create, leaveOpen: true))
        {
            AddUtf8Entry(archive, "manifest.json", JsonSerializer.Serialize(manifest, SerializerOptions));
            AddUtf8Entry(archive, "resources.json", JsonSerializer.Serialize(resourceRows, SerializerOptions));
            AddUtf8Entry(archive, "policy-compliance.json", JsonSerializer.Serialize(policyCompliance, SerializerOptions));
            AddUtf8Entry(archive, "README.txt", readme);
        }

        return zipStream.ToArray();
    }

    private static void AddUtf8Entry(ZipArchive archive, string entryName, string content)
    {
        ZipArchiveEntry entry = archive.CreateEntry(entryName, CompressionLevel.Optimal);

        using Stream entryStream = entry.Open();

        byte[] bytes = Encoding.UTF8.GetBytes(content);

        entryStream.Write(bytes, 0, bytes.Length);
    }
}
