using ArchLucid.Core.AzureExtractor;

using System.IO.Compression;
using System.Text;
using System.Text.Json;

namespace ArchLucid.Integrations.AzureExtractor;

/// <summary>
///     Builds schema v1 Azure extractor ZIP bytes matching the PowerShell collector layout.
/// </summary>
public static class HostedAzureExtractorZipBuilder
{
    private const int SchemaVersion = AzureExtractorZipSchema.Version2;

    private const string HostedScriptVersion = "hosted-1.0.0";

    private static readonly JsonSerializerOptions SerializerOptions =
        new()
        {
            WriteIndented = true
        };

    public static byte[] BuildZip(
        string? subscriptionId,
        IReadOnlyList<HostedAzureArmResourceRecord> resources,
        bool includeCostRequested,
        DateTimeOffset collectionTimestampUtc,
        string? subscriptionName = null,
        IReadOnlyList<AzureInventoryEntraGroupMembershipRow>? entraGroupMemberships = null,
        IReadOnlyList<HostedAzureArmRoleAssignmentRecord>? roleAssignments = null,
        IReadOnlyList<HostedAzureArmNetworkAssociationRecord>? networkAssociations = null,
        IReadOnlyList<HostedAzureArmFederatedCredentialRecord>? federatedCredentials = null,
        string? managementGroupId = null,
        IReadOnlyList<HostedAzureArmPolicyAssignmentRecord>? policyAssignments = null,
        IReadOnlyList<HostedAzureArmDiagnosticSettingRecord>? diagnosticSettings = null,
        IReadOnlyList<HostedAzureArmDefenderSummaryRecord>? defenderSummaries = null)
    {
        bool hasSubscriptionId = !string.IsNullOrWhiteSpace(subscriptionId);
        bool hasManagementGroupId = !string.IsNullOrWhiteSpace(managementGroupId);

        if (hasSubscriptionId == hasManagementGroupId)
        {
            throw new ArgumentException("Specify exactly one of subscriptionId or managementGroupId.");
        }

        string scope = hasManagementGroupId
            ? $"/providers/Microsoft.Management/managementGroups/{managementGroupId!.Trim()}"
            : $"/subscriptions/{subscriptionId!.Trim()}";
        List<string> switchesUsed = [];

        if (includeCostRequested)
            switchesUsed.Add("IncludeCost");

        Dictionary<string, object?> manifest = new(StringComparer.Ordinal)
        {
            ["schemaVersion"] = SchemaVersion,
            ["scriptVersion"] = HostedScriptVersion,
            ["collectionTimestamp"] = collectionTimestampUtc.ToString("o"),
            ["subscriptionId"] = hasSubscriptionId ? subscriptionId!.Trim() : null,
            ["subscriptionName"] = AzureExtractorSubscriptionDisplayName.Normalize(subscriptionName),
            ["managementGroupId"] = hasManagementGroupId ? managementGroupId!.Trim() : null,
            ["scope"] = scope,
            ["switchesUsed"] = switchesUsed,
            ["azModuleVersion"] = "hosted-extractor",
            ["completenessScore"] = 1.0,
            ["warnings"] = Array.Empty<string>(),
            ["errors"] = Array.Empty<string>(),
            ["resourceCount"] = resources.Count,
            ["captureMethod"] = "HostedReader",
            ["collectorVersion"] = HostedScriptVersion,
        };

        if (includeCostRequested)
        {
            // Cost Management query requires POST on management.azure.com — omitted on hosted GET-only path.
            manifest["actualCostSummary"] = null;
        }

        object[] resourceRows = resources
            .Select(static r => new
            {
                resourceType = r.ResourceType,
                resourceId = r.ResourceId,
                name = r.Name,
                location = r.Location,
                sku = r.Sku,
                tags = r.Tags,
                properties = r.Properties
            })
            .ToArray<object>();

        Dictionary<string, object?> policyCompliance = new(StringComparer.Ordinal)
        {
            ["schemaVersion"] = 1,
            ["collectionTimestampUtc"] = collectionTimestampUtc.ToString("o"),
            ["scope"] = scope,
            ["subscriptionId"] = hasSubscriptionId ? subscriptionId!.Trim() : null,
            ["policyStates"] = Array.Empty<object>(),
            ["note"] =
                "Hosted Tier 2 collector uses GET-only management.azure.com calls; policy states require POST and are not collected in this path."
        };

        const string readme = """
                              ArchLucid hosted Azure extractor package (Tier 2 — Workload Identity Federation).
                              Generated by ArchLucid's cloud-hosted read-only collector. No customer client secrets cross the boundary.
                              Upload via POST /v1/azure-extractor/upload or the hosted run endpoint.
                              """;

        object[] entraMembershipRows = (entraGroupMemberships ?? [])
            .Select(static row => new
            {
                memberId = row.MemberId,
                groupId = row.GroupId,
                provenanceKind = row.ProvenanceKind.ToString(),
                evidenceHashSha256 = row.EvidenceHashSha256 is null
                    ? null
                    : Convert.ToHexStringLower(row.EvidenceHashSha256),
            })
            .ToArray<object>();

        object[] roleAssignmentRows = (roleAssignments ?? [])
            .Select(static row => new
            {
                scope = row.Scope,
                principalId = row.PrincipalId,
                principalType = row.PrincipalType,
                roleDefinitionId = row.RoleDefinitionId,
                pimEligibilityKind = row.PimEligibilityKind,
            })
            .ToArray<object>();

        object[] networkAssociationRows = (networkAssociations ?? [])
            .Select(static row => new
            {
                fromResourceId = row.FromResourceId,
                toResourceId = row.ToResourceId,
                associationType = row.AssociationType,
                ruleName = row.RuleName,
            })
            .ToArray<object>();

        object[] federatedCredentialRows = (federatedCredentials ?? [])
            .Select(static row => new
            {
                issuer = row.Issuer,
                subject = row.Subject,
                principalId = row.PrincipalId,
                appId = row.AppId,
                parentResourceId = row.ParentResourceId,
                credentialName = row.CredentialName,
                provenanceKind = "ObservedFact",
            })
            .ToArray<object>();

        object[] policyAssignmentRows = (policyAssignments ?? [])
            .Select(static row => new
            {
                scope = row.Scope,
                policyDefinitionId = row.PolicyDefinitionId,
                name = row.Name,
                assignmentId = row.AssignmentId,
            })
            .ToArray<object>();

        object[] diagnosticSettingRows = (diagnosticSettings ?? [])
            .Select(static row => new
            {
                targetResourceId = row.TargetResourceId,
                name = row.Name,
                workspaceId = row.WorkspaceId,
            })
            .ToArray<object>();

        object[] defenderSummaryRows = (defenderSummaries ?? [])
            .Select(static row => new
            {
                resourceId = row.ResourceId,
                secureScore = row.SecureScore,
            })
            .ToArray<object>();

        using MemoryStream zipStream = new();

        using (ZipArchive archive = new(zipStream, ZipArchiveMode.Create, leaveOpen: true))
        {
            AddUtf8Entry(archive, AzureExtractorPackageZipEntryNames.Manifest, JsonSerializer.Serialize(manifest, SerializerOptions));
            AddUtf8Entry(archive, AzureExtractorPackageZipEntryNames.Resources, JsonSerializer.Serialize(resourceRows, SerializerOptions));
            AddUtf8Entry(
                archive,
                AzureExtractorPackageZipEntryNames.RoleAssignments,
                JsonSerializer.Serialize(roleAssignmentRows, SerializerOptions));
            AddUtf8Entry(
                archive,
                AzureExtractorPackageZipEntryNames.NetworkAssociations,
                JsonSerializer.Serialize(networkAssociationRows, SerializerOptions));
            AddUtf8Entry(
                archive,
                AzureExtractorPackageZipEntryNames.DiagnosticSettings,
                JsonSerializer.Serialize(diagnosticSettingRows, SerializerOptions));
            AddUtf8Entry(
                archive,
                AzureExtractorPackageZipEntryNames.PolicyAssignments,
                JsonSerializer.Serialize(policyAssignmentRows, SerializerOptions));
            AddUtf8Entry(
                archive,
                AzureExtractorPackageZipEntryNames.FederatedCredentials,
                JsonSerializer.Serialize(federatedCredentialRows, SerializerOptions));
            AddUtf8Entry(
                archive,
                AzureExtractorPackageZipEntryNames.DefenderSummary,
                JsonSerializer.Serialize(defenderSummaryRows, SerializerOptions));
            AddUtf8Entry(
                archive,
                AzureExtractorPackageZipEntryNames.EntraGroupMemberships,
                JsonSerializer.Serialize(entraMembershipRows, SerializerOptions));
            AddUtf8Entry(archive, "policy-compliance.json", JsonSerializer.Serialize(policyCompliance, SerializerOptions));
            AddUtf8Entry(archive, "README.txt", readme);
        }

        return zipStream.ToArray();
    }

    private static void AddUtf8Entry(ZipArchive archive, string entryName, string content)
    {
        ZipArchiveEntry entry = archive.CreateEntry(entryName, CompressionLevel.Optimal);

        using Stream entryStream = entry.Open();

        byte[] bytes = Encoding.UTF8.GetBytes(content);

        entryStream.Write(bytes, 0, bytes.Length);
    }
}
