import { describe, expect, it } from "vitest";

import { ARCHITECTURE_DIAGRAM_MERMAID_WRAPPING_WIDTH } from "@/lib/architecture/architecture-diagram-mermaid-config";
import {
  ARCHITECTURE_DIAGRAM_LABEL_FONT_SIZE_PX,
  estimateArchitectureDiagramLabelWidthPx,
  formatArchitectureDiagramCanvasLabelLines,
  joinArchitectureDiagramMermaidLabelLines,
  looksAutoGeneratedArchitectureDiagramResourceName,
  wrapArchitectureDiagramLabelForMermaidSource,
  wrapArchitectureDiagramLabelToWidth,
  wrapWidthInsideNodeRectPx,
} from "@/lib/architecture/wrap-architecture-diagram-label";

describe("wrapArchitectureDiagramLabelToWidth", () => {
  it("keeps short names on one line", () => {
    const lines = wrapArchitectureDiagramLabelToWidth("vnet-eastus", 240);

    expect(lines).toEqual(["vnet-eastus"]);
  });

  it("wraps Azure product names that overrun a wrappingWidth node box", () => {
    const wrapWidth = wrapWidthInsideNodeRectPx(160);
    const lines = wrapArchitectureDiagramLabelToWidth(
      "Azure Kubernetes Service (AKS) Cluster",
      wrapWidth,
    );

    expect(lines.length).toBeGreaterThan(1);
    expect(lines.join(" ")).toBe("Azure Kubernetes Service (AKS) Cluster");

    for (const line of lines) {
      expect(estimateArchitectureDiagramLabelWidthPx(line)).toBeLessThanOrEqual(wrapWidth + 1);
    }
  });

  it("breaks hyphenated resource ids instead of overflowing", () => {
    const wrapWidth = wrapWidthInsideNodeRectPx(160);
    const lines = wrapArchitectureDiagramLabelToWidth(
      "vnet-eastus-hub-shared-connectivity-001",
      wrapWidth,
      ARCHITECTURE_DIAGRAM_LABEL_FONT_SIZE_PX,
    );

    expect(lines.length).toBeGreaterThan(1);
    expect(lines.join("").replace(/ /g, "")).toContain("vnet-eastus");
  });

  it("returns no lines for empty input", () => {
    expect(wrapArchitectureDiagramLabelToWidth("   ", 240)).toEqual([]);
  });
});

describe("looksAutoGeneratedArchitectureDiagramResourceName", () => {
  it("detects trailing numeric azure suffixes", () => {
    expect(looksAutoGeneratedArchitectureDiagramResourceName("vnet-aep-hi-test-wus-001")).toBe(true);
  });

  it("does not flag short human resource names", () => {
    expect(looksAutoGeneratedArchitectureDiagramResourceName("vnet-eastus")).toBe(false);
  });
});

describe("formatArchitectureDiagramCanvasLabelLines", () => {
  it("keeps typical vnet names on one line inside a 400px box", () => {
    const lines = formatArchitectureDiagramCanvasLabelLines("vnet-userprovision-hi-nonprod01", [
      "vnet-userprovision-hi-nonprod01",
      "vnet-eastus",
    ]);

    expect(lines).toEqual(["vnet-userprovision-hi-nonprod01"]);
  });

  it("truncates auto-generated names with a correlatable prefix", () => {
    const longName = `vm-production-eastus-${"a".repeat(30)}-001`;
    const lines = formatArchitectureDiagramCanvasLabelLines(longName, [
      longName,
      `vm-production-eastus-${"a".repeat(30)}-002`,
    ]);

    expect(lines).toHaveLength(1);
    expect(lines[0]).toMatch(/^vm-production-eastus.*\.\.\.$/u);
  });
});

describe("wrapArchitectureDiagramLabelForMermaidSource", () => {
  it("emits mermaid \\n so layout allocates height before SVG sanitize", () => {
    const wrappedLabel = joinArchitectureDiagramMermaidLabelLines(
      formatArchitectureDiagramCanvasLabelLines(
        "Azure Kubernetes Service (AKS) Cluster",
        ["Azure Kubernetes Service (AKS) Cluster"],
        160,
      ),
    );

    expect(wrappedLabel).toContain("\\n");
    expect(wrappedLabel).not.toContain("\n");
  });

  it("does not insert breaks for names that already fit", () => {
    expect(wrapArchitectureDiagramLabelForMermaidSource("Claims API")).toBe("Claims API");
  });
});
