import {
  ARCHITECTURE_DIAGRAM_MERMAID_WRAPPING_WIDTH,
} from "@/lib/architecture/architecture-diagram-mermaid-config";

/** Matches mermaid `themeVariables.fontSize` for architecture and inventory diagrams. */
export const ARCHITECTURE_DIAGRAM_LABEL_FONT_SIZE_PX = 15;

/**
 * Average glyph width as a fraction of font size for ui-sans-serif.
 * 0.58em keeps wrapped lines inside a 400px wrappingWidth box with padding.
 */
export const ARCHITECTURE_DIAGRAM_LABEL_GLYPH_WIDTH_RATIO = 0.58;

export const ARCHITECTURE_DIAGRAM_LABEL_LINE_HEIGHT_RATIO = 1.25;

/** Inset so glyphs sit inside the stroke instead of on the node border. */
export const ARCHITECTURE_DIAGRAM_LABEL_HORIZONTAL_PADDING_PX = 16;

export function architectureDiagramLabelLineHeightPx(
  fontSizePx: number = ARCHITECTURE_DIAGRAM_LABEL_FONT_SIZE_PX,
): number {
  return fontSizePx * ARCHITECTURE_DIAGRAM_LABEL_LINE_HEIGHT_RATIO;
}

export function estimateArchitectureDiagramLabelWidthPx(
  text: string,
  fontSizePx: number = ARCHITECTURE_DIAGRAM_LABEL_FONT_SIZE_PX,
): number {
  return text.length * fontSizePx * ARCHITECTURE_DIAGRAM_LABEL_GLYPH_WIDTH_RATIO;
}

export function wrapWidthInsideNodeRectPx(rectWidthPx: number): number {
  return Math.max(48, rectWidthPx - ARCHITECTURE_DIAGRAM_LABEL_HORIZONTAL_PADDING_PX);
}

export function maxArchitectureDiagramLabelCharsForWidth(
  maxWidthPx: number,
  fontSizePx: number = ARCHITECTURE_DIAGRAM_LABEL_FONT_SIZE_PX,
): number {
  const usableWidth = Math.max(1, maxWidthPx);
  const glyphWidth = fontSizePx * ARCHITECTURE_DIAGRAM_LABEL_GLYPH_WIDTH_RATIO;

  return Math.max(8, Math.floor(usableWidth / glyphWidth));
}

const TRAILING_HYPHEN_DIGITS = /-\d{1,5}$/u;
const GUID_SEGMENT =
  /[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}/u;
const LONG_HEX_RUN = /(?<![0-9a-fA-F])[0-9a-fA-F]{12,}(?![0-9a-fA-F])/u;

export function looksAutoGeneratedArchitectureDiagramResourceName(resourceName: string): boolean {
  const trimmed = resourceName.trim();

  if (trimmed.length === 0) {
    return false;
  }

  if (GUID_SEGMENT.test(trimmed)) {
    return true;
  }

  if (LONG_HEX_RUN.test(trimmed)) {
    return true;
  }

  if (TRAILING_HYPHEN_DIGITS.test(trimmed)) {
    return true;
  }

  return false;
}

function commonPrefixLength(left: string, right: string): number {
  const limit = Math.min(left.length, right.length);
  let index = 0;

  while (index < limit && left[index] === right[index]) {
    index += 1;
  }

  return index;
}

function computeMinimumUniquePrefixLength(resourceName: string, peerResourceNames: readonly string[]): number {
  let minimumUnique = resourceName.length;

  for (const peer of peerResourceNames) {
    if (peer === resourceName) {
      continue;
    }

    const commonPrefixLengthValue = commonPrefixLength(resourceName, peer);
    minimumUnique = Math.min(minimumUnique, commonPrefixLengthValue + 1);
  }

  return Math.max(1, minimumUnique);
}

function truncateAutoGeneratedArchitectureDiagramLabel(
  resourceName: string,
  peerResourceNames: readonly string[],
  maxChars: number,
): string {
  const minimumUniquePrefixLength = computeMinimumUniquePrefixLength(resourceName, peerResourceNames);

  for (let length = resourceName.length; length >= minimumUniquePrefixLength; length -= 1) {
    const candidate = length >= resourceName.length ? resourceName : `${resourceName.slice(0, length)}...`;

    if (candidate.length <= maxChars) {
      return candidate;
    }
  }

  const keepLength = Math.max(minimumUniquePrefixLength, Math.min(resourceName.length, maxChars - 3));

  return `${resourceName.slice(0, keepLength)}...`;
}

export function formatArchitectureDiagramCanvasLabelLines(
  raw: string,
  peerResourceNames: readonly string[] = [],
  nodeRectWidthPx: number = ARCHITECTURE_DIAGRAM_MERMAID_WRAPPING_WIDTH,
  fontSizePx: number = ARCHITECTURE_DIAGRAM_LABEL_FONT_SIZE_PX,
): string[] {
  const normalized = raw.replace(/[ \t]+/g, " ").trim();

  if (normalized.length === 0) {
    return [];
  }

  const wrapWidth = wrapWidthInsideNodeRectPx(nodeRectWidthPx);
  const maxChars = maxArchitectureDiagramLabelCharsForWidth(wrapWidth, fontSizePx);

  if (normalized.length <= maxChars) {
    return [normalized];
  }

  if (looksAutoGeneratedArchitectureDiagramResourceName(normalized)) {
    return [truncateAutoGeneratedArchitectureDiagramLabel(normalized, peerResourceNames, maxChars)];
  }

  return wrapArchitectureDiagramLabelToWidth(normalized, wrapWidth, fontSizePx);
}

function hardSplitToken(token: string, maxChars: number): string[] {
  const chunks: string[] = [];
  let remaining = token;

  while (remaining.length > maxChars) {
    chunks.push(remaining.slice(0, maxChars));
    remaining = remaining.slice(maxChars);
  }

  if (remaining.length > 0) {
    chunks.push(remaining);
  }

  return chunks.length > 0 ? chunks : [token];
}

/** Breaks long Azure resource ids at hyphens before hard-slicing. */
function splitOversizedToken(token: string, maxChars: number): string[] {
  if (token.length <= maxChars) {
    return [token];
  }

  if (!token.includes("-")) {
    return hardSplitToken(token, maxChars);
  }

  const parts = token.split("-");
  const chunks: string[] = [];
  let current = "";

  for (let index = 0; index < parts.length; index++) {
    const part = parts[index];

    if (part === undefined) {
      continue;
    }

    const suffix = index === 0 ? part : `-${part}`;
    const candidate = `${current}${suffix}`;

    if (candidate.length <= maxChars) {
      current = candidate;
      continue;
    }

    if (current.length > 0) {
      chunks.push(current);
    }

    if (suffix.length <= maxChars) {
      current = suffix;
      continue;
    }

    chunks.push(...hardSplitToken(suffix, maxChars));
    current = "";
  }

  if (current.length > 0) {
    chunks.push(current);
  }

  return chunks.length > 0 ? chunks : hardSplitToken(token, maxChars);
}

/**
 * Word-wraps a diagram label to a pixel budget. Does not ellipsize: architecture
 * and inventory names are the content, so every character stays visible.
 */
export function wrapArchitectureDiagramLabelToWidth(
  text: string,
  maxWidthPx: number,
  fontSizePx: number = ARCHITECTURE_DIAGRAM_LABEL_FONT_SIZE_PX,
): string[] {
  const normalized = text.replace(/[ \t]+/g, " ").trim();

  if (normalized.length === 0) {
    return [];
  }

  const maxChars = maxArchitectureDiagramLabelCharsForWidth(maxWidthPx, fontSizePx);
  const words = normalized.split(" ").filter((word) => word.length > 0);
  const lines: string[] = [];
  let current = "";

  for (const word of words) {
    const pieces = splitOversizedToken(word, maxChars);

    for (const piece of pieces) {
      const glue = current.length === 0 || piece.startsWith("-") ? "" : " ";
      const candidate = `${current}${glue}${piece}`;

      if (candidate.length <= maxChars) {
        current = candidate;
        continue;
      }

      if (current.length > 0) {
        lines.push(current);
      }

      current = piece;
    }
  }

  if (current.length > 0) {
    lines.push(current);
  }

  return lines.length > 0 ? lines : [normalized];
}

/** Mermaid quoted labels use a literal `\n` sequence for line breaks when htmlLabels is false. */
export function joinArchitectureDiagramMermaidLabelLines(lines: readonly string[]): string {
  return lines.join("\\n");
}

export function wrapArchitectureDiagramLabelForMermaidSource(
  raw: string,
  peerResourceNames: readonly string[] = [],
): string {
  const lines = formatArchitectureDiagramCanvasLabelLines(raw, peerResourceNames);

  if (lines.length === 0) {
    return raw;
  }

  if (lines.length === 1) {
    return lines[0] ?? raw;
  }

  return joinArchitectureDiagramMermaidLabelLines(lines);
}
