import type { DeferredChunkManifestEntry } from "@/lib/operator/deferred-chunk-manifest";

/** TB-2371 — app shell deferred chunk catalog (wave 1). */
export const APP_SHELL_CHUNK_MANIFEST: readonly DeferredChunkManifestEntry[] = [
  {
    id: "app-shell-workspace-footer",
    label: "Loading workspace footer",
    variant: "compact",
    modulePath: "@/components/shell/AppShellWorkspaceFooter",
    exportName: "AppShellWorkspaceFooter",
  },
  {
    id: "app-shell-idle-overlays",
    label: "Loading idle overlays",
    variant: "compact",
    modulePath: "@/components/shell/AppShellIdleOverlays",
    exportName: "AppShellIdleOverlays",
  },
  {
    id: "app-shell-idle-core-pilot-wizard-launcher",
    label: "Loading pilot wizard",
    variant: "compact",
    modulePath: "@/components/CorePilotWizard",
    exportName: "CorePilotWizardLauncher",
  },
  {
    id: "app-shell-idle-pilot-baseline-wizard-launcher",
    label: "Loading baseline wizard",
    variant: "compact",
    modulePath: "@/components/PilotBaselineWizardLauncher",
    exportName: "PilotBaselineWizardLauncher",
  },
  {
    id: "app-shell-idle-cto-demo-offline-auto-fallback-listener",
    label: "Loading demo offline listener",
    variant: "compact",
    modulePath: "@/components/cto-demo/CtoDemoOfflineAutoFallbackListener",
    exportName: "CtoDemoOfflineAutoFallbackListener",
  },
  {
    id: "app-shell-idle-cto-demo-panic-mode-banner",
    label: "Loading demo panic banner",
    variant: "compact",
    modulePath: "@/components/cto-demo/CtoDemoPanicModeBanner",
    exportName: "CtoDemoPanicModeBanner",
  },
  {
    id: "app-shell-idle-cto-demo-spotlight-overlay",
    label: "Loading demo spotlight overlay",
    variant: "compact",
    modulePath: "@/components/cto-demo/CtoDemoSpotlightOverlay",
    exportName: "CtoDemoSpotlightOverlay",
  },
  {
    id: "app-shell-idle-buyer-cto-demo-tour-overlay",
    label: "Loading buyer demo tour overlay",
    variant: "compact",
    modulePath: "@/components/BuyerCtoDemoTourOverlay",
    exportName: "BuyerCtoDemoTourOverlay",
  },
  {
    id: "app-shell-footer-trust-center-shell-link",
    label: "Loading trust center link",
    variant: "compact",
    modulePath: "@/components/usability/TrustCenterShellLink",
    exportName: "TrustCenterShellLink",
  },
  {
    id: "app-shell-footer-system-health-status-strip",
    label: "Loading system health strip",
    variant: "compact",
    modulePath: "@/components/operator-home/SystemHealthStatusStrip",
    exportName: "SystemHealthStatusStrip",
  },
  {
    id: "app-shell-footer-deployment-build-fingerprint-strip",
    label: "Loading deployment fingerprint",
    variant: "compact",
    modulePath: "@/components/shell/DeploymentBuildFingerprintStrip",
    exportName: "DeploymentBuildFingerprintStrip",
  },
  {
    id: "app-shell-command-palette",
    label: "Loading command palette",
    variant: "compact",
    modulePath: "@/components/CommandPalette",
    exportName: "CommandPalette",
  },
  {
    id: "app-shell-dev-testing-shortcuts",
    label: "Loading dev testing shortcuts",
    variant: "compact",
    modulePath: "@/components/dev-testing/DevTestingShellShortcuts",
    exportName: "DevTestingShellShortcuts",
  },
  {
    id: "app-shell-telemetry-bundle",
    label: "Loading telemetry bundle",
    variant: "compact",
    modulePath: "@/components/shell/AppShellTelemetryBundle",
    exportName: "AppShellTelemetryBundle",
  },
  {
    id: "app-shell-session-idle-timeout",
    label: "Loading session idle guard",
    variant: "compact",
    modulePath: "@/components/SessionIdleTimeoutGuard",
    exportName: "SessionIdleTimeoutGuard",
  },
  {
    id: "app-shell-auth-panel",
    label: "Loading auth panel",
    variant: "compact",
    modulePath: "@/components/AuthPanel",
    exportName: "AuthPanel",
  },
  {
    id: "app-shell-sync-active-run",
    label: "Loading active run sync",
    variant: "compact",
    modulePath: "@/components/SyncActiveRunFromPathname",
    exportName: "SyncActiveRunFromPathname",
  },
  {
    id: "app-shell-main-content-gate",
    label: "Loading main content gate",
    variant: "compact",
    modulePath: "@/components/shell/AppShellMainContentGate",
    exportName: "AppShellMainContentGate",
  },
  {
    id: "app-shell-access-redirects-host",
    label: "Loading access redirects",
    variant: "compact",
    modulePath: "@/components/shell/OperatorShellAccessRedirectsHost",
    exportName: "OperatorShellAccessRedirectsHost",
  },
  {
    id: "app-shell-toaster",
    label: "Loading toaster",
    variant: "compact",
    modulePath: "@/components/AppToaster",
    exportName: "AppToaster",
  },
  {
    id: "app-shell-route-announcer",
    label: "Loading route announcer",
    variant: "compact",
    modulePath: "@/components/RouteAnnouncer",
    exportName: "RouteAnnouncer",
  },
  {
    id: "operator-shell-top-bar",
    label: "Loading shell navigation",
    variant: "compact",
    modulePath: "@/components/shell/OperatorShellTopBar",
    exportName: "OperatorShellTopBar",
  },
  {
    id: "app-shell-keyboard-shortcut-boundary",
    label: "Loading keyboard shortcuts",
    variant: "compact",
    modulePath: "@/components/shell/AppShellKeyboardShortcutBoundary",
    exportName: "AppShellKeyboardShortcutBoundary",
  },
  {
    id: "app-shell-color-mode-toggle",
    label: "Loading color mode toggle",
    variant: "compact",
    modulePath: "@/components/ColorModeToggle",
    exportName: "ColorModeToggle",
  },
  {
    id: "app-shell-authority-theme-toggle",
    label: "Loading authority theme toggle",
    variant: "compact",
    modulePath: "@/components/AuthorityThemeToggle",
    exportName: "AuthorityThemeToggle",
  },
  {
    id: "app-shell-theme-preferences-vocabulary-rail",
    label: "Loading theme preferences",
    variant: "compact",
    modulePath: "@/components/ShellThemePreferencesAppearanceVocabularyRail",
    exportName: "ShellThemePreferencesAppearanceVocabularyRail",
  },
  {
    id: "app-shell-frictionless-trial-banner",
    label: "Loading trial banner",
    variant: "compact",
    modulePath: "@/components/FrictionlessTrialBanner",
    exportName: "FrictionlessTrialBanner",
  },
  {
    id: "app-shell-main-affordances",
    label: "Loading main affordances",
    variant: "compact",
    modulePath: "@/components/shell/AppShellMainAffordances",
    exportName: "AppShellMainAffordances",
  },
  {
    id: "app-shell-onboarding-tour",
    label: "Loading onboarding tour",
    variant: "compact",
    modulePath: "@/components/OnboardingTour",
    exportName: "OnboardingTour",
  },
  {
    id: "app-shell-registration-onboarding-tour-auto-start",
    label: "Loading registration tour",
    variant: "compact",
    modulePath: "@/components/usability/RegistrationOnboardingTourAutoStart",
    exportName: "RegistrationOnboardingTourAutoStart",
  },
  {
    id: "app-shell-help-search-panel",
    label: "Loading help search",
    variant: "compact",
    modulePath: "@/components/HelpSearchPanel",
    exportName: "HelpSearchPanel",
  },
  {
    id: "app-shell-help-panel",
    label: "Loading help panel",
    variant: "compact",
    modulePath: "@/components/HelpPanel",
    exportName: "HelpPanel",
  },
  {
    id: "app-shell-sidebar-nav",
    label: "Loading sidebar navigation",
    variant: "panel",
    modulePath: "@/components/SidebarNav",
    exportName: "SidebarNav",
  },
  {
    id: "app-shell-status-banners",
    label: "Loading status banners",
    variant: "compact",
    modulePath: "@/components/shell/AppShellStatusBanners",
    exportName: "AppShellStatusBanners",
  },
  {
    id: "app-shell-trial-limit-modal-host",
    label: "Loading trial limit modal",
    variant: "compact",
    modulePath: "@/components/trial/TrialLimitModal",
    exportName: "TrialLimitModalHost",
  },
  {
    id: "app-shell-cto-demo-journey-caption-bar",
    label: "Loading demo journey caption",
    variant: "compact",
    modulePath: "@/components/cto-demo/CtoDemoJourneyCaptionBar",
    exportName: "CtoDemoJourneyCaptionBar",
  },
  {
    id: "app-shell-client",
    label: "Loading workspace shell",
    variant: "section",
    modulePath: "@/components/AppShellClient",
    exportName: "AppShellClient",
  },
] as const;
