/**
 * Generated by `scripts/generate-deferred-chunk-import-loaders.mjs`. Do not edit by hand.
 * Run: `npm run generate:deferred-chunk-loaders`
 */
import type { ComponentType } from "react";

import { deferredChunkLoader } from "@/lib/import-deferred-chunk-with-retry";

/** Static import map so webpack can split deferred chunks predictably. */
export function resolveDeferredChunkImportLoader(
  entryId: string,
): () => Promise<ComponentType<Record<string, unknown>>> {
  switch (entryId) {
    case "operator-home-command-center":
      return deferredChunkLoader(() =>
        import("@/components/usability/PilotCommandCenterCard").then(
          (module) => module.PilotCommandCenterCard,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-home-hero":
      return deferredChunkLoader(() =>
        import("@/components/operator-home/BuyerPolishedHomeHeroSection").then(
          (module) => module.BuyerPolishedHomeHeroSection,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-home-gate":
      return deferredChunkLoader(() =>
        import("@/components/operator-home/OperatorHomeGate").then(
          (module) => module.OperatorHomeGate,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-home-below-fold":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/_sections/OperatorHomeBelowFoldPanels").then(
          (module) => module.OperatorHomeBelowFoldPanels,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-home-stickiness":
      return deferredChunkLoader(() =>
        import("@/components/operator-home/OperatorHomeStickinessCockpit").then(
          (module) => module.OperatorHomeStickinessCockpit,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-home-sponsor-roi":
      return deferredChunkLoader(() =>
        import("@/components/operator-home/OperatorHomeSponsorRoiStrip").then(
          (module) => module.OperatorHomeSponsorRoiStrip,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-home-runs-dashboard":
      return deferredChunkLoader(() =>
        import("@/components/operator-home/RunsDashboardPanel").then(
          (module) => module.RunsDashboardPanel,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-home-before-after-delta":
      return deferredChunkLoader(() =>
        import("@/components/BeforeAfterDeltaPanel").then(
          (module) => module.BeforeAfterDeltaPanel,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-home-workspace-status":
      return deferredChunkLoader(() =>
        import("@/components/operator-home/OperatorHomeWorkspaceStatusSection").then(
          (module) => module.OperatorHomeWorkspaceStatusSection,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-home-welcome-onboarding":
      return deferredChunkLoader(() =>
        import("@/components/operator/OperatorWelcomeOnboarding").then(
          (module) => module.OperatorWelcomeOnboarding,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-home-trial-welcome-deep-link":
      return deferredChunkLoader(() =>
        import("@/components/trial/TrialWelcomeRunDeepLink").then(
          (module) => module.TrialWelcomeRunDeepLink,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-home-first-value-callout":
      return deferredChunkLoader(() =>
        import("@/components/FirstValueReachedCallout").then(
          (module) => module.FirstValueReachedCallout,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-home-cto-demo-sponsor-landing":
      return deferredChunkLoader(() =>
        import("@/components/cto-demo/CtoDemoSponsorLandingRedirect").then(
          (module) => module.CtoDemoSponsorLandingRedirect,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-home-advanced-guidance":
      return deferredChunkLoader(() =>
        import("@/components/operator-home/OperatorHomeAdvancedGuidanceSection").then(
          (module) => module.OperatorHomeAdvancedGuidanceSection,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-home-dev-testing-quick-switch":
      return deferredChunkLoader(() =>
        import("@/components/dev-testing/DevTestingQuickSwitchPanel").then(
          (module) => module.DevTestingQuickSwitchPanel,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-hub-inventory":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/reviews/_sections/ReviewsHubReviewInventory").then(
          (module) => module.ReviewsHubReviewInventory,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-hub-welcome-onboarding":
      return deferredChunkLoader(() =>
        import("@/components/operator/OperatorWelcomeOnboarding").then(
          (module) => module.OperatorWelcomeOnboarding,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-hub-explore-samples":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/reviews/_sections/ReviewsHubExploreSamples").then(
          (module) => module.ReviewsHubExploreSamples,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-hub-package-includes":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/reviews/_sections/ReviewsHubPackageIncludes").then(
          (module) => module.ReviewsHubPackageIncludes,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-hub-before-after-delta":
      return deferredChunkLoader(() =>
        import("@/components/BeforeAfterDeltaPanel").then(
          (module) => module.BeforeAfterDeltaPanel,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-hub-index-before-after":
      return deferredChunkLoader(() =>
        import("@/components/runs/RunsIndexBeforeAfterPanel").then(
          (module) => module.RunsIndexBeforeAfterPanel,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-hub-list-error-boundary":
      return deferredChunkLoader(() =>
        import("@/components/runs/RunsListAggregateErrorBoundary").then(
          (module) => module.RunsListAggregateErrorBoundary,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-quick-review-advanced-config":
      return deferredChunkLoader(() =>
        import("@/components/usability/QuickReviewAdvancedConfigAccordion").then(
          (module) => module.QuickReviewAdvancedConfigAccordion,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-wizard-evidence-upload":
      return deferredChunkLoader(() =>
        import("@/components/usability/WizardEvidenceUploadZone").then(
          (module) => module.WizardEvidenceUploadZone,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-wizard-package-preview":
      return deferredChunkLoader(() =>
        import("@/components/usability/WizardPackagePreview").then(
          (module) => module.WizardPackagePreview,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-cto-demo-fast-create":
      return deferredChunkLoader(() =>
        import("@/components/cto-demo/CtoDemoFastCreatePanel").then(
          (module) => module.CtoDemoFastCreatePanel,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-cto-demo-review-mode-callout":
      return deferredChunkLoader(() =>
        import("@/components/cto-demo/CtoDemoReviewModeCallout").then(
          (module) => module.CtoDemoReviewModeCallout,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-draft-intake-decision-receipt":
      return deferredChunkLoader(() =>
        import("@/components/draft-intake/DraftIntakeDecisionReceiptCard").then(
          (module) => module.DraftIntakeDecisionReceiptCard,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-wizard-step-advanced":
      return deferredChunkLoader(() =>
        import("@/components/wizard/steps/WizardStepAdvanced").then(
          (module) => module.WizardStepAdvanced,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-wizard-step-cloud-inventory":
      return deferredChunkLoader(() =>
        import("@/components/wizard/steps/WizardStepCloudInventoryContext").then(
          (module) => module.WizardStepCloudInventoryContext,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-wizard-step-baseline-zip":
      return deferredChunkLoader(() =>
        import("@/components/wizard/steps/WizardStepBaselineZip").then(
          (module) => module.WizardStepBaselineZip,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-wizard-step-baseline-metrics":
      return deferredChunkLoader(() =>
        import("@/components/wizard/steps/WizardStepBaselineMetrics").then(
          (module) => module.WizardStepBaselineMetrics,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-wizard-post-create-evidence":
      return deferredChunkLoader(() =>
        import("@/components/wizard/steps/WizardPostCreateEvidenceUploadPanel").then(
          (module) => module.WizardPostCreateEvidenceUploadPanel,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-wizard-step-track":
      return deferredChunkLoader(() =>
        import("@/components/wizard/steps/WizardStepTrack").then(
          (module) => module.WizardStepTrack,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-intent-callout":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/reviews/new/NewReviewIntentCallout").then(
          (module) => module.NewReviewIntentCallout,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-socratic-advanced-rail":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/reviews/new/SocraticIntakeWizardAdvancedRail").then(
          (module) => module.SocraticIntakeWizardAdvancedRail,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-wizard-help-drawer":
      return deferredChunkLoader(() =>
        import("@/components/wizard/ArchitectureRequestWizardHelpDrawer").then(
          (module) => module.ArchitectureRequestWizardHelpDrawer,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-quick-start-wizard":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/reviews/new/QuickStartWizard").then(
          (module) => module.QuickStartWizard,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-simplified-pilot-wizard":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/reviews/new/SimplifiedPilotWizard").then(
          (module) => module.SimplifiedPilotWizard,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-first-pilot-intake-wizard":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/reviews/new/FirstPilotIntakeWizard").then(
          (module) => module.FirstPilotIntakeWizard,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-socratic-intake-wizard":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/reviews/new/SocraticIntakeWizard").then(
          (module) => module.SocraticIntakeWizard,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-new-run-wizard-client":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/reviews/new/NewRunWizardClient").then(
          (module) => module.NewRunWizardClient,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "reviews-new-path-switcher":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/reviews/new/ReviewsNewPathSwitcher").then(
          (module) => module.ReviewsNewPathSwitcher,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "governance-workflow-overview-panel":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/governance/_sections/GovernanceOverviewPanel").then(
          (module) => module.GovernanceOverviewPanel,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "governance-workflow-review-context-bar":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/governance/_sections/GovernanceReviewContextBar").then(
          (module) => module.GovernanceReviewContextBar,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "governance-workflow-approvals-list":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/governance/_sections/GovernanceWorkflowApprovalsList").then(
          (module) => module.GovernanceWorkflowApprovalsList,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "governance-workflow-submit-section":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/governance/_sections/GovernanceWorkflowSubmitSection").then(
          (module) => module.GovernanceWorkflowSubmitSection,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "governance-workflow-promotions-activations":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/governance/_sections/GovernanceWorkflowPromotionsActivationsSection").then(
          (module) => module.GovernanceWorkflowPromotionsActivationsSection,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "governance-workflow-dialogs":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/governance/_sections/GovernanceWorkflowDialogs").then(
          (module) => module.GovernanceWorkflowDialogs,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "governance-workflow-interactive-quickstart":
      return deferredChunkLoader(() =>
        import("@/components/governance/GovernanceInteractiveQuickstartContent").then(
          (module) => module.GovernanceInteractiveQuickstartContent,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "governance-workflow-approval-story-card":
      return deferredChunkLoader(() =>
        import("@/components/governance/GovernanceApprovalStoryCard").then(
          (module) => module.GovernanceApprovalStoryCard,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "governance-workflow-advanced-options":
      return deferredChunkLoader(() =>
        import("@/components/AdvancedOptionsAccordion").then(
          (module) => module.AdvancedOptionsAccordion,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "governance-workflow-cto-demo-buyer-value-strip":
      return deferredChunkLoader(() =>
        import("@/components/cto-demo/CtoDemoBuyerValueStrip").then(
          (module) => module.CtoDemoBuyerValueStrip,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "governance-workflow-cto-demo-segregation-callout":
      return deferredChunkLoader(() =>
        import("@/components/cto-demo/CtoDemoSegregationCallout").then(
          (module) => module.CtoDemoSegregationCallout,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "governance-workflow-cto-demo-governance-preview-hint":
      return deferredChunkLoader(() =>
        import("@/components/OperateCapabilityHints").then(
          (module) => module.CtoDemoGovernancePreviewHint,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "governance-workflow-page-content":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/governance/_sections/GovernanceWorkflowPageContent").then(
          (module) => module.GovernanceWorkflowPageContent,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "governance-findings-queue-client":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/governance/findings/GovernanceFindingsQueueClient").then(
          (module) => module.default,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "policy-packs-authoring-wizard":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/governance/policy-packs/_sections/PolicyRuleAuthoringWizard").then(
          (module) => module.PolicyRuleAuthoringWizard,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "policy-packs-authoring-natural-language-builder":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/governance/policy-packs/_sections/PolicyPackNaturalLanguageBuilder").then(
          (module) => module.PolicyPackNaturalLanguageBuilder,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "policy-packs-authoring-visual-builder":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/governance/policy-packs/_sections/PolicyPackVisualBuilder").then(
          (module) => module.PolicyPackVisualBuilder,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "alert-rules-hub-conditions":
      return deferredChunkLoader(() =>
        import("@/components/alerts/AlertRulesContent").then(
          (module) => module.AlertRulesContent,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "alert-rules-hub-routing":
      return deferredChunkLoader(() =>
        import("@/components/alerts/AlertRoutingContent").then(
          (module) => module.AlertRoutingContent,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "alert-rules-hub-composite-rules":
      return deferredChunkLoader(() =>
        import("@/components/alerts/CompositeAlertRulesContent").then(
          (module) => module.CompositeAlertRulesContent,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "alert-rules-hub-simulation-tuning":
      return deferredChunkLoader(() =>
        import("@/components/alerts/AlertSimulationTuningSection").then(
          (module) => module.AlertSimulationTuningSection,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "signed-records-list-client":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/governance/sealed-records/_sections/SignedRecordsListClient").then(
          (module) => module.default,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "signed-records-list-table":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/governance/sealed-records/_sections/SignedRecordsListTable").then(
          (module) => module.SignedRecordsListTable,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "sponsor-roi-dashboard-next-action":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/sponsor-dashboard/_sections/SponsorDashboardNextActionSection").then(
          (module) => module.SponsorDashboardNextActionSection,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "sponsor-roi-dashboard-primary-metrics":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/sponsor-dashboard/_sections/SponsorDashboardPrimaryMetricsSection").then(
          (module) => module.SponsorDashboardPrimaryMetricsSection,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "sponsor-roi-dashboard-how-it-works":
      return deferredChunkLoader(() =>
        import("@/components/sponsor/SponsorDashboardHowItWorks").then(
          (module) => module.SponsorDashboardHowItWorks,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "sponsor-roi-dashboard-exports":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/sponsor-dashboard/_sections/SponsorExportsSection").then(
          (module) => module.SponsorExportsSection,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "sponsor-roi-dashboard-business-impact":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/sponsor-dashboard/_sections/BusinessImpactSummaryWidget").then(
          (module) => module.BusinessImpactSummaryWidget,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "sponsor-roi-dashboard-roi-summary":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/sponsor-dashboard/_sections/SponsorRoiSummarySection").then(
          (module) => module.SponsorRoiSummarySection,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "sponsor-roi-dashboard-compliance-drift-trend":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/sponsor-dashboard/_sections/SponsorComplianceDriftTrendSection").then(
          (module) => module.SponsorComplianceDriftTrendSection,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "sponsor-roi-dashboard-welcome-onboarding":
      return deferredChunkLoader(() =>
        import("@/components/operator/OperatorWelcomeOnboarding").then(
          (module) => module.OperatorWelcomeOnboarding,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "sponsor-roi-dashboard-roi-trend":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/sponsor-dashboard/_sections/SponsorRoiTrendSection").then(
          (module) => module.SponsorRoiTrendSection,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "sponsor-roi-dashboard-environment-savings":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/sponsor-dashboard/_sections/SponsorRoiEnvironmentSavingsSection").then(
          (module) => module.SponsorRoiEnvironmentSavingsSection,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "sponsor-roi-dashboard-supporting-metrics":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/sponsor-dashboard/_sections/SponsorDashboardSupportingMetricsSection").then(
          (module) => module.SponsorDashboardSupportingMetricsSection,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "sponsor-roi-dashboard-page-view":
      return deferredChunkLoader(() =>
        import("@/app/(operator)/architecture/sponsor-dashboard/_sections/SponsorRoiDashboardPageView").then(
          (module) => module.SponsorRoiDashboardPageView,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "sponsor-roi-dashboard-systemic-issue-trend-chart":
      return deferredChunkLoader(() =>
        import("@/components/SponsorRoiSystemicIssueTrendChart").then(
          (module) => module.SponsorRoiSystemicIssueTrendChart,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "alerts-inbox-governance-context-panel":
      return deferredChunkLoader(() =>
        import("@/components/alerts/AlertsGovernanceContextPanel").then(
          (module) => module.AlertsGovernanceContextPanel,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "alerts-inbox-dialogs":
      return deferredChunkLoader(() =>
        import("@/components/alerts/AlertsInboxDialogs").then(
          (module) => module.AlertsInboxDialogs,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-workspace-footer":
      return deferredChunkLoader(() =>
        import("@/components/shell/AppShellWorkspaceFooter").then(
          (module) => module.AppShellWorkspaceFooter,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-idle-overlays":
      return deferredChunkLoader(() =>
        import("@/components/shell/AppShellIdleOverlays").then(
          (module) => module.AppShellIdleOverlays,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-idle-core-pilot-wizard-launcher":
      return deferredChunkLoader(() =>
        import("@/components/CorePilotWizard").then(
          (module) => module.CorePilotWizardLauncher,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-idle-pilot-baseline-wizard-launcher":
      return deferredChunkLoader(() =>
        import("@/components/PilotBaselineWizardLauncher").then(
          (module) => module.PilotBaselineWizardLauncher,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-idle-cto-demo-offline-auto-fallback-listener":
      return deferredChunkLoader(() =>
        import("@/components/cto-demo/CtoDemoOfflineAutoFallbackListener").then(
          (module) => module.CtoDemoOfflineAutoFallbackListener,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-idle-cto-demo-panic-mode-banner":
      return deferredChunkLoader(() =>
        import("@/components/cto-demo/CtoDemoPanicModeBanner").then(
          (module) => module.CtoDemoPanicModeBanner,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-idle-cto-demo-spotlight-overlay":
      return deferredChunkLoader(() =>
        import("@/components/cto-demo/CtoDemoSpotlightOverlay").then(
          (module) => module.CtoDemoSpotlightOverlay,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-idle-buyer-cto-demo-tour-overlay":
      return deferredChunkLoader(() =>
        import("@/components/BuyerCtoDemoTourOverlay").then(
          (module) => module.BuyerCtoDemoTourOverlay,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-footer-trust-center-shell-link":
      return deferredChunkLoader(() =>
        import("@/components/usability/TrustCenterShellLink").then(
          (module) => module.TrustCenterShellLink,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-footer-system-health-status-strip":
      return deferredChunkLoader(() =>
        import("@/components/operator-home/SystemHealthStatusStrip").then(
          (module) => module.SystemHealthStatusStrip,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-footer-deployment-build-fingerprint-strip":
      return deferredChunkLoader(() =>
        import("@/components/shell/DeploymentBuildFingerprintStrip").then(
          (module) => module.DeploymentBuildFingerprintStrip,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-command-palette":
      return deferredChunkLoader(() =>
        import("@/components/CommandPalette").then(
          (module) => module.CommandPalette,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-dev-testing-shortcuts":
      return deferredChunkLoader(() =>
        import("@/components/dev-testing/DevTestingShellShortcuts").then(
          (module) => module.DevTestingShellShortcuts,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-telemetry-bundle":
      return deferredChunkLoader(() =>
        import("@/components/shell/AppShellTelemetryBundle").then(
          (module) => module.AppShellTelemetryBundle,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-session-idle-timeout":
      return deferredChunkLoader(() =>
        import("@/components/SessionIdleTimeoutGuard").then(
          (module) => module.SessionIdleTimeoutGuard,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-auth-panel":
      return deferredChunkLoader(() =>
        import("@/components/AuthPanel").then(
          (module) => module.AuthPanel,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-sync-active-run":
      return deferredChunkLoader(() =>
        import("@/components/SyncActiveRunFromPathname").then(
          (module) => module.SyncActiveRunFromPathname,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-main-content-gate":
      return deferredChunkLoader(() =>
        import("@/components/shell/AppShellMainContentGate").then(
          (module) => module.AppShellMainContentGate,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-access-redirects-host":
      return deferredChunkLoader(() =>
        import("@/components/shell/OperatorShellAccessRedirectsHost").then(
          (module) => module.OperatorShellAccessRedirectsHost,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-toaster":
      return deferredChunkLoader(() =>
        import("@/components/AppToaster").then(
          (module) => module.AppToaster,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-route-announcer":
      return deferredChunkLoader(() =>
        import("@/components/RouteAnnouncer").then(
          (module) => module.RouteAnnouncer,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-shell-top-bar":
      return deferredChunkLoader(() =>
        import("@/components/shell/OperatorShellTopBar").then(
          (module) => module.OperatorShellTopBar,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-keyboard-shortcut-boundary":
      return deferredChunkLoader(() =>
        import("@/components/shell/AppShellKeyboardShortcutBoundary").then(
          (module) => module.AppShellKeyboardShortcutBoundary,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-color-mode-toggle":
      return deferredChunkLoader(() =>
        import("@/components/ColorModeToggle").then(
          (module) => module.ColorModeToggle,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-authority-theme-toggle":
      return deferredChunkLoader(() =>
        import("@/components/AuthorityThemeToggle").then(
          (module) => module.AuthorityThemeToggle,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-theme-preferences-vocabulary-rail":
      return deferredChunkLoader(() =>
        import("@/components/ShellThemePreferencesAppearanceVocabularyRail").then(
          (module) => module.ShellThemePreferencesAppearanceVocabularyRail,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-frictionless-trial-banner":
      return deferredChunkLoader(() =>
        import("@/components/FrictionlessTrialBanner").then(
          (module) => module.FrictionlessTrialBanner,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-main-affordances":
      return deferredChunkLoader(() =>
        import("@/components/shell/AppShellMainAffordances").then(
          (module) => module.AppShellMainAffordances,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-onboarding-tour":
      return deferredChunkLoader(() =>
        import("@/components/OnboardingTour").then(
          (module) => module.OnboardingTour,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-registration-onboarding-tour-auto-start":
      return deferredChunkLoader(() =>
        import("@/components/usability/RegistrationOnboardingTourAutoStart").then(
          (module) => module.RegistrationOnboardingTourAutoStart,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-help-search-panel":
      return deferredChunkLoader(() =>
        import("@/components/HelpSearchPanel").then(
          (module) => module.HelpSearchPanel,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-help-panel":
      return deferredChunkLoader(() =>
        import("@/components/HelpPanel").then(
          (module) => module.HelpPanel,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-sidebar-nav":
      return deferredChunkLoader(() =>
        import("@/components/SidebarNav").then(
          (module) => module.SidebarNav,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-status-banners":
      return deferredChunkLoader(() =>
        import("@/components/shell/AppShellStatusBanners").then(
          (module) => module.AppShellStatusBanners,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-trial-limit-modal-host":
      return deferredChunkLoader(() =>
        import("@/components/trial/TrialLimitModal").then(
          (module) => module.TrialLimitModalHost,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-cto-demo-journey-caption-bar":
      return deferredChunkLoader(() =>
        import("@/components/cto-demo/CtoDemoJourneyCaptionBar").then(
          (module) => module.CtoDemoJourneyCaptionBar,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "app-shell-client":
      return deferredChunkLoader(() =>
        import("@/components/AppShellClient").then(
          (module) => module.AppShellClient,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-shell-top-bar-global-search":
      return deferredChunkLoader(() =>
        import("@/components/GlobalSearchBar").then(
          (module) => module.GlobalSearchBar,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-shell-top-bar-mobile-nav-drawer":
      return deferredChunkLoader(() =>
        import("@/components/MobileNavDrawer").then(
          (module) => module.MobileNavDrawer,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-shell-top-bar-scope-switcher":
      return deferredChunkLoader(() =>
        import("@/components/ScopeSwitcher").then(
          (module) => module.ScopeSwitcher,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-shell-top-bar-in-flight-operations":
      return deferredChunkLoader(() =>
        import("@/components/shell/ShellInFlightOperationsAffordance").then(
          (module) => module.ShellInFlightOperationsAffordance,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-shell-top-bar-more-menu":
      return deferredChunkLoader(() =>
        import("@/components/shell/OperatorShellTopBarMoreMenu").then(
          (module) => module.OperatorShellTopBarMoreMenu,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-shell-top-bar-account-settings":
      return deferredChunkLoader(() =>
        import("@/components/shell/AccountSettingsMenu").then(
          (module) => module.AccountSettingsMenu,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "operator-shell-top-bar-llm-budget-pill":
      return deferredChunkLoader(() =>
        import("@/components/llm/LlmBudgetStatusPill").then(
          (module) => module.LlmBudgetStatusPill,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "marketing-welcome-tier-pricing-section":
      return deferredChunkLoader(() =>
        import("@/components/marketing/MarketingTierPricingSection").then(
          (module) => module.MarketingTierPricingSection,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "marketing-first-touch-capture":
      return deferredChunkLoader(() =>
        import("@/components/MarketingFirstTouchCapture").then(
          (module) => module.MarketingFirstTouchCapture,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "marketing-microsoft-clarity-loader":
      return deferredChunkLoader(() =>
        import("@/components/MicrosoftClarityLoader").then(
          (module) => module.MicrosoftClarityLoader,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "marketing-public-footer":
      return deferredChunkLoader(() =>
        import("@/components/marketing/MarketingPublicFooter").then(
          (module) => module.MarketingPublicFooter,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    case "marketing-analytics-consent-banner":
      return deferredChunkLoader(() =>
        import("@/components/MarketingAnalyticsConsentBanner").then(
          (module) => module.MarketingAnalyticsConsentBanner,
        ),
      ) as () => Promise<ComponentType<Record<string, unknown>>>;
    default:
      throw new Error(`No deferred chunk import loader registered for manifest entry "${entryId}".`);
  }
}
