import type { DeferredChunkManifestEntry } from "@/lib/operator/deferred-chunk-manifest";

/** TB-2371 — operator home deferred chunk catalog. */
export const OPERATOR_HOME_CHUNK_MANIFEST: readonly DeferredChunkManifestEntry[] = [
  {
    id: "operator-home-command-center",
    label: "Loading overview command center",
    variant: "panel",
    modulePath: "@/components/usability/PilotCommandCenterCard",
    exportName: "PilotCommandCenterCard",
  },
  {
    id: "operator-home-hero",
    label: "Loading overview hero",
    variant: "panel",
    modulePath: "@/components/operator-home/BuyerPolishedHomeHeroSection",
    exportName: "BuyerPolishedHomeHeroSection",
  },
  {
    id: "operator-home-gate",
    label: "Checking workspace access",
    variant: "section",
    modulePath: "@/components/operator-home/OperatorHomeGate",
    exportName: "OperatorHomeGate",
  },
  {
    id: "operator-home-below-fold",
    label: "Loading overview guidance panels",
    variant: "section",
    modulePath: "@/app/(operator)/_sections/OperatorHomeBelowFoldPanels",
    exportName: "OperatorHomeBelowFoldPanels",
  },
  {
    id: "operator-home-stickiness",
    label: "Loading stickiness cockpit",
    variant: "panel",
    modulePath: "@/components/operator-home/OperatorHomeStickinessCockpit",
    exportName: "OperatorHomeStickinessCockpit",
  },
  {
    id: "operator-home-sponsor-roi",
    label: "Loading sponsor ROI strip",
    variant: "compact",
    modulePath: "@/components/operator-home/OperatorHomeSponsorRoiStrip",
    exportName: "OperatorHomeSponsorRoiStrip",
  },
  {
    id: "operator-home-runs-dashboard",
    label: "Loading recent reviews",
    variant: "panel",
    modulePath: "@/components/operator-home/RunsDashboardPanel",
    exportName: "RunsDashboardPanel",
  },
  {
    id: "operator-home-before-after-delta",
    label: "Loading before/after delta",
    variant: "panel",
    modulePath: "@/components/BeforeAfterDeltaPanel",
    exportName: "BeforeAfterDeltaPanel",
  },
  {
    id: "operator-home-workspace-status",
    label: "Loading workspace status",
    variant: "panel",
    modulePath: "@/components/operator-home/OperatorHomeWorkspaceStatusSection",
    exportName: "OperatorHomeWorkspaceStatusSection",
  },
  {
    id: "operator-home-welcome-onboarding",
    label: "Loading welcome guidance",
    variant: "panel",
    modulePath: "@/components/operator/OperatorWelcomeOnboarding",
    exportName: "OperatorWelcomeOnboarding",
  },
  {
    id: "operator-home-trial-welcome-deep-link",
    label: "Loading trial welcome link",
    variant: "compact",
    modulePath: "@/components/trial/TrialWelcomeRunDeepLink",
    exportName: "TrialWelcomeRunDeepLink",
  },
  {
    id: "operator-home-first-value-callout",
    label: "Loading first value callout",
    variant: "panel",
    modulePath: "@/components/FirstValueReachedCallout",
    exportName: "FirstValueReachedCallout",
  },
  {
    id: "operator-home-cto-demo-sponsor-landing",
    label: "Loading sponsor landing redirect",
    variant: "compact",
    modulePath: "@/components/cto-demo/CtoDemoSponsorLandingRedirect",
    exportName: "CtoDemoSponsorLandingRedirect",
  },
  {
    id: "operator-home-advanced-guidance",
    label: "Loading advanced guidance",
    variant: "panel",
    modulePath: "@/components/operator-home/OperatorHomeAdvancedGuidanceSection",
    exportName: "OperatorHomeAdvancedGuidanceSection",
  },
  {
    id: "operator-home-dev-testing-quick-switch",
    label: "Loading dev testing quick switch",
    variant: "compact",
    modulePath: "@/components/dev-testing/DevTestingQuickSwitchPanel",
    exportName: "DevTestingQuickSwitchPanel",
  },
] as const;
