import {
  BUYER_OPERATOR_HOME_PAGE_SUBTITLE,
  OPERATOR_HOME_COMMAND_CENTER_TAGLINE,
} from "@/lib/buyer/buyer-polish-copy";
import { OPERATOR_NAV_LINK_LABELS } from "@/lib/i18n";

export const OPERATOR_HOME_PAGE_TITLE = OPERATOR_NAV_LINK_LABELS.home;

export const OPERATOR_HOME_PAGE_SUBTITLE = OPERATOR_HOME_COMMAND_CENTER_TAGLINE;

export { BUYER_OPERATOR_HOME_PAGE_SUBTITLE };

export const OPERATOR_HOME_PAGE_SUBTITLE_OPERATOR = OPERATOR_HOME_PAGE_SUBTITLE;

export function operatorHomePageSubtitle(buyerPolishedShell: boolean): string {
  return buyerPolishedShell ? BUYER_OPERATOR_HOME_PAGE_SUBTITLE : OPERATOR_HOME_PAGE_SUBTITLE_OPERATOR;
}

export const OPERATOR_HOME_LAST_REFRESHED_PREFIX = "Last refreshed" as const;

export const OPERATOR_HOME_ACTION_REFRESH = "Refresh" as const;

export const OPERATOR_HOME_ACTION_REFRESHING = "Refreshing…" as const;

export const OPERATOR_HOME_SCOPE_DETAILS_TRIGGER = `About ${OPERATOR_NAV_LINK_LABELS.home}` as const;

export const OPERATOR_HOME_SCOPE_OVERVIEW = OPERATOR_HOME_COMMAND_CENTER_TAGLINE;
