import type { DeferredChunkManifestEntry } from "@/lib/operator/deferred-chunk-manifest";

/** TB-2371 — reviews new (intake wizard) deferred chunk catalog (wave 1). */
export const REVIEWS_NEW_CHUNK_MANIFEST: readonly DeferredChunkManifestEntry[] = [
  {
    id: "reviews-new-quick-review-advanced-config",
    label: "Loading advanced configuration",
    variant: "panel",
    modulePath: "@/components/usability/QuickReviewAdvancedConfigAccordion",
    exportName: "QuickReviewAdvancedConfigAccordion",
  },
  {
    id: "reviews-new-wizard-evidence-upload",
    label: "Loading evidence upload",
    variant: "panel",
    modulePath: "@/components/usability/WizardEvidenceUploadZone",
    exportName: "WizardEvidenceUploadZone",
  },
  {
    id: "reviews-new-wizard-package-preview",
    label: "Loading package preview",
    variant: "panel",
    modulePath: "@/components/usability/WizardPackagePreview",
    exportName: "WizardPackagePreview",
  },
  {
    id: "reviews-new-cto-demo-fast-create",
    label: "Loading demo fast create",
    variant: "panel",
    modulePath: "@/components/cto-demo/CtoDemoFastCreatePanel",
    exportName: "CtoDemoFastCreatePanel",
  },
  {
    id: "reviews-new-cto-demo-review-mode-callout",
    label: "Loading demo review mode callout",
    variant: "panel",
    modulePath: "@/components/cto-demo/CtoDemoReviewModeCallout",
    exportName: "CtoDemoReviewModeCallout",
  },
  {
    id: "reviews-new-draft-intake-decision-receipt",
    label: "Loading decision receipt",
    variant: "panel",
    modulePath: "@/components/draft-intake/DraftIntakeDecisionReceiptCard",
    exportName: "DraftIntakeDecisionReceiptCard",
  },
  {
    id: "reviews-new-wizard-step-advanced",
    label: "Loading advanced wizard step",
    variant: "panel",
    modulePath: "@/components/wizard/steps/WizardStepAdvanced",
    exportName: "WizardStepAdvanced",
  },
  {
    id: "reviews-new-wizard-step-cloud-inventory",
    label: "Loading cloud inventory step",
    variant: "panel",
    modulePath: "@/components/wizard/steps/WizardStepCloudInventoryContext",
    exportName: "WizardStepCloudInventoryContext",
  },
  {
    id: "reviews-new-wizard-step-baseline-zip",
    label: "Loading baseline zip step",
    variant: "panel",
    modulePath: "@/components/wizard/steps/WizardStepBaselineZip",
    exportName: "WizardStepBaselineZip",
  },
  {
    id: "reviews-new-wizard-step-baseline-metrics",
    label: "Loading baseline metrics step",
    variant: "panel",
    modulePath: "@/components/wizard/steps/WizardStepBaselineMetrics",
    exportName: "WizardStepBaselineMetrics",
  },
  {
    id: "reviews-new-wizard-post-create-evidence",
    label: "Loading post-create evidence panel",
    variant: "panel",
    modulePath: "@/components/wizard/steps/WizardPostCreateEvidenceUploadPanel",
    exportName: "WizardPostCreateEvidenceUploadPanel",
  },
  {
    id: "reviews-new-wizard-step-track",
    label: "Loading track wizard step",
    variant: "panel",
    modulePath: "@/components/wizard/steps/WizardStepTrack",
    exportName: "WizardStepTrack",
  },
  {
    id: "reviews-new-intent-callout",
    label: "Loading review intent callout",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/new/NewReviewIntentCallout",
    exportName: "NewReviewIntentCallout",
  },
  {
    id: "reviews-new-socratic-advanced-rail",
    label: "Loading guided intake advanced options",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/new/SocraticIntakeWizardAdvancedRail",
    exportName: "SocraticIntakeWizardAdvancedRail",
  },
  {
    id: "reviews-new-wizard-help-drawer",
    label: "Loading wizard help drawer",
    variant: "panel",
    modulePath: "@/components/wizard/ArchitectureRequestWizardHelpDrawer",
    exportName: "ArchitectureRequestWizardHelpDrawer",
  },
  {
    id: "reviews-new-quick-start-wizard",
    label: "Loading quick start wizard",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/new/QuickStartWizard",
    exportName: "QuickStartWizard",
  },
  {
    id: "reviews-new-simplified-pilot-wizard",
    label: "Loading simplified pilot wizard",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/new/SimplifiedPilotWizard",
    exportName: "SimplifiedPilotWizard",
  },
  {
    id: "reviews-new-first-pilot-intake-wizard",
    label: "Loading first pilot intake wizard",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/new/FirstPilotIntakeWizard",
    exportName: "FirstPilotIntakeWizard",
  },
  {
    id: "reviews-new-socratic-intake-wizard",
    label: "Loading guided intake wizard",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/new/SocraticIntakeWizard",
    exportName: "SocraticIntakeWizard",
  },
  {
    id: "reviews-new-new-run-wizard-client",
    label: "Loading detailed review wizard",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/new/NewRunWizardClient",
    exportName: "NewRunWizardClient",
  },
  {
    id: "reviews-new-path-switcher",
    label: "Loading review start paths",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/new/ReviewsNewPathSwitcher",
    exportName: "ReviewsNewPathSwitcher",
  },
] as const;
