import type { DeferredChunkManifestEntry } from "@/lib/operator/deferred-chunk-manifest";

/** TB-2371 — run detail deferred chunk catalog (subset used by manifest import tests). */
export const RUN_DETAIL_CHUNK_MANIFEST: readonly DeferredChunkManifestEntry[] = [
  {
    id: "run-detail-review-workspace-shell",
    label: "Loading review workspace",
    variant: "section",
    modulePath: "@/components/reviews/ReviewWorkspaceShell",
    exportName: "ReviewWorkspaceShell",
  },
  {
    id: "run-detail-overview-panel",
    label: "Loading review overview",
    variant: "panel",
    modulePath: "@/components/reviews/RunDetailOverviewPanelClient",
    exportName: "RunDetailOverviewPanelClient",
  },
  {
    id: "run-detail-evidence-tab",
    label: "Loading evidence tab",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailEvidenceTabPanel",
    exportName: "RunDetailEvidenceTabPanel",
  },
  {
    id: "run-detail-below-fold",
    label: "Loading additional review sections",
    variant: "section",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailBelowFoldSections",
    exportName: "RunDetailBelowFoldSections",
  },
  {
    id: "run-detail-architecture-created-workspace",
    label: "Loading create-home workspace",
    variant: "section",
    modulePath: "@/components/architecture/ArchitectureCreatedReviewWorkspaceShell",
    exportName: "ArchitectureCreatedReviewWorkspaceShell",
  },
  {
    id: "run-detail-create-home-evidence",
    label: "Loading evidence panel",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailCreateHomeEvidencePanel",
    exportName: "RunDetailCreateHomeEvidencePanel",
  },
  {
    id: "run-detail-create-home-activity",
    label: "Loading activity panel",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailCreateHomeActivityPanel",
    exportName: "RunDetailCreateHomeActivityPanel",
  },
  {
    id: "run-detail-technology-baseline",
    label: "Loading technology baseline",
    variant: "section",
    modulePath: "@/components/reviews/technology-baseline/TechnologyBaselineSection",
    exportName: "TechnologyBaselineSection",
  },
  {
    id: "run-detail-changes-since-last-review",
    label: "Loading review changes banner",
    variant: "panel",
    modulePath: "@/components/ChangesSinceLastReviewBanner",
    exportName: "ChangesSinceLastReviewBanner",
  },
  {
    id: "run-detail-savings-summary",
    label: "Loading savings summary",
    variant: "panel",
    modulePath: "@/components/RunSavingsSummary",
    exportName: "RunSavingsSummary",
  },
  {
    id: "run-detail-decision-delta",
    label: "Loading decision delta",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailDecisionDeltaPanel",
    exportName: "RunDetailDecisionDeltaPanel",
  },
  {
    id: "run-detail-explanation-collapsible",
    label: "Loading review explanation",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailRunExplanationCollapsible",
    exportName: "RunDetailRunExplanationCollapsible",
  },
  {
    id: "run-detail-activity-sources",
    label: "Loading activity sources",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailActivitySourcesPanel",
    exportName: "RunDetailActivitySourcesPanel",
  },
  {
    id: "run-detail-workspace-header",
    label: "Loading review header",
    variant: "section",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailWorkspaceChrome",
    exportName: "RunDetailWorkspaceHeader",
  },
  {
    id: "run-detail-workspace-summary-strip",
    label: "Loading decision snapshot",
    variant: "panel",
    modulePath:
      "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailWorkspaceSummaryStripTabAware",
    exportName: "RunDetailWorkspaceSummaryStripTabAware",
  },
  {
    id: "run-detail-workspace-blocking-banner",
    label: "Loading review blocking banner",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailWorkspaceChrome",
    exportName: "RunDetailWorkspaceBlockingBanner",
  },
  {
    id: "run-detail-workspace-sticky-actions",
    label: "Loading review actions",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailWorkspaceStickyActions",
    exportName: "RunDetailWorkspaceStickyActions",
  },
  {
    id: "run-detail-section-nav",
    label: "Loading section navigation",
    variant: "panel",
    modulePath: "@/components/runs/RunDetailSectionNav",
    exportName: "RunDetailSectionNav",
  },
  {
    id: "run-detail-outcome-cards",
    label: "Loading outcome cards",
    variant: "panel",
    modulePath: "@/components/runs/RunDetailOutcomeCards",
    exportName: "RunDetailOutcomeCards",
  },
  {
    id: "run-detail-artifacts-exports-section",
    label: "Loading artifacts and exports",
    variant: "section",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailArtifactsExportsSection",
    exportName: "RunDetailArtifactsExportsSection",
  },
  {
    id: "run-detail-operator-technical-forensics",
    label: "Loading operator forensics",
    variant: "panel",
    modulePath:
      "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailOperatorTechnicalForensicsPanel",
    exportName: "RunDetailOperatorTechnicalForensicsPanel",
  },
  {
    id: "run-detail-sponsor-bottom-line",
    label: "Loading sponsor report",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailSponsorBottomLine",
    exportName: "RunDetailSponsorBottomLine",
  },
  {
    id: "run-detail-review-package-do-this-next-resolved",
    label: "Loading next step",
    variant: "panel",
    modulePath:
      "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailReviewPackageDoThisNextResolved",
    exportName: "RunDetailReviewPackageDoThisNextResolved",
  },
  {
    id: "run-detail-review-package-sponsor-handoff-gate",
    label: "Loading sponsor handoff gate",
    variant: "panel",
    modulePath:
      "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailReviewPackageSponsorHandoffGate",
    exportName: "RunDetailReviewPackageSponsorHandoffGate",
  },
  {
    id: "run-detail-help-page-situation-registrar",
    label: "Loading help context",
    variant: "panel",
    modulePath: "@/components/help/HelpPageSituationRegistrar",
    exportName: "HelpPageSituationRegistrar",
  },
  {
    id: "run-detail-review-generation-created-notice",
    label: "Loading review generation notice",
    variant: "panel",
    modulePath: "@/components/review-intake/ReviewGenerationCreatedNotice",
    exportName: "ReviewGenerationCreatedNotice",
  },
  {
    id: "run-detail-progress-tracker",
    label: "Loading review progress",
    variant: "panel",
    modulePath: "@/components/runs/RunProgressTracker",
    exportName: "RunProgressTracker",
  },
  {
    id: "run-detail-estimated-llm-cost-card",
    label: "Loading estimated LLM cost",
    variant: "panel",
    modulePath: "@/components/runs/RunEstimatedLlmCostCard",
    exportName: "RunEstimatedLlmCostCard",
  },
  {
    id: "run-detail-capture-evidence-section",
    label: "Loading evidence capture",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailCaptureEvidenceSection",
    exportName: "RunDetailCaptureEvidenceSection",
  },
  {
    id: "run-detail-manifest-summary-section",
    label: "Loading architecture package summary",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailManifestSummarySection",
    exportName: "RunDetailManifestSummarySection",
  },
  {
    id: "run-detail-agent-results-summary-card",
    label: "Loading agent results summary",
    variant: "panel",
    modulePath: "@/components/runs/RunAgentResultsSummaryCard",
    exportName: "RunAgentResultsSummaryCard",
  },
  {
    id: "run-detail-review-agent-execution-log-section",
    label: "Loading agent execution log",
    variant: "panel",
    modulePath: "@/components/reviews/ReviewAgentExecutionLogSection",
    exportName: "ReviewAgentExecutionLogSection",
  },
  {
    id: "run-detail-retrieval-grounding-summary-card",
    label: "Loading retrieval grounding summary",
    variant: "panel",
    modulePath: "@/components/runs/RunRetrievalGroundingSummaryCard",
    exportName: "RunRetrievalGroundingSummaryCard",
  },
  {
    id: "run-detail-run-metadata-section",
    label: "Loading run metadata",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailRunMetadataSection",
    exportName: "RunDetailRunMetadataSection",
  },
  {
    id: "run-detail-last-failure-card",
    label: "Loading last failure details",
    variant: "panel",
    modulePath: "@/components/runs/RunDetailLastFailureCard",
    exportName: "RunDetailLastFailureCard",
  },
  {
    id: "run-detail-trust-evidence-card-section",
    label: "Loading trust evidence",
    variant: "panel",
    modulePath: "@/components/runs/RunTrustEvidenceCardSection",
    exportName: "RunTrustEvidenceCardSection",
  },
  {
    id: "run-detail-sample-review-package-summary",
    label: "Loading sample architecture package",
    variant: "panel",
    modulePath: "@/components/SampleReviewPackageSummary",
    exportName: "SampleReviewPackageSummary",
  },
  {
    id: "run-detail-architecture-create-work-item-section",
    label: "Loading create work item",
    variant: "panel",
    modulePath: "@/components/architecture/ArchitectureCreateWorkItemSection",
    exportName: "ArchitectureCreateWorkItemSection",
  },
  {
    id: "run-detail-architecture-sponsor-sharing-panel",
    label: "Loading sponsor sharing",
    variant: "panel",
    modulePath: "@/components/architecture/ArchitectureSponsorSharingPanel",
    exportName: "ArchitectureSponsorSharingPanel",
  },
  {
    id: "run-detail-first-week-route-guidance",
    label: "Loading first-week guidance",
    variant: "panel",
    modulePath: "@/components/FirstWeekRouteGuidance",
    exportName: "FirstWeekRouteGuidance",
  },
  {
    id: "run-detail-cold-open-orientation",
    label: "Loading review orientation",
    variant: "panel",
    modulePath: "@/components/reviews/RunDetailColdOpenOrientationClient",
    exportName: "RunDetailColdOpenOrientationClient",
  },
  {
    id: "run-detail-explanation-confidence-banner",
    label: "Loading explanation confidence",
    variant: "panel",
    modulePath: "@/components/runs/RunExplanationConfidenceBanner",
    exportName: "RunExplanationConfidenceBanner",
  },
  {
    id: "run-detail-governance-alerts",
    label: "Loading governance alerts",
    variant: "panel",
    modulePath: "@/components/reviews/RunDetailGovernanceAlerts",
    exportName: "RunDetailGovernanceAlerts",
  },
  {
    id: "run-detail-what-if-branch-compare-banner",
    label: "Loading branch compare banner",
    variant: "panel",
    modulePath: "@/components/draft-intake/WhatIfBranchCompareBanner",
    exportName: "WhatIfBranchCompareBanner",
  },
  {
    id: "run-detail-commit-blocking-findings-banner",
    label: "Loading commit blocking banner",
    variant: "panel",
    modulePath: "@/components/usability/CommitBlockingFindingsBanner",
    exportName: "CommitBlockingFindingsBanner",
  },
  {
    id: "run-detail-stalled-review-guidance-callout",
    label: "Loading stalled review guidance",
    variant: "panel",
    modulePath: "@/components/usability/StalledReviewGuidanceCallout",
    exportName: "StalledReviewGuidanceCallout",
  },
  {
    id: "run-detail-cto-demo-review-route-guard",
    label: "Loading demo route guard",
    variant: "panel",
    modulePath: "@/components/cto-demo/CtoDemoReviewRouteGuard",
    exportName: "CtoDemoReviewRouteGuard",
  },
  {
    id: "run-detail-policy-pack-impact-callout",
    label: "Loading policy pack impact",
    variant: "panel",
    modulePath: "@/components/findings/ReviewDetailPolicyPackImpactSection",
    exportName: "ReviewDetailPolicyPackImpactSection",
  },
  {
    id: "run-detail-tabbed-section-nav",
    label: "Loading section navigation",
    variant: "panel",
    modulePath: "@/components/runs/RunDetailTabbedSectionNav",
    exportName: "RunDetailTabbedSectionNav",
  },
  {
    id: "run-detail-before-after-delta-panel",
    label: "Loading before/after delta",
    variant: "panel",
    modulePath: "@/components/BeforeAfterDeltaPanel",
    exportName: "BeforeAfterDeltaPanel",
  },
  {
    id: "run-detail-recurrence-schedule-post-commit-card",
    label: "Loading recurrence schedule card",
    variant: "panel",
    modulePath: "@/components/governance/RecurrenceSchedulePostCommitCard",
    exportName: "RecurrenceSchedulePostCommitCard",
  },
  {
    id: "run-detail-retrieval-grounding-section",
    label: "Loading retrieval grounding",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailRetrievalGroundingSection",
    exportName: "RunDetailRetrievalGroundingSection",
  },
  {
    id: "run-detail-authority-chain-section",
    label: "Loading authority chain",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailAuthorityChainSection",
    exportName: "RunDetailAuthorityChainSection",
  },
  {
    id: "run-detail-advanced-analysis-section",
    label: "Loading advanced analysis",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailAdvancedAnalysisSection",
    exportName: "RunDetailAdvancedAnalysisSection",
  },
  {
    id: "run-detail-sponsor-report-cta-card",
    label: "Loading sponsor report CTA",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailExecutiveSummaryCtaCard",
    exportName: "RunDetailSponsorReportCtaCard",
  },
  {
    id: "run-detail-review-package-primary-action",
    label: "Loading architecture package action",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/ReviewPackagePrimaryActionTabAware",
    exportName: "ReviewPackagePrimaryActionTabAware",
  },
  {
    id: "run-detail-review-package-sponsor-handoff-strip",
    label: "Loading sponsor handoff strip",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/ReviewPackageSponsorHandoffStrip",
    exportName: "ReviewPackageSponsorHandoffStrip",
  },
  {
    id: "run-detail-review-package-do-this-next-strip",
    label: "Loading do-this-next strip",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/ReviewPackageDoThisNextStrip",
    exportName: "ReviewPackageDoThisNextStrip",
  },
  {
    id: "run-detail-governance-decision-section",
    label: "Loading governance decision",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailGovernanceDecisionSection",
    exportName: "RunDetailGovernanceDecisionSection",
  },
  {
    id: "run-detail-review-package-section",
    label: "Loading architecture package",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailReviewPackageSection",
    exportName: "RunDetailReviewPackageSection",
  },
  {
    id: "run-detail-submitted-architecture-section",
    label: "Loading submitted architecture",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailSubmittedArchitectureSection",
    exportName: "RunDetailSubmittedArchitectureSection",
  },
  {
    id: "run-detail-governance-cta",
    label: "Loading governance CTA",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailGovernanceCta",
    exportName: "RunDetailGovernanceCta",
  },
  {
    id: "run-detail-buyer-pilot-conversion-section",
    label: "Loading buyer pilot conversion",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailBuyerPilotConversionSection",
    exportName: "RunDetailBuyerPilotConversionSection",
  },
  {
    id: "run-detail-buyer-mode-fallback-banner",
    label: "Loading buyer mode banner",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailBuyerModeFallbackBanner",
    exportName: "RunDetailBuyerModeFallbackBanner",
  },
  {
    id: "run-detail-review-package-share-row",
    label: "Loading architecture package share row",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailReviewPackageShareRow",
    exportName: "RunDetailReviewPackageShareRow",
  },
  {
    id: "run-detail-demo-marketing-chrome",
    label: "Loading demo marketing chrome",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailDemoMarketingChrome",
    exportName: "RunDetailDemoMarketingChrome",
  },
  {
    id: "run-detail-manifest-summary-alerts",
    label: "Loading architecture package summary alerts",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailManifestSummaryAlerts",
    exportName: "RunDetailManifestSummaryAlerts",
  },
  {
    id: "run-detail-holistic-critic-panel",
    label: "Loading holistic critique panel",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailHolisticCriticPanel",
    exportName: "RunDetailHolisticCriticPanel",
  },
  {
    id: "run-detail-run-actions-section",
    label: "Loading run actions",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailRunActionsSection",
    exportName: "RunDetailRunActionsSection",
  },
  {
    id: "run-detail-golden-sponsor-walkthrough",
    label: "Loading sponsor walkthrough",
    variant: "panel",
    modulePath: "@/components/golden-walkthrough/GoldenSponsorPackageWalkthroughDestination",
    exportName: "GoldenSponsorPackageWalkthroughDestination",
  },
  {
    id: "run-detail-export-deliverable-dialog",
    label: "Loading export dialog",
    variant: "panel",
    modulePath: "@/components/usability/ExportDeliverableDialog",
    exportName: "ExportDeliverableDialog",
  },
  {
    id: "run-detail-generate-adr-from-run-modal",
    label: "Loading generate ADR modal",
    variant: "panel",
    modulePath: "@/components/GenerateAdrFromRunModal",
    exportName: "GenerateAdrFromRunModal",
  },
  {
    id: "run-detail-compare-to-baseline-cta",
    label: "Loading compare to baseline",
    variant: "panel",
    modulePath: "@/components/CompareToBaselineCta",
    exportName: "CompareToBaselineCta",
  },
  {
    id: "run-detail-post-commit-habit-loop",
    label: "Loading post-commit habit loop",
    variant: "panel",
    modulePath: "@/components/PostCommitHabitLoopCard",
    exportName: "PostCommitHabitLoopCard",
  },
  {
    id: "run-detail-architecture-graph-section",
    label: "Loading architecture graph",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailArchitectureGraphSection",
    exportName: "RunDetailArchitectureGraphSection",
  },
] as const;
