import type { DeferredChunkManifestEntry } from "@/lib/operator/deferred-chunk-manifest";

export const RUN_DETAIL_CHUNK_MANIFEST_CREATE_HOME: readonly DeferredChunkManifestEntry[] = [
  {
    id: "run-detail-architecture-created-workspace",
    label: "Loading create-home workspace",
    variant: "section",
    modulePath: "@/components/architecture/ArchitectureCreatedReviewWorkspaceShell",
    exportName: "ArchitectureCreatedReviewWorkspaceShell",
  },
  {
    id: "run-detail-create-home-evidence",
    label: "Loading evidence panel",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailCreateHomeEvidencePanel",
    exportName: "RunDetailCreateHomeEvidencePanel",
  },
  {
    id: "run-detail-create-home-activity",
    label: "Loading activity panel",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailCreateHomeActivityPanel",
    exportName: "RunDetailCreateHomeActivityPanel",
  },
  {
    id: "run-detail-technology-baseline",
    label: "Loading technology baseline",
    variant: "section",
    modulePath: "@/components/reviews/technology-baseline/TechnologyBaselineSection",
    exportName: "TechnologyBaselineSection",
  },
  {
    id: "run-detail-pre-finalize-checklist",
    label: "Loading pre-finalize checklist",
    variant: "section",
    modulePath: "@/components/reviews/PreFinalizeChecklistSection",
    exportName: "PreFinalizeChecklistSection",
  },
  {
    id: "run-detail-changes-since-last-review",
    label: "Loading review changes banner",
    variant: "panel",
    modulePath: "@/components/ChangesSinceLastReviewBanner",
    exportName: "ChangesSinceLastReviewBanner",
  },
  {
    id: "run-detail-savings-summary",
    label: "Loading savings summary",
    variant: "panel",
    modulePath: "@/components/RunSavingsSummary",
    exportName: "RunSavingsSummary",
  },
  {
    id: "run-detail-decision-delta",
    label: "Loading decision delta",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailDecisionDeltaPanel",
    exportName: "RunDetailDecisionDeltaPanel",
  },
  {
    id: "run-detail-explanation-collapsible",
    label: "Loading review explanation",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailRunExplanationCollapsible",
    exportName: "RunDetailRunExplanationCollapsible",
  },
  {
    id: "run-detail-manifest-summary-section",
    label: "Loading architecture package summary",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailManifestSummarySection",
    exportName: "RunDetailManifestSummarySection",
  },
  {
    id: "run-detail-sample-review-package-summary",
    label: "Loading sample architecture package",
    variant: "panel",
    modulePath: "@/components/SampleReviewPackageSummary",
    exportName: "SampleReviewPackageSummary",
  },
  {
    id: "run-detail-architecture-create-work-item-section",
    label: "Loading create work item",
    variant: "panel",
    modulePath: "@/components/architecture/ArchitectureCreateWorkItemSection",
    exportName: "ArchitectureCreateWorkItemSection",
  },
  {
    id: "run-detail-before-after-delta-panel",
    label: "Loading before/after delta",
    variant: "panel",
    modulePath: "@/components/BeforeAfterDeltaPanel",
    exportName: "BeforeAfterDeltaPanel",
  },
  {
    id: "run-detail-submitted-architecture-section",
    label: "Loading submitted architecture",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailSubmittedArchitectureSection",
    exportName: "RunDetailSubmittedArchitectureSection",
  },
  {
    id: "run-detail-manifest-summary-alerts",
    label: "Loading architecture package summary alerts",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailManifestSummaryAlerts",
    exportName: "RunDetailManifestSummaryAlerts",
  },
  {
    id: "run-detail-architecture-graph-section",
    label: "Loading architecture graph",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailArchitectureGraphSection",
    exportName: "RunDetailArchitectureGraphSection",
  },
] as const;
