import type { DeferredChunkManifestEntry } from "@/lib/operator/deferred-chunk-manifest";

export const RUN_DETAIL_CHUNK_MANIFEST_WORKSPACE: readonly DeferredChunkManifestEntry[] = [
  {
    id: "run-detail-review-workspace-shell",
    label: "Loading review workspace",
    variant: "section",
    modulePath: "@/components/reviews/ReviewWorkspaceShell",
    exportName: "ReviewWorkspaceShell",
  },
  {
    id: "run-detail-overview-panel",
    label: "Loading review overview",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailOverviewPanelClient",
    exportName: "RunDetailOverviewPanelClient",
  },
  {
    id: "run-detail-evidence-tab",
    label: "Loading evidence tab",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailEvidenceTabPanel",
    exportName: "RunDetailEvidenceTabPanel",
  },
  {
    id: "run-detail-activity-sources",
    label: "Loading activity sources",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailActivitySourcesPanel",
    exportName: "RunDetailActivitySourcesPanel",
  },
  {
    id: "run-detail-workspace-header",
    label: "Loading review header",
    variant: "section",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailWorkspaceChrome",
    exportName: "RunDetailWorkspaceHeader",
  },
  {
    id: "run-detail-workspace-summary-strip",
    label: "Loading decision snapshot",
    variant: "panel",
    modulePath:
      "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailWorkspaceSummaryStripTabAware",
    exportName: "RunDetailWorkspaceSummaryStripTabAware",
  },
  {
    id: "run-detail-workspace-blocking-banner",
    label: "Loading review blocking banner",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailWorkspaceChrome",
    exportName: "RunDetailWorkspaceBlockingBanner",
  },
  {
    id: "run-detail-workspace-sticky-actions",
    label: "Loading review actions",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailWorkspaceStickyActions",
    exportName: "RunDetailWorkspaceStickyActions",
  },
  {
    id: "run-detail-section-nav",
    label: "Loading section navigation",
    variant: "panel",
    modulePath: "@/components/runs/RunDetailSectionNav",
    exportName: "RunDetailSectionNav",
  },
  {
    id: "run-detail-outcome-cards",
    label: "Loading outcome cards",
    variant: "panel",
    modulePath: "@/components/runs/RunDetailOutcomeCards",
    exportName: "RunDetailOutcomeCards",
  },
  {
    id: "run-detail-help-page-situation-registrar",
    label: "Loading help context",
    variant: "panel",
    modulePath: "@/components/help/HelpPageSituationRegistrar",
    exportName: "HelpPageSituationRegistrar",
  },
  {
    id: "run-detail-review-generation-created-notice",
    label: "Loading review generation notice",
    variant: "panel",
    modulePath: "@/components/review-intake/ReviewGenerationCreatedNotice",
    exportName: "ReviewGenerationCreatedNotice",
  },
  {
    id: "run-detail-progress-tracker",
    label: "Loading review progress",
    variant: "panel",
    modulePath: "@/components/runs/RunProgressTracker",
    exportName: "RunProgressTracker",
  },
  {
    id: "run-detail-estimated-llm-cost-card",
    label: "Loading estimated LLM cost",
    variant: "panel",
    modulePath: "@/components/runs/RunEstimatedLlmCostCard",
    exportName: "RunEstimatedLlmCostCard",
  },
  {
    id: "run-detail-capture-evidence-section",
    label: "Loading evidence capture",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailCaptureEvidenceSection",
    exportName: "RunDetailCaptureEvidenceSection",
  },
  {
    id: "run-detail-agent-results-summary-card",
    label: "Loading agent results summary",
    variant: "panel",
    modulePath: "@/components/runs/RunAgentResultsSummaryCard",
    exportName: "RunAgentResultsSummaryCard",
  },
  {
    id: "run-detail-review-agent-execution-log-section",
    label: "Loading agent execution log",
    variant: "panel",
    modulePath: "@/components/reviews/ReviewAgentExecutionLogSection",
    exportName: "ReviewAgentExecutionLogSection",
  },
  {
    id: "run-detail-retrieval-grounding-summary-card",
    label: "Loading retrieval grounding summary",
    variant: "panel",
    modulePath: "@/components/runs/RunRetrievalGroundingSummaryCard",
    exportName: "RunRetrievalGroundingSummaryCard",
  },
  {
    id: "run-detail-run-metadata-section",
    label: "Loading run metadata",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailRunMetadataSection",
    exportName: "RunDetailRunMetadataSection",
  },
  {
    id: "run-detail-last-failure-card",
    label: "Loading last failure details",
    variant: "panel",
    modulePath: "@/components/runs/RunDetailLastFailureCard",
    exportName: "RunDetailLastFailureCard",
  },
  {
    id: "run-detail-trust-evidence-card-section",
    label: "Loading trust evidence",
    variant: "panel",
    modulePath: "@/components/runs/RunTrustEvidenceCardSection",
    exportName: "RunTrustEvidenceCardSection",
  },
  {
    id: "run-detail-first-week-route-guidance",
    label: "Loading first-week guidance",
    variant: "panel",
    modulePath: "@/components/FirstWeekRouteGuidance",
    exportName: "FirstWeekRouteGuidance",
  },
  {
    id: "run-detail-cold-open-orientation",
    label: "Loading review orientation",
    variant: "panel",
    modulePath: "@/components/reviews/RunDetailColdOpenOrientationClient",
    exportName: "RunDetailColdOpenOrientationClient",
  },
  {
    id: "run-detail-explanation-confidence-banner",
    label: "Loading explanation confidence",
    variant: "panel",
    modulePath: "@/components/runs/RunExplanationConfidenceBanner",
    exportName: "RunExplanationConfidenceBanner",
  },
  {
    id: "run-detail-what-if-branch-compare-banner",
    label: "Loading branch compare banner",
    variant: "panel",
    modulePath: "@/components/draft-intake/WhatIfBranchCompareBanner",
    exportName: "WhatIfBranchCompareBanner",
  },
  {
    id: "run-detail-stalled-review-guidance-callout",
    label: "Loading stalled review guidance",
    variant: "panel",
    modulePath: "@/components/usability/StalledReviewGuidanceCallout",
    exportName: "StalledReviewGuidanceCallout",
  },
  {
    id: "run-detail-cto-demo-review-route-guard",
    label: "Loading demo route guard",
    variant: "panel",
    modulePath: "@/components/cto-demo/CtoDemoReviewRouteGuard",
    exportName: "CtoDemoReviewRouteGuard",
  },
  {
    id: "run-detail-tabbed-section-nav",
    label: "Loading section navigation",
    variant: "panel",
    modulePath: "@/components/runs/RunDetailTabbedSectionNav",
    exportName: "RunDetailTabbedSectionNav",
  },
  {
    id: "run-detail-buyer-mode-fallback-banner",
    label: "Loading buyer mode banner",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailBuyerModeFallbackBanner",
    exportName: "RunDetailBuyerModeFallbackBanner",
  },
  {
    id: "run-detail-demo-marketing-chrome",
    label: "Loading demo marketing chrome",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailDemoMarketingChrome",
    exportName: "RunDetailDemoMarketingChrome",
  },
  {
    id: "run-detail-run-actions-section",
    label: "Loading run actions",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailRunActionsSection",
    exportName: "RunDetailRunActionsSection",
  },
] as const;
