import type { DeferredChunkManifestEntry } from "@/lib/operator/deferred-chunk-manifest";

export const RUN_DETAIL_CHUNK_MANIFEST_EXPORTS_SPONSOR: readonly DeferredChunkManifestEntry[] = [
  {
    id: "run-detail-email-run-to-sponsor-banner",
    label: "Loading sponsor email banner",
    variant: "compact",
    modulePath: "@/components/EmailRunToSponsorBanner",
    exportName: "EmailRunToSponsorBanner",
  },
  {
    id: "run-detail-pilot-roi-validation-handoff",
    label: "Loading ROI validation handoff",
    variant: "compact",
    modulePath: "@/components/pilots/PilotRoiValidationHandoffCard",
    exportName: "PilotRoiValidationHandoffClient",
  },
  {
    id: "run-detail-artifacts-exports-section",
    label: "Loading artifacts and exports",
    variant: "section",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailArtifactsExportsSection",
    exportName: "RunDetailArtifactsExportsSection",
  },
  {
    id: "run-detail-operator-technical-forensics",
    label: "Loading operator forensics",
    variant: "panel",
    modulePath:
      "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailOperatorTechnicalForensicsPanel",
    exportName: "RunDetailOperatorTechnicalForensicsPanel",
  },
  {
    id: "run-detail-sponsor-bottom-line",
    label: "Loading sponsor report",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailSponsorBottomLine",
    exportName: "RunDetailSponsorBottomLine",
  },
  {
    id: "run-detail-review-package-do-this-next-resolved",
    label: "Loading next step",
    variant: "panel",
    modulePath:
      "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailReviewPackageDoThisNextResolved",
    exportName: "RunDetailReviewPackageDoThisNextResolved",
  },
  {
    id: "run-detail-review-package-sponsor-handoff-gate",
    label: "Loading sponsor handoff gate",
    variant: "panel",
    modulePath:
      "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailReviewPackageSponsorHandoffGate",
    exportName: "RunDetailReviewPackageSponsorHandoffGate",
  },
  {
    id: "run-detail-architecture-sponsor-sharing-panel",
    label: "Loading sponsor sharing",
    variant: "panel",
    modulePath: "@/components/architecture/ArchitectureSponsorSharingPanel",
    exportName: "ArchitectureSponsorSharingPanel",
  },
  {
    id: "run-detail-sponsor-report-cta-card",
    label: "Loading sponsor report CTA",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailExecutiveSummaryCtaCard",
    exportName: "RunDetailSponsorReportCtaCard",
  },
  {
    id: "run-detail-review-package-primary-action",
    label: "Loading architecture package action",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/ReviewPackagePrimaryActionTabAware",
    exportName: "ReviewPackagePrimaryActionTabAware",
  },
  {
    id: "run-detail-review-package-sponsor-handoff-strip",
    label: "Loading sponsor handoff strip",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/ReviewPackageSponsorHandoffStrip",
    exportName: "ReviewPackageSponsorHandoffStrip",
  },
  {
    id: "run-detail-review-package-do-this-next-strip",
    label: "Loading do-this-next strip",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/ReviewPackageDoThisNextStrip",
    exportName: "ReviewPackageDoThisNextStrip",
  },
  {
    id: "run-detail-review-package-section",
    label: "Loading architecture package",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailReviewPackageSection",
    exportName: "RunDetailReviewPackageSection",
  },
  {
    id: "run-detail-buyer-pilot-conversion-section",
    label: "Loading buyer pilot conversion",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailBuyerPilotConversionSection",
    exportName: "RunDetailBuyerPilotConversionSection",
  },
  {
    id: "run-detail-review-package-share-row",
    label: "Loading architecture package share row",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailReviewPackageShareRow",
    exportName: "RunDetailReviewPackageShareRow",
  },
  {
    id: "run-detail-golden-sponsor-walkthrough",
    label: "Loading sponsor walkthrough",
    variant: "panel",
    modulePath: "@/components/golden-walkthrough/GoldenSponsorPackageWalkthroughDestination",
    exportName: "GoldenSponsorPackageWalkthroughDestination",
  },
  {
    id: "run-detail-export-deliverable-dialog",
    label: "Loading export dialog",
    variant: "panel",
    modulePath: "@/components/usability/ExportDeliverableDialog",
    exportName: "ExportDeliverableDialog",
  },
  {
    id: "run-detail-generate-adr-from-run-modal",
    label: "Loading generate ADR modal",
    variant: "panel",
    modulePath: "@/components/GenerateAdrFromRunModal",
    exportName: "GenerateAdrFromRunModal",
  },
  {
    id: "run-detail-compare-to-baseline-cta",
    label: "Loading compare to baseline",
    variant: "panel",
    modulePath: "@/components/CompareToBaselineCta",
    exportName: "CompareToBaselineCta",
  },
  {
    id: "run-detail-post-commit-habit-loop",
    label: "Loading post-commit habit loop",
    variant: "panel",
    modulePath: "@/components/PostCommitHabitLoopCard",
    exportName: "PostCommitHabitLoopCard",
  },
] as const;
