import type { DeferredChunkManifestEntry } from "@/lib/operator/deferred-chunk-manifest";

export const RUN_DETAIL_CHUNK_MANIFEST_FINDINGS_GOVERNANCE: readonly DeferredChunkManifestEntry[] = [
  {
    id: "run-detail-findings-what-if-analysis-panel",
    label: "Loading what-if analysis",
    variant: "panel",
    modulePath: "@/components/findings/FindingsWhatIfAnalysisPanel",
    exportName: "FindingsWhatIfAnalysisPanel",
  },
  {
    id: "run-detail-findings-workspace",
    label: "Loading findings workspace",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailFindingsWorkspace",
    exportName: "RunDetailFindingsWorkspace",
  },
  {
    id: "run-detail-run-explanation-section",
    label: "Loading run explanation",
    variant: "panel",
    modulePath: "@/components/runs/RunExplanationSection",
    exportName: "RunExplanationSection",
  },
  {
    id: "run-detail-run-finding-explainability-table",
    label: "Loading finding explainability",
    variant: "panel",
    modulePath: "@/components/runs/RunFindingExplainabilityTable",
    exportName: "RunFindingExplainabilityTable",
  },
  {
    id: "run-detail-governance-alerts",
    label: "Loading alerts",
    variant: "panel",
    modulePath: "@/components/reviews/RunDetailGovernanceAlerts",
    exportName: "RunDetailGovernanceAlerts",
  },
  {
    id: "run-detail-commit-blocking-findings-banner",
    label: "Loading commit blocking banner",
    variant: "panel",
    modulePath: "@/components/usability/CommitBlockingFindingsBanner",
    exportName: "CommitBlockingFindingsBanner",
  },
  {
    id: "run-detail-policy-pack-impact-callout",
    label: "Loading policy pack impact",
    variant: "panel",
    modulePath: "@/components/findings/ReviewDetailPolicyPackImpactSection",
    exportName: "ReviewDetailPolicyPackImpactSection",
  },
  {
    id: "run-detail-recurrence-schedule-post-commit-card",
    label: "Loading recurrence schedule card",
    variant: "panel",
    modulePath: "@/components/governance/RecurrenceSchedulePostCommitCard",
    exportName: "RecurrenceSchedulePostCommitCard",
  },
  {
    id: "run-detail-retrieval-grounding-section",
    label: "Loading retrieval grounding",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailRetrievalGroundingSection",
    exportName: "RunDetailRetrievalGroundingSection",
  },
  {
    id: "run-detail-authority-chain-section",
    label: "Loading authority chain",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailAuthorityChainSection",
    exportName: "RunDetailAuthorityChainSection",
  },
  {
    id: "run-detail-advanced-analysis-section",
    label: "Loading advanced analysis",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailAdvancedAnalysisSection",
    exportName: "RunDetailAdvancedAnalysisSection",
  },
  {
    id: "run-detail-governance-decision-section",
    label: "Loading approval decision",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailGovernanceDecisionSection",
    exportName: "RunDetailGovernanceDecisionSection",
  },
  {
    id: "run-detail-governance-cta",
    label: "Loading approval CTA",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailGovernanceCta",
    exportName: "RunDetailGovernanceCta",
  },
  {
    id: "run-detail-holistic-critic-panel",
    label: "Loading holistic critique panel",
    variant: "panel",
    modulePath: "@/app/(operator)/architecture/reviews/[reviewId]/_sections/RunDetailHolisticCriticPanel",
    exportName: "RunDetailHolisticCriticPanel",
  },
] as const;
