import type { DeferredChunkManifestEntry } from "@/lib/operator/deferred-chunk-manifest";

/** TB-2371 — sponsor ROI dashboard deferred chunk catalog. */
export const SPONSOR_ROI_DASHBOARD_CHUNK_MANIFEST: readonly DeferredChunkManifestEntry[] = [
  {
    id: "sponsor-roi-dashboard-next-action",
    label: "Loading next action",
    variant: "section",
    modulePath: "@/app/(operator)/architecture/sponsor-dashboard/_sections/SponsorDashboardNextActionSection",
    exportName: "SponsorDashboardNextActionSection",
  },
  {
    id: "sponsor-roi-dashboard-primary-metrics",
    label: "Loading primary metrics",
    variant: "section",
    modulePath: "@/app/(operator)/architecture/sponsor-dashboard/_sections/SponsorDashboardPrimaryMetricsSection",
    exportName: "SponsorDashboardPrimaryMetricsSection",
  },
  {
    id: "sponsor-roi-dashboard-how-it-works",
    label: "Loading dashboard guide",
    variant: "section",
    modulePath: "@/components/sponsor/SponsorDashboardHowItWorks",
    exportName: "SponsorDashboardHowItWorks",
  },
  {
    id: "sponsor-roi-dashboard-exports",
    label: "Loading sponsor exports",
    variant: "section",
    modulePath: "@/app/(operator)/architecture/sponsor-dashboard/_sections/SponsorExportsSection",
    exportName: "SponsorExportsSection",
  },
  {
    id: "sponsor-roi-dashboard-business-impact",
    label: "Loading business impact",
    variant: "section",
    modulePath: "@/app/(operator)/architecture/sponsor-dashboard/_sections/BusinessImpactSummaryWidget",
    exportName: "BusinessImpactSummaryWidget",
  },
  {
    id: "sponsor-roi-dashboard-roi-summary",
    label: "Loading ROI summary",
    variant: "section",
    modulePath: "@/app/(operator)/architecture/sponsor-dashboard/_sections/SponsorRoiSummarySection",
    exportName: "SponsorRoiSummarySection",
  },
  {
    id: "sponsor-roi-dashboard-compliance-drift-trend",
    label: "Loading compliance drift trend",
    variant: "section",
    modulePath: "@/app/(operator)/architecture/sponsor-dashboard/_sections/SponsorComplianceDriftTrendSection",
    exportName: "SponsorComplianceDriftTrendSection",
  },
  {
    id: "sponsor-roi-dashboard-welcome-onboarding",
    label: "Loading welcome guidance",
    variant: "section",
    modulePath: "@/components/operator/OperatorWelcomeOnboarding",
    exportName: "OperatorWelcomeOnboarding",
  },
  {
    id: "sponsor-roi-dashboard-roi-trend",
    label: "Loading ROI trend",
    variant: "section",
    modulePath: "@/app/(operator)/architecture/sponsor-dashboard/_sections/SponsorRoiTrendSection",
    exportName: "SponsorRoiTrendSection",
  },
  {
    id: "sponsor-roi-dashboard-environment-savings",
    label: "Loading environment savings",
    variant: "section",
    modulePath: "@/app/(operator)/architecture/sponsor-dashboard/_sections/SponsorRoiEnvironmentSavingsSection",
    exportName: "SponsorRoiEnvironmentSavingsSection",
  },
  {
    id: "sponsor-roi-dashboard-supporting-metrics",
    label: "Loading supporting metrics",
    variant: "section",
    modulePath: "@/app/(operator)/architecture/sponsor-dashboard/_sections/SponsorDashboardSupportingMetricsSection",
    exportName: "SponsorDashboardSupportingMetricsSection",
  },
  {
    id: "sponsor-roi-dashboard-workspace-health",
    label: "Loading workspace health",
    variant: "section",
    modulePath: "@/components/SponsorWorkspaceHealthDashboard",
    exportName: "SponsorWorkspaceHealthDashboard",
  },
  {
    id: "sponsor-roi-dashboard-page-view",
    label: "Loading sponsor dashboard",
    variant: "section",
    modulePath: "@/app/(operator)/architecture/sponsor-dashboard/_sections/SponsorRoiDashboardPageView",
    exportName: "SponsorRoiDashboardPageView",
  },
  {
    id: "sponsor-roi-dashboard-systemic-issue-trend-chart",
    label: "Loading systemic issue trend chart",
    variant: "section",
    modulePath: "@/components/SponsorRoiSystemicIssueTrendChart",
    exportName: "SponsorRoiSystemicIssueTrendChart",
  },
] as const;
