import { OperatorApiProblem } from "@/components/OperatorApiProblem";
import type { WhyArchLucidPageState } from "@/app/(operator)/why-archlucid/_sections/why-archlucid-page-state";

export type WhyArchLucidFirstValueReportSectionProps = {
  readonly state: WhyArchLucidPageState;
};

export function WhyArchLucidFirstValueReportSection(props: WhyArchLucidFirstValueReportSectionProps) {
  const { state } = props;

  return (
    <section
      aria-labelledby="why-archlucid-report-heading"
      data-testid="why-archlucid-first-value-report"
      className="space-y-3"
    >
      <h2 id="why-archlucid-report-heading" className="text-sm font-semibold text-al-text-primary">
        Sponsor first-value report
      </h2>
      <p className="text-sm text-neutral-600 dark:text-neutral-400">
        Markdown generated by <code>FirstValueReportBuilder</code> from the committed Contoso Retail demo review.
      </p>

      {state.reportError ? (
        <OperatorApiProblem
          problem={state.reportError.problem}
          fallbackMessage={state.reportError.message}
          correlationId={state.reportError.correlationId}
        />
      ) : null}

      {state.reportMissing ? (
        <p className="text-sm text-neutral-500">
          The demo review has not been committed yet — run <code>pilot up</code> or seed the Contoso Retail demo and refresh.
        </p>
      ) : null}

      {state.reportMarkdown ? (
        <pre
          data-testid="why-archlucid-first-value-report-body"
          className="max-h-[480px] overflow-auto rounded border border-neutral-200 bg-neutral-50 p-3 text-xs leading-relaxed text-neutral-800 dark:border-neutral-800 dark:bg-neutral-900 dark:text-neutral-200 whitespace-pre-wrap"
        >
          {state.reportMarkdown}
        </pre>
      ) : !state.reportError && !state.reportMissing && state.loading ? (
        <div className="space-y-2 rounded border border-neutral-200 bg-neutral-50 p-4 dark:border-neutral-800 dark:bg-neutral-900/40">
          <div className="h-3 max-w-xl animate-pulse rounded bg-neutral-200 dark:bg-neutral-700" />
          <div
            className="mt-4 h-[200px] max-h-[480px] animate-pulse rounded bg-neutral-200/80 dark:bg-neutral-700/70"
            role="status"
            aria-busy
            aria-label="Loading first-value report"
          />
        </div>
      ) : null}
    </section>
  );
}
