import { cn } from "@/lib/utils";
import { OperatorApiProblem } from "@/components/operator/OperatorApiProblem";
import type { WhyArchLucidDemoUniverse } from "@/app/(operator)/why-archlucid/_sections/why-archlucid-demo-universe";
import type { WhyArchLucidPageState } from "@/app/(operator)/why-archlucid/_sections/why-archlucid-page-state";
import { OPERATOR_TYPOGRAPHY } from "@/lib/design-tokens";

export type WhyArchLucidFirstValueReportSectionProps = {
  readonly state: WhyArchLucidPageState;
  readonly universe: WhyArchLucidDemoUniverse;
};

function firstValueReportHelperLead(universe: WhyArchLucidDemoUniverse): string {
  switch (universe) {
    case "claims":
      return "the committed Claims Intake demo review";
    case "contoso":
      return "the committed Retail baseline demo review";
    case "unknown":
      return "the committed demo review when available";
    default: {
      const _exhaustive: never = universe;

      return _exhaustive;
    }
  }
}

function firstValueReportMissingLead(universe: WhyArchLucidDemoUniverse): string {
  switch (universe) {
    case "claims":
      return "seed the Claims Intake demo";
    case "contoso":
      return "seed the Retail baseline demo";
    case "unknown":
      return "seed a consistent demo package";
    default: {
      const _exhaustive: never = universe;

      return _exhaustive;
    }
  }
}

export function WhyArchLucidFirstValueReportSection(props: WhyArchLucidFirstValueReportSectionProps) {
  const { state, universe } = props;
  const helperLead = firstValueReportHelperLead(universe);
  const missingLead = firstValueReportMissingLead(universe);

  return (
    <section
      aria-labelledby="why-archlucid-report-heading"
      data-testid="why-archlucid-first-value-report"
      className="space-y-3"
    >
      <h2 id="why-archlucid-report-heading" className={cn("text-al-text-primary", OPERATOR_TYPOGRAPHY.sectionTitle)}>
        Sponsor first-value report
      </h2>
      <p className={cn("text-al-text-secondary", OPERATOR_TYPOGRAPHY.helper)} data-testid="why-archlucid-report-helper">
        Markdown generated by <code>FirstValueReportBuilder</code> from {helperLead}.
      </p>

      {state.reportError ? (
        <OperatorApiProblem
          problem={state.reportError.problem}
          fallbackMessage={state.reportError.message}
          correlationId={state.reportError.correlationId}
        />
      ) : null}

      {state.reportMissing ? (
        <p className={cn("text-al-text-secondary", OPERATOR_TYPOGRAPHY.body)}>
          The demo review has not been committed yet — run <code>pilot up</code> or {missingLead} and refresh.
        </p>
      ) : null}

      {state.reportMarkdown ? (
        <pre
          data-testid="why-archlucid-first-value-report-body"
          className={cn(
            "max-h-[480px] overflow-auto whitespace-pre-wrap rounded border border-neutral-200 bg-neutral-50 p-3 leading-relaxed text-al-text-primary dark:border-neutral-800 dark:bg-neutral-900",
            OPERATOR_TYPOGRAPHY.micro,
          )}
        >
          {state.reportMarkdown}
        </pre>
      ) : !state.reportError && !state.reportMissing && state.loading ? (
        <div className="space-y-2 rounded border border-neutral-200 bg-neutral-50 p-4 dark:border-neutral-800 dark:bg-neutral-900/40">
          <div className="h-3 max-w-xl animate-pulse rounded bg-neutral-200 dark:bg-neutral-700" />
          <div
            className="mt-4 h-[200px] max-h-[480px] animate-pulse rounded bg-neutral-200/80 dark:bg-neutral-700/70"
            role="status"
            aria-busy
            aria-label="Loading first-value report"
          />
        </div>
      ) : null}
    </section>
  );
}
