import { OPERATOR_NAV_LINK_LABELS } from "@/lib/i18n";
import { BASELINE_SETTINGS_CANONICAL_PATH } from "@/lib/baseline-settings-evidence-copy";
import {
  BASELINE_SETTINGS_PAGE_SUBTITLE,
  BASELINE_SETTINGS_PAGE_TITLE,
} from "@/lib/baseline-settings-present";
import { SETTINGS_SECURITY_TRUST_PATH } from "@/lib/settings-admin-route-paths";

import {
  INTERNAL_DEVELOPER_TOOLS_CATALOG_DESCRIPTION,
  INTERNAL_DEVELOPER_TOOLS_CATALOG_GATE_NOTE,
} from "../developer/developer-settings-copy";
import type { SettingsMasterSection } from "./settings-master-types";

/** Governance, policy packs, security & trust, identity, and internal developer sections. */
export const SETTINGS_MASTER_SECTIONS_SECURITY: readonly SettingsMasterSection[] = [
  {
    id: "governance",
    navLabel: "Approval",
    title: "Approval",
    description: "Approval workflows, findings, and audit surfaces.",
    keywords: ["governance", "approval", "workflow", "audit", "findings"],
    tier: "common",
    destinations: [
      {
        id: "governance-queue",
        title: "Approval queue",
        description: "Review and approve decisions for this workspace.",
        href: "/governance/approval-queue",
        cta: "Open approval queue",
        keywords: ["governance", "approval", "workflow"],
        requiredAuthority: "ReadAuthority",
        tier: "common",
        scope: "workspace",
        source: "inherited",
        editability: "read-only",
        saveBehavior: "Changes require confirmation on destination page",
        highImpact: true,
      },
      {
        id: "governance-audit",
        title: "Audit trail",
        description: "Browse configuration and approval events for this workspace.",
        href: "/governance/audit",
        cta: "Open audit trail",
        keywords: ["audit", "history", "changes", "compliance"],
        requiredAuthority: "ReadAuthority",
        tier: "common",
        scope: "workspace",
        source: "default",
        editability: "read-only",
      },
      {
        id: "recurrence-schedules",
        title: "Recurrence schedules",
        description: "Scheduled architecture reviews and recurrence health.",
        href: "/governance/recurrence-schedules",
        cta: "Manage schedules",
        keywords: ["recurrence", "schedule", "review"],
        requiredAuthority: "ReadAuthority",
        tier: "common",
        scope: "workspace",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
    ],
  },
  {
    id: "policy-packs",
    navLabel: "Policy packs",
    title: "Policy packs",
    description: "Standards packs that shape review findings.",
    keywords: ["policy", "pack", "standards", "rules"],
    tier: "common",
    destinations: [
      {
        id: "policy-packs-hub",
        title: "Policy packs",
        description: "Browse catalog packs and manage workspace-owned packs.",
        href: "/governance/policy-packs",
        cta: "Open policy packs",
        keywords: ["policy", "pack", "catalog"],
        requiredAuthority: "ReadAuthority",
        tier: "common",
        scope: "workspace",
        source: "inherited",
        editability: "admin-only",
      },
    ],
  },
  {
    id: "security-trust",
    navLabel: "Security & Trust",
    title: "Security & Trust",
    description: "Procurement materials and trust-center links.",
    keywords: ["security", "trust", "procurement", "compliance"],
    tier: "common",
    destinations: [
      {
        id: "security-trust-hub",
        title: OPERATOR_NAV_LINK_LABELS.securityTrust,
        description: "Share procurement-ready materials, trust-center links, and assessment status.",
        href: SETTINGS_SECURITY_TRUST_PATH,
        cta: "Open security & trust",
        keywords: ["security", "trust", "procurement"],
        requiredAuthority: "ReadAuthority",
        tier: "common",
        scope: "tenant",
        source: "default",
        editability: "read-only",
      },
    ],
  },
  {
    id: "advanced",
    navLabel: "Advanced",
    title: "Advanced configuration",
    description: "Identity, ROI baseline, and rarely changed tenant controls.",
    keywords: ["advanced", "sso", "scim", "identity", "recycle", "baseline", "roi"],
    tier: "advanced",
    destinations: [
      {
        id: "auth-domains",
        title: "Sign-in domains",
        description: "Verify email domains, test routing, and enforce organization SSO.",
        href: "/administration/auth-domains",
        cta: "Manage sign-in domains",
        keywords: ["domain", "sso", "email", "verification", "routing"],
        requiredAuthority: "AdminAuthority",
        tier: "advanced",
        scope: "tenant",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
      {
        id: "identity-providers",
        title: "Identity providers",
        description: "OIDC authority and audience catalog for this tenant.",
        href: "/administration/identity-providers",
        cta: "Open identity providers",
        keywords: ["identity", "oidc", "saml", "sso"],
        requiredAuthority: "AdminAuthority",
        tier: "advanced",
        scope: "tenant",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
      {
        id: "sso-wizard",
        title: "SSO wizard",
        description: "Guided OIDC or SAML tenant configuration.",
        href: "/administration/identity/sso-wizard",
        cta: "Open SSO wizard",
        keywords: ["sso", "saml", "oidc"],
        requiredAuthority: "AdminAuthority",
        tier: "advanced",
        scope: "tenant",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
      {
        id: "scim-provisioning",
        title: "SCIM provisioning",
        description: "Inbound bearer tokens and connectivity verification.",
        href: "/administration/scim-provisioning",
        cta: "Open SCIM provisioning",
        keywords: ["scim", "provisioning", "directory"],
        requiredAuthority: "AdminAuthority",
        tier: "advanced",
        scope: "tenant",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
      {
        id: "workspace-baseline",
        title: BASELINE_SETTINGS_PAGE_TITLE,
        description: BASELINE_SETTINGS_PAGE_SUBTITLE,
        href: BASELINE_SETTINGS_CANONICAL_PATH,
        cta: "Open baseline settings",
        keywords: ["baseline", "roi", "measurement", "sponsor", "hours", "value"],
        requiredAuthority: "AdminAuthority",
        tier: "advanced",
        scope: "workspace",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
      },
      {
        id: "projects-recycle-bin",
        title: "Projects recycle bin",
        description: "Restore soft-deleted architecture projects.",
        href: "/administration/workspace-settings/recycle-bin",
        cta: "Open recycle bin",
        keywords: ["recycle", "restore", "project", "delete"],
        requiredAuthority: "ReadAuthority",
        tier: "advanced",
        scope: "workspace",
        source: "default",
        editability: "admin-only",
        highImpact: true,
      },
    ],
  },
  {
    id: "developer-internal",
    navLabel: "Developer / internal",
    title: "Developer / internal",
    description: "Internal architect tools for demos and support workflows.",
    keywords: ["developer", "internal", "cli", "theme"],
    tier: "internal",
    destinations: [
      {
        id: "developer-tools",
        title: "Internal developer tools",
        description: `${INTERNAL_DEVELOPER_TOOLS_CATALOG_DESCRIPTION} ${INTERNAL_DEVELOPER_TOOLS_CATALOG_GATE_NOTE}`,
        href: "/administration/developer",
        cta: "Open internal developer tools",
        keywords: ["developer", "cli", "demo"],
        requiredAuthority: "ReadAuthority",
        tier: "internal",
        scope: "user",
        source: "local",
        editability: "editable",
      },
    ],
  },
] as const;
