import { OPERATOR_NAV_LINK_LABELS } from "@/lib/i18n";
import { EXTRACT_UPLOAD_SETTINGS_CANONICAL_PATH } from "@/lib/extract-upload-settings-evidence-copy";
import {
  EXTRACT_UPLOAD_SETTINGS_PAGE_SUBTITLE,
  EXTRACT_UPLOAD_SETTINGS_PAGE_TITLE,
} from "@/lib/extract-upload-settings-page-copy";
import { ITSM_ADMIN_TICKET_LINKAGE_DESCRIPTION } from "@/lib/vocabulary/finding-correlation-vocabulary";

import type { SettingsMasterSection } from "./settings-master-types";

/** Cloud connections, ITSM bridges, and AI usage hub sections. */
export const SETTINGS_MASTER_SECTIONS_INTEGRATIONS: readonly SettingsMasterSection[] = [
  {
    id: "integrations",
    navLabel: "Integrations",
    title: "Integrations",
    description: "Cloud connections, manual inventory upload, and ITSM bridges.",
    keywords: ["integration", "jira", "servicenow", "cloud", "azure", "aws", "extract", "upload", "inventory"],
    tier: "common",
    destinations: [
      {
        id: "cloud-connections",
        title: "Cloud connections",
        description: "Automated inventory connections for evidence collection.",
        href: "/integrations/cloud-connections",
        cta: "Manage connections",
        keywords: ["cloud", "azure", "aws", "gcp", "connection"],
        requiredAuthority: "ExecuteAuthority",
        tier: "common",
        scope: "workspace",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
      {
        id: "extract-upload",
        title: EXTRACT_UPLOAD_SETTINGS_PAGE_TITLE,
        description: EXTRACT_UPLOAD_SETTINGS_PAGE_SUBTITLE,
        href: EXTRACT_UPLOAD_SETTINGS_CANONICAL_PATH,
        cta: "Open extract & upload",
        keywords: ["extract", "upload", "inventory", "azure", "zip", "evidence", "intake"],
        requiredAuthority: "ExecuteAuthority",
        tier: "common",
        scope: "workspace",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
      {
        id: "itsm-jira",
        title: "Jira",
        description: ITSM_ADMIN_TICKET_LINKAGE_DESCRIPTION,
        href: "/integrations/jira",
        cta: "Open Jira settings",
        keywords: ["jira", "itsm", "ticket"],
        requiredAuthority: "AdminAuthority",
        tier: "common",
        scope: "tenant",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
      {
        id: "itsm-servicenow",
        title: "ServiceNow",
        description: ITSM_ADMIN_TICKET_LINKAGE_DESCRIPTION,
        href: "/integrations/servicenow",
        cta: "Open ServiceNow settings",
        keywords: ["servicenow", "itsm", "ticket"],
        requiredAuthority: "AdminAuthority",
        tier: "common",
        scope: "tenant",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
    ],
  },
  {
    id: "ai-usage",
    navLabel: "AI usage and budget",
    title: "AI usage and budget",
    description: "Estimated AI spend and budget utilization.",
    keywords: ["ai", "llm", "cost", "budget", "usage"],
    tier: "common",
    destinations: [
      {
        id: "ai-usage-report",
        title: OPERATOR_NAV_LINK_LABELS.aiUsage,
        description: "Review estimated AI usage, trends, and monthly cap utilization.",
        href: "/administration/ai-usage",
        cta: "Open AI usage",
        keywords: ["ai", "cost", "budget", "llm"],
        requiredAuthority: "AdminAuthority",
        tier: "common",
        scope: "workspace",
        source: "default",
        editability: "read-only",
      },
      {
        id: "model-governance",
        title: "AI models",
        description: "Workspace execution profile, allowed models, and task-to-model mappings used on reviews.",
        href: "/administration/model-governance",
        cta: "Open AI models",
        keywords: ["ai", "model", "governance", "alias", "profile", "llm"],
        requiredAuthority: "AdminAuthority",
        tier: "common",
        scope: "tenant",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
    ],
  },
] as const;
