import { OPERATOR_NAV_LINK_LABELS } from "@/lib/i18n";
import { BASELINE_SETTINGS_CANONICAL_PATH } from "@/lib/baseline-settings-evidence-copy";
import {
  BASELINE_SETTINGS_PAGE_SUBTITLE,
  BASELINE_SETTINGS_PAGE_TITLE,
} from "@/lib/baseline-settings-present";
import { EXTRACT_UPLOAD_SETTINGS_CANONICAL_PATH } from "@/lib/extract-upload-settings-evidence-copy";
import {
  EXTRACT_UPLOAD_SETTINGS_PAGE_SUBTITLE,
  EXTRACT_UPLOAD_SETTINGS_PAGE_TITLE,
} from "@/lib/extract-upload-settings-page-copy";
import { ITSM_ADMIN_TICKET_LINKAGE_DESCRIPTION } from "@/lib/vocabulary/finding-correlation-vocabulary";
import { SETTINGS_NOTIFICATIONS_PATH, SETTINGS_SECURITY_TRUST_PATH } from "@/lib/settings-admin-route-paths";

import {
  INTERNAL_DEVELOPER_TOOLS_CATALOG_DESCRIPTION,
  INTERNAL_DEVELOPER_TOOLS_CATALOG_GATE_NOTE,
} from "../developer/developer-settings-copy";
import type { SettingsMasterSection } from "./settings-master-types";

/** Searchable master settings index — hub links; detail pages own editable controls. */
export const SETTINGS_MASTER_SECTIONS: readonly SettingsMasterSection[] = [
  {
    id: "workspace",
    // Personal settings (appearance, sign-in methods) belong to SELF_SETTINGS_DESTINATIONS and are published
    // from the top-bar account menu. Adding a `scope: "user"` destination here would hide it behind this hub's
    // authority filter — `settings-master-audience.ts` drops personal audiences so that mistake cannot ship.
    navLabel: "Workspace",
    title: "Workspace",
    description: "Defaults and operational preferences for this workspace.",
    keywords: ["workspace", "tenant", "digest", "timezone", "trial"],
    tier: "common",
    destinations: [
      {
        id: "workspace-settings",
        title: OPERATOR_NAV_LINK_LABELS.workspaceSettings,
        description: "Trial posture, cost settings, request scope, and workspace defaults.",
        href: "/administration/workspace-settings",
        cta: "Open workspace settings",
        keywords: ["workspace", "tenant", "defaults", "cost"],
        requiredAuthority: "AdminAuthority",
        tier: "common",
        scope: "workspace",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
      },
    ],
  },
  {
    id: "notifications",
    navLabel: "Notifications",
    title: "Notifications",
    description: "Digests, policy alerts, Teams, and Slack - what can ping this workspace.",
    keywords: ["notification", "digest", "alert", "teams", "slack", "email", "ping"],
    tier: "common",
    destinations: [
      {
        id: "notification-preference-center",
        title: OPERATOR_NAV_LINK_LABELS.notifications,
        description:
          "Open the notification preference hub for digests, alerts inbox and rules, Teams, and Slack. Each channel is configured on its own page.",
        href: SETTINGS_NOTIFICATIONS_PATH,
        cta: "Open notifications",
        keywords: ["notification", "digest", "alert", "teams", "slack"],
        requiredAuthority: "ReadAuthority",
        tier: "common",
        scope: "workspace",
        source: "default",
        editability: "read-only",
      },
    ],
  },
  {
    id: "users-roles",
    navLabel: OPERATOR_NAV_LINK_LABELS.usersAndRoles,
    title: OPERATOR_NAV_LINK_LABELS.usersAndRoles,
    description: "Directory, role assignments, and access control.",
    keywords: ["users", "roles", "directory", "admin", "access"],
    tier: "common",
    destinations: [
      {
        id: "users-directory",
        title: OPERATOR_NAV_LINK_LABELS.usersAndRoles,
        description: "Manage workspace members, role assignments, and invitations.",
        href: "/administration/users",
        cta: "Manage users",
        keywords: ["users", "roles", "directory", "invite"],
        requiredAuthority: "AdminAuthority",
        tier: "common",
        scope: "tenant",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
    ],
  },
  {
    id: "governance",
    navLabel: "Approval",
    title: "Approval",
    description: "Approval workflows, findings, and audit surfaces.",
    keywords: ["governance", "approval", "workflow", "audit", "findings"],
    tier: "common",
    destinations: [
      {
        id: "governance-queue",
        title: "Approval queue",
        description: "Review and approve decisions for this workspace.",
        href: "/governance/approval-queue",
        cta: "Open approval queue",
        keywords: ["governance", "approval", "workflow"],
        requiredAuthority: "ReadAuthority",
        tier: "common",
        scope: "workspace",
        source: "inherited",
        editability: "read-only",
        saveBehavior: "Changes require confirmation on destination page",
        highImpact: true,
      },
      {
        id: "governance-audit",
        title: "Audit trail",
        description: "Browse configuration and approval events for this workspace.",
        href: "/governance/audit",
        cta: "Open audit trail",
        keywords: ["audit", "history", "changes", "compliance"],
        requiredAuthority: "ReadAuthority",
        tier: "common",
        scope: "workspace",
        source: "default",
        editability: "read-only",
      },
      {
        id: "recurrence-schedules",
        title: "Recurrence schedules",
        description: "Scheduled architecture reviews and recurrence health.",
        href: "/governance/recurrence-schedules",
        cta: "Manage schedules",
        keywords: ["recurrence", "schedule", "review"],
        requiredAuthority: "ReadAuthority",
        tier: "common",
        scope: "workspace",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
    ],
  },
  {
    id: "policy-packs",
    navLabel: "Policy packs",
    title: "Policy packs",
    description: "Standards packs that shape review findings.",
    keywords: ["policy", "pack", "standards", "rules"],
    tier: "common",
    destinations: [
      {
        id: "policy-packs-hub",
        title: "Policy packs",
        description: "Browse catalog packs and manage workspace-owned packs.",
        href: "/governance/policy-packs",
        cta: "Open policy packs",
        keywords: ["policy", "pack", "catalog"],
        requiredAuthority: "ReadAuthority",
        tier: "common",
        scope: "workspace",
        source: "inherited",
        editability: "admin-only",
      },
    ],
  },
  {
    id: "integrations",
    navLabel: "Integrations",
    title: "Integrations",
    description: "Cloud connections, manual inventory upload, and ITSM bridges.",
    keywords: ["integration", "jira", "servicenow", "cloud", "azure", "aws", "extract", "upload", "inventory"],
    tier: "common",
    destinations: [
      {
        id: "cloud-connections",
        title: "Cloud connections",
        description: "Automated inventory connections for evidence collection.",
        href: "/integrations/cloud-connections",
        cta: "Manage connections",
        keywords: ["cloud", "azure", "aws", "gcp", "connection"],
        requiredAuthority: "ExecuteAuthority",
        tier: "common",
        scope: "workspace",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
      {
        id: "extract-upload",
        title: EXTRACT_UPLOAD_SETTINGS_PAGE_TITLE,
        description: EXTRACT_UPLOAD_SETTINGS_PAGE_SUBTITLE,
        href: EXTRACT_UPLOAD_SETTINGS_CANONICAL_PATH,
        cta: "Open extract & upload",
        keywords: ["extract", "upload", "inventory", "azure", "zip", "evidence", "intake"],
        requiredAuthority: "ExecuteAuthority",
        tier: "common",
        scope: "workspace",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
      {
        id: "itsm-jira",
        title: "Jira",
        description: ITSM_ADMIN_TICKET_LINKAGE_DESCRIPTION,
        href: "/integrations/jira",
        cta: "Open Jira settings",
        keywords: ["jira", "itsm", "ticket"],
        requiredAuthority: "AdminAuthority",
        tier: "common",
        scope: "tenant",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
      {
        id: "itsm-servicenow",
        title: "ServiceNow",
        description: ITSM_ADMIN_TICKET_LINKAGE_DESCRIPTION,
        href: "/integrations/servicenow",
        cta: "Open ServiceNow settings",
        keywords: ["servicenow", "itsm", "ticket"],
        requiredAuthority: "AdminAuthority",
        tier: "common",
        scope: "tenant",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
    ],
  },
  {
    id: "ai-usage",
    navLabel: "AI usage and budget",
    title: "AI usage and budget",
    description: "Estimated AI spend and budget utilization.",
    keywords: ["ai", "llm", "cost", "budget", "usage"],
    tier: "common",
    destinations: [
      {
        id: "ai-usage-report",
        title: OPERATOR_NAV_LINK_LABELS.aiUsage,
        description: "Review estimated AI usage, trends, and monthly cap utilization.",
        href: "/administration/ai-usage",
        cta: "Open AI usage",
        keywords: ["ai", "cost", "budget", "llm"],
        requiredAuthority: "AdminAuthority",
        tier: "common",
        scope: "workspace",
        source: "default",
        editability: "read-only",
      },
      {
        id: "model-governance",
        title: "AI and model governance",
        description: "Workspace default execution profile, approved model aliases, and profile→alias mappings.",
        href: "/administration/model-governance",
        cta: "Open model governance",
        keywords: ["ai", "model", "governance", "alias", "profile", "llm"],
        requiredAuthority: "AdminAuthority",
        tier: "common",
        scope: "tenant",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
    ],
  },
  {
    id: "billing",
    navLabel: "Billing",
    title: "Billing",
    description: "Plans, wallet balance, and payment settings.",
    keywords: ["billing", "plan", "wallet", "payment", "invoice"],
    tier: "common",
    destinations: [
      {
        id: "billing-wallet",
        title: "Billing & plans",
        description: "View plan tier, wallet balance, and credit settings.",
        href: "/administration/billing",
        cta: "Open billing",
        keywords: ["billing", "wallet", "plan"],
        requiredAuthority: "ReadAuthority",
        tier: "common",
        scope: "tenant",
        source: "inherited",
        editability: "read-only",
        saveBehavior: "Credit changes require admin confirmation on destination page",
        highImpact: true,
      },
    ],
  },
  {
    id: "security-trust",
    navLabel: "Security & Trust",
    title: "Security & Trust",
    description: "Procurement materials and trust-center links.",
    keywords: ["security", "trust", "procurement", "compliance"],
    tier: "common",
    destinations: [
      {
        id: "security-trust-hub",
        title: OPERATOR_NAV_LINK_LABELS.securityTrust,
        description: "Share procurement-ready materials, trust-center links, and assessment status.",
        href: SETTINGS_SECURITY_TRUST_PATH,
        cta: "Open security & trust",
        keywords: ["security", "trust", "procurement"],
        requiredAuthority: "ReadAuthority",
        tier: "common",
        scope: "tenant",
        source: "default",
        editability: "read-only",
      },
    ],
  },
  {
    id: "support",
    navLabel: "Support",
    title: "Support",
    description: "Diagnostics bundles and support workflows.",
    keywords: ["support", "bundle", "diagnostics", "ticket"],
    tier: "common",
    destinations: [],
  },
  {
    id: "advanced",
    navLabel: "Advanced",
    title: "Advanced configuration",
    description: "Identity, ROI baseline, and rarely changed tenant controls.",
    keywords: ["advanced", "sso", "scim", "identity", "recycle", "baseline", "roi"],
    tier: "advanced",
    destinations: [
      {
        id: "auth-domains",
        title: "Sign-in domains",
        description: "Verify email domains, test routing, and enforce organization SSO.",
        href: "/administration/auth-domains",
        cta: "Manage sign-in domains",
        keywords: ["domain", "sso", "email", "verification", "routing"],
        requiredAuthority: "AdminAuthority",
        tier: "advanced",
        scope: "tenant",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
      {
        id: "identity-providers",
        title: "Identity providers",
        description: "OIDC authority and audience catalog for this tenant.",
        href: "/administration/identity-providers",
        cta: "Open identity providers",
        keywords: ["identity", "oidc", "saml", "sso"],
        requiredAuthority: "AdminAuthority",
        tier: "advanced",
        scope: "tenant",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
      {
        id: "sso-wizard",
        title: "SSO wizard",
        description: "Guided OIDC or SAML tenant configuration.",
        href: "/administration/identity/sso-wizard",
        cta: "Open SSO wizard",
        keywords: ["sso", "saml", "oidc"],
        requiredAuthority: "AdminAuthority",
        tier: "advanced",
        scope: "tenant",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
      {
        id: "scim-provisioning",
        title: "SCIM provisioning",
        description: "Inbound bearer tokens and connectivity verification.",
        href: "/administration/scim-provisioning",
        cta: "Open SCIM provisioning",
        keywords: ["scim", "provisioning", "directory"],
        requiredAuthority: "AdminAuthority",
        tier: "advanced",
        scope: "tenant",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
        highImpact: true,
      },
      {
        id: "workspace-baseline",
        title: BASELINE_SETTINGS_PAGE_TITLE,
        description: BASELINE_SETTINGS_PAGE_SUBTITLE,
        href: BASELINE_SETTINGS_CANONICAL_PATH,
        cta: "Open baseline settings",
        keywords: ["baseline", "roi", "measurement", "sponsor", "hours", "value"],
        requiredAuthority: "AdminAuthority",
        tier: "advanced",
        scope: "workspace",
        source: "overridden",
        editability: "admin-only",
        saveBehavior: "Save on destination page",
      },
      {
        id: "projects-recycle-bin",
        title: "Projects recycle bin",
        description: "Restore soft-deleted architecture projects.",
        href: "/administration/workspace-settings/recycle-bin",
        cta: "Open recycle bin",
        keywords: ["recycle", "restore", "project", "delete"],
        requiredAuthority: "ReadAuthority",
        tier: "advanced",
        scope: "workspace",
        source: "default",
        editability: "admin-only",
        highImpact: true,
      },
    ],
  },
  {
    id: "developer-internal",
    navLabel: "Developer / internal",
    title: "Developer / internal",
    description: "Internal architect tools for demos and support workflows.",
    keywords: ["developer", "internal", "cli", "theme"],
    tier: "internal",
    destinations: [
      {
        id: "developer-tools",
        title: "Internal developer tools",
        description: `${INTERNAL_DEVELOPER_TOOLS_CATALOG_DESCRIPTION} ${INTERNAL_DEVELOPER_TOOLS_CATALOG_GATE_NOTE}`,
        href: "/administration/developer",
        cta: "Open internal developer tools",
        keywords: ["developer", "cli", "demo"],
        requiredAuthority: "ReadAuthority",
        tier: "internal",
        scope: "user",
        source: "local",
        editability: "editable",
      },
    ],
  },
] as const;

export function settingsMasterSectionDomId(sectionId: string): string {
  return `settings-section-${sectionId}`;
}
