import {
  AUTH_INVITE_HELP_LABEL,
  AUTH_INVITE_HELP_PATH,
  AUTH_INVITE_PUBLIC_EXIT_LABEL,
  AUTH_INVITE_PUBLIC_EXIT_PATH,
} from "@/lib/auth/invitation-invalid-recovery-copy";
import {
  POST_AUTH_BOOTSTRAP_SIGN_IN_AGAIN_LABEL,
  POST_AUTH_BOOTSTRAP_SIGN_IN_PATH,
  POST_AUTH_BOOTSTRAP_USE_DIFFERENT_ACCOUNT_LABEL,
} from "@/lib/auth/post-auth-bootstrap-exit-copy";

export {
  AUTH_INVITE_HELP_LABEL,
  AUTH_INVITE_HELP_PATH,
  AUTH_INVITE_PUBLIC_EXIT_LABEL,
  AUTH_INVITE_PUBLIC_EXIT_PATH,
  POST_AUTH_BOOTSTRAP_SIGN_IN_AGAIN_LABEL as AUTH_INVITE_SIGN_IN_AGAIN_LABEL,
  POST_AUTH_BOOTSTRAP_SIGN_IN_PATH as AUTH_INVITE_SIGN_IN_AGAIN_PATH,
  POST_AUTH_BOOTSTRAP_USE_DIFFERENT_ACCOUNT_LABEL as AUTH_INVITE_USE_DIFFERENT_ACCOUNT_LABEL,
};
