using ArchLucid.Core.Configuration;
using ArchLucid.Core.ProductLine;

using FluentAssertions;

namespace ArchLucid.Core.Tests.ProductLine;

[Trait("Category", "Unit")]
public sealed class ProductLineConsumerNamesTests
{
    [Fact]
    public void DisplayName_returns_defaults_when_options_unset()
    {
        ProductLineConsumerNames.DisplayName(ProductLineId.Architecture).Should().Be("ArchLucid");
        ProductLineConsumerNames.DisplayName(ProductLineId.Security).Should().Be("SecureNow");
    }

    [Fact]
    public void DisplayName_honors_configured_overrides()
    {
        ProductLineDisplayNamesOptions options = new()
        {
            Architecture = "Custom Arch",
            Security = "Custom Sec",
        };

        ProductLineConsumerNames.DisplayName(ProductLineId.Architecture, options).Should().Be("Custom Arch");
        ProductLineConsumerNames.DisplayName(ProductLineId.Security, options).Should().Be("Custom Sec");
    }

    [Fact]
    public void GeneratedByLine_uses_security_display_name()
    {
        ProductLineConsumerNames.GeneratedByLine(ProductLineId.Security)
            .Should()
            .Be("Generated by SecureNow");
    }

    [Fact]
    public void DefaultFooterAttributionTemplate_uses_product_line_name()
    {
        ProductLineConsumerNames.DefaultFooterAttributionTemplate(ProductLineId.Security)
            .Should()
            .Be("Prepared by {FirmDisplayName} using SecureNow");
    }
}
