import { describe, expect, it } from "vitest";

import {
  GOVERNANCE_WORKFLOW_AUDIT_TRAIL_ACTOR_HELPER,
  GOVERNANCE_WORKFLOW_AUDIT_TRAIL_ACTOR_LABEL,
  GOVERNANCE_WORKFLOW_AUDIT_TRAIL_ACTOR_PLACEHOLDER,
  GOVERNANCE_WORKFLOW_ENVIRONMENT_RELEASES_ACCORDION_LABEL,
  GOVERNANCE_WORKFLOW_NO_RELEASES_RECORDED_TITLE,
  GOVERNANCE_WORKFLOW_READER_LOAD_REVIEW_HINT,
  GOVERNANCE_WORKFLOW_RELEASE_CARD_TITLE_PREFIX,
  GOVERNANCE_WORKFLOW_RELEASE_CONFIRM_BUTTON,
  GOVERNANCE_WORKFLOW_RELEASE_CONFIRM_TITLE,
  GOVERNANCE_WORKFLOW_RELEASE_SUCCESS_TOAST,
  GOVERNANCE_WORKFLOW_RELEASE_TO_ENVIRONMENT_BUTTON,
  GOVERNANCE_WORKFLOW_RELEASE_TO_ENVIRONMENT_BUTTON_READER,
  GOVERNANCE_WORKFLOW_SUBMIT_CARD_DESCRIPTION_OPERATOR,
  GOVERNANCE_WORKFLOW_TIMELINE_LEAD,
  governanceWorkflowReleaseConfirmDescription,
} from "@/lib/governance/governance-workflow-release-copy";

describe("governance-workflow-release-copy (TB-510)", () => {
  it("avoids promote or promotion as standalone action verbs in release vocabulary", () => {
    const strings = [
      GOVERNANCE_WORKFLOW_RELEASE_TO_ENVIRONMENT_BUTTON,
      GOVERNANCE_WORKFLOW_RELEASE_TO_ENVIRONMENT_BUTTON_READER,
      GOVERNANCE_WORKFLOW_ENVIRONMENT_RELEASES_ACCORDION_LABEL,
      GOVERNANCE_WORKFLOW_RELEASE_CONFIRM_TITLE,
      GOVERNANCE_WORKFLOW_RELEASE_CONFIRM_BUTTON,
      GOVERNANCE_WORKFLOW_NO_RELEASES_RECORDED_TITLE,
      GOVERNANCE_WORKFLOW_RELEASE_CARD_TITLE_PREFIX,
      GOVERNANCE_WORKFLOW_TIMELINE_LEAD,
      GOVERNANCE_WORKFLOW_AUDIT_TRAIL_ACTOR_LABEL,
      GOVERNANCE_WORKFLOW_AUDIT_TRAIL_ACTOR_PLACEHOLDER,
      GOVERNANCE_WORKFLOW_AUDIT_TRAIL_ACTOR_HELPER,
      GOVERNANCE_WORKFLOW_SUBMIT_CARD_DESCRIPTION_OPERATOR,
      GOVERNANCE_WORKFLOW_READER_LOAD_REVIEW_HINT,
      GOVERNANCE_WORKFLOW_RELEASE_SUCCESS_TOAST,
      governanceWorkflowReleaseConfirmDescription("3.4.1", "test"),
    ];

    for (const value of strings) {
      expect(value.toLowerCase()).not.toMatch(/\bpromote\b/);
      expect(value.toLowerCase()).not.toMatch(/\bpromotion\b/);
    }
  });
});
