import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";

import { PolicyRulePlainEnglishDraftPanel } from "@/app/(operator)/governance/policy-packs/_sections/PolicyRulePlainEnglishDraftPanel";
import { createEmptyCuratedRulesDocument } from "@/lib/policy-pack-curated-rules-v1";

vi.mock("@/lib/api/policy-pack-draft-api", () => ({
  draftPolicyPackRule: vi.fn(async () => ({
    disclaimer: "This draft was generated by AI and requires human review before activation.",
    draftRuleJson: JSON.stringify({
      id: "tls-lb-001",
      title: "Require TLS 1.2 on load balancers",
      description: "Public load balancers must enforce TLS 1.2 or higher.",
      severity: "High",
      remediationGuidance: "Update listener policies and document cipher suites.",
      evidenceHints: ["governance.RequiredControls"],
      frameworkMappings: [{ framework: "Security baseline", requirement: "Transport encryption" }],
    }),
  })),
}));

vi.mock("@/lib/toast", () => ({
  showSuccess: vi.fn(),
}));

describe("PolicyRulePlainEnglishDraftPanel", () => {
  it("drafts rule JSON and shows schema side-by-side preview", async () => {
    const onCuratedDocChange = vi.fn();

    render(
      <PolicyRulePlainEnglishDraftPanel
        canMutatePacks
        curatedDoc={createEmptyCuratedRulesDocument({})}
        onCuratedDocChange={onCuratedDocChange}
      />,
    );

    fireEvent.change(screen.getByTestId("policy-rule-plain-english-intent"), {
      target: { value: "Require TLS 1.2 on all public-facing load balancers in this architecture." },
    });
    fireEvent.click(screen.getByTestId("policy-rule-plain-english-draft-button"));

    await waitFor(() => {
      expect(screen.getByTestId("policy-rule-plain-english-preview")).toHaveTextContent("tls-lb-001");
    });

    expect(screen.getByText(/requires human review/i)).toBeTruthy();
    expect(screen.getByText("Expected schema")).toBeTruthy();
  });
});
