using System.Globalization;
using System.Text;
using System.Text.Json;

namespace ArchLucid.AgentRuntime.Tests.DriftDetection;

internal static class GoldenCohortDriftSummaryGenerator
{
    private static readonly JsonSerializerOptions TrendJsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    internal static void AppendTrendEntry(GoldenCohortSimulatorVsRealDriftReport report)
    {
        string path = GoldenCohortDriftRepoPaths.ResolveDriftTrendLogPath();

        GoldenCohortDriftTrendEvent row = new()
        {
            ScenarioId = report.ScenarioName,
            TimestampUtc = report.TimestampUtc,
            SeverityDivergence = report.SeverityDivergence,
            TitleOverlap = report.TitleOverlap,
            RecommendationOverlap = report.RecommendationOverlap,
            CountDelta = report.CountDelta,
        };

        string line = JsonSerializer.Serialize(row, TrendJsonOptions) + Environment.NewLine;
        File.AppendAllText(path, line);
    }

    internal static void RegenerateMarkdownSummary(IReadOnlyList<GoldenCohortSimulatorVsRealDriftReport> latestBatch)
    {
        string driftDir = GoldenCohortDriftRepoPaths.ResolveDriftReportsDirectory();
        string outPath = GoldenCohortDriftRepoPaths.ResolveDriftSummaryMarkdownPath();

        List<GoldenCohortSimulatorVsRealDriftReport> reports = [];

        foreach (string file in Directory.EnumerateFiles(driftDir, "*-drift.json", SearchOption.TopDirectoryOnly))
        {
            if (file.EndsWith(".sample.json", StringComparison.OrdinalIgnoreCase))
                continue;

            try
            {
                string json = File.ReadAllText(file);

                GoldenCohortSimulatorVsRealDriftReport? row =
                    JsonSerializer.Deserialize<GoldenCohortSimulatorVsRealDriftReport>(
                        json,
                        new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

                if (row is not null)
                    reports.Add(row);
            }
            catch
            {
                // Skip malformed local artifacts — summary stays best-effort.
            }
        }

        if (reports.Count == 0 && latestBatch.Count > 0)
            reports.AddRange(latestBatch);

        StringBuilder md = new();
        md.AppendLine("> **Scope:** Human-readable rollup of simulator-vs-real golden cohort drift — regenerated by drift tests.");
        md.AppendLine();
        md.AppendLine("# Simulator vs real LLM drift summary");
        md.AppendLine();
        md.AppendLine("Regenerated from JSON rows under `tests/golden-cohort/drift-reports/` (and this run's in-memory batch when files are gitignored).");
        md.AppendLine();

        if (reports.Count == 0)
        {
            md.AppendLine("## Latest averages");
            md.AppendLine();
            md.AppendLine("_(No drift reports discovered.)_");
            md.AppendLine();

            File.WriteAllText(outPath, md.ToString());

            return;
        }

        double avgSev = reports.Average(static r => r.SeverityDivergence);
        double avgTitle = reports.Average(static r => r.TitleOverlap);
        double avgRec = reports.Average(static r => r.RecommendationOverlap);
        double avgCountDelta = reports.Average(static r => (double)Math.Abs(r.CountDelta));

        md.AppendLine("## Latest averages");
        md.AppendLine();
        md.AppendLine($"| Metric | Average |");
        md.AppendLine("| --- | --- |");
        md.AppendLine($"| Severity divergence (0-1) | {avgSev.ToString("F4", CultureInfo.InvariantCulture)} |");
        md.AppendLine($"| Title overlap (Jaccard) | {avgTitle.ToString("F4", CultureInfo.InvariantCulture)} |");
        md.AppendLine($"| Recommendation overlap (Jaccard) | {avgRec.ToString("F4", CultureInfo.InvariantCulture)} |");
        md.AppendLine($"| Mean absolute finding-count delta | {avgCountDelta.ToString("F2", CultureInfo.InvariantCulture)} |");
        md.AppendLine();

        md.AppendLine("## Highest divergence scenarios (severity)");
        md.AppendLine();

        foreach (GoldenCohortSimulatorVsRealDriftReport row in reports
                     .OrderByDescending(static r => r.SeverityDivergence)
                     .ThenByDescending(static r => Math.Abs(r.CountDelta))
                     .Take(8))
        {
            md.AppendLine($"- **{row.ScenarioName}** - severity divergence {row.SeverityDivergence.ToString("F4", CultureInfo.InvariantCulture)}, "
                           + $"title overlap {row.TitleOverlap.ToString("F4", CultureInfo.InvariantCulture)}, "
                           + $"count delta {row.CountDelta.ToString(CultureInfo.InvariantCulture)}"
                           + (string.IsNullOrWhiteSpace(row.RealExecutionError)
                               ? string.Empty
                               : $" (real note: `{row.RealExecutionError}`)"));
        }

        md.AppendLine();

        md.AppendLine("## Trend");
        md.AppendLine();
        md.AppendLine("Append-only JSON Lines events live in `tests/golden-cohort/drift-trend.jsonl` when drift runs append rows.");
        md.AppendLine();

        File.WriteAllText(outPath, md.ToString());
    }
}
