using System.Globalization;
using System.Text;

using ArchLucid.Application.Reporting;

namespace ArchLucid.Application.Pilots;

/// <inheritdoc cref="IPilotValueReportMarkdownFormatter" />
public sealed class PilotValueReportMarkdownFormatter(ExportFormatterService exportFormatter) : IPilotValueReportMarkdownFormatter
{
    private readonly ExportFormatterService _exportFormatter =
        exportFormatter ?? throw new ArgumentNullException(nameof(exportFormatter));

    /// <inheritdoc />
    public string Format(PilotValueReport r)
    {
        ArgumentNullException.ThrowIfNull(r);

        StringBuilder sb = new();

        sb.AppendLine("# ArchLucid pilot value report");
        sb.AppendLine();
        _exportFormatter.AppendMarkdownTwoColumnTableStart(sb, "Field", "Value");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Tenant | `{r.TenantId}` |");
        sb.AppendLine(
            CultureInfo.InvariantCulture,
            $"| Window (UTC) | `{_exportFormatter.FormatIso8601Utc(r.FromUtc)}` inclusive → `{_exportFormatter.FormatIso8601Utc(r.ToUtc)}` exclusive |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Committed runs | {r.TotalRunsCommitted} |");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"| Run-detail cap | {r.RunDetailCap} (truncated: {r.RunDetailsTruncated}) |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Audit export truncated | {r.AuditExportTruncated} |");
        sb.AppendLine();

        sb.AppendLine("## Summary");
        sb.AppendLine();
        _exportFormatter.AppendMarkdownTwoColumnTableStart(sb, "Metric", "Value");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Total findings | {r.TotalFindings} |");
        sb.AppendLine(
            CultureInfo.InvariantCulture,
            $"| Avg pipeline completion | {FormatAvgSeconds(r.AveragePipelineCompletionSeconds)} |");

        sb.AppendLine(CultureInfo.InvariantCulture,
            $"| Recommendations generated (audit) | {r.TotalRecommendationsProduced} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Governance approvals | {r.GovernanceApprovals} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Governance rejections | {r.GovernanceRejections} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Policy pack assignments | {r.PolicyPackAssignments} |");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"| Comparison / drift detections | {r.ComparisonOrDriftDetections} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Pending approvals (now) | {r.GovernancePendingApprovalsNow} |");
        sb.AppendLine();

        sb.AppendLine("## Findings by severity");
        sb.AppendLine();
        _exportFormatter.AppendMarkdownTwoColumnTableStart(sb, "Severity", "Count");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Critical | {r.FindingsBySeverity.Critical} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| High | {r.FindingsBySeverity.High} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Medium | {r.FindingsBySeverity.Medium} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Low | {r.FindingsBySeverity.Low} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Info | {r.FindingsBySeverity.Info} |");
        sb.AppendLine();
        AppendSeverityNote(sb);
        sb.AppendLine();

        sb.AppendLine("## Agent types observed");
        sb.AppendLine();
        sb.AppendLine(string.Join(", ", r.UniqueAgentTypes.Select(static t => $"`{t}`")));
        sb.AppendLine();

        sb.AppendLine("## Committed runs (sample loaded for detail)");
        sb.AppendLine();
        _exportFormatter.AppendMarkdownFourColumnTableStart(sb, "Run", "Created (UTC)", "Committed (UTC)", "System");

        foreach (PilotValueReportRunTimelinePoint row in r.CommittedRunsTimeline)
        {
            string committedCell = _exportFormatter.FormatIso8601UtcMarkdownQuotedCell(row.CommittedUtc);

            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"| `{row.RunId}` | {_exportFormatter.FormatIso8601UtcMarkdownQuotedCell(row.CreatedUtc)} | {committedCell} | {EscapeCell(row.SystemName)} |");
        }

        sb.AppendLine();
        sb.AppendLine("— *Generated by ArchLucid in-product pilot value report.*");

        return sb.ToString();
    }

    private static void AppendSeverityNote(StringBuilder sb)
    {
        sb.AppendLine(
            "> Severity mapping: pipeline `FindingSeverity` uses Critical / High (Error) / Medium (Warning) / Info; `Low` is reserved for future contract extensions.");
    }

    private static string FormatAvgSeconds(double? seconds)
    {
        if (seconds is null)
            return "—";

        double s = seconds.Value;

        if (double.IsNaN(s) || double.IsInfinity(s))
            return "—";

        if (s >= 3600)
            return $"{s / 3600:0.##} h";

        return s >= 60 ? $"{s / 60:0.##} min" : $"{s:0.##} s";
    }

    private static string EscapeCell(string value)
    {
        return string.IsNullOrEmpty(value) ? "—" : value.Replace("|", "\\|", StringComparison.Ordinal);
    }
}
