namespace ArchLucid.Contracts.Explanation;

/// <summary>Unstructured markdown critique plus mandatory human-review disclaimer.</summary>
public sealed class HolisticCriticResponse
{
    public const string DefaultDisclaimer =
        "This holistic critique was generated by AI and is not a formal finding. "
        + "Validate recommendations against your standards, evidence, and risk appetite before acting.";

    public string Disclaimer
    {
        get;
        set;
    } = DefaultDisclaimer;

    /// <summary>Free-form markdown critique (not structured findings JSON).</summary>
    public string CritiqueMarkdown
    {
        get;
        set;
    } = string.Empty;
}
