import { describe, expect, it } from "vitest";

import {
  AZURE_CLOUD_CONNECTION_BANNED_COPY,
  AZURE_CONNECTION_CLIENT_APP_ID_HINT,
  AZURE_CONNECTION_IDS_STEP_LEAD,
  AZURE_CONNECTION_POST_SAVE_VALIDATE_LEAD,
  AZURE_CONNECTION_RECENT_ACTIVITY_EMPTY_STATE,
  AZURE_CONNECTION_SAVE_VALIDATE_LEAD,
  AZURE_CONNECTION_SETUP_SCRIPT_FEDERATION_DESCRIPTION,
  AZURE_CONNECTION_SETUP_SCRIPT_VALIDATION_NOTE,
  AZURE_CONNECTION_SUBSCRIPTION_IDS_HINT,
  AZURE_CONNECTION_TENANT_ID_HINT,
  AZURE_CONNECTION_VALIDATE_EMPTY_STATE,
  AZURE_CONNECTION_VALIDATION_DISABLED_ERROR,
  AZURE_CONNECTION_VALIDATION_FALLBACK_ERROR,
  AZURE_CONNECTION_VALIDATION_PREREQUISITES,
} from "@/lib/azure-cloud-connection-copy";

describe("azure-cloud-connection-copy", () => {
  it("keeps operator copy free of Tier/hosted-pull jargon (TB-1766)", () => {
    const surfaces = [
      AZURE_CONNECTION_VALIDATE_EMPTY_STATE,
      AZURE_CONNECTION_RECENT_ACTIVITY_EMPTY_STATE,
      AZURE_CONNECTION_SAVE_VALIDATE_LEAD,
      AZURE_CONNECTION_POST_SAVE_VALIDATE_LEAD,
      AZURE_CONNECTION_VALIDATION_PREREQUISITES,
      AZURE_CONNECTION_VALIDATION_FALLBACK_ERROR,
      AZURE_CONNECTION_VALIDATION_DISABLED_ERROR,
      AZURE_CONNECTION_SETUP_SCRIPT_VALIDATION_NOTE,
      AZURE_CONNECTION_SETUP_SCRIPT_FEDERATION_DESCRIPTION,
      AZURE_CONNECTION_IDS_STEP_LEAD,
      AZURE_CONNECTION_CLIENT_APP_ID_HINT,
      AZURE_CONNECTION_TENANT_ID_HINT,
      AZURE_CONNECTION_SUBSCRIPTION_IDS_HINT,
    ];

    for (const surface of surfaces) {
      for (const banned of AZURE_CLOUD_CONNECTION_BANNED_COPY) {
        expect(surface.toLowerCase()).not.toContain(banned.toLowerCase());
      }
    }
  });
});
