/**
 * TB-2295 — Residual `Button` className chromatic override inventory.
 *
 * Shrink this list as outline/icon buttons migrate to canonical variants.
 * New production modules must not add chromatic `className` overrides on `Button`.
 */
export const TB_2295_BUTTON_CLASSNAME_COLOR_ALLOWLIST = [
  "src/app/(operator)/architecture/sponsor-dashboard/_sections/SponsorDashboardBaselineWarningBanner.tsx",
  "src/app/(operator)/architecture/sponsor-dashboard/_sections/SponsorExportsSection.tsx",
  "src/app/(operator)/governance/audit/_sections/AuditBuyerEmptyState.tsx",
  "src/app/(operator)/governance/audit/_sections/AuditResultsSection.tsx",
  "src/app/(operator)/governance/_sections/GovernanceWorkflowApprovalsList.tsx",
  "src/app/(operator)/insights/ask-review-questions/_sections/AskCompareReviewsCollapsible.tsx",
  "src/app/(operator)/insights/ask-review-questions/_sections/AskMessageThreadPanel.tsx",
  "src/app/(operator)/insights/ask-review-questions/_sections/AskQuestionForm.tsx",
  "src/app/(operator)/insights/ask-review-questions/_sections/AskThreadHistoryPanel.tsx",
  "src/components/AdvancedOptionsAccordion.tsx",
  "src/components/alerts/CompositeAlertRulesContent.tsx",
  "src/components/architecture/ArchitectureDraftStructuredBriefFields.tsx",
  "src/components/BuyerCtoDemoTourOverlay.tsx",
  "src/components/CommandPalette.tsx",
  "src/components/CopyFindingAsWorkItemButton.tsx",
  "src/components/CopyIdButton.tsx",
  "src/components/CopyManifestButton.tsx",
  "src/components/cto-demo/CtoDemoSoftRestartButton.tsx",
  "src/components/DownloadManifestButton.tsx",
  "src/components/EnterpriseCompactEmptyState.tsx",
  "src/components/FrictionlessTrialBanner.tsx",
  "src/components/governance/findings/GovernanceFindingsFilterBar.tsx",
  "src/components/help/HelpMarkdownCodeBlock.tsx",
  "src/components/llm/LlmBudgetStatusPill.tsx",
  "src/components/marketing/HeroEarlyAccessCta.tsx",
  "src/components/OnboardingTour.tsx",
  "src/components/operator-home/OperatorHomeDisclosureSection.tsx",
  "src/components/provenance/ProvenanceGraphViewport.tsx",
  "src/components/reviews/FavoriteReviewToggle.tsx",
  "src/components/runs/ReviewPipelineStopAnalysisButton.tsx",
  "src/components/runs/RunTraceViewerLink.tsx",
  "src/components/ScopeSwitcherProjectOptionButton.tsx",
  "src/components/shell/ShellInFlightOperationsAffordance.tsx",
  "src/components/sidebar-nav/RoleNavDensityExpandControl.tsx",
  "src/components/SponsorShellFrame.tsx",
  "src/components/tour/OptInTourLauncher.tsx",
  "src/components/trial/TrialBanner.tsx",
  "src/components/ui/welcome-modal.tsx",
  "src/components/usability/ProductConceptsGlossaryDialog.tsx",
  "src/components/usability/UsabilityFeedbackWidget.tsx",
  "src/components/wizard/steps/WizardStepConstraints.tsx",
  "src/components/WorkspaceScopeEmptyTeaching.tsx",
] as const;
