/**
 * Surfaces whose title block already carries folded claim-discipline copy omit the shared
 * claim-discipline hero band — operators should not see the same negation twice.
 *
 * Exception: {@link expectsVisibleClaimDisciplineBand} returns true for `package-print` (print
 * orientation must stay on the artifact surface, not only in a web header).
 */
export const CLAIM_DISCIPLINE_BAND_OMIT_SLUGS: ReadonlySet<string> = new Set([
  "access-denied",
  "account-security-settings",
  "admin-configuration",
  "admin-health",
  "admin-itsm-connectors",
  "admin-tenants",
  "agent-model-catalog",
  "ai-usage-settings",
  "alerts-inbox",
  "api-keys-settings",
  "architecture-draft-detail",
  "architecture-intelligence",
  "architecture-scorecard",
  "architectures-hub",
  "architectures-new",
  "audit-trail",
  "auth-callback",
  "auth-domains-settings",
  "auth-invite",
  "azure-boards-integration",
  "azure-permissions-help",
  "baseline-settings",
  "cloud-connections",
  "cloud-connections-gcp",
  "comparison-replay-help",
  "compliance-journey",
  "connection-status",
  "contextual-help-drawer",
  "decision-register",
  "demo-readiness",
  "deployment-status",
  "digest-sponsor",
  "digests-schedule",
  "evidence-graph",
  "evidence-proposals",
  "enterprise-onboarding-help",
  "extract-upload-settings",
  "faq",
  "finding-detail",
  "finding-eru",
  "findings-help",
  "fleet-llm-cogs",
  "get-started",
  "governance-findings",
  "help-ai-usage",
  "help-advisory-scans",
  "help-accelerator-chooser",
  "help-alerts",
  "help-api-keys",
  "help-architecture-drafts",
  "help-baseline-settings",
  "help-billing-and-plans",
  "help-connection-status",
  "help-architecture-intelligence",
  "help-architecture-scorecard",
  "help-azure-boards",
  "help-caiq-sig-response",
  "help-configuration-reference",
  "help-decision-register",
  "help-digests",
  "help-dpa-template",
  "help-impact-preview",
  "help-improvement-planning",
  "help-evidence-graph",
  "help-engineering-troubleshooting",
  "help-first-review",
  "help-first-value-20-minutes",
  "help-getting-started",
  "help-governance-approval",
  "help-hub",
  "help-jira-integration",
  "help-model-governance",
  "help-notifications",
  "help-pilot-feedback",
  "help-policy-pack-delta-demo",
  "help-path-chooser",
  "help-preferences",
  "help-recurrence-schedules",
  "help-review-guide",
  "help-roi-summary",
  "help-search-review-evidence",
  "help-servicenow-integration",
  "help-standards-rules",
  "help-structured-brief",
  "help-slack-integration",
  "help-soc2-self-assessment",
  "help-sponsor-report",
  "help-system-health",
  "help-teams-integration",
  "help-webhooks-integration",
  "help-workspace-settings",
  "identity-providers-diagnostics-settings",
  "identity-providers-oidc-settings",
  "identity-providers-saml-settings",
  "identity-providers-settings",
  "impact-preview",
  "improvement-planning",
  "integration-events-dlq",
  "integration-readiness-help",
  "invite-reviewer",
  "itsm-oauth-callback",
  "jira-integration",
  "model-governance-settings",
  "notification-preference-center",
  "operator-billing-settings",
  "operator-home",
  "pattern-library",
  "pattern-library-detail",
  "pilot-outcomes",
  "planning-plan-detail",
  "platform-bundled-policy-packs",
  "policy-pack-detail",
  "policy-packs-hub",
  "post-auth-bootstrap",
  "preferences-settings",
  "pricing-quote-aging",
  "product-learning",
  "provenance",
  "quick-scan",
  "rag-health",
  "recommendation-learning",
  "report-a-problem-help",
  "repeat-review-loop-help",
  "risk-exceptions",
  "roi-summary",
  "role-mapping-settings",
  "scim-provisioning-settings",
  "scope-help",
  "search-review-evidence",
  "sealed-record-detail",
  "security-trust-help",
  "servicenow-integration",
  "session-expired",
  "showcase",
  "signup",
  "signup-verify",
  "slack-integration",
  "sso-wizard-settings",
  "subprocessors-help",
  "support-workspace",
  "teams-integration",
  "tenant-health",
  "tenant-settings",
  "trial-funnel",
  "troubleshooting-help",
  "users-and-roles-help",
  "validate-route",
  "webhooks-integration",
  "welcome",
  "why",
  "why-archlucid",
]);

export function shouldOmitClaimDisciplineBand(stripSlug: string): boolean {
  return CLAIM_DISCIPLINE_BAND_OMIT_SLUGS.has(stripSlug);
}

export function expectsVisibleClaimDisciplineBand(stripSlug: string): boolean {
  return !shouldOmitClaimDisciplineBand(stripSlug);
}

export function resolveClaimDisciplineForStrip(
  stripSlug: string,
  claim: string | undefined,
): string | undefined {
  if (shouldOmitClaimDisciplineBand(stripSlug)) {
    return undefined;
  }

  return claim;
}

/** Drops the claim-discipline TOC entry when the strip omits the band so scroll-spy links stay valid. */
export function resolveGuideHeadingsForStrip<T extends { readonly id: string }>(
  stripSlug: string,
  headings: readonly T[],
  claimHeadingId: string,
): readonly T[] {
  if (!shouldOmitClaimDisciplineBand(stripSlug)) {
    return headings;
  }

  return headings.filter((heading) => heading.id !== claimHeadingId);
}
