// Auto-generated from GLOSSARY.md
export const glossaryTerms: Record<string, string> = {
  "Review": "A structured examination of architecture change or design intent tied to **artifacts** and **policies**. In product copy, prefer **architecture review** when the reader might confuse “review” with code review alone.",
  "Review package": "The cohesive set of **review** outputs the product assembles for stakeholders: summaries, manifests, explanations, diagrams, findings, and links to underlying **evidence**. Exportable variants are still review packages unless the doc distinguishes **bundle** packaging.",
  "Signed manifest": "The **provenance-backed** record that closes the **authority** ledger for committed work (what was decided, bound to lineage). **PKI-style cryptographic signing** of manifests is **not** claimed for current V1 storage unless a deployment explicitly enables it — treat “signed” as lineage / provenance closure unless an architecture note says otherwise. Treat “manifest” alone as ambiguous until provenance semantics are stated.",
  "Finding": "A machine- or assisted-generated observation from **decisioning** (risk, drift, conformance, duplication, etc.). **Finding** severity and policy mapping live in packs and workflows; distinguish from informal “comments” outside the ledger.",
  "Risk": "A potential adverse outcome attached to architecture or operational change — often materialized through **finding** types and surfaced in dashboards and approvals. Risk **without** linkage to artifacts or approvals is conversational, not authoritative.",
  "Control": "A mitigating safeguard (process, tooling, entitlement, isolation, retention, alerting) asserted against **risk** — whether customer-operated (“customer control”) or platform-operated (**ArchLucid control** surfaces are documented separately from customer obligations).",
  "Decision": "A recorded disposition on **review** proposals (approve, waive, defer with rationale, escalate), auditable alongside **finding** deltas. Casual “team decided in Slack” is not a committed **decision** in this sense.",
  "Evidence trail": "The chronological, inspectable lineage from inputs (prompts, repositories, citations) through deterministic steps to reviewer-visible outputs. Evidence that cannot be reconstructed from stored traces is weaker procurement posture — call that gap explicitly.",
  "Governance approval": "A committed **decision** in the governance workflow affecting merge, rollout, waiver, exception, or escalation — differentiated from UX affordances labelled “Approve” unless they write to governance state.",
  "Audit trail": "The persisted, replayable ledger of authenticated actions across **reviews**, merges, approvals, retention, notifications, exports, and integrations — narrower than informal logging; wider than SIEM payloads alone. Audit trail retention norms are posture-specific.",
  "Tenant": "The top-level customer boundary for data isolation; scoped rows carry **`TenantId`**. In typical SaaS posture, one tenant is one customer organization unless the contract defines otherwise.",
  "Workspace": "A collaboration boundary under a tenant (team, program, or environment); scoped rows carry **`WorkspaceId`**.",
  "Policy pack": "A versioned bundle of rules, thresholds, and governance mappings applied to **reviews** (compliance, finding treatment, pre-commit gates). Packs are assigned, published, and audited — not informal one-off prose.",
  "Deliverable": "An exportable artifact aimed at a specific audience (executive summary, architecture board packet, security appendix, diligence bundle). Distinct from a raw **finding** row: deliverables are packaged outputs."
};
