/**
 * Generated by `scripts/build-help-search-index.mjs`. Do not edit by hand.
 * Run: `npm run build:help-index`
 */
export type HelpDocSearchRecord = {
  docPath: string;
  docTitle: string;
  /** Anchor slug without leading '#'; empty means doc root. */
  sectionSlug: string;
  sectionHeading: string;
  excerpt: string;
};

export const HELP_DOC_SEARCH_RECORDS: readonly HelpDocSearchRecord[] = [
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "",
    "sectionHeading": "First-pilot troubleshooting decision tree — overview",
    "excerpt": "Canonical pilot path: [`FIRST_PILOT_OPERATOR_PATH.md`](FIRST_PILOT_OPERATOR_PATH.md) · Stuck mid-pilot index: [`PILOT_RESCUE_PLAYBOOK.md`](PILOT_RESCUE_PLAYBOOK.md) · Full detail: [`TROUBLESHOOTING.md`](TROUBLESHOOTING.md)"
  },
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "1-api-not-ready-connection-refused",
    "sectionHeading": "1. API not ready / connection refused",
    "excerpt": "→ [`COMMON_ERRORS.md`](COMMON_ERRORS.md) · [`DEPLOYMENT_RUNBOOK.md`](../library/DEPLOYMENT_RUNBOOK.md)"
  },
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "2-sql-migration-failure-dbup-errors-at-startup",
    "sectionHeading": "2. SQL migration failure / DbUp errors at startup",
    "excerpt": "→ [`SQL_SCRIPTS.md`](../library/SQL_SCRIPTS.md) · [`TROUBLESHOOTING.md`](TROUBLESHOOTING.md) (API startup)"
  },
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "3-auth-401-403",
    "sectionHeading": "3. Auth 401 / 403",
    "excerpt": "→ [`GENERIC_OIDC_SETUP.md`](GENERIC_OIDC_SETUP.md) · [`API_KEY_ROTATION.md`](API_KEY_ROTATION.md)) · Settings → Identity providers (OIDC discovery strip)"
  },
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "4-trial-402-entitlement",
    "sectionHeading": "4. Trial 402 (entitlement)",
    "excerpt": "→ [`TRIAL_AND_SIGNUP.md`](../go-to-market/TRIAL_AND_SIGNUP.md)"
  },
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "5-azure-extractor-upload-422",
    "sectionHeading": "5. Azure extractor upload 422",
    "excerpt": "→ [`AZURE_EXTRACTOR.md`](../library/AZURE_EXTRACTOR.md)"
  },
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "6-execute-stalls-review-not-ready-to-finalize",
    "sectionHeading": "6. Execute stalls / review not Ready to finalize",
    "excerpt": "→ [`PILOT_RESCUE_PLAYBOOK.md`](PILOT_RESCUE_PLAYBOOK.md) · [`FIRST_REAL_VALUE.md`](../library/FIRST_REAL_VALUE.md)"
  },
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "7-finalize-409-governance-pre-finalize-gate-blocked",
    "sectionHeading": "7. Finalize 409 / governance pre-finalize gate blocked",
    "excerpt": "→ [`PRE_COMMIT_GOVERNANCE_GATE.md`](../library/PRE_COMMIT_GOVERNANCE_GATE.md)"
  },
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "8-missing-artifact-bundle-after-finalize",
    "sectionHeading": "8. Missing artifact bundle after finalize",
    "excerpt": "→ [`CORE_PILOT.md`](../CORE_PILOT.md) (step 4)"
  },
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "9-low-confidence-ai-output-disputed-finding",
    "sectionHeading": "9. Low-confidence AI output / disputed finding",
    "excerpt": "→ [`AGENT_OUTPUT_EVALUATION.md`](../library/AGENT_OUTPUT_EVALUATION.md) · [`AGENT_TRACE_FORENSICS.md`](../library/AGENT_TRACE_FORENSICS.md)"
  },
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "support-bundle-any-symptom",
    "sectionHeading": "Support bundle (any symptom)",
    "excerpt": "Review `README.txt` and `next-steps.json` before external send — see [`TROUBLESHOOTING.md`](TROUBLESHOOTING.md) (support bundle checklist)."
  },
  {
    "docPath": "docs/library/customer-facing/OPERATOR_ADMIN_DIAGNOSTICS.md",
    "docTitle": "Admin diagnostics",
    "sectionSlug": "",
    "sectionHeading": "Admin diagnostics — overview",
    "excerpt": "Use these checks when a workspace symptom points to platform health rather than a single architecture review."
  },
  {
    "docPath": "docs/library/customer-facing/OPERATOR_ADMIN_DIAGNOSTICS.md",
    "docTitle": "Admin diagnostics",
    "sectionSlug": "start-here",
    "sectionHeading": "Start here",
    "excerpt": "1. Open System status (`/health`) in the workspace — live/ready checks and version identity. 2. On Overview, expand Workspace readiness — per-area status and next actions. 3. Open Assistant readiness diagnostics on Overview when LLM or assistant features fail."
  },
  {
    "docPath": "docs/library/customer-facing/OPERATOR_ADMIN_DIAGNOSTICS.md",
    "docTitle": "Admin diagnostics",
    "sectionSlug": "what-each-signal-means",
    "sectionHeading": "What each signal means",
    "excerpt": "What each signal means"
  },
  {
    "docPath": "docs/library/customer-facing/OPERATOR_ADMIN_DIAGNOSTICS.md",
    "docTitle": "Admin diagnostics",
    "sectionSlug": "related-help-topics",
    "sectionHeading": "Related Help topics",
    "excerpt": "- [Troubleshooting](/help/troubleshooting) — symptom-first fixes for review and workspace issues. - [Report a problem](/help/report-a-problem) — structured support intake with correlation identifiers. - [CLI usage](/help/cli-usage) — `archlucid doctor` and support-bundle commands (Admin-only Help topic; also Help dr…"
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "",
    "sectionHeading": "Configuration reference — overview",
    "excerpt": "This document lists operator-facing configuration keys (colon paths or environment names) recognized by `archlucid config check` and by `GET /v1/admin/config-summary` / `GET /v1/admin/configuration/summary` (presence plus optional redacted scalars; never raw secrets). `GET /v1/admin/config-lint` returns structured b…"
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "testing-non-production",
    "sectionHeading": "Testing (non-production)",
    "excerpt": "Testing (non-production)"
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "public-marketing-site-archlucid-ui-build-time",
    "sectionHeading": "Public marketing site (`archlucid-ui`, build-time)",
    "excerpt": "These keys are not in `ConfigurationKeyCatalog` (Next.js `NEXT_PUBLIC_*` only). They apply to the `(marketing)` subtree and signup funnel — see TB-019 / TB-020 and [`PUBLIC_MARKETING_SITE_TOPOLOGY.md`](PUBLIC_MARKETING_SITE_TOPOLOGY.md)."
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "itsm-integration-posture-tb-387",
    "sectionHeading": "ITSM integration posture (TB-387)",
    "excerpt": "Outbound vendor credentials are configured through deployment-level ITSM outbound and inbound connector settings (unchanged)."
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "tooling",
    "sectionHeading": "Tooling",
    "excerpt": "- Validate locally: `archlucid config check` (add `--no-api` to skip the API snapshot; use global `--json` for machine-readable output; exit `0` when all required keys for the current mode are set, exit `4` when not). - Auth / production-like traps (`ArchLucidAuth:Mode`, bypass flags): `archlucid config lint` (runs …"
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "hosting-roles",
    "sectionHeading": "Hosting roles",
    "excerpt": "- Api — HTTP API process (`Hosting:Role=Api`). - Worker — background / job host (`Hosting:Role=Worker`). - Combined — single process running both (`Hosting:Role=Combined`). - CLI — `archlucid` on a developer or automation machine (not a host process)."
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "keys",
    "sectionHeading": "Keys",
    "excerpt": "The When required column reflects `ConfigurationKeyRequirement` in code (e.g. SQL connection string when storage is SQL; Azure OpenAI when `AgentExecution:Mode=Real` and the completion client is not `Echo`)."
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "quick-start-by-mode",
    "sectionHeading": "Quick start by mode",
    "excerpt": "Use `archlucid config check` and the full table below to validate your host. This section is a minimum set per pilot profile only; all other keys remain optional unless their When required column applies."
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "pilot-configuration-profiles",
    "sectionHeading": "Pilot configuration profiles",
    "excerpt": "These profiles are operator shortcuts, not new configuration modes. Use them to decide which existing keys and checks must be present before a handoff. Before deploy: [`PILOT_PREREQUISITES.md`](../runbooks/PILOT_PREREQUISITES.md) (resource checklist, cost table, Azure AI Search blocking callout) and `.\\scripts\\Test-…"
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "staged-critic-archlucidagentsstagedcriticenabled",
    "sectionHeading": "Staged Critic (`ArchLucid:Agents:StagedCriticEnabled`)",
    "excerpt": "Scope: `RealAgentExecutor` when `AgentExecution:Mode=Real` (deterministic simulator is unchanged)."
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "generic-oidc-setup-okta-auth0",
    "sectionHeading": "Generic OIDC Setup (Okta / Auth0)",
    "excerpt": "When configuring a generic OIDC issuer (such as Okta or Auth0), use `JwtBearer` mode and specify the authority."
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "saml-20-sp-claim-mapping-examples",
    "sectionHeading": "SAML 2.0 SP claim mapping examples",
    "excerpt": "When `ArchLucidAuth:Saml2:Enabled=true`, map IdP assertion attributes to ArchLucid scope and roles using the `ArchLucidAuth:Saml2:*ClaimType` keys above. Validate attribute names with your IdP administrator — URIs differ by vendor."
  },
  {
    "docPath": "docs/CORE_PILOT.md",
    "docTitle": "Your first architecture review",
    "sectionSlug": "",
    "sectionHeading": "Your first architecture review — overview",
    "excerpt": "Use this guide with the [Pilot guide](/help/pilot-guide) to prepare for a pilot, interpret outputs, and get support contacts."
  },
  {
    "docPath": "docs/CORE_PILOT.md",
    "docTitle": "Your first architecture review",
    "sectionSlug": "first-review-path",
    "sectionHeading": "First review path",
    "excerpt": "Start with evidence, run the review, finalize the architecture review, then share sponsor-ready outputs."
  },
  {
    "docPath": "docs/CORE_PILOT.md",
    "docTitle": "Your first architecture review",
    "sectionSlug": "run-the-first-review",
    "sectionHeading": "Run the first review",
    "excerpt": "1. Start review — open New architecture review and name what you want reviewed. Saving an architecture draft is optional and separate from starting a review. 2. Add evidence — attach briefs, diagrams, documents, IaC, or exports. Cloud connectors are optional. 3. Run analysis — execute the assessment on review detail…"
  },
  {
    "docPath": "docs/CORE_PILOT.md",
    "docTitle": "Your first architecture review",
    "sectionSlug": "cloud-connectors-are-optional-for-your-first-review",
    "sectionHeading": "Cloud connectors are optional for your first review",
    "excerpt": "You can run an evidence-only review first, then connect Azure, AWS, or GCP later when source-system evidence is needed."
  },
  {
    "docPath": "docs/CORE_PILOT.md",
    "docTitle": "Your first architecture review",
    "sectionSlug": "fast-path-evidence-only-review",
    "sectionHeading": "Fast path: evidence-only review",
    "excerpt": "Recommended when connector access has not yet been approved, or when your first session only has briefs, diagrams, IaC, screenshots, exports, or policy documents."
  },
  {
    "docPath": "docs/CORE_PILOT.md",
    "docTitle": "Your first architecture review",
    "sectionSlug": "what-can-wait",
    "sectionHeading": "What can wait",
    "excerpt": "What can wait"
  },
  {
    "docPath": "docs/CORE_PILOT.md",
    "docTitle": "Your first architecture review",
    "sectionSlug": "ready-to-begin",
    "sectionHeading": "Ready to begin?",
    "excerpt": "- [Start architecture review](/reviews/new) - [Open sample review](/reviews/claims-intake-modernization)"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "",
    "sectionHeading": "Buyer security and procurement packet — overview",
    "excerpt": "Audience: Procurement reviewers, security reviewers, GRC teams, CISOs, and enterprise buyers evaluating ArchLucid for a controlled pilot."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "isolation-one-pager-m-114",
    "sectionHeading": "Isolation one-pager (M-114)",
    "excerpt": "Claim (G3): Authenticated identity binds tenant/workspace scope; client-supplied scope headers cannot override that binding on production-like hosts."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "pa-claim-honesty-short-rows",
    "sectionHeading": "PA claim-honesty short rows (M-115+)",
    "excerpt": "Companion one-pagers and full do-not/do-promise table: [`PA_CLAIM_HONESTY_INDEX.md`](PA_CLAIM_HONESTY_INDEX.md) · [`../library/PUBLIC_CLAIM_BOUNDARY_GUIDE.md#gtm-do-not-promise`](../library/PUBLIC_CLAIM_BOUNDARY_GUIDE.md#gtm-do-not-promise)."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "tenant-isolation-buyer-overview",
    "sectionHeading": "Tenant isolation (buyer overview)",
    "excerpt": "Former standalone body: `docs/go-to-market/TENANT_ISOLATION.md` → this section (`TENANT_ISOLATION.md` remains a path-stable procurement-pack alias)."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "tenant-isolation-three-layers",
    "sectionHeading": "Three layers",
    "excerpt": "- Layer 1 — Identity: Prefer Entra-issued JWTs with app roles; API keys are server-side secrets mapped to limited roles ([SECURITY.md](../library/contributor-reference/SECURITY.md)). - Layer 2 — Application: Controllers enforce policies; orchestration sets tenant / workspace / project scope before data access ([../s…"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "tenant-isolation-encryption",
    "sectionHeading": "Encryption",
    "excerpt": "- In transit: TLS to the API; TLS to Azure services per Microsoft’s stack. - At rest: Azure SQL (TDE) and blob encryption are standard Azure controls; see [../CUSTOMER_TRUST_AND_ACCESS.md](../library/CUSTOMER_TRUST_AND_ACCESS.md). - Secrets: Prefer Key Vault references in hosted configs ([../CONFIGURATION_KEY_VAULT.…"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "tenant-isolation-network",
    "sectionHeading": "Network",
    "excerpt": "Optional Front Door + WAF, optional APIM, and private endpoints for SQL and blob reduce exposure ([../CUSTOMER_TRUST_AND_ACCESS.md](../library/CUSTOMER_TRUST_AND_ACCESS.md)). SMB (445) is not used for tenant data at the API boundary (workspace security rule)."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "tenant-isolation-audit-and-accountability",
    "sectionHeading": "Audit and accountability",
    "excerpt": "Durable append-only audit events and correlation IDs support forensic review ([../AUDIT_COVERAGE_MATRIX.md](../library/AUDIT_COVERAGE_MATRIX.md), [SECURITY.md](../library/contributor-reference/SECURITY.md))."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "tenant-isolation-what-we-do-not-claim",
    "sectionHeading": "What we do not claim here",
    "excerpt": "Hosted trial tenants and commercial pilots use ArchLucid's single supported multitenant data-plane model: `SystemWithPerTenantCatalogs` (database-per-tenant routing via `TenantDatabaseBindings` — one product catalog per tenant organization). `SingleCatalog` may exist only for narrow developer/CI convenience and is n…"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "tenant-isolation-verification-pack",
    "sectionHeading": "Verification pack (generated)",
    "excerpt": "Generate a buyer-safe metadata pack (no tenant data, no secrets):"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "tenant-isolation-deep-dives",
    "sectionHeading": "Deep dives",
    "excerpt": "Deep dives"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "principal-architect-falsification-script-m-113",
    "sectionHeading": "Principal architect falsification script (M-113)",
    "excerpt": "Audience: Founder / SE running a procurement technical review with a skeptical principal architect (or security reviewer). Duration: 30–45 minutes. Goal: Let them try to break three highest-stakes V1 claims; walk out with pass/fail notes and artifact links. Spine: [`CLAIM_READINESS_STATUS.md`](CLAIM_READINESS_STATUS…"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "preflight-5-min",
    "sectionHeading": "Preflight (5 min)",
    "excerpt": "Preflight (5 min)"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "claim-1-tenant-isolation-identity-wins",
    "sectionHeading": "Claim 1 — Tenant isolation (identity wins)",
    "excerpt": "Claim: Forged `x-tenant-id` / workspace headers cannot steer scope away from the JWT tenant."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "claim-2-audit-chain-hash-verified-manifest",
    "sectionHeading": "Claim 2 — Audit chain + hash-verified manifest",
    "excerpt": "Claim: Findings are evidence-linked; committed package hash can be verified (application-layer lineage, not WORM/PKI)."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "claim-3-real-vs-simulator-honesty",
    "sectionHeading": "Claim 3 — Real vs Simulator honesty",
    "excerpt": "Claim: Sponsor-facing surfaces label execution mode; PilotStrict does not forward Simulator as enterprise proof."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "close-out",
    "sectionHeading": "Close-out",
    "excerpt": "1. Record pass/fail per claim in the deal notes or defect log (M-101). 2. If Claim 1 failed → stop the deal path until TB-948/TB-949 green on that host. 3. If Claim 2/3 weak → schedule TB-886/TB-950 or a Real run before the next PA review. 4. Update [`CLAIM_READINESS_STATUS.md`](CLAIM_READINESS_STATUS.md) evidence l…"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "azure-extractor-infosec-pre-read",
    "sectionHeading": "Azure extractor — InfoSec pre-read",
    "excerpt": "Audience: Customer security, cloud platform, and procurement reviewers who must approve running `Get-ArchLucidAzurePackage.ps1` or uploading its ZIP output to ArchLucid. Status: V1 GA — aligns with [`V1_SCOPE.md`](../library/V1_SCOPE.md) §2.16 and [`trust-center.md`](trust-center.md) Azure connectivity posture. Rela…"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "decision-summary-30-seconds",
    "sectionHeading": "Decision summary (30 seconds)",
    "excerpt": "Decision summary (30 seconds)"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "tier-1-customer-run-collector-default-v1-path",
    "sectionHeading": "Tier 1 — customer-run collector (default V1 path)",
    "excerpt": "1. Your team downloads and reviews `scripts/azure/Get-ArchLucidAzurePackage.ps1` from the ArchLucid distribution you received (or repository tag aligned to your pilot build). 2. An authorized operator runs the script inside your Azure context (Azure PowerShell / Cloud Shell / approved automation runner). 3. The arch…"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "upload-and-audit-trail-archlucid-side",
    "sectionHeading": "Upload and audit trail (ArchLucid side)",
    "excerpt": "- Package stored in tenant-scoped SQL/blob per deployment ([`trust-center.md`](trust-center.md) data residency table). - Durable audit events include `AzureExtractorPackage.Uploaded`, `AzureExtractorPackage.IngestSucceeded`, and rejection events when schema validation fails — see [`AUDIT_COVERAGE_MATRIX.md`](../libr…"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "tier-2-optional-hosted-collection-separate-approval",
    "sectionHeading": "Tier 2 — optional hosted collection (separate approval)",
    "excerpt": "Tier 2 is opt-in and not required for V1 pilots. If enabled later: customer provisions a dedicated read-only service principal with `Reader` + `Cost Management Reader` only; federated workload identity preferred; ArchLucid stores only `{ customerTenantId, customerAppId, subscriptionId, includeCost }` — never custome…"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "alternative-when-the-script-is-blocked",
    "sectionHeading": "Alternative when the script is blocked",
    "excerpt": "1. Run an evidence-only review (`CloudProvider.None`). 2. Use demo evidence for internal evaluator dry-runs only (label demo-derived; do not quote externally). 3. Revisit Tier 1 after sandbox approval or use a narrow resource-group scope on a non-production subscription."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "reviewer-checklist",
    "sectionHeading": "Reviewer checklist",
    "excerpt": "Reviewer checklist"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "faq-security-reviewers",
    "sectionHeading": "FAQ (security reviewers)",
    "excerpt": "Can ArchLucid call back into our tenant after upload? Tier 1: No standing access from upload alone. Tier 2: only if you separately configure hosted extractor (opt-in)."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "change-control",
    "sectionHeading": "Change control",
    "excerpt": "When extractor schema, RBAC posture, or trust-center rows change, update this pre-read and [`trust-center.md`](trust-center.md) § Azure connectivity in the same change."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "evidence-routing-map",
    "sectionHeading": "Evidence routing map",
    "excerpt": "Evidence routing map"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "1-how-to-use-this-packet",
    "sectionHeading": "1. How to use this packet",
    "excerpt": "1. Send this packet to the buyer's security or procurement contact. 2. Before sending, run through Section 7 (staleness and accuracy checklist) to confirm no dates or status fields are outdated. 3. Mark items that are draft / not yet available clearly rather than leaving them blank. 4. Do not add or remove assurance…"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "2-company-and-product-summary",
    "sectionHeading": "2. Company and product summary",
    "excerpt": "2. Company and product summary"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "3-security-controls-shipped-v1",
    "sectionHeading": "3. Security controls (shipped V1)",
    "excerpt": "3. Security controls (shipped V1)"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "4-assurance-status-explicit",
    "sectionHeading": "4. Assurance status — explicit",
    "excerpt": "> Reading this table: Status values are Shipped, Self-assessed, Roadmap / V1.1, or Not available. Do not treat Roadmap items as current capabilities."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "5-approved-security-questionnaire-answers",
    "sectionHeading": "5. Approved security questionnaire answers",
    "excerpt": "Use these answers verbatim or adapted in buyer questionnaires. Do not deviate from the assurance scope without owner approval."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "51-authentication-and-access-control",
    "sectionHeading": "5.1 Authentication and access control",
    "excerpt": "Q: How does ArchLucid authenticate users? A: ArchLucid uses Azure Entra ID via OIDC/SAML for human authentication. Machine clients use service principals or API keys. App-level JWT validation is enforced on all API paths."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "52-data-isolation-and-tenant-boundaries",
    "sectionHeading": "5.2 Data isolation and tenant boundaries",
    "excerpt": "Q: Is customer data isolated from other customers? A: Yes. Hosted posture uses database-per-tenant product catalogs with identity-bound scope and application-layer predicates. Tenants cannot access each other's reviews, architecture reviews, findings, or evidence. See [Tenant isolation (buyer overview)](#tenant-iso…"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "53-data-handling-and-retention",
    "sectionHeading": "5.3 Data handling and retention",
    "excerpt": "Q: How long is customer data retained? A: Retention posture is documented and configurable. A formal data-retention schedule is a draft artifact pending owner review. See [`trust-center.md`](trust-center.md)."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "54-encryption",
    "sectionHeading": "5.4 Encryption",
    "excerpt": "Q: Is data encrypted at rest? A: Yes. Azure SQL Transparent Data Encryption (TDE) and Azure Blob Storage encryption are enabled by default."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "55-audit-and-logging",
    "sectionHeading": "5.5 Audit and logging",
    "excerpt": "Q: Does ArchLucid produce an audit trail? A: Yes. All material user and system actions produce structured audit events in an append-only audit log. The audit coverage model is documented in [`../library/AUDIT_COVERAGE_MATRIX.md`](../library/AUDIT_COVERAGE_MATRIX.md)."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "56-incident-response",
    "sectionHeading": "5.6 Incident response",
    "excerpt": "Q: Does ArchLucid have an incident response plan? A: An incident communications policy is documented at [`INCIDENT_COMMUNICATIONS_POLICY.md`](INCIDENT_COMMUNICATIONS_POLICY.md). A formal IR plan is a draft artifact pending owner review. Pilot buyers will be contacted within 24 hours of a confirmed incident affecting…"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "57-vendor-and-sub-processor-risk",
    "sectionHeading": "5.7 Vendor and sub-processor risk",
    "excerpt": "Q: What third-party sub-processors does ArchLucid use? A: Current sub-processors are listed in [`SUBPROCESSORS.md`](SUBPROCESSORS.md). Material additions will be communicated per the DPA template."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "6-buyer-risk-questions-and-honest-answers",
    "sectionHeading": "6. Buyer-risk questions and honest answers",
    "excerpt": "6. Buyer-risk questions and honest answers"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "enterprise-procurement-faq",
    "sectionHeading": "Q & A",
    "excerpt": "Former standalone: `docs/go-to-market/PROCUREMENT_FAQ.md` → this section (Enterprise procurement FAQ)."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "1-do-you-have-soc-2-type-ii",
    "sectionHeading": "1. Do you have SOC 2 Type II?",
    "excerpt": "Answer: Today we publish a SOC 2 self-assessment and control mapping—SOC 2 Type II CPA attestation is not currently issued ([SOC 2 self-assessment](/help/soc2-self-assessment)). Type I followed by Type II is the typical SaaS roadmap once operating evidence exists alongside budget."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "2-can-we-see-the-latest-penetration-test-report",
    "sectionHeading": "2. Can we see the latest penetration-test report?",
    "excerpt": "Answer: V1 uses owner-conducted penetration-style testing and internal assessments (see [`2026-Q2-OWNER-CONDUCTED.md`](../security/pen-test-summaries/2026-Q2-OWNER-CONDUCTED.md)). A third-party vendor engagement is planned, not yet scheduled; when funded, it follows an SoW shaped like [2026-Q2-SOW.md](../security/pe…"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "3-where-is-customer-data-processed-stored",
    "sectionHeading": "3. Where is customer data processed / stored?",
    "excerpt": "Answer: Vendor-hosted Azure workloads (region choices depend on contracted Azure regions and private-connectivity setup). For buyer-facing isolation and residency messaging, see [Data handling and tenant isolation](/help/data-handling-tenant-isolation). Architectural networking guidance: [CUSTOMER_TRUST_AND_ACCESS.m…"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "4-can-we-authenticate-with-okta-ping-auth0-instead-of-microsoft-entra-id",
    "sectionHeading": "4. Can we authenticate with Okta / Ping / Auth0 instead of Microsoft Entra ID?",
    "excerpt": "Answer: Yes — V1 GA. [V1_SCOPE.md](../library/V1_SCOPE.md) §2.12 commits `JwtBearer` against configurable OIDC issuers (metadata discovery + JWKS), including non-Microsoft IdPs; `ArchLucidAuth:Authority` / audience and role claim mapping are documented in [SECURITY.md](../library/contributor-reference/SECURITY.md) a…"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "5-what-sla-do-you-publish",
    "sectionHeading": "5. What SLA do you publish?",
    "excerpt": "Answer: Targets are documented ([SLA_SUMMARY.md](SLA_SUMMARY.md) · [#hosted-saas-availability-target](SLA_SUMMARY.md#hosted-saas-availability-target); `SLA_TARGETS.md` alias). Contractual SLA language is finalized per Order Form ([ORDER_FORM_TEMPLATE.md](ORDER_FORM_TEMPLATE.md))—pre-contract targets, not uncondition…"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "6-can-we-execute-the-data-processing-agreement",
    "sectionHeading": "6. Can we execute the Data Processing Agreement?",
    "excerpt": "Answer: Yes — start from the in-app [DPA template](/help/dpa-template) (negotiation template, not a countersigned agreement) and [Subprocessors](/help/subprocessors)."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "7-what-subprocessors-apply",
    "sectionHeading": "7. What subprocessors apply?",
    "excerpt": "Answer: See [Subprocessors](/help/subprocessors) (maintained quarterly); aligns with contractual notification windows in the [DPA template](/help/dpa-template)."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "8-what-happens-if-archlucid-ceases-trading",
    "sectionHeading": "8. What happens if ArchLucid ceases trading?",
    "excerpt": "Answer: Operational continuity hinges on contractual termination assistance, export rights, negotiated escrow arrangements, and staged migration timelines—explicit source-code escrow is negotiable rather than universally bundled in starter paper. Start from [MSA_TEMPLATE.md](MSA_TEMPLATE.md) / Order Form playbook."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "9-do-you-maintain-cyber-insurance",
    "sectionHeading": "9. Do you maintain cyber insurance?",
    "excerpt": "Answer: Procurement should request current coverage limits, carrier, renewal date, and claims history directly from Vendor during diligence—figures change year to year (do not cite an unsigned MD as proof)."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "10-can-we-speak-with-reference-customers",
    "sectionHeading": "10. Can we speak with reference customers?",
    "excerpt": "Answer: Public Published references are tracked ([reference-customers/README.md](reference-customers/README.md)) with Status placeholders until V1.1-program approvals—coordinate via sales for permissioned pilots."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "11-how-do-we-get-extended-audit-retention-eg-7-years",
    "sectionHeading": "11. How do we get extended audit retention (e.g. 7 years)?",
    "excerpt": "Answer: Per-tier defaults are 90 days (Team), 1 year (Professional), and custom (Enterprise) — see [`PRICING_PHILOSOPHY.md`](PRICING_PHILOSOPHY.md). Extended retention is an Enterprise-negotiated add-on documented in [`AUDIT_RETENTION_EXTENSION.md`](../library/AUDIT_RETENTION_EXTENSION.md): scheduled CSV exports to …"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "12-can-we-commission-custom-policy-packs-beyond-bundled-defaults",
    "sectionHeading": "12. Can we commission custom policy packs beyond bundled defaults?",
    "excerpt": "Answer: Yes — V1 professional services. ArchLucid ships productized Custom Policy Pack Authoring SKUs (Starter / Standard / Program) with customer-exclusive or ArchLucid-owned IP tiers. Scope, delivery windows, and canonical USD list prices are in [PRICING_PHILOSOPHY.md §4.2](PRICING_PHILOSOPHY.md#42-custom-policy-p…"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "trust-progression-timeline-informal",
    "sectionHeading": "Trust progression timeline (informal)",
    "excerpt": "Note: Dates are illustrative—bind via executed Order Form milestones when procuring regulated workloads. Stripped from `/help/procurement` buyer presentation (internal enablement)."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "7-staleness-and-accuracy-checklist",
    "sectionHeading": "7. Staleness and accuracy checklist",
    "excerpt": "Run before each new buyer send:"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "procurement-response-accelerator",
    "sectionHeading": "Procurement response accelerator",
    "excerpt": "Former standalone body: `docs/go-to-market/PROCUREMENT_RESPONSE_ACCELERATOR.md` → this section (filename kept as a path-stable alias)."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "status-legend",
    "sectionHeading": "Status legend",
    "excerpt": "Status legend"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "questions-sig-aligned-families-50-prompts",
    "sectionHeading": "Questions (SIG-aligned families — 50 prompts)",
    "excerpt": "Answers are pointers only; pull quotations from targets during diligence."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "security-reviewer-one-pager",
    "sectionHeading": "Security reviewer one-pager",
    "excerpt": "Former standalone body: `docs/go-to-market/SECURITY_REVIEWER_ONE_PAGER.md` → this section (filename kept as a path-stable pack alias)."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "current-controls-v1-evidence-today",
    "sectionHeading": "Current controls (V1 evidence today)",
    "excerpt": "- Tenant-scoped auth (OIDC/SAML/API key) with least-privilege operator ranks - Append-only audit events and correlation IDs on API failures - Config summary and config lint without returning secrets - Policy packs and governance workflows (optional after first commit) - DPA/SIG/CAIQ-style templates in procurement pa…"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "deferred-informational-only-not-v1-blockers",
    "sectionHeading": "Deferred / informational only (not V1 blockers)",
    "excerpt": "- CPA SOC 2 Type I/II report - Third-party penetration test publication - No ISO or statutory certification automation in V1 (deferred) - Live marketplace checkout as procurement gate"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "we-will-never-ask-you-to-paste",
    "sectionHeading": "We will never ask you to paste",
    "excerpt": "- Production database connection strings in tickets - API keys, SAML secrets, or Key Vault values in email - Unredacted LLM prompts in buyer-safe attachments - Customer-operated webhook secrets in V1 required path"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "control-to-evidence-map",
    "sectionHeading": "Control-to-evidence map",
    "excerpt": "Not issued (do not imply): SOC 2 Type I/II CPA report · third-party penetration test attestation · public customer reference."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "example-audit-walkthrough-one-finalized-review",
    "sectionHeading": "Example audit walkthrough (one finalized review)",
    "excerpt": "Assume review id `runId` and tenant scope already established. Uses existing routes and exports only."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "one-pager-source-documents",
    "sectionHeading": "One-pager source documents",
    "excerpt": "- [`trust-center.md`](trust-center.md) — Trust center narrative - [`../security/SOC2_SELF_ASSESSMENT_2026.md`](../security/SOC2_SELF_ASSESSMENT_2026.md) — SOC 2 self-assessment (not CPA attestation) - [`ASSURANCE_STATUS_CANONICAL.md#soc-2-readiness-roadmap`](ASSURANCE_STATUS_CANONICAL.md#soc-2-readiness-roadmap) — S…"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "procurement-objection-playbook",
    "sectionHeading": "Procurement objection playbook",
    "excerpt": "Former standalone body: `docs/go-to-market/PROCUREMENT_OBJECTION_PLAYBOOK.md` → this section (filename kept as a path-stable alias for proof-language CI). High-frequency procurement objection responses with approved short/long answers, evidence links, and escalation triggers; designed to reduce deal-cycle friction w…"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "usage",
    "sectionHeading": "Usage",
    "excerpt": "- Use the short answer first. - Expand with the long answer when reviewers request detail. - Escalate when the trigger condition is met. - Keep claims aligned with `ASSURANCE_STATUS_CANONICAL.md`."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "objections",
    "sectionHeading": "Objections",
    "excerpt": "Objections"
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "controlled-pilot-drill",
    "sectionHeading": "Controlled pilot drill",
    "excerpt": "Duration: 45–60 minutes (solo or with a colleague playing procurement). Rehearse top V1 objections without over-claiming deferred assurance (SOC 2 CPA, third-party pen test)."
  },
  {
    "docPath": "docs/go-to-market/BUYER_SECURITY_PROCUREMENT_PACKET.md",
    "docTitle": "Buyer security and procurement packet",
    "sectionSlug": "8-references",
    "sectionHeading": "8. References",
    "excerpt": "Former standalone script: `docs/go-to-market/PRINCIPAL_ARCHITECT_FALSIFICATION_SCRIPT.md` → [falsification script](#principal-architect-falsification-script-m-113). Former standalone pre-read: `docs/go-to-market/AZURE_EXTRACTOR_INFOSEC_PREREAD.md` → [Azure extractor InfoSec pre-read](#azure-extractor--infosec-pre-re…"
  }
] as const;
