/**
 * Generated by `scripts/build-help-search-index.mjs`. Do not edit by hand.
 * Run: `npm run build:help-index`
 */
export type HelpDocSearchRecord = {
  docPath: string;
  docTitle: string;
  /** Anchor slug without leading '#'; empty means doc root. */
  sectionSlug: string;
  sectionHeading: string;
  excerpt: string;
};

export const HELP_DOC_SEARCH_RECORDS: readonly HelpDocSearchRecord[] = [
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "",
    "sectionHeading": "First-pilot troubleshooting decision tree — overview",
    "excerpt": "Canonical pilot path: [`FIRST_PILOT_OPERATOR_PATH.md`](FIRST_PILOT_OPERATOR_PATH.md) · Stuck mid-pilot index: [`PILOT_RESCUE_PLAYBOOK.md`](PILOT_RESCUE_PLAYBOOK.md) · Full detail: [`TROUBLESHOOTING.md`](TROUBLESHOOTING.md)"
  },
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "1-api-not-ready-connection-refused",
    "sectionHeading": "1. API not ready / connection refused",
    "excerpt": "→ [`COMMON_ERRORS.md`](COMMON_ERRORS.md) · [`DEPLOYMENT_RUNBOOK.md`](../library/DEPLOYMENT_RUNBOOK.md)"
  },
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "2-sql-migration-failure-dbup-errors-at-startup",
    "sectionHeading": "2. SQL migration failure / DbUp errors at startup",
    "excerpt": "→ [`SQL_SCRIPTS.md`](../library/SQL_SCRIPTS.md) · [`TROUBLESHOOTING.md`](TROUBLESHOOTING.md) (API startup)"
  },
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "3-auth-401-403",
    "sectionHeading": "3. Auth 401 / 403",
    "excerpt": "→ [`GENERIC_OIDC_SETUP.md`](GENERIC_OIDC_SETUP.md) · [`API_KEY_ROTATION.md`](API_KEY_ROTATION.md)) · Settings → Identity providers (OIDC discovery strip)"
  },
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "4-trial-402-entitlement",
    "sectionHeading": "4. Trial 402 (entitlement)",
    "excerpt": "→ [`TRIAL_AND_SIGNUP.md`](../go-to-market/TRIAL_AND_SIGNUP.md)"
  },
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "5-azure-extractor-upload-422",
    "sectionHeading": "5. Azure extractor upload 422",
    "excerpt": "→ [`AZURE_EXTRACTOR.md`](../library/AZURE_EXTRACTOR.md)"
  },
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "6-execute-stalls-review-not-ready-to-finalize",
    "sectionHeading": "6. Execute stalls / review not Ready to finalize",
    "excerpt": "→ [`PILOT_RESCUE_PLAYBOOK.md`](PILOT_RESCUE_PLAYBOOK.md) · [`FIRST_REAL_VALUE.md`](../library/FIRST_REAL_VALUE.md)"
  },
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "7-finalize-409-governance-pre-finalize-gate-blocked",
    "sectionHeading": "7. Finalize 409 / governance pre-finalize gate blocked",
    "excerpt": "→ [`PRE_COMMIT_GOVERNANCE_GATE.md`](../library/PRE_COMMIT_GOVERNANCE_GATE.md)"
  },
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "8-missing-artifact-bundle-after-finalize",
    "sectionHeading": "8. Missing artifact bundle after finalize",
    "excerpt": "→ [`CORE_PILOT.md`](../CORE_PILOT.md) (step 4)"
  },
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "9-low-confidence-ai-output-disputed-finding",
    "sectionHeading": "9. Low-confidence AI output / disputed finding",
    "excerpt": "→ [`AGENT_OUTPUT_EVALUATION.md`](../library/AGENT_OUTPUT_EVALUATION.md) · [`AGENT_TRACE_FORENSICS.md`](../library/AGENT_TRACE_FORENSICS.md)"
  },
  {
    "docPath": "docs/runbooks/FIRST_PILOT_TROUBLESHOOTING.md",
    "docTitle": "First-pilot troubleshooting decision tree",
    "sectionSlug": "support-bundle-any-symptom",
    "sectionHeading": "Support bundle (any symptom)",
    "excerpt": "Review `README.txt` and `next-steps.json` before external send — see [`TROUBLESHOOTING.md`](TROUBLESHOOTING.md) (support bundle checklist)."
  },
  {
    "docPath": "docs/library/customer-facing/OPERATOR_ADMIN_DIAGNOSTICS.md",
    "docTitle": "Admin diagnostics",
    "sectionSlug": "",
    "sectionHeading": "Admin diagnostics — overview",
    "excerpt": "Use these checks when a workspace symptom points to platform health rather than a single architecture review."
  },
  {
    "docPath": "docs/library/customer-facing/OPERATOR_ADMIN_DIAGNOSTICS.md",
    "docTitle": "Admin diagnostics",
    "sectionSlug": "start-here",
    "sectionHeading": "Start here",
    "excerpt": "1. Open System status (`/health`) in the workspace — live/ready checks and version identity. 2. On Overview, expand Workspace readiness — per-area status and next actions. 3. Open Assistant readiness diagnostics on Overview when LLM or assistant features fail."
  },
  {
    "docPath": "docs/library/customer-facing/OPERATOR_ADMIN_DIAGNOSTICS.md",
    "docTitle": "Admin diagnostics",
    "sectionSlug": "what-each-signal-means",
    "sectionHeading": "What each signal means",
    "excerpt": "What each signal means"
  },
  {
    "docPath": "docs/library/customer-facing/OPERATOR_ADMIN_DIAGNOSTICS.md",
    "docTitle": "Admin diagnostics",
    "sectionSlug": "related-help-topics",
    "sectionHeading": "Related Help topics",
    "excerpt": "- [Troubleshooting](/help/troubleshooting) — symptom-first fixes for review and workspace issues. - [Report a problem](/help/report-a-problem) — structured support intake with correlation identifiers. - [Engineering troubleshooting](/help/developer-troubleshooting) — CLI, logs, environment variables, and support bun…"
  },
  {
    "docPath": "docs/runbooks/TROUBLESHOOTING.md",
    "docTitle": "Engineering troubleshooting runbook",
    "sectionSlug": "",
    "sectionHeading": "Engineering troubleshooting runbook — overview",
    "excerpt": "Goal: Faster triage without reading the whole codebase."
  },
  {
    "docPath": "docs/runbooks/TROUBLESHOOTING.md",
    "docTitle": "Engineering troubleshooting runbook",
    "sectionSlug": "first-line-steps-try-in-order",
    "sectionHeading": "First-line steps (try in order)",
    "excerpt": "1. See [Common operator errors (top 10)](COMMON_ERRORS.md) for step-by-step fixes to startup, auth, migrations, OpenAI, rate limits, concurrency, and readiness checks. 2. `GET /health/live` — process up? Then `GET /health/ready` — read JSON `entries[]` for the first `Unhealthy` / `Degraded` check. 2. `GET /version` …"
  },
  {
    "docPath": "docs/runbooks/TROUBLESHOOTING.md",
    "docTitle": "Engineering troubleshooting runbook",
    "sectionSlug": "orchestrator-degraded-health",
    "sectionHeading": "Orchestrator degraded health",
    "excerpt": "When `OrchestratorHealthCheck` reports Degraded or Unhealthy on `GET /health/ready`, or runs stall in Executing without task progress:"
  },
  {
    "docPath": "docs/runbooks/TROUBLESHOOTING.md",
    "docTitle": "Engineering troubleshooting runbook",
    "sectionSlug": "problem-details-applicationproblemjson-and-supporthint",
    "sectionHeading": "Problem Details (`application/problem+json`) and `supportHint`",
    "excerpt": "Shape follows RFC 9457 (Problem Details for HTTP APIs; obsoletes RFC 7807). API error responses may include:"
  },
  {
    "docPath": "docs/runbooks/TROUBLESHOOTING.md",
    "docTitle": "Engineering troubleshooting runbook",
    "sectionSlug": "quick-matrix",
    "sectionHeading": "Quick matrix",
    "excerpt": "Quick matrix"
  },
  {
    "docPath": "docs/runbooks/TROUBLESHOOTING.md",
    "docTitle": "Engineering troubleshooting runbook",
    "sectionSlug": "api-startup-failures",
    "sectionHeading": "API startup failures",
    "excerpt": "1. Read the console output from first line to first `InvalidOperationException` / stack stop. 2. Configuration validation runs right after the host is built: errors are logged as `Startup configuration error:` — fix each listed setting. 3. If `ConnectionStrings:ArchLucid` is unset while `ArchLucid:StorageProvider` i…"
  },
  {
    "docPath": "docs/runbooks/TROUBLESHOOTING.md",
    "docTitle": "Engineering troubleshooting runbook",
    "sectionSlug": "logs-what-to-search-for",
    "sectionHeading": "Logs — what to search for",
    "excerpt": "- `ReviewId=` — ties log lines to a single architecture review. - `X-Correlation-ID` you sent on the request (or the ID the server returned) — ties client attempts to server handling; if you only have a problem JSON body, use `correlationId` there (same value). - `Authority pipeline` / `architecture review execution fa…"
  },
  {
    "docPath": "docs/runbooks/TROUBLESHOOTING.md",
    "docTitle": "Engineering troubleshooting runbook",
    "sectionSlug": "artifact-list-empty-or-download-404",
    "sectionHeading": "Artifact list empty or download 404",
    "excerpt": "- An empty artifact list (`[]`) can be valid: signed review record exists but no synthesized files yet or none stored for that architecture review. - Bundle ZIP 404 can mean “no bundle” vs “review not found” depending on API ProblemDetails — compare `title` / `type` / `detail` in the response."
  },
  {
    "docPath": "docs/runbooks/TROUBLESHOOTING.md",
    "docTitle": "Engineering troubleshooting runbook",
    "sectionSlug": "support-bundle-attach-to-tickets",
    "sectionHeading": "Support bundle (attach to tickets)",
    "excerpt": "With the API running, from repo root (or set `ARCHLUCID_API_URL` to your API base):"
  },
  {
    "docPath": "docs/runbooks/TROUBLESHOOTING.md",
    "docTitle": "Engineering troubleshooting runbook",
    "sectionSlug": "still-stuck",
    "sectionHeading": "Still stuck?",
    "excerpt": "1. Run `dotnet run --project ArchLucid.Cli -- doctor` with the API up. 2. Run `support-bundle --zip` (above) and attach the archive after redacting anything your policy still forbids. 3. Run `scripts\\run-readiness-check.cmd` (or `scripts\\run-readiness-check.ps1`) to confirm build + fast core + UI unit tests on your …"
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "",
    "sectionHeading": "Configuration reference — overview",
    "excerpt": "This document lists operator-facing configuration keys (colon paths or environment names) recognized by `archlucid config check` and by `GET /v1/admin/config-summary` / `GET /v1/admin/configuration/summary` (presence plus optional redacted scalars; never raw secrets). `GET /v1/admin/config-lint` returns structured b…"
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "testing-non-production",
    "sectionHeading": "Testing (non-production)",
    "excerpt": "Testing (non-production)"
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "public-marketing-site-archlucid-ui-build-time",
    "sectionHeading": "Public marketing site (`archlucid-ui`, build-time)",
    "excerpt": "These keys are not in `ConfigurationKeyCatalog` (Next.js `NEXT_PUBLIC_*` only). They apply to the `(marketing)` subtree and signup funnel — see TB-019 / TB-020 and [`PUBLIC_MARKETING_SITE_TOPOLOGY.md`](PUBLIC_MARKETING_SITE_TOPOLOGY.md)."
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "itsm-integration-posture-tb-387",
    "sectionHeading": "ITSM integration posture (TB-387)",
    "excerpt": "Outbound vendor credentials are configured through deployment-level ITSM outbound and inbound connector settings (unchanged)."
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "tooling",
    "sectionHeading": "Tooling",
    "excerpt": "- Validate locally: `archlucid config check` (add `--no-api` to skip the API snapshot; use global `--json` for machine-readable output; exit `0` when all required keys for the current mode are set, exit `4` when not). - Auth / production-like traps (`ArchLucidAuth:Mode`, bypass flags): `archlucid config lint` (runs …"
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "hosting-roles",
    "sectionHeading": "Hosting roles",
    "excerpt": "- Api — HTTP API process (`Hosting:Role=Api`). - Worker — background / job host (`Hosting:Role=Worker`). - Combined — single process running both (`Hosting:Role=Combined`). - CLI — `archlucid` on a developer or automation machine (not a host process)."
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "keys",
    "sectionHeading": "Keys",
    "excerpt": "The When required column reflects `ConfigurationKeyRequirement` in code (e.g. SQL connection string when storage is SQL; Azure OpenAI when `AgentExecution:Mode=Real` and the completion client is not `Echo`)."
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "quick-start-by-mode",
    "sectionHeading": "Quick start by mode",
    "excerpt": "Use `archlucid config check` and the full table below to validate your host. This section is a minimum set per pilot profile only; all other keys remain optional unless their When required column applies."
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "pilot-configuration-profiles",
    "sectionHeading": "Pilot configuration profiles",
    "excerpt": "These profiles are operator shortcuts, not new configuration modes. Use them to decide which existing keys and checks must be present before a handoff. Before deploy: [`PILOT_PREREQUISITES.md`](../runbooks/PILOT_PREREQUISITES.md) (resource checklist, cost table, Azure AI Search blocking callout) and `.\\scripts\\Test-…"
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "staged-critic-archlucidagentsstagedcriticenabled",
    "sectionHeading": "Staged Critic (`ArchLucid:Agents:StagedCriticEnabled`)",
    "excerpt": "Scope: `RealAgentExecutor` when `AgentExecution:Mode=Real` (deterministic simulator is unchanged)."
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "generic-oidc-setup-okta-auth0",
    "sectionHeading": "Generic OIDC Setup (Okta / Auth0)",
    "excerpt": "When configuring a generic OIDC issuer (such as Okta or Auth0), use `JwtBearer` mode and specify the authority."
  },
  {
    "docPath": "docs/library/CONFIGURATION_REFERENCE.md",
    "docTitle": "Configuration reference",
    "sectionSlug": "saml-20-sp-claim-mapping-examples",
    "sectionHeading": "SAML 2.0 SP claim mapping examples",
    "excerpt": "When `ArchLucidAuth:Saml2:Enabled=true`, map IdP assertion attributes to ArchLucid scope and roles using the `ArchLucidAuth:Saml2:*ClaimType` keys above. Validate attribute names with your IdP administrator — URIs differ by vendor."
  },
  {
    "docPath": "docs/CORE_PILOT.md",
    "docTitle": "Your first architecture review",
    "sectionSlug": "",
    "sectionHeading": "Your first architecture review — overview",
    "excerpt": "Use this guide with the [Pilot guide](/help/pilot-guide) to prepare for a pilot, interpret outputs, and get support contacts."
  },
  {
    "docPath": "docs/CORE_PILOT.md",
    "docTitle": "Your first architecture review",
    "sectionSlug": "first-review-path",
    "sectionHeading": "First review path",
    "excerpt": "Start with evidence, run the review, finalize the architecture review, then share sponsor-ready outputs."
  },
  {
    "docPath": "docs/CORE_PILOT.md",
    "docTitle": "Your first architecture review",
    "sectionSlug": "run-the-first-review",
    "sectionHeading": "Run the first review",
    "excerpt": "1. Start review — open New architecture review and name what you want reviewed. Saving an architecture draft is optional and separate from starting a review. 2. Add evidence — attach briefs, diagrams, documents, IaC, or exports. Cloud connectors are optional. 3. Run analysis — execute the assessment on review detail…"
  },
  {
    "docPath": "docs/CORE_PILOT.md",
    "docTitle": "Your first architecture review",
    "sectionSlug": "cloud-connectors-are-optional-for-your-first-review",
    "sectionHeading": "Cloud connectors are optional for your first review",
    "excerpt": "You can run an evidence-only review first, then connect Azure, AWS, or GCP later when source-system evidence is needed."
  },
  {
    "docPath": "docs/CORE_PILOT.md",
    "docTitle": "Your first architecture review",
    "sectionSlug": "fast-path-evidence-only-review",
    "sectionHeading": "Fast path: evidence-only review",
    "excerpt": "Recommended when connector access has not yet been approved, or when your first session only has briefs, diagrams, IaC, screenshots, exports, or policy documents."
  },
  {
    "docPath": "docs/CORE_PILOT.md",
    "docTitle": "Your first architecture review",
    "sectionSlug": "what-can-wait",
    "sectionHeading": "What can wait",
    "excerpt": "What can wait"
  },
  {
    "docPath": "docs/CORE_PILOT.md",
    "docTitle": "Your first architecture review",
    "sectionSlug": "ready-to-begin",
    "sectionHeading": "Ready to begin?",
    "excerpt": "- [Start architecture review](/reviews/new) - [Open sample review](/reviews/claims-intake-modernization)"
  },
  {
    "docPath": "docs/go-to-market/PROCUREMENT_FAQ.md",
    "docTitle": "Procurement FAQ (Enterprise)",
    "sectionSlug": "",
    "sectionHeading": "Procurement FAQ (Enterprise) — overview",
    "excerpt": "Audience: procurement, InfoSec questionnaires, resilience reviews preparing SOC 2 / SIG / CAIQ spreadsheets."
  },
  {
    "docPath": "docs/go-to-market/PROCUREMENT_FAQ.md",
    "docTitle": "Procurement FAQ (Enterprise)",
    "sectionSlug": "q-a",
    "sectionHeading": "Q & A",
    "excerpt": "Q & A"
  },
  {
    "docPath": "docs/go-to-market/PROCUREMENT_FAQ.md",
    "docTitle": "Procurement FAQ (Enterprise)",
    "sectionSlug": "1-do-you-have-soc-2-type-ii",
    "sectionHeading": "1. Do you have SOC 2 Type II?",
    "excerpt": "Answer: Today we publish a SOC 2 self-assessment and control mapping—SOC 2 Type II CPA attestation is not currently issued ([SOC 2 self-assessment](/help/soc2-self-assessment)). Type I followed by Type II is the typical SaaS roadmap once operating evidence exists alongside budget."
  },
  {
    "docPath": "docs/go-to-market/PROCUREMENT_FAQ.md",
    "docTitle": "Procurement FAQ (Enterprise)",
    "sectionSlug": "2-can-we-see-the-latest-penetration-test-report",
    "sectionHeading": "2. Can we see the latest penetration-test report?",
    "excerpt": "Answer: V1 uses owner-conducted penetration-style testing and internal assessments (see [`2026-Q2-OWNER-CONDUCTED.md`](../security/pen-test-summaries/2026-Q2-OWNER-CONDUCTED.md)). A third-party vendor engagement is planned, not yet scheduled; when funded, it follows an SoW shaped like [2026-Q2-SOW.md](../security/pe…"
  },
  {
    "docPath": "docs/go-to-market/PROCUREMENT_FAQ.md",
    "docTitle": "Procurement FAQ (Enterprise)",
    "sectionSlug": "3-where-is-customer-data-processed-stored",
    "sectionHeading": "3. Where is customer data processed / stored?",
    "excerpt": "Answer: Vendor-hosted Azure workloads (region choices depend on contracted Azure regions and private-connectivity setup). For buyer-facing isolation and residency messaging, see [Data handling and tenant isolation](/help/data-handling-tenant-isolation). Architectural networking guidance: [CUSTOMER_TRUST_AND_ACCESS.m…"
  },
  {
    "docPath": "docs/go-to-market/PROCUREMENT_FAQ.md",
    "docTitle": "Procurement FAQ (Enterprise)",
    "sectionSlug": "4-can-we-authenticate-with-okta-ping-auth0-instead-of-microsoft-entra-id",
    "sectionHeading": "4. Can we authenticate with Okta / Ping / Auth0 instead of Microsoft Entra ID?",
    "excerpt": "Answer: Yes — V1 GA. [V1_SCOPE.md](../library/V1_SCOPE.md) §2.12 commits `JwtBearer` against configurable OIDC issuers (metadata discovery + JWKS), including non-Microsoft IdPs; `ArchLucidAuth:Authority` / audience and role claim mapping are documented in [SECURITY.md](../library/contributor-reference/SECURITY.md) a…"
  },
  {
    "docPath": "docs/go-to-market/PROCUREMENT_FAQ.md",
    "docTitle": "Procurement FAQ (Enterprise)",
    "sectionSlug": "5-what-sla-do-you-publish",
    "sectionHeading": "5. What SLA do you publish?",
    "excerpt": "Answer: Targets are documented ([SLA_TARGETS.md](../library/SLA_TARGETS.md), [SLA_SUMMARY.md](SLA_SUMMARY.md)). Contractual SLA language is finalized per Order Form ([ORDER_FORM_TEMPLATE.md](ORDER_FORM_TEMPLATE.md))—pre-contract targets, not unconditional guarantees until executed."
  },
  {
    "docPath": "docs/go-to-market/PROCUREMENT_FAQ.md",
    "docTitle": "Procurement FAQ (Enterprise)",
    "sectionSlug": "6-can-we-execute-the-data-processing-agreement",
    "sectionHeading": "6. Can we execute the Data Processing Agreement?",
    "excerpt": "Answer: Yes — start from the in-app [DPA template](/help/dpa-template) (negotiation template, not a countersigned agreement) and [Subprocessors](/help/subprocessors)."
  },
  {
    "docPath": "docs/go-to-market/PROCUREMENT_FAQ.md",
    "docTitle": "Procurement FAQ (Enterprise)",
    "sectionSlug": "7-what-subprocessors-apply",
    "sectionHeading": "7. What subprocessors apply?",
    "excerpt": "Answer: See [Subprocessors](/help/subprocessors) (maintained quarterly); aligns with contractual notification windows in the [DPA template](/help/dpa-template)."
  },
  {
    "docPath": "docs/go-to-market/PROCUREMENT_FAQ.md",
    "docTitle": "Procurement FAQ (Enterprise)",
    "sectionSlug": "8-what-happens-if-archlucid-ceases-trading",
    "sectionHeading": "8. What happens if ArchLucid ceases trading?",
    "excerpt": "Answer: Operational continuity hinges on contractual termination assistance, export rights, negotiated escrow arrangements, and staged migration timelines—explicit source-code escrow is negotiable rather than universally bundled in starter paper. Start from [MSA_TEMPLATE.md](MSA_TEMPLATE.md) / Order Form playbook."
  },
  {
    "docPath": "docs/go-to-market/PROCUREMENT_FAQ.md",
    "docTitle": "Procurement FAQ (Enterprise)",
    "sectionSlug": "9-do-you-maintain-cyber-insurance",
    "sectionHeading": "9. Do you maintain cyber insurance?",
    "excerpt": "Answer: Procurement should request current coverage limits, carrier, renewal date, and claims history directly from Vendor during diligence—figures change year to year (do not cite an unsigned MD as proof)."
  },
  {
    "docPath": "docs/go-to-market/PROCUREMENT_FAQ.md",
    "docTitle": "Procurement FAQ (Enterprise)",
    "sectionSlug": "10-can-we-speak-with-reference-customers",
    "sectionHeading": "10. Can we speak with reference customers?",
    "excerpt": "Answer: Public Published references are tracked ([reference-customers/README.md](reference-customers/README.md)) with Status placeholders until V1.1-program approvals—coordinate via sales for permissioned pilots."
  },
  {
    "docPath": "docs/go-to-market/PROCUREMENT_FAQ.md",
    "docTitle": "Procurement FAQ (Enterprise)",
    "sectionSlug": "11-how-do-we-get-extended-audit-retention-eg-7-years",
    "sectionHeading": "11. How do we get extended audit retention (e.g. 7 years)?",
    "excerpt": "Answer: Per-tier defaults are 90 days (Team), 1 year (Professional), and custom (Enterprise) — see [`PRICING_PHILOSOPHY.md`](PRICING_PHILOSOPHY.md). Extended retention is an Enterprise-negotiated add-on documented in [`AUDIT_RETENTION_EXTENSION.md`](../library/AUDIT_RETENTION_EXTENSION.md): scheduled CSV exports to …"
  },
  {
    "docPath": "docs/go-to-market/PROCUREMENT_FAQ.md",
    "docTitle": "Procurement FAQ (Enterprise)",
    "sectionSlug": "12-can-we-commission-custom-policy-packs-beyond-bundled-defaults",
    "sectionHeading": "12. Can we commission custom policy packs beyond bundled defaults?",
    "excerpt": "Answer: Yes — V1 professional services. ArchLucid ships productized Custom Policy Pack Authoring SKUs (Starter / Standard / Program) with customer-exclusive or ArchLucid-owned IP tiers. Scope, delivery windows, and canonical USD list prices are in [PRICING_PHILOSOPHY.md §4.2](PRICING_PHILOSOPHY.md#42-custom-policy-p…"
  },
  {
    "docPath": "docs/go-to-market/PROCUREMENT_FAQ.md",
    "docTitle": "Procurement FAQ (Enterprise)",
    "sectionSlug": "trust-progression-timeline-informal",
    "sectionHeading": "Trust progression timeline (informal)",
    "excerpt": "Note: Dates are illustrative—bind via executed Order Form milestones when procuring regulated workloads."
  }
] as const;
