import {
  BarChart3,
  BookOpen,
  ClipboardList,
  Cpu,
  FilePlus,
  FileSearch,
  FileText,
  Fingerprint,
  Gauge,
  HeartPulse,
  KeyRound,
  LineChart,
  PackageCheck,
  Settings2,
  Sparkles,
  UserCog,
  Users,
  Wallet,
  Webhook,
} from "lucide-react";

import type { NavGroupConfig } from "@/lib/nav-config.types";
import { AI_COST_DIAGNOSTICS_PATH } from "@/lib/ai-usage-nav-paths";
import { BUYER_TERMINOLOGY } from "@/lib/buyer-surface-vocabulary";
import { OPERATOR_NAV_LINK_LABELS } from "@/lib/i18n";

import { NavGroupBuilderBase } from "@/lib/nav-group-builder-base";

/** Internal cross-tenant, diagnostic, and employee-only surfaces — gated by `features.showSystemAdministrationNav`. */
export class OperatorSystemAdminNavGroupBuilder extends NavGroupBuilderBase {
  build(): NavGroupConfig {
    return {
      id: "operator-system-admin",
      label: "Internal Operations",
      surface: "system-admin",
      links: [
        {
          href: AI_COST_DIAGNOSTICS_PATH,
          label: "AI processing diagnostics",
          title: "AI processing diagnostics — outbox queue depth, dead-letter posture, and operator health signals",
          icon: Cpu,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/admin/pricing-quote-aging",
          label: "Pricing quote follow-up",
          title: "Pricing quote follow-up — open quote requests and SLA posture",
          icon: ClipboardList,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/admin/trial-funnel",
          label: "Trial funnel",
          title: "Trial funnel — signup, first commit, conversion, and estimated first-review COGS",
          icon: LineChart,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/admin/fleet-llm-cogs",
          label: "Fleet LLM COGS",
          title: "Fleet LLM COGS — per-tenant estimated LLM budget pressure and margin risk",
          icon: Wallet,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/admin/tenant-health",
          label: "Tenant health",
          title: "Tenant health — engagement, governance, and pilot funnel stage per scope",
          icon: BarChart3,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/admin/health",
          label: "Diagnostics dashboard",
          title: "Diagnostics dashboard — readiness, circuit breakers, onboarding funnel metrics",
          icon: Gauge,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/admin/rag-health",
          label: "RAG health",
          title: "RAG health — per-corpus index freshness and embedding dimension",
          icon: BookOpen,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/admin/configuration",
          label: "Configuration",
          title: "Configuration — catalog summary and environment health config-lint dashboard",
          icon: Settings2,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/operate/integration-events/dlq",
          label: "Integration DLQ",
          title: "Integration dead letters — inspect and retry failed outbound integration events",
          icon: Webhook,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/recommendation-learning",
          label: OPERATOR_NAV_LINK_LABELS.recommendationTuning,
          title: "Recommendation tuning — profiles and ranking signals",
          icon: Sparkles,
          tier: "advanced",
          requiredAuthority: "ReadAuthority",
        },
        {
          href: "/product-learning",
          label: OPERATOR_NAV_LINK_LABELS.pilotFeedback,
          title: `${BUYER_TERMINOLOGY.evaluationFeedback} — recurring issues and improvement opportunities`,
          icon: ClipboardList,
          tier: "advanced",
          requiredAuthority: "ReadAuthority",
        },
        {
          href: "/planning",
          label: OPERATOR_NAV_LINK_LABELS.planning,
          title: "Planning — improvement themes and prioritized plans",
          icon: BarChart3,
          tier: "advanced",
          requiredAuthority: "ExecuteAuthority",
        },
        {
          href: "/admin/evidence-proposals",
          label: "Evidence proposals",
          title: "Evidence proposals — review and promote agent-curated catalog entries",
          icon: FilePlus,
          tier: "extended",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/replay",
          label: OPERATOR_NAV_LINK_LABELS.replayReview,
          title: this.shortcutTitle("Validate review package — check stored review output integrity", "alt+p"),
          keyShortcut: "alt+p",
          icon: PackageCheck,
          tier: "extended",
          requiredAuthority: "ExecuteAuthority",
        },
        {
          href: "/health",
          label: OPERATOR_NAV_LINK_LABELS.systemHealth,
          title: "System health — API liveness, readiness, and critical dependencies",
          icon: HeartPulse,
          tier: "extended",
          requiredAuthority: "ReadAuthority",
        },
        {
          href: "/digests",
          label: OPERATOR_NAV_LINK_LABELS.digests,
          title: "Digests — generated digests, subscriptions, and sponsor schedule",
          icon: FileSearch,
          tier: "advanced",
          requiredAuthority: "ReadAuthority",
        },
        {
          href: "/value-report/pilot",
          label: OPERATOR_NAV_LINK_LABELS.pilotValueReport,
          title: `${BUYER_TERMINOLOGY.evaluationValueReport} — finalized-review metrics and governance signals`,
          icon: FileText,
          tier: "extended",
          requiredAuthority: "ReadAuthority",
        },
        {
          href: "/value-report/roi",
          label: OPERATOR_NAV_LINK_LABELS.roiReport,
          title: "ROI report — hours estimate from severities and pre-finalize audit blocks",
          icon: LineChart,
          tier: "extended",
          requiredAuthority: "ReadAuthority",
        },
        {
          href: "/settings/identity-providers",
          label: "Identity providers",
          title: "Identity providers — OIDC authority and audience (read-only catalog row)",
          icon: Fingerprint,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/settings/identity/sso-wizard",
          label: "SSO wizard",
          title: "SSO wizard — guided OIDC / SAML 2.0 tenant configuration",
          icon: UserCog,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/settings/api-keys",
          label: "API keys",
          title: "API keys — host Authentication:ApiKey status and rotation material",
          icon: KeyRound,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/settings/scim-provisioning",
          label: "SCIM provisioning",
          title: "SCIM provisioning — inbound bearer tokens and connectivity verification",
          icon: Users,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
      ],
    };
  }
}
