import {
  Activity,
  BarChart3,
  BookOpen,
  CalendarClock,
  ClipboardList,
  Cpu,
  FileSearch,
  FileText,
  Fingerprint,
  GitBranch,
  HeartPulse,
  KeyRound,
  LineChart,
  Play,
  Scale,
  Settings2,
  ShieldCheck,
  Sparkles,
  Users,
  Wallet,
  Webhook,
} from "lucide-react";

import type { NavGroupConfig } from "@/lib/nav-config.types";
import { BUYER_TERMINOLOGY } from "@/lib/buyer-surface-vocabulary";
import { OPERATOR_NAV_LINK_LABELS } from "@/lib/i18n";

import { NavGroupBuilderBase } from "@/lib/nav-group-builder-base";

/** Internal cross-tenant, diagnostic, and employee-only surfaces — gated by `features.showSystemAdministrationNav`. */
export class OperatorSystemAdminNavGroupBuilder extends NavGroupBuilderBase {
  build(): NavGroupConfig {
    return {
      id: "operator-system-admin",
      label: "System Administration",
      surface: "system-admin",
      caption: "Internal tools, diagnostics, experiments, and employee operations.",
      links: [
        {
          href: "/admin/ai-usage-cost",
          label: "AI usage and cost",
          title: "AI usage and cost — estimated LLM spend, token usage, monthly budget, and processing queue health",
          icon: Cpu,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/admin/pricing-quote-aging",
          label: "Pricing quote follow-up",
          title: "Pricing quote follow-up — open quote requests and SLA posture",
          icon: ClipboardList,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/admin/trial-funnel",
          label: "Trial funnel",
          title: "Trial funnel — signup, first commit, conversion, and estimated first-review COGS",
          icon: LineChart,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/admin/fleet-llm-cogs",
          label: "Fleet LLM COGS",
          title: "Fleet LLM COGS — per-tenant estimated LLM budget pressure and margin risk",
          icon: Wallet,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/admin/tenant-health",
          label: "Tenant health",
          title: "Tenant health — engagement, governance, and pilot funnel stage per scope",
          icon: BarChart3,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/admin/health",
          label: "System health",
          title: "System health — readiness, circuit breakers, onboarding funnel metrics",
          icon: HeartPulse,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/admin/rag-health",
          label: "RAG health",
          title: "RAG health — per-corpus index freshness and embedding dimension",
          icon: BookOpen,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/admin/configuration",
          label: "Configuration",
          title: "Configuration — catalog summary and environment health config-lint dashboard",
          icon: Settings2,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/operate/integration-events/dlq",
          label: "Integration DLQ",
          title: "Integration dead letters — inspect and retry failed outbound integration events",
          icon: Webhook,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/recommendation-learning",
          label: OPERATOR_NAV_LINK_LABELS.recommendationTuning,
          title: "Recommendation tuning — profiles and ranking signals",
          icon: Sparkles,
          tier: "advanced",
          requiredAuthority: "ReadAuthority",
        },
        {
          href: "/product-learning",
          label: OPERATOR_NAV_LINK_LABELS.pilotFeedback,
          title: `${BUYER_TERMINOLOGY.evaluationFeedback} — recurring issues and improvement opportunities`,
          icon: ClipboardList,
          tier: "advanced",
          requiredAuthority: "ReadAuthority",
        },
        {
          href: "/planning",
          label: OPERATOR_NAV_LINK_LABELS.planning,
          title: "Planning — improvement themes and prioritized plans",
          icon: BarChart3,
          tier: "advanced",
          requiredAuthority: "ExecuteAuthority",
        },
        {
          href: "/evolution-review",
          label: OPERATOR_NAV_LINK_LABELS.evolutionCandidates,
          title: "Change simulation — preview expected impact of proposed architecture changes",
          icon: GitBranch,
          tier: "advanced",
          requiredAuthority: "ExecuteAuthority",
        },
        {
          href: "/admin/evidence-proposals",
          label: "Evidence proposals",
          title: "Evidence proposals — review and promote agent-curated catalog entries",
          icon: BookOpen,
          tier: "extended",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/replay",
          label: OPERATOR_NAV_LINK_LABELS.replayReview,
          title: this.shortcutTitle("Validate review package — check stored review output integrity", "alt+p"),
          keyShortcut: "alt+p",
          icon: Play,
          tier: "extended",
          requiredAuthority: "ExecuteAuthority",
        },
        {
          href: "/advisory",
          label: OPERATOR_NAV_LINK_LABELS.architectureAdvisory,
          title: "Architecture advisory — architecture scans and scan schedules",
          icon: Activity,
          tier: "advanced",
          requiredAuthority: "ReadAuthority",
        },
        {
          href: "/governance-resolution",
          label: OPERATOR_NAV_LINK_LABELS.governanceResolution,
          title: "Governance resolution — effective policy for this scope (read view)",
          icon: Scale,
          tier: "extended",
          requiredAuthority: "ReadAuthority",
        },
        {
          href: "/governance/recurrence-schedules",
          label: OPERATOR_NAV_LINK_LABELS.recurrenceSchedules,
          title: "Recurrence schedules — automated follow-up architecture reviews after commit",
          icon: CalendarClock,
          tier: "extended",
          requiredAuthority: "ReadAuthority",
        },
        {
          href: "/health",
          label: OPERATOR_NAV_LINK_LABELS.systemHealth,
          title: "System health — API liveness, readiness, and critical dependencies",
          icon: HeartPulse,
          tier: "extended",
          requiredAuthority: "ReadAuthority",
        },
        {
          href: "/workspace/security-trust",
          label: OPERATOR_NAV_LINK_LABELS.securityTrust,
          title: "Security & trust — published assessments, CAIQ/SIG, trust-center links",
          icon: ShieldCheck,
          tier: "extended",
          requiredAuthority: "ReadAuthority",
        },
        {
          href: "/digests",
          label: OPERATOR_NAV_LINK_LABELS.digests,
          title: "Digests — generated digests, subscriptions, and sponsor schedule",
          icon: FileSearch,
          tier: "advanced",
          requiredAuthority: "ReadAuthority",
        },
        {
          href: "/value-report/pilot",
          label: OPERATOR_NAV_LINK_LABELS.pilotValueReport,
          title: `${BUYER_TERMINOLOGY.evaluationValueReport} — finalized-review metrics and governance signals`,
          icon: FileText,
          tier: "extended",
          requiredAuthority: "ReadAuthority",
        },
        {
          href: "/value-report/roi",
          label: OPERATOR_NAV_LINK_LABELS.roiReport,
          title: "ROI report — hours estimate from severities and pre-finalize audit blocks",
          icon: LineChart,
          tier: "extended",
          requiredAuthority: "ReadAuthority",
        },
        {
          href: "/settings/identity-providers",
          label: "Identity providers",
          title: "Identity providers — OIDC authority and audience (read-only catalog row)",
          icon: Fingerprint,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/settings/identity/sso-wizard",
          label: "SSO wizard",
          title: "SSO wizard — guided OIDC / SAML 2.0 tenant configuration",
          icon: Fingerprint,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/settings/api-keys",
          label: "API keys",
          title: "API keys — host Authentication:ApiKey status and rotation material",
          icon: KeyRound,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
        {
          href: "/settings/scim-provisioning",
          label: "SCIM provisioning",
          title: "SCIM provisioning — inbound bearer tokens and connectivity verification",
          icon: Users,
          tier: "advanced",
          requiredAuthority: "AdminAuthority",
        },
      ],
    };
  }
}
