import type { PatternLibraryRecord } from "@/lib/pattern-library-types";

export const PATTERN_LIBRARY_LAST_UPDATED_UTC = "2026-06-15T12:00:00.000Z";

export const PATTERN_LIBRARY_SAMPLE_CATALOG: readonly PatternLibraryRecord[] = [
  {
    patternKey: "private-endpoints-paas",
    name: "Private endpoints for PaaS data planes",
    description:
      "Route application traffic to SQL, storage, and messaging through private endpoints instead of public service endpoints.",
    domains: ["Financial services", "Healthcare", "Public sector"],
    platforms: ["Azure", "AWS", "Multi-cloud"],
    patternType: "Connectivity",
    adoption: "Common",
    risk: "Moderate",
    governance: "Usually approved",
    relatedControls: ["Network isolation", "Private DNS", "Service endpoint policy"],
    relatedPolicyPacks: ["Regulated data handling", "Zero-trust network"],
    reviewCountLabel: "10–20 reviews",
    tenantCountLabel: "5+ tenants",
    overview:
      "Peers in regulated industries frequently adopt private endpoints to keep PaaS control planes off the public internet while preserving managed-service benefits.",
    whereAppears:
      "Claims modernization, core banking replatforming, and clinical data platforms where egress is tightly controlled.",
    typicalRisks: [
      "DNS resolution gaps between on-premises and cloud private zones",
      "Firewall rule sprawl when endpoint policies are not centralized",
      "Operational blind spots if endpoint health is not monitored",
    ],
    requiredEvidence: [
      "Network diagram with private endpoint placement",
      "DNS zone configuration and resolution paths",
      "Firewall or NSG rules referencing private endpoints",
    ],
    governanceConsiderations: [
      "Document exception process for break-glass administrative access",
      "Confirm logging covers private endpoint connection attempts",
    ],
    relatedPolicyRules: ["No public PaaS endpoints for tier-1 data", "Private link required for production"],
    alternatives: ["Service endpoints only", "Hub-spoke with centralized egress", "Dedicated private connectivity"],
    architectureShape:
      "App tier in spoke VNet → private endpoint → PaaS data plane (SQL, storage, or queue) with centralized DNS forwarding.",
    reviewQuestions: [
      "Which data planes still expose public endpoints?",
      "How is administrative access audited when private endpoints are enforced?",
      "What is the rollback plan if DNS forwarding fails?",
    ],
  },
  {
    patternKey: "three-tier-app-modernization",
    name: "Three-tier app modernization",
    description:
      "Classic presentation, application, and data tiers migrated to managed compute and relational data services.",
    domains: ["General", "Internal enterprise", "SaaS"],
    platforms: ["Azure", "AWS"],
    patternType: "Application",
    adoption: "Common",
    risk: "Low",
    governance: "Usually approved",
    relatedControls: ["Managed identity", "Autoscale", "Backup and restore"],
    relatedPolicyPacks: ["Application baseline", "Cost guardrails"],
    reviewCountLabel: "20–40 reviews",
    tenantCountLabel: "8+ tenants",
    overview:
      "A pragmatic lift-and-modernize shape that keeps familiar boundaries while replacing VMs with managed app and database services.",
    whereAppears:
      "Line-of-business portals, internal admin tools, and pilot modernizations that must ship quickly with recognizable tiers.",
    typicalRisks: [
      "Session affinity assumptions carried over from VM farms",
      "Under-sized connection pooling after moving to PaaS SQL",
      "Missing cache layer causing latency regressions",
    ],
    requiredEvidence: ["Tier diagram", "Data flow between tiers", "Identity model for app-to-data access"],
    governanceConsiderations: ["Confirm production SKUs meet RTO/RPO targets", "Validate secrets are not embedded in app config"],
    relatedPolicyRules: ["Managed compute required for new workloads", "SQL encryption at rest"],
    alternatives: ["Containerized three-tier", "Serverless API with static web", "Modular monolith"],
    architectureShape: "Web/app service → API layer → managed relational database with private connectivity.",
    reviewQuestions: [
      "Which tier owns authentication and authorization?",
      "How is schema migration handled across releases?",
      "What autoscale signals drive each tier?",
    ],
  },
  {
    patternKey: "event-driven-claims-intake",
    name: "Event-driven claims intake",
    description:
      "Intake channels publish domain events to a bus so adjudication, enrichment, and notification scale independently.",
    domains: ["Financial services", "Healthcare"],
    platforms: ["Azure", "AWS", "Multi-cloud"],
    patternType: "Integration",
    adoption: "Emerging",
    risk: "Moderate",
    governance: "Needs evidence",
    relatedControls: ["Event schema registry", "Dead-letter handling", "Idempotent consumers"],
    relatedPolicyPacks: ["Claims processing", "Message durability"],
    reviewCountLabel: "10–20 reviews",
    tenantCountLabel: "5+ tenants",
    overview:
      "Decouples volatile intake spikes from downstream adjudication by standardizing events at the platform edge.",
    whereAppears: "Insurance claims, benefits intake, and prior-authorization workflows with seasonal volume.",
    typicalRisks: [
      "Poison messages without dead-letter triage",
      "PII leakage in event payloads",
      "Ordering assumptions across partitioned topics",
    ],
    requiredEvidence: ["Event catalog", "Consumer dependency map", "Retry and DLQ configuration"],
    governanceConsiderations: ["Define data minimization for event payloads", "Require schema versioning for breaking changes"],
    relatedPolicyRules: ["PII fields masked in async messages", "Consumer idempotency required"],
    alternatives: ["Synchronous API orchestration", "Batch file drops", "Workflow engine with human tasks"],
    architectureShape: "Intake API → event bus → enrichment workers → adjudication service → notification fan-out.",
    reviewQuestions: [
      "Which events carry regulated data?",
      "How are duplicate deliveries detected?",
      "What is the maximum acceptable end-to-end latency?",
    ],
  },
  {
    patternKey: "api-gateway-bff",
    name: "API gateway with backend-for-frontend",
    description:
      "A gateway terminates edge concerns while BFF services shape responses for web and mobile clients.",
    domains: ["SaaS", "General", "Internal enterprise"],
    platforms: ["AWS", "Azure", "GCP", "Multi-cloud"],
    patternType: "Application",
    adoption: "Common",
    risk: "Moderate",
    governance: "Usually approved",
    relatedControls: ["Rate limiting", "OAuth/OIDC at edge", "WAF"],
    relatedPolicyPacks: ["API security baseline", "Public exposure"],
    reviewCountLabel: "15–30 reviews",
    tenantCountLabel: "6+ tenants",
    overview:
      "Separates channel-specific aggregation from core domain services and centralizes throttling, auth, and observability at the edge.",
    whereAppears: "Customer portals, partner APIs, and multi-channel SaaS products.",
    typicalRisks: [
      "BFF logic becoming a second monolith",
      "Token validation inconsistencies between gateway and services",
      "Latency stacking when BFF chains too many downstream calls",
    ],
    requiredEvidence: ["Gateway policy map", "BFF-to-service contract", "Auth token flow diagram"],
    governanceConsiderations: ["Publish API versioning policy", "Document break-glass admin routes"],
    relatedPolicyRules: ["WAF on public APIs", "mTLS for internal service hops"],
    alternatives: ["Direct service mesh exposure", "GraphQL federation", "Single public API surface"],
    architectureShape: "Clients → API gateway/WAF → BFF per channel → domain microservices.",
    reviewQuestions: [
      "Where is authorization enforced — gateway, BFF, or domain service?",
      "How are breaking API changes communicated to partners?",
      "What cache strategy exists at the BFF layer?",
    ],
  },
  {
    patternKey: "governed-data-lake-zones",
    name: "Data lake ingestion with governed zones",
    description:
      "Landing, curated, and consumption zones separate raw ingestion from curated analytics products.",
    domains: ["Financial services", "Healthcare", "Public sector"],
    platforms: ["Azure", "AWS", "GCP"],
    patternType: "Data",
    adoption: "Common",
    risk: "High",
    governance: "Often requires exception",
    relatedControls: ["Column-level security", "Lakehouse ACLs", "Lineage catalog"],
    relatedPolicyPacks: ["Data residency", "Analytics governance"],
    reviewCountLabel: "10–20 reviews",
    tenantCountLabel: "5+ tenants",
    overview:
      "Balances analytics agility with regulatory controls by enforcing promotion rules between raw and curated zones.",
    whereAppears: "Enterprise analytics programs, population health insights, and fraud analytics platforms.",
    typicalRisks: [
      "Shadow datasets in consumption zone without lineage",
      "Over-broad analyst access to landing zone",
      "Insufficient retention policies on raw copies",
    ],
    requiredEvidence: ["Zone diagram", "Promotion workflow", "Access matrix by zone"],
    governanceConsiderations: ["Align retention with legal hold requirements", "Require approval for PII in consumption zone"],
    relatedPolicyRules: ["No direct analyst access to landing zone", "Masking required for indirect identifiers"],
    alternatives: ["Warehouse-only model", "Federated query without central lake", "Event streaming to OLTP replicas"],
    architectureShape: "Ingest → landing storage → curation jobs → governed consumption layer → BI/ML tools.",
    reviewQuestions: [
      "Who can promote datasets between zones?",
      "How is lineage captured for derived tables?",
      "What breaks if landing zone retention is shortened?",
    ],
  },
  {
    patternKey: "zero-trust-admin-access",
    name: "Zero-trust administrative access",
    description:
      "Privileged access uses just-in-time elevation, strong identity, and session recording instead of standing admin accounts.",
    domains: ["Financial services", "Public sector", "Internal enterprise"],
    platforms: ["Azure", "AWS", "GCP", "Multi-cloud"],
    patternType: "Security",
    adoption: "Emerging",
    risk: "Moderate",
    governance: "Needs evidence",
    relatedControls: ["PIM/JIT", "Conditional access", "Session recording"],
    relatedPolicyPacks: ["Privileged access", "Zero trust admin"],
    reviewCountLabel: "10–20 reviews",
    tenantCountLabel: "5+ tenants",
    overview:
      "Reduces blast radius of compromised administrator credentials while preserving break-glass procedures.",
    whereAppears: "Regulated cloud landing zones, hybrid operations teams, and multi-team platform estates.",
    typicalRisks: [
      "Break-glass accounts without equivalent monitoring",
      "Approval fatigue leading to standing privileges",
      "Gaps between cloud IAM and on-premises directory groups",
    ],
    requiredEvidence: ["Admin access flow", "JIT policy configuration", "Audit log destinations"],
    governanceConsiderations: ["Test break-glass quarterly", "Separate platform admin from workload admin roles"],
    relatedPolicyRules: ["No permanent Owner on production subscriptions", "MFA required for privileged roles"],
    alternatives: ["Bastion-only access", "Dedicated admin VNet", "Third-party PAM appliance"],
    architectureShape: "Operator identity → conditional access → JIT elevation → recorded session → target control plane.",
    reviewQuestions: [
      "Which admin actions are still standing vs just-in-time?",
      "How quickly can emergency access be granted and audited?",
      "Are service principals excluded from human JIT policies?",
    ],
  },
  {
    patternKey: "queue-adjudication-handoff",
    name: "Queue-based adjudication handoff",
    description:
      "Human adjudication steps pull work items from durable queues with explicit SLA and escalation paths.",
    domains: ["Financial services", "Healthcare", "Other"],
    platforms: ["Azure", "AWS", "Evidence-only"],
    patternType: "Integration",
    adoption: "Common",
    risk: "Moderate",
    governance: "Frequently flagged",
    relatedControls: ["Queue encryption", "Visibility timeout", "Poison message handling"],
    relatedPolicyPacks: ["Operations resilience", "Workflow audit"],
    reviewCountLabel: "10–20 reviews",
    tenantCountLabel: "5+ tenants",
    overview:
      "Makes manual review queues observable and auditable while keeping peak intake off synchronous call chains.",
    whereAppears: "Underwriting, claims adjudication, and clinical review queues with compliance timers.",
    typicalRisks: [
      "SLA breaches when worker scaling lags",
      "Sensitive fields visible to broad operator roles",
      "Stuck messages without operational dashboards",
    ],
    requiredEvidence: ["Queue structure", "Worker scaling rules", "Escalation playbook"],
    governanceConsiderations: ["Map queue access to least-privilege roles", "Retain dequeue audit for regulated cases"],
    relatedPolicyRules: ["Encryption in transit for workflow messages", "Escalation within defined SLA"],
    alternatives: ["Case management SaaS", "Database-backed work queues", "Human-in-the-loop orchestration engine"],
    architectureShape: "Intake → durable queue → worker pool → adjudication UI → outcome events.",
    reviewQuestions: [
      "What happens when the queue depth exceeds threshold?",
      "How are reassigned cases tracked?",
      "Which fields are redacted in architect views?",
    ],
  },
  {
    patternKey: "rag-knowledge-assistant",
    name: "RAG knowledge assistant with evidence controls",
    description:
      "Retrieval-augmented assistants ground answers in approved corpora with citation and policy guardrails.",
    domains: ["SaaS", "Healthcare", "Internal enterprise"],
    platforms: ["Azure", "AWS", "Multi-cloud", "Evidence-only"],
    patternType: "AI and knowledge",
    adoption: "Emerging",
    risk: "High",
    governance: "Needs evidence",
    relatedControls: ["Corpus allow-list", "Prompt injection filters", "Citation requirements"],
    relatedPolicyPacks: ["Responsible AI", "Knowledge retrieval"],
    reviewCountLabel: "10–20 reviews",
    tenantCountLabel: "5+ tenants",
    overview:
      "Helps architects and reviewers query architecture knowledge without exposing unapproved sources or tenant data.",
    whereAppears: "Architecture review assistants, policy copilots, and internal enablement chat experiences.",
    typicalRisks: [
      "Retrieval of stale or draft policy documents",
      "Over-trust in uncited model answers",
      "Cross-tenant leakage via shared indexes",
    ],
    requiredEvidence: ["Corpus inventory", "Retrieval pipeline diagram", "Red-team or eval results"],
    governanceConsiderations: ["Require citations for regulated answers", "Separate dev and prod corpora"],
    relatedPolicyRules: ["No customer data in shared embedding index", "Human review for high-risk answers"],
    alternatives: ["Keyword search only", "Fine-tuned closed model", "Deterministic FAQ bot"],
    architectureShape: "User query → retrieval service → allow-listed corpus → LLM with citations → audited response.",
    reviewQuestions: [
      "Which documents are excluded from retrieval?",
      "How are hallucinations detected in production?",
      "What logging is retained for prompts and responses?",
    ],
  },
  {
    patternKey: "multi-region-active-passive",
    name: "Multi-region active/passive recovery",
    description:
      "Primary region serves traffic while a secondary region holds warm standby data and failover runbooks.",
    domains: ["Financial services", "SaaS", "Public sector"],
    platforms: ["Azure", "AWS", "GCP", "Multi-cloud"],
    patternType: "Resilience",
    adoption: "Common",
    risk: "High",
    governance: "Often requires exception",
    relatedControls: ["RPO/RTO targets", "Geo-replication", "Failover testing"],
    relatedPolicyPacks: ["Business continuity", "Resilience baseline"],
    reviewCountLabel: "15–30 reviews",
    tenantCountLabel: "6+ tenants",
    overview:
      "Balances cost and resilience for workloads that need geographic recovery without full active/active complexity.",
    whereAppears: "Core payment services, member portals, and regional SaaS control planes.",
    typicalRisks: [
      "Replication lag beyond stated RPO",
      "DNS failover dependencies on manual steps",
      "Untested secondary region capacity",
    ],
    requiredEvidence: ["Region layout", "Replication configuration", "Last failover test results"],
    governanceConsiderations: ["Document data residency constraints per region", "Schedule game days for failover"],
    relatedPolicyRules: ["Production workloads require tested DR", "RTO/RPO declared per tier"],
    alternatives: ["Active/active multi-region", "Backup-restore only", "Pilot light secondary"],
    architectureShape: "Active region stack → async replication → passive region standby → controlled DNS/traffic shift.",
    reviewQuestions: [
      "What is measured RPO during peak load?",
      "Which dependencies block automated failover?",
      "How is write traffic handled during partial region loss?",
    ],
  },
  {
    patternKey: "legacy-batch-to-managed-workflows",
    name: "Legacy batch migration to managed workflows",
    description:
      "Scheduled batch jobs move to managed workflow engines with observability, retries, and idempotent steps.",
    domains: ["Internal enterprise", "General", "Other"],
    platforms: ["Azure", "AWS", "Evidence-only"],
    patternType: "Migration",
    adoption: "Declining",
    risk: "Moderate",
    governance: "Usually approved",
    relatedControls: ["Step retries", "Compensation logic", "Schedule monitoring"],
    relatedPolicyPacks: ["Migration factory", "Operational readiness"],
    reviewCountLabel: "10–20 reviews",
    tenantCountLabel: "5+ tenants",
    overview:
      "Replaces opaque cron-and-script estates with durable workflows that are easier to audit and replay.",
    whereAppears: "Finance close processes, inventory reconciliation, and legacy mainframe offload programs.",
    typicalRisks: [
      "Hidden side effects in migrated scripts",
      "Insufficient idempotency on partial reruns",
      "Cost surprises from high-frequency orchestration",
    ],
    requiredEvidence: ["Job dependency graph", "Workflow definition", "Monitoring dashboards"],
    governanceConsiderations: ["Align batch windows with downstream SLAs", "Retain rollback scripts during transition"],
    relatedPolicyRules: ["Production batch requires alerting", "Secrets via vault integration"],
    alternatives: ["Containerized cron", "Spark on managed cluster", "Event-driven replacement"],
    architectureShape: "Scheduler → workflow engine → activity workers → downstream systems with retry policies.",
    reviewQuestions: [
      "Which steps are safe to retry?",
      "How are partial failures communicated to owners?",
      "What is the cost model at peak batch windows?",
    ],
  },
];

export function findPatternLibraryRecord(patternKey: string): PatternLibraryRecord | null {
  const normalized = patternKey.trim().toLowerCase();

  return (
    PATTERN_LIBRARY_SAMPLE_CATALOG.find((record) => record.patternKey.toLowerCase() === normalized) ?? null
  );
}
