/**
 * Customer-visible in-app documentation registry entries (operator).
 * Source of truth: `docs/library/PRODUCT_DOCUMENTATION_PRESENTATION.md`.
 */
import type { ProductDocumentationRegistryInput } from "./product-documentation-registry-types";
import { PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR_GOVERNANCE } from "./product-documentation-registry-entries-operator-governance";
import { PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR_INTEGRATIONS } from "./product-documentation-registry-entries-operator-integrations";
import { PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR_WORKSPACE } from "./product-documentation-registry-entries-operator-workspace";

export const PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR: readonly ProductDocumentationRegistryInput[] = [
  ...PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR_WORKSPACE.slice(0, 8),
  ...PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR_GOVERNANCE.slice(0, 3),
  ...PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR_WORKSPACE.slice(8, 10),
  ...PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR_INTEGRATIONS.slice(0, 5),
  ...PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR_WORKSPACE.slice(10, 11),
  ...PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR_INTEGRATIONS.slice(5, 7),
  ...PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR_WORKSPACE.slice(11, 21),
  ...PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR_GOVERNANCE.slice(3, 4),
  ...PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR_WORKSPACE.slice(21, 26),
  ...PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR_INTEGRATIONS.slice(7, 8),
  ...PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR_GOVERNANCE.slice(4, 5),
  ...PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR_WORKSPACE.slice(26, 27),
  ...PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR_INTEGRATIONS.slice(8, 11),
  ...PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR_WORKSPACE.slice(27),
  ...PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR_GOVERNANCE.slice(5, 6),
  ...PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR_INTEGRATIONS.slice(11),
  ...PRODUCT_DOCUMENTATION_REGISTRY_ENTRIES_OPERATOR_GOVERNANCE.slice(6),
] as const;
