using System.Text;

namespace ArchLucid.Cli.Stack;

internal static partial class ArchlucidStackArtifactGenerator
{
    private static string BuildTerraformPrivateTfvars(
        ArchlucidStackDocument document,
        string resourceGroupName,
        string location)
    {
        StringBuilder builder = new();
        builder.AppendLine("# Generated by archlucid stack init (TB-654). Review before terraform apply.");
        builder.AppendLine("enable_private_data_plane = true");
        builder.AppendLine("create_resource_group     = true");
        builder.AppendLine($"resource_group_name       = \"{resourceGroupName}\"");
        builder.AppendLine($"location                  = \"{location}\"");
        builder.AppendLine();
        builder.AppendLine("# Populate ARM IDs from Azure Portal or az resource show before first apply.");
        builder.AppendLine("sql_server_id      = \"/subscriptions/REPLACE/resourceGroups/REPLACE/providers/Microsoft.Sql/servers/REPLACE\"");
        builder.AppendLine("storage_account_id = \"/subscriptions/REPLACE/resourceGroups/REPLACE/providers/Microsoft.Storage/storageAccounts/REPLACE\"");
        builder.AppendLine();
        builder.AppendLine("tags = {");
        builder.AppendLine("  workload    = \"archlucid\"");
        builder.AppendLine($"  environment = \"{document.Azure.Environment}\"");
        builder.AppendLine("  layer       = \"private-data\"");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string BuildTerraformContainerAppsTfvars(
        ArchlucidStackDocument document,
        string resourceGroupName,
        string location,
        string apiImage,
        string uiImage)
    {
        StringBuilder builder = new();
        builder.AppendLine("# Generated by archlucid stack init (TB-654). CD owns runtime image tags after first deploy (TB-657).");
        builder.AppendLine("enable_container_apps = true");
        builder.AppendLine("create_resource_group = true");
        builder.AppendLine($"resource_group_name   = \"{resourceGroupName}\"");
        builder.AppendLine($"location              = \"{location}\"");
        builder.AppendLine();
        builder.AppendLine($"api_container_image = \"{apiImage}\"");
        builder.AppendLine($"ui_container_image  = \"{uiImage}\"");
        builder.AppendLine();
        builder.AppendLine("api_min_replicas = 2");
        builder.AppendLine("api_max_replicas = 5");
        builder.AppendLine("ui_min_replicas  = 1");
        builder.AppendLine("ui_max_replicas  = 6");
        builder.AppendLine("ui_scale_concurrent_requests = 10");
        builder.AppendLine("worker_min_replicas = 1");
        builder.AppendLine("worker_max_replicas = 20");
        builder.AppendLine();
        builder.AppendLine("tags = {");
        builder.AppendLine("  workload    = \"archlucid\"");
        builder.AppendLine($"  environment = \"{document.Azure.Environment}\"");
        builder.AppendLine("  layer       = \"container-apps\"");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string BuildTerraformPilotTfvars(ArchlucidStackDocument document)
    {
        StringBuilder builder = new();
        builder.AppendLine("# Generated by archlucid stack init (TB-654).");
        builder.AppendLine($"deployment_profile      = \"{MapDeploymentProfile(document.Azure.Environment)}\"");
        builder.AppendLine($"multi_root_apply_opt_in = {document.Deployment.MultiRootApplyOptIn.ToString().ToLowerInvariant()}");

        if (document.Deployment.PilotMonthlyBudgetUsd is int budget)
            builder.AppendLine($"pilot_monthly_budget_usd = {budget}");

        builder.AppendLine("app_insights_sampling_percent = 40");

        return builder.ToString();
    }

    private static string BuildTerraformKeyVaultTfvars(ArchlucidStackDocument document, string vaultName)
    {
        StringBuilder builder = new();
        builder.AppendLine("# Generated by archlucid stack init (TB-654). Review before terraform apply.");
        builder.AppendLine("enable_key_vault = true");
        builder.AppendLine("enable_user_assigned_keyvault_workload_identities = true");
        builder.AppendLine($"key_vault_name   = \"{vaultName}\"");
        builder.AppendLine();
        builder.AppendLine("# Assign api_managed_identity_principal_id / worker_managed_identity_principal_id after Container Apps apply (TB-092).");
        builder.AppendLine("tags = {");
        builder.AppendLine("  workload    = \"archlucid\"");
        builder.AppendLine($"  environment = \"{document.Azure.Environment}\"");
        builder.AppendLine("  layer       = \"keyvault\"");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string MapDeploymentProfile(string environment)
    {
        return environment switch
        {
            "production" => "production",
            "staging" => "staging",
            _ => "pilot",
        };
    }
}
