using System.Text;
using System.Text.Json;

namespace ArchLucid.Cli.Stack;

/// <summary>Emits per-root tfvars, hosted appsettings, GitHub env manifest, and Key Vault checklist from stack answers.</summary>
internal static class ArchlucidStackArtifactGenerator
{
    private static readonly JsonSerializerOptions IndentedJsonOptions = new()
    {
        WriteIndented = true,
    };

    internal static ArchlucidStackGeneratedArtifacts Generate(ArchlucidStackDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        string prefix = document.Naming.ResourcePrefix.Trim();
        string environment = document.Azure.Environment.Trim();
        string location = document.Azure.Location.Trim();
        string loginServer = document.ContainerRegistry.LoginServer.Trim().TrimEnd('/');
        string imageTag = document.ContainerRegistry.ImageTag.Trim();
        string vaultName = document.KeyVault.Name.Trim();

        string privateResourceGroup = $"rg-{prefix}-private";
        string containerAppsResourceGroup = $"rg-{prefix}-ca-{environment}";
        string apiImage = $"{loginServer}/archlucid:{imageTag}";
        string uiImage = $"{loginServer}/archlucid-ui:{imageTag}";

        Dictionary<string, string> files = new(StringComparer.OrdinalIgnoreCase)
        {
            ["terraform-private.tfvars"] = BuildTerraformPrivateTfvars(document, privateResourceGroup, location),
            ["terraform-container-apps.tfvars"] = BuildTerraformContainerAppsTfvars(
                document,
                containerAppsResourceGroup,
                location,
                apiImage,
                uiImage),
            ["terraform-pilot.tfvars"] = BuildTerraformPilotTfvars(document),
            ["terraform-keyvault.tfvars"] = BuildTerraformKeyVaultTfvars(document, vaultName),
            ["appsettings.Hosted.json"] = BuildHostedAppsettingsJson(document, vaultName),
            ["github-environment-variables.json"] = BuildGitHubEnvironmentManifest(document),
            ["key-vault-secret-checklist.md"] = BuildKeyVaultChecklistMarkdown(document, vaultName),
        };

        return new ArchlucidStackGeneratedArtifacts(files);
    }

    private static string BuildTerraformPrivateTfvars(
        ArchlucidStackDocument document,
        string resourceGroupName,
        string location)
    {
        StringBuilder builder = new();
        builder.AppendLine("# Generated by archlucid stack init (TB-654). Review before terraform apply.");
        builder.AppendLine("enable_private_data_plane = true");
        builder.AppendLine("create_resource_group     = true");
        builder.AppendLine($"resource_group_name       = \"{resourceGroupName}\"");
        builder.AppendLine($"location                  = \"{location}\"");
        builder.AppendLine();
        builder.AppendLine("# Populate ARM IDs from Azure Portal or az resource show before first apply.");
        builder.AppendLine("sql_server_id      = \"/subscriptions/REPLACE/resourceGroups/REPLACE/providers/Microsoft.Sql/servers/REPLACE\"");
        builder.AppendLine("storage_account_id = \"/subscriptions/REPLACE/resourceGroups/REPLACE/providers/Microsoft.Storage/storageAccounts/REPLACE\"");
        builder.AppendLine();
        builder.AppendLine("tags = {");
        builder.AppendLine("  workload    = \"archlucid\"");
        builder.AppendLine($"  environment = \"{document.Azure.Environment}\"");
        builder.AppendLine("  layer       = \"private-data\"");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string BuildTerraformContainerAppsTfvars(
        ArchlucidStackDocument document,
        string resourceGroupName,
        string location,
        string apiImage,
        string uiImage)
    {
        StringBuilder builder = new();
        builder.AppendLine("# Generated by archlucid stack init (TB-654). CD owns runtime image tags after first deploy (TB-657).");
        builder.AppendLine("enable_container_apps = true");
        builder.AppendLine("create_resource_group = true");
        builder.AppendLine($"resource_group_name   = \"{resourceGroupName}\"");
        builder.AppendLine($"location              = \"{location}\"");
        builder.AppendLine();
        builder.AppendLine($"api_container_image = \"{apiImage}\"");
        builder.AppendLine($"ui_container_image  = \"{uiImage}\"");
        builder.AppendLine();
        builder.AppendLine("api_min_replicas = 2");
        builder.AppendLine("api_max_replicas = 5");
        builder.AppendLine("ui_min_replicas  = 1");
        builder.AppendLine("ui_max_replicas  = 6");
        builder.AppendLine("ui_scale_concurrent_requests = 10");
        builder.AppendLine("worker_min_replicas = 1");
        builder.AppendLine("worker_max_replicas = 20");
        builder.AppendLine();
        builder.AppendLine("tags = {");
        builder.AppendLine("  workload    = \"archlucid\"");
        builder.AppendLine($"  environment = \"{document.Azure.Environment}\"");
        builder.AppendLine("  layer       = \"container-apps\"");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string BuildTerraformPilotTfvars(ArchlucidStackDocument document)
    {
        StringBuilder builder = new();
        builder.AppendLine("# Generated by archlucid stack init (TB-654).");
        builder.AppendLine($"deployment_profile      = \"{MapDeploymentProfile(document.Azure.Environment)}\"");
        builder.AppendLine($"multi_root_apply_opt_in = {document.Deployment.MultiRootApplyOptIn.ToString().ToLowerInvariant()}");

        if (document.Deployment.PilotMonthlyBudgetUsd is int budget)
            builder.AppendLine($"pilot_monthly_budget_usd = {budget}");

        builder.AppendLine("app_insights_sampling_percent = 40");

        return builder.ToString();
    }

    private static string BuildTerraformKeyVaultTfvars(ArchlucidStackDocument document, string vaultName)
    {
        StringBuilder builder = new();
        builder.AppendLine("# Generated by archlucid stack init (TB-654). Review before terraform apply.");
        builder.AppendLine("enable_key_vault = true");
        builder.AppendLine("enable_user_assigned_keyvault_workload_identities = true");
        builder.AppendLine($"key_vault_name   = \"{vaultName}\"");
        builder.AppendLine();
        builder.AppendLine("# Assign api_managed_identity_principal_id / worker_managed_identity_principal_id after Container Apps apply (TB-092).");
        builder.AppendLine("tags = {");
        builder.AppendLine("  workload    = \"archlucid\"");
        builder.AppendLine($"  environment = \"{document.Azure.Environment}\"");
        builder.AppendLine("  layer       = \"keyvault\"");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string BuildHostedAppsettingsJson(ArchlucidStackDocument document, string vaultName)
    {
        string KvRef(string secretName) =>
            $"@Microsoft.KeyVault(VaultName={vaultName};SecretName={secretName})";

        object payload = new
        {
            _comment = "Generated by archlucid stack init (TB-654). Merge into Container Apps application settings.",
            ArchLucid = new
            {
                PublicSite = new
                {
                    BaseUrl = document.PublicSite.BaseUrl.TrimEnd('/'),
                },
                Secrets = new
                {
                    Provider = "KeyVault",
                    KeyVaultUri = $"https://{vaultName}.vault.azure.net/",
                },
                AgentModelTiers = new
                {
                    DefaultTier = "Standard",
                    NonAgentDefaultTier = "Standard",
                    EconomyDeploymentName = document.OpenAi?.EconomyDeploymentName ?? "gpt-5.6-luna",
                    StandardDeploymentName = document.OpenAi?.ChatDeploymentName ?? "gpt-5.6-terra",
                    PremiumDeploymentName = document.OpenAi?.PremiumDeploymentName ?? "gpt-5.6-sol",
                },
            },
            ConnectionStrings = new
            {
                ArchLucid = KvRef("archlucid-sql-connection-string"),
            },
            AzureOpenAI = new
            {
                AuthenticationMode = "ManagedIdentity",
                ApiKey = KvRef("archlucid-azure-openai-api-key"),
                Endpoint = document.OpenAi?.ExistingEndpoint?.TrimEnd('/') ?? "https://REPLACE.openai.azure.com/",
                DeploymentName = document.OpenAi?.ChatDeploymentName ?? "gpt-5.6-terra",
                EmbeddingDeploymentName = document.OpenAi?.EmbeddingDeploymentName ?? "text-embedding-3-small",
            },
            ArchLucidAuth = new
            {
                Mode = "ApiKey",
            },
            Authentication = new
            {
                ApiKey = new
                {
                    Enabled = true,
                    DevelopmentBypassAll = false,
                    AdminKey = KvRef("archlucid-api-admin-key"),
                    ReadOnlyKey = KvRef("archlucid-api-readonly-key"),
                },
            },
        };

        return JsonSerializer.Serialize(payload, IndentedJsonOptions);
    }

    private static string BuildGitHubEnvironmentManifest(ArchlucidStackDocument document)
    {
        object payload = new
        {
            _comment = "Generated by archlucid stack init (TB-654). Store values as GitHub Environment secrets — never commit real credentials.",
            githubEnvironment = document.Azure.Environment,
            secrets = new[]
            {
                new { name = "AZURE_SUBSCRIPTION_ID", valueFrom = "azure.subscriptionId" },
                new { name = "AZURE_TENANT_ID", valueFrom = "azure.tenantId" },
                new { name = "AZURE_CLIENT_ID", valueFrom = "(OIDC federated app registration — set manually)" },
                new { name = "SMOKE_TEST_BASE_URL", valueFrom = "publicSite.baseUrl" },
            },
            variables = new[]
            {
                new { name = "ARCHLUCID_STACK_LOCATION", value = document.Azure.Location },
                new { name = "ARCHLUCID_STACK_RESOURCE_PREFIX", value = document.Naming.ResourcePrefix },
            },
        };

        return JsonSerializer.Serialize(payload, IndentedJsonOptions);
    }

    private static string BuildKeyVaultChecklistMarkdown(ArchlucidStackDocument document, string vaultName)
    {
        StringBuilder builder = new();
        builder.AppendLine("# Key Vault populate checklist (names only)");
        builder.AppendLine();
        builder.AppendLine($"Generated by `archlucid stack init` for environment **{document.Azure.Environment}**.");
        builder.AppendLine($"Vault: **{vaultName}** (`https://{vaultName}.vault.azure.net/`).");
        builder.AppendLine();
        builder.AppendLine("Populate each secret in Azure Key Vault. **Never** commit secret values to git.");
        builder.AppendLine();
        builder.AppendLine("| Secret name | Maps to appsettings |");
        builder.AppendLine("|-------------|---------------------|");

        foreach (string secretName in ArchlucidStackKeyVaultSecretNames.HostedPilotSecrets)
        {
            string mapping = MapSecretToAppsettings(secretName);
            builder.AppendLine($"| `{secretName}` | {mapping} |");
        }

        builder.AppendLine();
        builder.AppendLine("See `docs/library/CONFIGURATION_KEY_VAULT.md` and `ArchLucid.Api/appsettings.KeyVault.sample.json`.");

        return builder.ToString();
    }

    private static string MapSecretToAppsettings(string secretName)
    {
        return secretName switch
        {
            "archlucid-sql-connection-string" => "`ConnectionStrings:ArchLucid`",
            "archlucid-azure-openai-api-key" => "`AzureOpenAI:ApiKey`",
            "archlucid-fallback-llm-api-key" => "`ArchLucid:FallbackLlm:ApiKey`",
            "archlucid-api-admin-key" => "`Authentication:ApiKey:AdminKey`",
            "archlucid-api-readonly-key" => "`Authentication:ApiKey:ReadOnlyKey`",
            "archlucid-azuredevops-archlucid-api-key" => "`AzureDevOps:ArchLucidApiKey`",
            "archlucid-servicebus-connection-string" => "`IntegrationEvents:ServiceBusConnectionString`",
            "archlucid-webhook-hmac-secret" => "`WebhookDelivery:HmacSha256SharedSecret`",
            "archlucid-internal-cross-tenant-analytics-salt" => "`ArchLucid:InternalCrossTenantAnalytics:PseudonymizationSalt`",
            _ => "(see CONFIGURATION_REFERENCE.md)",
        };
    }

    private static string MapDeploymentProfile(string environment)
    {
        return environment switch
        {
            "production" => "production",
            "staging" => "staging",
            _ => "pilot",
        };
    }
}
