using System.Text.Json;

namespace ArchLucid.Cli.Stack;

internal static partial class ArchlucidStackArtifactGenerator
{
    private static string BuildHostedAppsettingsJson(ArchlucidStackDocument document, string vaultName)
    {
        string KvRef(string secretName) =>
            $"@Microsoft.KeyVault(VaultName={vaultName};SecretName={secretName})";

        object payload = new
        {
            _comment = "Generated by archlucid stack init (TB-654). Merge into Container Apps application settings.",
            ArchLucid = new
            {
                PublicSite = new
                {
                    BaseUrl = document.PublicSite.BaseUrl.TrimEnd('/'),
                },
                Secrets = new
                {
                    Provider = "KeyVault",
                    KeyVaultUri = $"https://{vaultName}.vault.azure.net/",
                },
                AgentModelTiers = new
                {
                    DefaultTier = "Standard",
                    NonAgentDefaultTier = "Standard",
                    EconomyDeploymentName = document.OpenAi?.EconomyDeploymentName ?? "gpt-5.6-luna",
                    StandardDeploymentName = document.OpenAi?.ChatDeploymentName ?? "gpt-5.6-terra",
                    PremiumDeploymentName = document.OpenAi?.PremiumDeploymentName ?? "gpt-5.6-sol",
                },
            },
            ConnectionStrings = new
            {
                ArchLucid = KvRef("archlucid-sql-connection-string"),
            },
            AzureOpenAI = new
            {
                AuthenticationMode = "ManagedIdentity",
                ApiKey = KvRef("archlucid-azure-openai-api-key"),
                Endpoint = document.OpenAi?.ExistingEndpoint?.TrimEnd('/') ?? "https://REPLACE.openai.azure.com/",
                DeploymentName = document.OpenAi?.ChatDeploymentName ?? "gpt-5.6-terra",
                EmbeddingDeploymentName = document.OpenAi?.EmbeddingDeploymentName ?? "text-embedding-3-small",
            },
            ArchLucidAuth = new
            {
                Mode = "ApiKey",
            },
            Authentication = new
            {
                ApiKey = new
                {
                    Enabled = true,
                    DevelopmentBypassAll = false,
                    AdminKey = KvRef("archlucid-api-admin-key"),
                    ReadOnlyKey = KvRef("archlucid-api-readonly-key"),
                },
            },
        };

        return JsonSerializer.Serialize(payload, IndentedJsonOptions);
    }

    private static string BuildGitHubEnvironmentManifest(ArchlucidStackDocument document)
    {
        object payload = new
        {
            _comment = "Generated by archlucid stack init (TB-654). Store values as GitHub Environment secrets — never commit real credentials.",
            githubEnvironment = document.Azure.Environment,
            secrets = new[]
            {
                new { name = "AZURE_SUBSCRIPTION_ID", valueFrom = "azure.subscriptionId" },
                new { name = "AZURE_TENANT_ID", valueFrom = "azure.tenantId" },
                new { name = "AZURE_CLIENT_ID", valueFrom = "(OIDC federated app registration — set manually)" },
                new { name = "SMOKE_TEST_BASE_URL", valueFrom = "publicSite.baseUrl" },
            },
            variables = new[]
            {
                new { name = "ARCHLUCID_STACK_LOCATION", value = document.Azure.Location },
                new { name = "ARCHLUCID_STACK_RESOURCE_PREFIX", value = document.Naming.ResourcePrefix },
            },
        };

        return JsonSerializer.Serialize(payload, IndentedJsonOptions);
    }
}
