using System.Text;

namespace ArchLucid.Cli.Stack;

internal static partial class ArchlucidStackArtifactGenerator
{
    private static string BuildKeyVaultChecklistMarkdown(ArchlucidStackDocument document, string vaultName)
    {
        StringBuilder builder = new();
        builder.AppendLine("# Key Vault populate checklist (names only)");
        builder.AppendLine();
        builder.AppendLine($"Generated by `archlucid stack init` for environment **{document.Azure.Environment}**.");
        builder.AppendLine($"Vault: **{vaultName}** (`https://{vaultName}.vault.azure.net/`).");
        builder.AppendLine();
        builder.AppendLine("Populate each secret in Azure Key Vault. **Never** commit secret values to git.");
        builder.AppendLine();
        builder.AppendLine("| Secret name | Maps to appsettings |");
        builder.AppendLine("|-------------|---------------------|");

        foreach (string secretName in ArchlucidStackKeyVaultSecretNames.HostedPilotSecrets)
        {
            string mapping = MapSecretToAppsettings(secretName);
            builder.AppendLine($"| `{secretName}` | {mapping} |");
        }

        builder.AppendLine();
        builder.AppendLine("See `docs/library/CONFIGURATION_KEY_VAULT.md` and `ArchLucid.Api/appsettings.KeyVault.sample.json`.");

        return builder.ToString();
    }

    private static string MapSecretToAppsettings(string secretName)
    {
        return secretName switch
        {
            "archlucid-sql-connection-string" => "`ConnectionStrings:ArchLucid`",
            "archlucid-azure-openai-api-key" => "`AzureOpenAI:ApiKey`",
            "archlucid-fallback-llm-api-key" => "`ArchLucid:FallbackLlm:ApiKey`",
            "archlucid-api-admin-key" => "`Authentication:ApiKey:AdminKey`",
            "archlucid-api-readonly-key" => "`Authentication:ApiKey:ReadOnlyKey`",
            "archlucid-azuredevops-archlucid-api-key" => "`AzureDevOps:ArchLucidApiKey`",
            "archlucid-servicebus-connection-string" => "`IntegrationEvents:ServiceBusConnectionString`",
            "archlucid-webhook-hmac-secret" => "`WebhookDelivery:HmacSha256SharedSecret`",
            "archlucid-internal-cross-tenant-analytics-salt" => "`ArchLucid:InternalCrossTenantAnalytics:PseudonymizationSalt`",
            _ => "(see CONFIGURATION_REFERENCE.md)",
        };
    }
}
