import type { LeakageRewriteRule } from "./leakage-rewrite-table";

/**
 * Declarative contributor-leakage rewrite tables for help markdown.
 * Order matters: later rules see earlier replacements.
 */

export const PROCUREMENT_LEAKAGE_REWRITES = [
  { pattern: /Improvement archived\s*\*?\*?#?\d+\*?\*?/gi, replacement: "" },
  { pattern: /`?archlucid auth(?:\s+validate-saml)?`?/gi, replacement: "IdP federation validation" },
  { pattern: /`?V1_SCOPE\.md`?/gi, replacement: "product scope" },
  { pattern: /V1_SCOPE\.md/gi, replacement: "product scope" },
  { pattern: /`?CONFIGURATION_REFERENCE\.md`?/gi, replacement: "configuration documentation" },
  { pattern: /CONFIGURATION_REFERENCE\.md/gi, replacement: "configuration documentation" },
  { pattern: /`?SECURITY\.md`?/gi, replacement: "security documentation" },
  { pattern: /contributor-reference\/SECURITY\.md/gi, replacement: "security documentation" },
  { pattern: /`?PENDING_QUESTIONS\.md`?/gi, replacement: "owner diligence notes" },
  { pattern: /PENDING_QUESTIONS\.md/gi, replacement: "owner diligence notes" },
  { pattern: /infra\/terraform-entra\/?/gi, replacement: "hosted identity samples" },
  { pattern: /`infra\/`/gi, replacement: "hosted infrastructure" },
  { pattern: /\binfra\//gi, replacement: "hosted infrastructure " },
  { pattern: /ArtifactLargePayload:[A-Za-z0-9]+/g, replacement: "regional storage configuration" },
  { pattern: /TenantProvisioning:[A-Za-z0-9]+/g, replacement: "tenant provisioning configuration" },
  { pattern: /dbo\.Tenants(?:\.[A-Za-z0-9_]+)?/gi, replacement: "tenant residency settings" },
  { pattern: /ArchLucidAuth:[A-Za-z0-9]+/g, replacement: "authentication configuration" },
  { pattern: /Order Form Addendum [A-Z]/gi, replacement: "Order Form addendum" },
  { pattern: /MSA_TEMPLATE\.md/gi, replacement: "MSA template" },
  { pattern: /ORDER_FORM_TEMPLATE\.md/gi, replacement: "Order Form template" },
  { pattern: /CUSTOM_POLICY_PACK_AUTHORING_SOW_TEMPLATE\.md/gi, replacement: "SoW template" },
  { pattern: /PRICING_PHILOSOPHY\.md/gi, replacement: "pricing documentation" },
  { pattern: /SLA_SUMMARY\.md/gi, replacement: "SLA summary" },
  { pattern: /SLA_TARGETS\.md/gi, replacement: "SLA targets" },
] as const satisfies ReadonlyArray<LeakageRewriteRule>;

export const CAIQ_SIG_LEAKAGE_REWRITES = [
  { pattern: /\|\s*Response \(summary\)\s*\|/gi, replacement: "| Response |" },
  { pattern: /\|\s*Evidence in repo\s*\|/gi, replacement: "| Evidence |" },
  { pattern: /Evidence in repo/gi, replacement: "Evidence" },
  { pattern: /`?\.github\/[^`\s)]+`?/gi, replacement: "automated security testing in CI" },
  { pattern: /\.github\/[^\s)`]+/gi, replacement: "automated security testing in CI" },
  { pattern: /`?infra\/[^`\s)]*`?/gi, replacement: "hosted infrastructure" },
  { pattern: /\binfra\//gi, replacement: "hosted infrastructure " },
  { pattern: /`?SECURITY\.md`?/gi, replacement: "security documentation" },
  { pattern: /contributor-reference\/SECURITY\.md/gi, replacement: "security documentation" },
  { pattern: /`?PENDING_QUESTIONS\.md`?/gi, replacement: "owner diligence notes" },
  { pattern: /PENDING_QUESTIONS\.md/gi, replacement: "owner diligence notes" },
  { pattern: /`?pen-test-summaries\/[^`\s)]+`?/gi, replacement: "penetration test program documentation" },
  { pattern: /pen-test-summaries\/[^\s`)]+/gi, replacement: "penetration test program documentation" },
] as const satisfies ReadonlyArray<LeakageRewriteRule>;

export const DPA_TEMPLATE_LEAKAGE_REWRITES = [
  { pattern: /> \*\*Spine doc:\*\*[^\n]*\n?/gi, replacement: "" },
  { pattern: /`?START_HERE\.md`?/gi, replacement: "product documentation hub" },
  { pattern: /START_HERE\.md/gi, replacement: "product documentation hub" },
  { pattern: /`?SECURITY\.md`?/gi, replacement: "security documentation" },
  { pattern: /contributor-reference\/SECURITY\.md/gi, replacement: "security documentation" },
  { pattern: /`?\.\.\/security\/PII_RETENTION_CONVERSATIONS\.md`?/gi, replacement: "conversation retention documentation" },
  { pattern: /PII_RETENTION_CONVERSATIONS\.md/gi, replacement: "conversation retention documentation" },
  { pattern: /`?BUYER_SECURITY_PROCUREMENT_PACKET\.md[^`\s)]*`?/gi, replacement: "[Procurement FAQ](/help/procurement)" },
  { pattern: /BUYER_SECURITY_PROCUREMENT_PACKET\.md[^\s)`]*/gi, replacement: "/help/procurement" },
  { pattern: /\[trust-center\.md\]\(trust-center\.md\)/gi, replacement: "[Security and trust](/help/security-trust)" },
  { pattern: /trust-center\.md/gi, replacement: "/help/security-trust" },
  { pattern: /`?SUBPROCESSORS\.md`?/gi, replacement: "[Subprocessors](/help/subprocessors)" },
  { pattern: /SUBPROCESSORS\.md/gi, replacement: "/help/subprocessors" },
  { pattern: /`?INCIDENT_COMMUNICATIONS_POLICY\.md`?/gi, replacement: "incident communications policy" },
  { pattern: /INCIDENT_COMMUNICATIONS_POLICY\.md/gi, replacement: "incident communications policy" },
  { pattern: /`?ASSURANCE_STATUS_CANONICAL\.md[^`\s)]*`?/gi, replacement: "assurance status documentation" },
  { pattern: /ASSURANCE_STATUS_CANONICAL\.md[^\s)`]*/gi, replacement: "assurance status documentation" },
  { pattern: /`?docs\/go-to-market\/CROSS_TENANT_DATA_PROCESSING_ADDENDUM\.md`?/gi, replacement: "cross-tenant processing addendum" },
  { pattern: /CROSS_TENANT_DATA_PROCESSING_ADDENDUM\.md/gi, replacement: "cross-tenant processing addendum" },
  { pattern: /`?\.\.\/architecture\/adrs\/0031[^`\s)]*`?/gi, replacement: "cross-tenant pattern library architecture decision" },
  { pattern: /ADR 0031/gi, replacement: "cross-tenant pattern library architecture decision" },
  { pattern: /architecture runs/gi, replacement: "architecture reviews" },
] as const satisfies ReadonlyArray<LeakageRewriteRule>;

export const DEVELOPER_TROUBLESHOOTING_LEAKAGE_REWRITES = [
  { pattern: /\[([^\]]*)\]\(\.\.\/library\/CONFIGURATION_REFERENCE\.md\)/gi, replacement: "[Configuration reference](/help/configuration-reference)" },
  { pattern: /\[([^\]]*)\]\(CONFIGURATION_REFERENCE\.md\)/gi, replacement: "[Configuration reference](/help/configuration-reference)" },
  { pattern: /\[([^\]]*)\]\(\.\.\/library\/CLI_USAGE\.md\)/gi, replacement: "[CLI usage](/help/cli-usage)" },
  { pattern: /\[([^\]]*)\]\(CLI_USAGE\.md\)/gi, replacement: "[CLI usage](/help/cli-usage)" },
  { pattern: /\[([^\]]*)\]\([^)]*contributor-reference\/[^)]+\)/gi, replacement: "$1" },
  { pattern: /\[([^\]]*)\]\(\.\.\/architecture\/adrs\/[^)]+\)/gi, replacement: "$1" },
  { pattern: /\[([^\]]*)\]\([^)]*architecture\/adrs\/[^)]+\)/gi, replacement: "$1" },
  { pattern: /\[([^\]]*)\]\(\.\.\/library\/V1_SCOPE\.md[^)]*\)/gi, replacement: "product scope" },
  { pattern: /\[([^\]]*)\]\(V1_SCOPE\.md[^)]*\)/gi, replacement: "product scope" },
  { pattern: /\[([^\]]*)\]\(\.\.\/go-to-market\/[^)]+\)/gi, replacement: "$1" },
  { pattern: /\bTB-\d+\b/gi, replacement: "" },
  { pattern: /\s*\(TB-\d+\)/gi, replacement: "" },
] as const satisfies ReadonlyArray<LeakageRewriteRule>;

export const PATH_CHOOSER_LEAKAGE_REWRITES = [
  { pattern: /> \*\*Start operators here:\*\*[^\n]*\n?/gi, replacement: "" },
  { pattern: /\*\*Start operators here:\*\*[^\n]*\n?/gi, replacement: "" },
  { pattern: /`?FIRST_PILOT_OPERATOR_PATH\.md`?/gi, replacement: "[Your first architecture review](/help/first-architecture-review)" },
  { pattern: /FIRST_PILOT_OPERATOR_PATH\.md/gi, replacement: "/help/first-architecture-review" },
  { pattern: /`?FIRST_EVALUATOR_DECISION\.md`?/gi, replacement: "[Your first architecture review](/help/first-architecture-review)" },
  { pattern: /FIRST_EVALUATOR_DECISION\.md/gi, replacement: "/help/first-architecture-review" },
  { pattern: /`?CORE_PILOT\.md`?/gi, replacement: "[Your first architecture review](/help/first-architecture-review)" },
  { pattern: /CORE_PILOT\.md/gi, replacement: "/help/first-architecture-review" },
  { pattern: /`?EXECUTIVE_SPONSOR_BRIEF\.md`?/gi, replacement: "[Executive summary](/help/executive-summary)" },
  { pattern: /EXECUTIVE_SPONSOR_BRIEF\.md/gi, replacement: "/help/executive-summary" },
  { pattern: /`?DIFFERENTIATION_PROOF_PACKET\.md`?/gi, replacement: "differentiation proof documentation" },
  { pattern: /DIFFERENTIATION_PROOF_PACKET\.md/gi, replacement: "differentiation proof documentation" },
  { pattern: /`first-pilot-command-center\.md`/gi, replacement: "pilot command center summary" },
  { pattern: /`go-no-go-summary\.md`/gi, replacement: "go/no-go summary" },
  { pattern: /`quote-to-proof-packet\.md`/gi, replacement: "quote-to-proof summary" },
  { pattern: /`commercial-closeout\.md`/gi, replacement: "commercial closeout summary" },
  { pattern: /`?FIRST_PILOT_EVIDENCE_BUNDLE\.md`?/gi, replacement: "first-pilot evidence bundle guide" },
  { pattern: /FIRST_PILOT_EVIDENCE_BUNDLE\.md/gi, replacement: "first-pilot evidence bundle guide" },
  { pattern: /artifacts\/first-pilot-proof\/?/gi, replacement: "proof working folder" },
  { pattern: /artifacts\/[^\s`|)]+/gi, replacement: "proof output folder" },
  { pattern: /`?V1_DEFERRED\.md`?/gi, replacement: "deferred capability documentation" },
  { pattern: /V1_DEFERRED\.md/gi, replacement: "deferred capability documentation" },
  { pattern: /`?PROCUREMENT_PACK_INDEX\.md[^`\s)]*`?/gi, replacement: "[Procurement FAQ](/help/procurement)" },
  { pattern: /PROCUREMENT_PACK_INDEX\.md[^\s)`]*/gi, replacement: "/help/procurement" },
  { pattern: /`?BUYER_SECURITY_PROCUREMENT_PACKET\.md[^`\s)]*`?/gi, replacement: "[Procurement FAQ](/help/procurement)" },
  { pattern: /BUYER_SECURITY_PROCUREMENT_PACKET\.md[^\s)`]*/gi, replacement: "/help/procurement" },
  { pattern: /`?AI_READINESS_POSTURE\.md[^`\s)]*`?/gi, replacement: "[Security and trust](/help/security-trust)" },
  { pattern: /AI_READINESS_POSTURE\.md[^\s)`]*/gi, replacement: "/help/security-trust" },
  { pattern: /\[trust-center\.md\]\(trust-center\.md\)/gi, replacement: "[Security and trust](/help/security-trust)" },
  { pattern: /trust-center\.md/gi, replacement: "/help/security-trust" },
  { pattern: /`?CLAIM_READINESS_STATUS\.md[^`\s)]*`?/gi, replacement: "claim readiness documentation" },
  { pattern: /CLAIM_READINESS_STATUS\.md[^\s)`]*/gi, replacement: "claim readiness documentation" },
  { pattern: /`?GTM_BACKLOG\.md`?/gi, replacement: "go-to-market planning documentation" },
  { pattern: /GTM_BACKLOG\.md/gi, replacement: "go-to-market planning documentation" },
  { pattern: /`?PRODUCT_PACKAGING\.md`?/gi, replacement: "product packaging guide" },
  { pattern: /PRODUCT_PACKAGING\.md/gi, replacement: "product packaging guide" },
  { pattern: /`?QUOTE_TO_PROOF_PACKET\.md[^`\s)]*`?/gi, replacement: "quote-to-proof documentation" },
  { pattern: /QUOTE_TO_PROOF_PACKET\.md[^\s)`]*/gi, replacement: "quote-to-proof documentation" },
  { pattern: /`?docs\/library\/[^`\s)]+`?/gi, replacement: "product documentation" },
  { pattern: /`?docs\/go-to-market\/[^`\s)]+`?/gi, replacement: "go-to-market documentation" },
] as const satisfies ReadonlyArray<LeakageRewriteRule>;
