namespace ArchLucid.Core.Requests;

/// <summary>
///     Standalone token matching for free-text architecture constraints and capabilities.
/// </summary>
internal static class RequestConstraintTokenMatcher
{
    internal static bool ContainsAffirmativePhrase(string? haystack, string phrase)
    {
        haystack = NormalizeNegationText(haystack);

        if (string.IsNullOrWhiteSpace(haystack) || string.IsNullOrWhiteSpace(phrase))
            return false;

        int index = 0;

        while (index < haystack.Length)
        {
            index = haystack.IndexOf(phrase, index, StringComparison.OrdinalIgnoreCase);

            if (index < 0)
                return false;

            if (!IsNegatedPhrasePrefix(haystack, index)
                && !IsNegatedPhraseSuffix(haystack, index, phrase.Length))
                return true;

            index++;
        }

        return false;
    }

    internal static bool ContainsStandaloneWordToken(string? haystack, string token)
    {
        haystack = NormalizeNegationText(haystack);

        if (string.IsNullOrWhiteSpace(haystack) || string.IsNullOrWhiteSpace(token))
            return false;

        int index = 0;

        while (index < haystack.Length)
        {
            index = haystack.IndexOf(token, index, StringComparison.OrdinalIgnoreCase);

            if (index < 0)
                return false;

            if (IsStandaloneWordToken(haystack, index, token.Length)
                && !IsNegatedPhrasePrefix(haystack, index)
                && !IsNegatedPhraseSuffix(haystack, index, token.Length))
                return true;

            index++;
        }

        return false;
    }

    internal static bool ContainsAffirmativePrivateWord(string? haystack)
    {
        haystack = NormalizeNegationText(haystack);

        if (string.IsNullOrWhiteSpace(haystack))
            return false;

        int index = 0;

        while (index < haystack.Length)
        {
            index = haystack.IndexOf("private", index, StringComparison.OrdinalIgnoreCase);

            if (index < 0)
                return false;

            if (IsStandaloneWordToken(haystack, index, "private".Length)
                && !IsNegatedPhrasePrefix(haystack, index)
                && !IsNegatedPhraseSuffix(haystack, index, "private".Length))
                return true;

            index++;
        }

        return false;
    }

    private static bool IsStandaloneWordToken(string haystack, int tokenIndex, int tokenLength)
    {
        bool okBefore = tokenIndex == 0 || !char.IsLetter(haystack[tokenIndex - 1]);

        int afterToken = tokenIndex + tokenLength;

        bool okAfter = afterToken >= haystack.Length || !char.IsLetter(haystack[afterToken]);

        return okBefore && okAfter;
    }

    private static bool IsNegatedPhrasePrefix(string haystack, int tokenIndex)
    {
        if (IsNonPrefixedNegation(haystack, tokenIndex))
            return true;

        if (IsNoPrefixedNegation(haystack, tokenIndex))
            return true;

        if (IsNotPrefixedNegation(haystack, tokenIndex))
            return true;

        if (IsWithoutPrefixedNegation(haystack, tokenIndex))
            return true;

        if (IsAdviceStyleNegation(haystack, tokenIndex))
            return true;

        ReadOnlySpan<char> before = haystack.AsSpan(0, tokenIndex).TrimEnd();

        if (before.Length < 2)
            return false;

        return before.EndsWith("un", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("un-", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("un_", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("un.", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("un ", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsNoPrefixedNegation(string haystack, int tokenIndex)
    {
        ReadOnlySpan<char> before = haystack.AsSpan(0, tokenIndex).TrimEnd();

        if (before.Length < 2)
            return false;

        return before.EndsWith("no", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("no-", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("no_", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("no.", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("no ", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsNotPrefixedNegation(string haystack, int tokenIndex)
    {
        ReadOnlySpan<char> before = haystack.AsSpan(0, tokenIndex).TrimEnd();

        if (before.Length < 3)
            return false;

        return before.EndsWith("not", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("not-", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("not_", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("not.", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("not ", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsAdviceStyleNegation(string haystack, int tokenIndex)
    {
        ReadOnlySpan<char> before = haystack.AsSpan(0, tokenIndex).TrimEnd();

        if (before.Length < 4)
            return false;

        if (before.StartsWith("not required to", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("is not required to", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("no requirement to", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("no need to", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("doesn't require", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("doesn't need to", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("won't need to", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("do not", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("do-not", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("don't", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("doesn't", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shouldn't", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("won't", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("must not", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("should not need", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("should not require", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("should not mandate", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("should not enforce", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("should not configure", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("should not apply", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("should not provision", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("should not ensure", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("should not maintain", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("should not enable", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("should not deploy", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("should not adopt", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("should not use", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("should not have", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("should not implement", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("ought not need", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("ought not require", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("ought not mandate", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("ought not enforce", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("ought not configure", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("ought not apply", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("ought not provision", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("ought not ensure", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("ought not maintain", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("ought not enable", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("ought not deploy", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("ought not adopt", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("ought not use", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("ought not have", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("ought not implement", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shall not need", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shall not require", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shall not mandate", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shall not enforce", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shall not configure", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shall not apply", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shall not provision", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shall not ensure", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shall not maintain", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shall not enable", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shall not deploy", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shall not adopt", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shall not use", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shall not have", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shall not implement", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("will not need", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("will not require", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("will not mandate", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("will not enforce", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("will not configure", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("will not apply", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("will not provision", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("will not ensure", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("will not maintain", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("will not enable", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("will not deploy", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("will not adopt", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("will not use", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("will not have", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("will not implement", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("would not need", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("would not require", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("would not mandate", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("would not enforce", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("would not configure", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("would not apply", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("would not provision", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("would not ensure", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("would not maintain", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("would not enable", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("would not deploy", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("would not adopt", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("would not use", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("would not have", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("would not implement", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("never", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("avoid", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("avoids", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("cannot use", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("can't use", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("cannot require", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("cannot", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("can't have", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("can't adopt", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("can't deploy", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("couldn't have", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("couldn't use", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("couldn't adopt", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("couldn't deploy", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("couldn't", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("mustn't have", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("mustn't use", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("mustn't adopt", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("mustn't deploy", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("mustn't enable", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("mustn't implement", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("mustn't", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("needn't have", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("needn't use", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("needn't adopt", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("needn't deploy", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("needn't enable", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("needn't implement", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("needn't", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("mightn't have", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("mightn't use", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("mightn't adopt", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("mightn't deploy", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("mightn't", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shan't have", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shan't use", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shan't adopt", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shan't deploy", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("shan't", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("ain't have", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("ain't use", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("ain't adopt", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("ain't deploy", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("ain't", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("daren't have", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("daren't use", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("daren't adopt", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("daren't deploy", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("daren't", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("mayn't have", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("mayn't use", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("mayn't", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("oughtn't have", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("oughtn't use", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("oughtn't", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("didn't have", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("didn't use", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("didn't", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("wasn't have", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("wasn't use", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("wasn't", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("can't", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("need not enable", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("need not use", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("need not have", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("need not adopt", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("need not deploy", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("need not mandate", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("need not enforce", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("need not configure", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("need not apply", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("need not provision", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("need not require", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("need not implement", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("need not maintain", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("is not needed for", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("is not necessary for", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("does not require", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("does not need", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("does not mandate", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("does not enforce", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("does not configure", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("does not apply", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("does not provision", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("does not ensure", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("does not maintain", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("does not enable", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("does not deploy", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("does not adopt", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("does not use", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("does not have", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("does not implement", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("need not ensure", StringComparison.OrdinalIgnoreCase)
            || before.StartsWith("need not need", StringComparison.OrdinalIgnoreCase))
            return true;

        if (ContainsMidSentenceNegation(before))
            return true;

        return before.EndsWith("don't", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("doesn't", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("shouldn't", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("won't", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("cannot", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("cannot require", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("doesn't require", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("doesn't need", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("never", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("avoids", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("avoid", StringComparison.OrdinalIgnoreCase);
    }

    private static bool ContainsMidSentenceNegation(ReadOnlySpan<char> before)
    {
        return ContainsPhrase(before, " do not require ")
            || ContainsPhrase(before, " is not required to ")
            || ContainsPhrase(before, " is not required to")
            || ContainsPhrase(before, " is not needed to ")
            || ContainsPhrase(before, " is not needed to")
            || ContainsPhrase(before, " no requirement to ")
            || ContainsPhrase(before, " no requirement to")
            || ContainsPhrase(before, " not required to ")
            || ContainsPhrase(before, " not required to")
            || ContainsPhrase(before, " is not necessary for ")
            || ContainsPhrase(before, " is not necessary for")
            || ContainsPhrase(before, " no need to ")
            || ContainsPhrase(before, " no need to")
            || ContainsPhrase(before, " is not needed for ")
            || ContainsPhrase(before, " is not needed for")
            || ContainsPhrase(before, " no need for ")
            || ContainsPhrase(before, " no need for")
            || ContainsPhrase(before, " not needed to ")
            || ContainsPhrase(before, " not needed to")
            || ContainsPhrase(before, " should not require ")
            || ContainsPhrase(before, " should not require")
            || ContainsPhrase(before, " should not need ")
            || ContainsPhrase(before, " should not need")
            || ContainsPhrase(before, " shall not require ")
            || ContainsPhrase(before, " shall not require")
            || ContainsPhrase(before, " shall not need ")
            || ContainsPhrase(before, " shall not need")
            || ContainsPhrase(before, " will not require ")
            || ContainsPhrase(before, " will not require")
            || ContainsPhrase(before, " would not require ")
            || ContainsPhrase(before, " would not require")
            || ContainsPhrase(before, " will not need ")
            || ContainsPhrase(before, " will not need")
            || ContainsPhrase(before, " would not need ")
            || ContainsPhrase(before, " would not need")
            || ContainsPhrase(before, " will not mandate ")
            || ContainsPhrase(before, " will not mandate")
            || ContainsPhrase(before, " would not mandate ")
            || ContainsPhrase(before, " would not mandate")
            || ContainsPhrase(before, " shall not mandate ")
            || ContainsPhrase(before, " shall not mandate")
            || ContainsPhrase(before, " should not mandate ")
            || ContainsPhrase(before, " should not mandate")
            || ContainsPhrase(before, " ought not mandate ")
            || ContainsPhrase(before, " ought not mandate")
            || ContainsPhrase(before, " ought not require ")
            || ContainsPhrase(before, " ought not require")
            || ContainsPhrase(before, " ought not need ")
            || ContainsPhrase(before, " ought not need")
            || ContainsPhrase(before, " will not enforce ")
            || ContainsPhrase(before, " will not enforce")
            || ContainsPhrase(before, " would not enforce ")
            || ContainsPhrase(before, " would not enforce")
            || ContainsPhrase(before, " shall not enforce ")
            || ContainsPhrase(before, " shall not enforce")
            || ContainsPhrase(before, " will not configure ")
            || ContainsPhrase(before, " will not configure")
            || ContainsPhrase(before, " would not configure ")
            || ContainsPhrase(before, " would not configure")
            || ContainsPhrase(before, " shall not configure ")
            || ContainsPhrase(before, " shall not configure")
            || ContainsPhrase(before, " cannot mandate ")
            || ContainsPhrase(before, " cannot mandate")
            || ContainsPhrase(before, " should not enforce ")
            || ContainsPhrase(before, " should not enforce")
            || ContainsPhrase(before, " ought not enforce ")
            || ContainsPhrase(before, " ought not enforce")
            || ContainsPhrase(before, " cannot enforce ")
            || ContainsPhrase(before, " cannot enforce")
            || ContainsPhrase(before, " will not apply ")
            || ContainsPhrase(before, " will not apply")
            || ContainsPhrase(before, " would not apply ")
            || ContainsPhrase(before, " would not apply")
            || ContainsPhrase(before, " shall not apply ")
            || ContainsPhrase(before, " shall not apply")
            || ContainsPhrase(before, " should not configure ")
            || ContainsPhrase(before, " should not configure")
            || ContainsPhrase(before, " ought not configure ")
            || ContainsPhrase(before, " ought not configure")
            || ContainsPhrase(before, " cannot apply ")
            || ContainsPhrase(before, " cannot apply")
            || ContainsPhrase(before, " should not apply ")
            || ContainsPhrase(before, " should not apply")
            || ContainsPhrase(before, " ought not apply ")
            || ContainsPhrase(before, " ought not apply")
            || ContainsPhrase(before, " cannot configure ")
            || ContainsPhrase(before, " cannot configure")
            || ContainsPhrase(before, " will not provision ")
            || ContainsPhrase(before, " will not provision")
            || ContainsPhrase(before, " would not provision ")
            || ContainsPhrase(before, " would not provision")
            || ContainsPhrase(before, " shall not provision ")
            || ContainsPhrase(before, " shall not provision")
            || ContainsPhrase(before, " cannot provision ")
            || ContainsPhrase(before, " cannot provision")
            || ContainsPhrase(before, " should not provision ")
            || ContainsPhrase(before, " should not provision")
            || ContainsPhrase(before, " ought not provision ")
            || ContainsPhrase(before, " ought not provision")
            || ContainsPhrase(before, " will not maintain ")
            || ContainsPhrase(before, " will not maintain")
            || ContainsPhrase(before, " would not maintain ")
            || ContainsPhrase(before, " would not maintain")
            || ContainsPhrase(before, " shall not maintain ")
            || ContainsPhrase(before, " shall not maintain")
            || ContainsPhrase(before, " cannot maintain ")
            || ContainsPhrase(before, " cannot maintain")
            || ContainsPhrase(before, " should not maintain ")
            || ContainsPhrase(before, " should not maintain")
            || ContainsPhrase(before, " ought not maintain ")
            || ContainsPhrase(before, " ought not maintain")
            || ContainsPhrase(before, " will not ensure ")
            || ContainsPhrase(before, " will not ensure")
            || ContainsPhrase(before, " would not ensure ")
            || ContainsPhrase(before, " would not ensure")
            || ContainsPhrase(before, " shall not ensure ")
            || ContainsPhrase(before, " shall not ensure")
            || ContainsPhrase(before, " cannot ensure ")
            || ContainsPhrase(before, " cannot ensure")
            || ContainsPhrase(before, " should not ensure ")
            || ContainsPhrase(before, " should not ensure")
            || ContainsPhrase(before, " ought not ensure ")
            || ContainsPhrase(before, " ought not ensure")
            || ContainsPhrase(before, " ought not implement ")
            || ContainsPhrase(before, " ought not implement")
            || ContainsPhrase(before, " ought not enable ")
            || ContainsPhrase(before, " ought not enable")
            || ContainsPhrase(before, " ought not deploy ")
            || ContainsPhrase(before, " ought not deploy")
            || ContainsPhrase(before, " ought not adopt ")
            || ContainsPhrase(before, " ought not adopt")
            || ContainsPhrase(before, " ought not use ")
            || ContainsPhrase(before, " ought not use")
            || ContainsPhrase(before, " ought not have ")
            || ContainsPhrase(before, " ought not have")
            || ContainsPhrase(before, " should not implement ")
            || ContainsPhrase(before, " should not implement")
            || ContainsPhrase(before, " should not enable ")
            || ContainsPhrase(before, " should not enable")
            || ContainsPhrase(before, " should not deploy ")
            || ContainsPhrase(before, " should not deploy")
            || ContainsPhrase(before, " should not adopt ")
            || ContainsPhrase(before, " should not adopt")
            || ContainsPhrase(before, " should not use ")
            || ContainsPhrase(before, " should not use")
            || ContainsPhrase(before, " should not have ")
            || ContainsPhrase(before, " should not have")
            || ContainsPhrase(before, " need not apply ")
            || ContainsPhrase(before, " need not apply")
            || ContainsPhrase(before, " need not provision ")
            || ContainsPhrase(before, " need not provision")
            || ContainsPhrase(before, " need not configure ")
            || ContainsPhrase(before, " need not configure")
            || ContainsPhrase(before, " need not enforce ")
            || ContainsPhrase(before, " need not enforce")
            || ContainsPhrase(before, " need not maintain ")
            || ContainsPhrase(before, " need not maintain")
            || ContainsPhrase(before, " need not mandate ")
            || ContainsPhrase(before, " need not mandate")
            || ContainsPhrase(before, " need not ensure ")
            || ContainsPhrase(before, " need not ensure")
            || ContainsPhrase(before, " need not require ")
            || ContainsPhrase(before, " need not require")
            || ContainsPhrase(before, " need not deploy ")
            || ContainsPhrase(before, " need not deploy")
            || ContainsPhrase(before, " need not adopt ")
            || ContainsPhrase(before, " need not adopt")
            || ContainsPhrase(before, " need not implement ")
            || ContainsPhrase(before, " need not implement")
            || ContainsPhrase(before, " need not enable ")
            || ContainsPhrase(before, " need not enable")
            || ContainsPhrase(before, " need not use ")
            || ContainsPhrase(before, " need not use")
            || ContainsPhrase(before, " need not have ")
            || ContainsPhrase(before, " need not have")
            || ContainsPhrase(before, " need not need ")
            || ContainsPhrase(before, " need not need")
            || ContainsPhrase(before, " shouldn't require ")
            || ContainsPhrase(before, " shouldn't require")
            || ContainsPhrase(before, " won't require ")
            || ContainsPhrase(before, " won't require")
            || ContainsPhrase(before, " shouldn't need ")
            || ContainsPhrase(before, " shouldn't need")
            || ContainsPhrase(before, " won't need ")
            || ContainsPhrase(before, " won't need")
            || ContainsPhrase(before, " shouldn't enforce ")
            || ContainsPhrase(before, " shouldn't enforce")
            || ContainsPhrase(before, " won't enforce ")
            || ContainsPhrase(before, " won't enforce")
            || ContainsPhrase(before, " shouldn't apply ")
            || ContainsPhrase(before, " shouldn't apply")
            || ContainsPhrase(before, " won't apply ")
            || ContainsPhrase(before, " won't apply")
            || ContainsPhrase(before, " shouldn't configure ")
            || ContainsPhrase(before, " shouldn't configure")
            || ContainsPhrase(before, " won't configure ")
            || ContainsPhrase(before, " won't configure")
            || ContainsPhrase(before, " shouldn't mandate ")
            || ContainsPhrase(before, " shouldn't mandate")
            || ContainsPhrase(before, " won't mandate ")
            || ContainsPhrase(before, " won't mandate")
            || ContainsPhrase(before, " shouldn't maintain ")
            || ContainsPhrase(before, " shouldn't maintain")
            || ContainsPhrase(before, " won't maintain ")
            || ContainsPhrase(before, " won't maintain")
            || ContainsPhrase(before, " shouldn't ensure ")
            || ContainsPhrase(before, " shouldn't ensure")
            || ContainsPhrase(before, " won't ensure ")
            || ContainsPhrase(before, " won't ensure")
            || ContainsPhrase(before, " shouldn't provision ")
            || ContainsPhrase(before, " shouldn't provision")
            || ContainsPhrase(before, " won't provision ")
            || ContainsPhrase(before, " won't provision")
            || ContainsPhrase(before, " shouldn't deploy ")
            || ContainsPhrase(before, " shouldn't deploy")
            || ContainsPhrase(before, " won't deploy ")
            || ContainsPhrase(before, " won't deploy")
            || ContainsPhrase(before, " shouldn't adopt ")
            || ContainsPhrase(before, " shouldn't adopt")
            || ContainsPhrase(before, " won't adopt ")
            || ContainsPhrase(before, " won't adopt")
            || ContainsPhrase(before, " shouldn't implement ")
            || ContainsPhrase(before, " shouldn't implement")
            || ContainsPhrase(before, " won't implement ")
            || ContainsPhrase(before, " won't implement")
            || ContainsPhrase(before, " shouldn't enable ")
            || ContainsPhrase(before, " shouldn't enable")
            || ContainsPhrase(before, " won't enable ")
            || ContainsPhrase(before, " won't enable")
            || ContainsPhrase(before, " shouldn't use ")
            || ContainsPhrase(before, " shouldn't use")
            || ContainsPhrase(before, " won't use ")
            || ContainsPhrase(before, " won't use")
            || ContainsPhrase(before, " shouldn't have ")
            || ContainsPhrase(before, " shouldn't have")
            || ContainsPhrase(before, " won't have ")
            || ContainsPhrase(before, " won't have")
            || ContainsPhrase(before, " doesn't implement ")
            || ContainsPhrase(before, " doesn't implement")
            || ContainsPhrase(before, " don't enable ")
            || ContainsPhrase(before, " don't enable")
            || ContainsPhrase(before, " don't implement ")
            || ContainsPhrase(before, " don't implement")
            || ContainsPhrase(before, " don't deploy ")
            || ContainsPhrase(before, " don't deploy")
            || ContainsPhrase(before, " don't adopt ")
            || ContainsPhrase(before, " don't adopt")
            || ContainsPhrase(before, " don't use ")
            || ContainsPhrase(before, " don't use")
            || ContainsPhrase(before, " don't require ")
            || ContainsPhrase(before, " don't require")
            || ContainsPhrase(before, " don't need ")
            || ContainsPhrase(before, " don't need")
            || ContainsPhrase(before, " don't have ")
            || ContainsPhrase(before, " don't have")
            || ContainsPhrase(before, " don't configure ")
            || ContainsPhrase(before, " don't configure")
            || ContainsPhrase(before, " don't mandate ")
            || ContainsPhrase(before, " don't mandate")
            || ContainsPhrase(before, " don't apply ")
            || ContainsPhrase(before, " don't apply")
            || ContainsPhrase(before, " don't enforce ")
            || ContainsPhrase(before, " don't enforce")
            || ContainsPhrase(before, " don't maintain ")
            || ContainsPhrase(before, " don't maintain")
            || ContainsPhrase(before, " don't ensure ")
            || ContainsPhrase(before, " don't ensure")
            || ContainsPhrase(before, " don't provision ")
            || ContainsPhrase(before, " don't provision")
            || ContainsPhrase(before, " doesn't enable ")
            || ContainsPhrase(before, " doesn't enable")
            || ContainsPhrase(before, " doesn't deploy ")
            || ContainsPhrase(before, " doesn't deploy")
            || ContainsPhrase(before, " doesn't adopt ")
            || ContainsPhrase(before, " doesn't adopt")
            || ContainsPhrase(before, " doesn't apply ")
            || ContainsPhrase(before, " doesn't apply")
            || ContainsPhrase(before, " doesn't configure ")
            || ContainsPhrase(before, " doesn't configure")
            || ContainsPhrase(before, " doesn't mandate ")
            || ContainsPhrase(before, " doesn't mandate")
            || ContainsPhrase(before, " doesn't maintain ")
            || ContainsPhrase(before, " doesn't maintain")
            || ContainsPhrase(before, " doesn't enforce ")
            || ContainsPhrase(before, " doesn't enforce")
            || ContainsPhrase(before, " doesn't ensure ")
            || ContainsPhrase(before, " doesn't ensure")
            || ContainsPhrase(before, " doesn't provision ")
            || ContainsPhrase(before, " doesn't provision")
            || ContainsPhrase(before, " doesn't use ")
            || ContainsPhrase(before, " doesn't use")
            || ContainsPhrase(before, " doesn't have ")
            || ContainsPhrase(before, " doesn't have")
            || ContainsPhrase(before, " cannot implement ")
            || ContainsPhrase(before, " cannot implement")
            || ContainsPhrase(before, " cannot enable ")
            || ContainsPhrase(before, " cannot enable")
            || ContainsPhrase(before, " cannot use ")
            || ContainsPhrase(before, " cannot use")
            || ContainsPhrase(before, " cannot deploy ")
            || ContainsPhrase(before, " cannot deploy")
            || ContainsPhrase(before, " cannot adopt ")
            || ContainsPhrase(before, " cannot adopt")
            || ContainsPhrase(before, " cannot have ")
            || ContainsPhrase(before, " cannot have")
            || ContainsPhrase(before, " can't have ")
            || ContainsPhrase(before, " can't have")
            || ContainsPhrase(before, " can't use ")
            || ContainsPhrase(before, " can't use")
            || ContainsPhrase(before, " can't adopt ")
            || ContainsPhrase(before, " can't adopt")
            || ContainsPhrase(before, " can't deploy ")
            || ContainsPhrase(before, " can't deploy")
            || ContainsPhrase(before, " couldn't have ")
            || ContainsPhrase(before, " couldn't have")
            || ContainsPhrase(before, " couldn't use ")
            || ContainsPhrase(before, " couldn't use")
            || ContainsPhrase(before, " couldn't adopt ")
            || ContainsPhrase(before, " couldn't adopt")
            || ContainsPhrase(before, " couldn't deploy ")
            || ContainsPhrase(before, " couldn't deploy")
            || ContainsPhrase(before, " couldn't enable ")
            || ContainsPhrase(before, " couldn't enable")
            || ContainsPhrase(before, " couldn't implement ")
            || ContainsPhrase(before, " couldn't implement")
            || ContainsPhrase(before, " mustn't have ")
            || ContainsPhrase(before, " mustn't have")
            || ContainsPhrase(before, " mustn't use ")
            || ContainsPhrase(before, " mustn't use")
            || ContainsPhrase(before, " mustn't adopt ")
            || ContainsPhrase(before, " mustn't adopt")
            || ContainsPhrase(before, " mustn't deploy ")
            || ContainsPhrase(before, " mustn't deploy")
            || ContainsPhrase(before, " mustn't enable ")
            || ContainsPhrase(before, " mustn't enable")
            || ContainsPhrase(before, " mustn't implement ")
            || ContainsPhrase(before, " mustn't implement")
            || ContainsPhrase(before, " needn't have ")
            || ContainsPhrase(before, " needn't have")
            || ContainsPhrase(before, " needn't use ")
            || ContainsPhrase(before, " needn't use")
            || ContainsPhrase(before, " needn't adopt ")
            || ContainsPhrase(before, " needn't adopt")
            || ContainsPhrase(before, " needn't deploy ")
            || ContainsPhrase(before, " needn't deploy")
            || ContainsPhrase(before, " needn't enable ")
            || ContainsPhrase(before, " needn't enable")
            || ContainsPhrase(before, " needn't implement ")
            || ContainsPhrase(before, " needn't implement")
            || ContainsPhrase(before, " mightn't have ")
            || ContainsPhrase(before, " mightn't have")
            || ContainsPhrase(before, " mightn't use ")
            || ContainsPhrase(before, " mightn't use")
            || ContainsPhrase(before, " mightn't adopt ")
            || ContainsPhrase(before, " mightn't adopt")
            || ContainsPhrase(before, " mightn't deploy ")
            || ContainsPhrase(before, " mightn't deploy")
            || ContainsPhrase(before, " mightn't enable ")
            || ContainsPhrase(before, " mightn't enable")
            || ContainsPhrase(before, " mightn't implement ")
            || ContainsPhrase(before, " mightn't implement")
            || ContainsPhrase(before, " shan't have ")
            || ContainsPhrase(before, " shan't have")
            || ContainsPhrase(before, " shan't use ")
            || ContainsPhrase(before, " shan't use")
            || ContainsPhrase(before, " shan't adopt ")
            || ContainsPhrase(before, " shan't adopt")
            || ContainsPhrase(before, " shan't deploy ")
            || ContainsPhrase(before, " shan't deploy")
            || ContainsPhrase(before, " shan't enable ")
            || ContainsPhrase(before, " shan't enable")
            || ContainsPhrase(before, " shan't implement ")
            || ContainsPhrase(before, " shan't implement")
            || ContainsPhrase(before, " ain't have ")
            || ContainsPhrase(before, " ain't have")
            || ContainsPhrase(before, " ain't use ")
            || ContainsPhrase(before, " ain't use")
            || ContainsPhrase(before, " ain't adopt ")
            || ContainsPhrase(before, " ain't adopt")
            || ContainsPhrase(before, " ain't deploy ")
            || ContainsPhrase(before, " ain't deploy")
            || ContainsPhrase(before, " ain't enable ")
            || ContainsPhrase(before, " ain't enable")
            || ContainsPhrase(before, " ain't implement ")
            || ContainsPhrase(before, " ain't implement")
            || ContainsPhrase(before, " daren't have ")
            || ContainsPhrase(before, " daren't have")
            || ContainsPhrase(before, " daren't use ")
            || ContainsPhrase(before, " daren't use")
            || ContainsPhrase(before, " daren't adopt ")
            || ContainsPhrase(before, " daren't adopt")
            || ContainsPhrase(before, " daren't deploy ")
            || ContainsPhrase(before, " daren't deploy")
            || ContainsPhrase(before, " daren't enable ")
            || ContainsPhrase(before, " daren't enable")
            || ContainsPhrase(before, " daren't implement ")
            || ContainsPhrase(before, " daren't implement")
            || ContainsPhrase(before, " mayn't have ")
            || ContainsPhrase(before, " mayn't have")
            || ContainsPhrase(before, " mayn't use ")
            || ContainsPhrase(before, " mayn't use")
            || ContainsPhrase(before, " mayn't enable ")
            || ContainsPhrase(before, " mayn't enable")
            || ContainsPhrase(before, " mayn't implement ")
            || ContainsPhrase(before, " mayn't implement")
            || ContainsPhrase(before, " mayn't adopt ")
            || ContainsPhrase(before, " mayn't adopt")
            || ContainsPhrase(before, " mayn't deploy ")
            || ContainsPhrase(before, " mayn't deploy")
            || ContainsPhrase(before, " oughtn't have ")
            || ContainsPhrase(before, " oughtn't have")
            || ContainsPhrase(before, " oughtn't use ")
            || ContainsPhrase(before, " oughtn't use")
            || ContainsPhrase(before, " oughtn't enable ")
            || ContainsPhrase(before, " oughtn't enable")
            || ContainsPhrase(before, " oughtn't implement ")
            || ContainsPhrase(before, " oughtn't implement")
            || ContainsPhrase(before, " oughtn't adopt ")
            || ContainsPhrase(before, " oughtn't adopt")
            || ContainsPhrase(before, " oughtn't deploy ")
            || ContainsPhrase(before, " oughtn't deploy")
            || ContainsPhrase(before, " didn't have ")
            || ContainsPhrase(before, " didn't have")
            || ContainsPhrase(before, " didn't use ")
            || ContainsPhrase(before, " didn't use")
            || ContainsPhrase(before, " didn't enable ")
            || ContainsPhrase(before, " didn't enable")
            || ContainsPhrase(before, " didn't implement ")
            || ContainsPhrase(before, " didn't implement")
            || ContainsPhrase(before, " didn't adopt ")
            || ContainsPhrase(before, " didn't adopt")
            || ContainsPhrase(before, " didn't deploy ")
            || ContainsPhrase(before, " didn't deploy")
            || ContainsPhrase(before, " didn't require ")
            || ContainsPhrase(before, " didn't require")
            || ContainsPhrase(before, " didn't need ")
            || ContainsPhrase(before, " didn't need")
            || ContainsPhrase(before, " didn't configure ")
            || ContainsPhrase(before, " didn't configure")
            || ContainsPhrase(before, " didn't mandate ")
            || ContainsPhrase(before, " didn't mandate")
            || ContainsPhrase(before, " didn't apply ")
            || ContainsPhrase(before, " didn't apply")
            || ContainsPhrase(before, " didn't enforce ")
            || ContainsPhrase(before, " didn't enforce")
            || ContainsPhrase(before, " didn't maintain ")
            || ContainsPhrase(before, " didn't maintain")
            || ContainsPhrase(before, " didn't ensure ")
            || ContainsPhrase(before, " didn't ensure")
            || ContainsPhrase(before, " didn't provision ")
            || ContainsPhrase(before, " didn't provision")
            || ContainsPhrase(before, " wasn't have ")
            || ContainsPhrase(before, " wasn't have")
            || ContainsPhrase(before, " wasn't use ")
            || ContainsPhrase(before, " wasn't use")
            || ContainsPhrase(before, " wasn't enable ")
            || ContainsPhrase(before, " wasn't enable")
            || ContainsPhrase(before, " wasn't implement ")
            || ContainsPhrase(before, " wasn't implement")
            || ContainsPhrase(before, " wasn't adopt ")
            || ContainsPhrase(before, " wasn't adopt")
            || ContainsPhrase(before, " wasn't deploy ")
            || ContainsPhrase(before, " wasn't deploy")
            || ContainsPhrase(before, " wasn't require ")
            || ContainsPhrase(before, " wasn't require")
            || ContainsPhrase(before, " wasn't need ")
            || ContainsPhrase(before, " wasn't need")
            || ContainsPhrase(before, " wasn't configure ")
            || ContainsPhrase(before, " wasn't configure")
            || ContainsPhrase(before, " wasn't mandate ")
            || ContainsPhrase(before, " wasn't mandate")
            || ContainsPhrase(before, " wasn't apply ")
            || ContainsPhrase(before, " wasn't apply")
            || ContainsPhrase(before, " wasn't enforce ")
            || ContainsPhrase(before, " wasn't enforce")
            || ContainsPhrase(before, " wasn't maintain ")
            || ContainsPhrase(before, " wasn't maintain")
            || ContainsPhrase(before, " wasn't ensure ")
            || ContainsPhrase(before, " wasn't ensure")
            || ContainsPhrase(before, " wasn't provision ")
            || ContainsPhrase(before, " wasn't provision")
            || ContainsPhrase(before, " can't require ")
            || ContainsPhrase(before, " can't require")
            || ContainsPhrase(before, " can't need ")
            || ContainsPhrase(before, " can't need")
            || ContainsPhrase(before, " can't configure ")
            || ContainsPhrase(before, " can't configure")
            || ContainsPhrase(before, " can't mandate ")
            || ContainsPhrase(before, " can't mandate")
            || ContainsPhrase(before, " can't apply ")
            || ContainsPhrase(before, " can't apply")
            || ContainsPhrase(before, " can't enforce ")
            || ContainsPhrase(before, " can't enforce")
            || ContainsPhrase(before, " can't maintain ")
            || ContainsPhrase(before, " can't maintain")
            || ContainsPhrase(before, " can't ensure ")
            || ContainsPhrase(before, " can't ensure")
            || ContainsPhrase(before, " can't provision ")
            || ContainsPhrase(before, " can't provision")
            || ContainsPhrase(before, " ain't require ")
            || ContainsPhrase(before, " ain't require")
            || ContainsPhrase(before, " ain't need ")
            || ContainsPhrase(before, " ain't need")
            || ContainsPhrase(before, " ain't configure ")
            || ContainsPhrase(before, " ain't configure")
            || ContainsPhrase(before, " ain't mandate ")
            || ContainsPhrase(before, " ain't mandate")
            || ContainsPhrase(before, " ain't apply ")
            || ContainsPhrase(before, " ain't apply")
            || ContainsPhrase(before, " ain't enforce ")
            || ContainsPhrase(before, " ain't enforce")
            || ContainsPhrase(before, " ain't maintain ")
            || ContainsPhrase(before, " ain't maintain")
            || ContainsPhrase(before, " ain't ensure ")
            || ContainsPhrase(before, " ain't ensure")
            || ContainsPhrase(before, " ain't provision ")
            || ContainsPhrase(before, " ain't provision")
            || ContainsPhrase(before, " daren't require ")
            || ContainsPhrase(before, " daren't require")
            || ContainsPhrase(before, " daren't need ")
            || ContainsPhrase(before, " daren't need")
            || ContainsPhrase(before, " daren't configure ")
            || ContainsPhrase(before, " daren't configure")
            || ContainsPhrase(before, " daren't mandate ")
            || ContainsPhrase(before, " daren't mandate")
            || ContainsPhrase(before, " daren't apply ")
            || ContainsPhrase(before, " daren't apply")
            || ContainsPhrase(before, " daren't enforce ")
            || ContainsPhrase(before, " daren't enforce")
            || ContainsPhrase(before, " daren't maintain ")
            || ContainsPhrase(before, " daren't maintain")
            || ContainsPhrase(before, " daren't ensure ")
            || ContainsPhrase(before, " daren't ensure")
            || ContainsPhrase(before, " daren't provision ")
            || ContainsPhrase(before, " daren't provision")
            || ContainsPhrase(before, " mayn't require ")
            || ContainsPhrase(before, " mayn't require")
            || ContainsPhrase(before, " mayn't need ")
            || ContainsPhrase(before, " mayn't need")
            || ContainsPhrase(before, " mayn't configure ")
            || ContainsPhrase(before, " mayn't configure")
            || ContainsPhrase(before, " mayn't mandate ")
            || ContainsPhrase(before, " mayn't mandate")
            || ContainsPhrase(before, " mayn't apply ")
            || ContainsPhrase(before, " mayn't apply")
            || ContainsPhrase(before, " mayn't enforce ")
            || ContainsPhrase(before, " mayn't enforce")
            || ContainsPhrase(before, " mayn't maintain ")
            || ContainsPhrase(before, " mayn't maintain")
            || ContainsPhrase(before, " mayn't ensure ")
            || ContainsPhrase(before, " mayn't ensure")
            || ContainsPhrase(before, " mayn't provision ")
            || ContainsPhrase(before, " mayn't provision")
            || ContainsPhrase(before, " oughtn't require ")
            || ContainsPhrase(before, " oughtn't require")
            || ContainsPhrase(before, " oughtn't need ")
            || ContainsPhrase(before, " oughtn't need")
            || ContainsPhrase(before, " oughtn't configure ")
            || ContainsPhrase(before, " oughtn't configure")
            || ContainsPhrase(before, " oughtn't mandate ")
            || ContainsPhrase(before, " oughtn't mandate")
            || ContainsPhrase(before, " oughtn't apply ")
            || ContainsPhrase(before, " oughtn't apply")
            || ContainsPhrase(before, " oughtn't enforce ")
            || ContainsPhrase(before, " oughtn't enforce")
            || ContainsPhrase(before, " oughtn't maintain ")
            || ContainsPhrase(before, " oughtn't maintain")
            || ContainsPhrase(before, " oughtn't ensure ")
            || ContainsPhrase(before, " oughtn't ensure")
            || ContainsPhrase(before, " oughtn't provision ")
            || ContainsPhrase(before, " oughtn't provision")
            || ContainsPhrase(before, " mustn't require ")
            || ContainsPhrase(before, " mustn't require")
            || ContainsPhrase(before, " mustn't need ")
            || ContainsPhrase(before, " mustn't need")
            || ContainsPhrase(before, " mustn't configure ")
            || ContainsPhrase(before, " mustn't configure")
            || ContainsPhrase(before, " mustn't mandate ")
            || ContainsPhrase(before, " mustn't mandate")
            || ContainsPhrase(before, " mustn't apply ")
            || ContainsPhrase(before, " mustn't apply")
            || ContainsPhrase(before, " mustn't enforce ")
            || ContainsPhrase(before, " mustn't enforce")
            || ContainsPhrase(before, " mustn't maintain ")
            || ContainsPhrase(before, " mustn't maintain")
            || ContainsPhrase(before, " mustn't ensure ")
            || ContainsPhrase(before, " mustn't ensure")
            || ContainsPhrase(before, " mustn't provision ")
            || ContainsPhrase(before, " mustn't provision")
            || ContainsPhrase(before, " shan't require ")
            || ContainsPhrase(before, " shan't require")
            || ContainsPhrase(before, " shan't need ")
            || ContainsPhrase(before, " shan't need")
            || ContainsPhrase(before, " shan't configure ")
            || ContainsPhrase(before, " shan't configure")
            || ContainsPhrase(before, " shan't mandate ")
            || ContainsPhrase(before, " shan't mandate")
            || ContainsPhrase(before, " shan't apply ")
            || ContainsPhrase(before, " shan't apply")
            || ContainsPhrase(before, " shan't enforce ")
            || ContainsPhrase(before, " shan't enforce")
            || ContainsPhrase(before, " shan't maintain ")
            || ContainsPhrase(before, " shan't maintain")
            || ContainsPhrase(before, " shan't ensure ")
            || ContainsPhrase(before, " shan't ensure")
            || ContainsPhrase(before, " shan't provision ")
            || ContainsPhrase(before, " shan't provision")
            || ContainsPhrase(before, " needn't require ")
            || ContainsPhrase(before, " needn't require")
            || ContainsPhrase(before, " needn't need ")
            || ContainsPhrase(before, " needn't need")
            || ContainsPhrase(before, " needn't configure ")
            || ContainsPhrase(before, " needn't configure")
            || ContainsPhrase(before, " needn't mandate ")
            || ContainsPhrase(before, " needn't mandate")
            || ContainsPhrase(before, " needn't apply ")
            || ContainsPhrase(before, " needn't apply")
            || ContainsPhrase(before, " needn't enforce ")
            || ContainsPhrase(before, " needn't enforce")
            || ContainsPhrase(before, " needn't maintain ")
            || ContainsPhrase(before, " needn't maintain")
            || ContainsPhrase(before, " needn't ensure ")
            || ContainsPhrase(before, " needn't ensure")
            || ContainsPhrase(before, " needn't provision ")
            || ContainsPhrase(before, " needn't provision")
            || ContainsPhrase(before, " mightn't require ")
            || ContainsPhrase(before, " mightn't require")
            || ContainsPhrase(before, " mightn't need ")
            || ContainsPhrase(before, " mightn't need")
            || ContainsPhrase(before, " mightn't configure ")
            || ContainsPhrase(before, " mightn't configure")
            || ContainsPhrase(before, " mightn't mandate ")
            || ContainsPhrase(before, " mightn't mandate")
            || ContainsPhrase(before, " mightn't apply ")
            || ContainsPhrase(before, " mightn't apply")
            || ContainsPhrase(before, " mightn't enforce ")
            || ContainsPhrase(before, " mightn't enforce")
            || ContainsPhrase(before, " mightn't maintain ")
            || ContainsPhrase(before, " mightn't maintain")
            || ContainsPhrase(before, " mightn't ensure ")
            || ContainsPhrase(before, " mightn't ensure")
            || ContainsPhrase(before, " mightn't provision ")
            || ContainsPhrase(before, " mightn't provision")
            || ContainsPhrase(before, " couldn't require ")
            || ContainsPhrase(before, " couldn't require")
            || ContainsPhrase(before, " couldn't need ")
            || ContainsPhrase(before, " couldn't need")
            || ContainsPhrase(before, " couldn't configure ")
            || ContainsPhrase(before, " couldn't configure")
            || ContainsPhrase(before, " couldn't mandate ")
            || ContainsPhrase(before, " couldn't mandate")
            || ContainsPhrase(before, " couldn't apply ")
            || ContainsPhrase(before, " couldn't apply")
            || ContainsPhrase(before, " couldn't enforce ")
            || ContainsPhrase(before, " couldn't enforce")
            || ContainsPhrase(before, " couldn't maintain ")
            || ContainsPhrase(before, " couldn't maintain")
            || ContainsPhrase(before, " couldn't ensure ")
            || ContainsPhrase(before, " couldn't ensure")
            || ContainsPhrase(before, " couldn't provision ")
            || ContainsPhrase(before, " couldn't provision")
            || ContainsPhrase(before, " can not require ")
            || ContainsPhrase(before, " can not require")
            || ContainsPhrase(before, " can not need ")
            || ContainsPhrase(before, " can not need")
            || ContainsPhrase(before, " can not configure ")
            || ContainsPhrase(before, " can not configure")
            || ContainsPhrase(before, " can not mandate ")
            || ContainsPhrase(before, " can not mandate")
            || ContainsPhrase(before, " can not apply ")
            || ContainsPhrase(before, " can not apply")
            || ContainsPhrase(before, " can not enforce ")
            || ContainsPhrase(before, " can not enforce")
            || ContainsPhrase(before, " can not maintain ")
            || ContainsPhrase(before, " can not maintain")
            || ContainsPhrase(before, " can not ensure ")
            || ContainsPhrase(before, " can not ensure")
            || ContainsPhrase(before, " can not provision ")
            || ContainsPhrase(before, " can not provision")
            || ContainsPhrase(before, " can not enable ")
            || ContainsPhrase(before, " can not enable")
            || ContainsPhrase(before, " can not implement ")
            || ContainsPhrase(before, " can not implement")
            || ContainsPhrase(before, " can not deploy ")
            || ContainsPhrase(before, " can not deploy")
            || ContainsPhrase(before, " can not adopt ")
            || ContainsPhrase(before, " can not adopt")
            || ContainsPhrase(before, " can not use ")
            || ContainsPhrase(before, " can not use")
            || ContainsPhrase(before, " can not have ")
            || ContainsPhrase(before, " can not have")
            || ContainsPhrase(before, " could not enable ")
            || ContainsPhrase(before, " could not enable")
            || ContainsPhrase(before, " could not implement ")
            || ContainsPhrase(before, " could not implement")
            || ContainsPhrase(before, " could not deploy ")
            || ContainsPhrase(before, " could not deploy")
            || ContainsPhrase(before, " could not adopt ")
            || ContainsPhrase(before, " could not adopt")
            || ContainsPhrase(before, " could not use ")
            || ContainsPhrase(before, " could not use")
            || ContainsPhrase(before, " could not have ")
            || ContainsPhrase(before, " could not have")
            || ContainsPhrase(before, " could not require ")
            || ContainsPhrase(before, " could not require")
            || ContainsPhrase(before, " could not need ")
            || ContainsPhrase(before, " could not need")
            || ContainsPhrase(before, " could not configure ")
            || ContainsPhrase(before, " could not configure")
            || ContainsPhrase(before, " could not mandate ")
            || ContainsPhrase(before, " could not mandate")
            || ContainsPhrase(before, " could not apply ")
            || ContainsPhrase(before, " could not apply")
            || ContainsPhrase(before, " could not enforce ")
            || ContainsPhrase(before, " could not enforce")
            || ContainsPhrase(before, " could not maintain ")
            || ContainsPhrase(before, " could not maintain")
            || ContainsPhrase(before, " could not ensure ")
            || ContainsPhrase(before, " could not ensure")
            || ContainsPhrase(before, " could not provision ")
            || ContainsPhrase(before, " could not provision")
            || ContainsPhrase(before, " can't enable ")
            || ContainsPhrase(before, " can't enable")
            || ContainsPhrase(before, " can't implement ")
            || ContainsPhrase(before, " can't implement")
            || ContainsPhrase(before, " does not implement ")
            || ContainsPhrase(before, " does not implement")
            || ContainsPhrase(before, " does not enable ")
            || ContainsPhrase(before, " does not enable")
            || ContainsPhrase(before, " does not deploy ")
            || ContainsPhrase(before, " does not deploy")
            || ContainsPhrase(before, " does not adopt ")
            || ContainsPhrase(before, " does not adopt")
            || ContainsPhrase(before, " does not use ")
            || ContainsPhrase(before, " does not use")
            || ContainsPhrase(before, " does not have ")
            || ContainsPhrase(before, " does not have")
            || ContainsPhrase(before, " does not maintain ")
            || ContainsPhrase(before, " does not maintain")
            || ContainsPhrase(before, " does not mandate ")
            || ContainsPhrase(before, " does not mandate")
            || ContainsPhrase(before, " does not ensure ")
            || ContainsPhrase(before, " does not ensure")
            || ContainsPhrase(before, " does not provision ")
            || ContainsPhrase(before, " does not provision")
            || ContainsPhrase(before, " does not apply ")
            || ContainsPhrase(before, " does not apply")
            || ContainsPhrase(before, " does not configure ")
            || ContainsPhrase(before, " does not configure")
            || ContainsPhrase(before, " does not enforce ")
            || ContainsPhrase(before, " does not enforce")
            || ContainsPhrase(before, " does not require ")
            || ContainsPhrase(before, " does not require")
            || ContainsPhrase(before, " does not need ")
            || ContainsPhrase(before, " does not need")
            || ContainsPhrase(before, " will not implement ")
            || ContainsPhrase(before, " will not implement")
            || ContainsPhrase(before, " will not enable ")
            || ContainsPhrase(before, " will not enable")
            || ContainsPhrase(before, " will not deploy ")
            || ContainsPhrase(before, " will not deploy")
            || ContainsPhrase(before, " will not adopt ")
            || ContainsPhrase(before, " will not adopt")
            || ContainsPhrase(before, " will not use ")
            || ContainsPhrase(before, " will not use")
            || ContainsPhrase(before, " will not have ")
            || ContainsPhrase(before, " will not have")
            || ContainsPhrase(before, " would not implement ")
            || ContainsPhrase(before, " would not implement")
            || ContainsPhrase(before, " would not enable ")
            || ContainsPhrase(before, " would not enable")
            || ContainsPhrase(before, " would not deploy ")
            || ContainsPhrase(before, " would not deploy")
            || ContainsPhrase(before, " would not adopt ")
            || ContainsPhrase(before, " would not adopt")
            || ContainsPhrase(before, " would not use ")
            || ContainsPhrase(before, " would not use")
            || ContainsPhrase(before, " would not have ")
            || ContainsPhrase(before, " would not have")
            || ContainsPhrase(before, " shall not implement ")
            || ContainsPhrase(before, " shall not implement")
            || ContainsPhrase(before, " shall not enable ")
            || ContainsPhrase(before, " shall not enable")
            || ContainsPhrase(before, " shall not deploy ")
            || ContainsPhrase(before, " shall not deploy")
            || ContainsPhrase(before, " shall not adopt ")
            || ContainsPhrase(before, " shall not adopt")
            || ContainsPhrase(before, " shall not use ")
            || ContainsPhrase(before, " shall not use")
            || ContainsPhrase(before, " shall not have ")
            || ContainsPhrase(before, " shall not have")
            || ContainsPhrase(before, " must not ")
            || ContainsPhrase(before, " do not ")
            || ContainsPhrase(before, " doesn't require ")
            || ContainsPhrase(before, " doesn't require")
            || ContainsPhrase(before, " doesn't need ")
            || ContainsPhrase(before, " doesn't need")
            || ContainsPhrase(before, " doesn't need to ")
            || ContainsPhrase(before, " doesn't need to")
            || ContainsPhrase(before, " won't need to ")
            || ContainsPhrase(before, " won't need to")
            || ContainsPhrase(before, " is not required for ")
            || ContainsPhrase(before, " is not required for")
            || ContainsPhrase(before, " not necessary to ")
            || ContainsPhrase(before, " not necessary to")
            || ContainsPhrase(before, " shouldn't need to ")
            || ContainsPhrase(before, " shouldn't need to")
            || ContainsPhrase(before, " doesn't require to ")
            || ContainsPhrase(before, " doesn't require to")
            || ContainsPhrase(before, " won't require to ")
            || ContainsPhrase(before, " won't require to")
            || ContainsPhrase(before, " shouldn't require to ")
            || ContainsPhrase(before, " shouldn't require to")
            || ContainsPhrase(before, " not required for ")
            || ContainsPhrase(before, " not required for")
            || ContainsPhrase(before, " is not necessary to ")
            || ContainsPhrase(before, " is not necessary to")
            || ContainsPhrase(before, " not necessary for ")
            || ContainsPhrase(before, " not necessary for")
            || ContainsPhrase(before, " need not require to ")
            || ContainsPhrase(before, " need not require to")
            || ContainsPhrase(before, " cannot require to ")
            || ContainsPhrase(before, " cannot require to")
            || ContainsPhrase(before, " won't mandate to ")
            || ContainsPhrase(before, " won't mandate to")
            || ContainsPhrase(before, " won't configure to ")
            || ContainsPhrase(before, " won't configure to")
            || ContainsPhrase(before, " shouldn't configure to ")
            || ContainsPhrase(before, " shouldn't configure to")
            || ContainsPhrase(before, " cannot configure to ")
            || ContainsPhrase(before, " cannot configure to")
            || ContainsPhrase(before, " need not configure to ")
            || ContainsPhrase(before, " need not configure to")
            || ContainsPhrase(before, " shouldn't mandate to ")
            || ContainsPhrase(before, " shouldn't mandate to")
            || ContainsPhrase(before, " cannot mandate to ")
            || ContainsPhrase(before, " cannot mandate to")
            || ContainsPhrase(before, " need not mandate to ")
            || ContainsPhrase(before, " need not mandate to")
            || ContainsPhrase(before, " won't apply to ")
            || ContainsPhrase(before, " won't apply to")
            || ContainsPhrase(before, " shouldn't apply to ")
            || ContainsPhrase(before, " shouldn't apply to")
            || ContainsPhrase(before, " cannot apply to ")
            || ContainsPhrase(before, " cannot apply to")
            || ContainsPhrase(before, " need not apply to ")
            || ContainsPhrase(before, " need not apply to")
            || ContainsPhrase(before, " won't enforce to ")
            || ContainsPhrase(before, " won't enforce to")
            || ContainsPhrase(before, " shouldn't enforce to ")
            || ContainsPhrase(before, " shouldn't enforce to")
            || ContainsPhrase(before, " cannot enforce to ")
            || ContainsPhrase(before, " cannot enforce to")
            || ContainsPhrase(before, " need not enforce to ")
            || ContainsPhrase(before, " need not enforce to")
            || ContainsPhrase(before, " won't provision to ")
            || ContainsPhrase(before, " won't provision to")
            || ContainsPhrase(before, " shouldn't provision to ")
            || ContainsPhrase(before, " shouldn't provision to")
            || ContainsPhrase(before, " cannot provision to ")
            || ContainsPhrase(before, " cannot provision to")
            || ContainsPhrase(before, " need not provision to ")
            || ContainsPhrase(before, " need not provision to")
            || ContainsPhrase(before, " won't maintain to ")
            || ContainsPhrase(before, " won't maintain to")
            || ContainsPhrase(before, " shouldn't maintain to ")
            || ContainsPhrase(before, " shouldn't maintain to")
            || ContainsPhrase(before, " cannot maintain to ")
            || ContainsPhrase(before, " cannot maintain to")
            || ContainsPhrase(before, " need not maintain to ")
            || ContainsPhrase(before, " need not maintain to")
            || ContainsPhrase(before, " won't ensure to ")
            || ContainsPhrase(before, " won't ensure to")
            || ContainsPhrase(before, " shouldn't ensure to ")
            || ContainsPhrase(before, " shouldn't ensure to")
            || ContainsPhrase(before, " cannot ensure to ")
            || ContainsPhrase(before, " cannot ensure to")
            || ContainsPhrase(before, " need not ensure to ")
            || ContainsPhrase(before, " need not ensure to")
            || ContainsPhrase(before, " should not require to ")
            || ContainsPhrase(before, " should not require to")
            || ContainsPhrase(before, " will not require to ")
            || ContainsPhrase(before, " will not require to")
            || ContainsPhrase(before, " would not require to ")
            || ContainsPhrase(before, " would not require to")
            || ContainsPhrase(before, " shall not require to ")
            || ContainsPhrase(before, " shall not require to")
            || ContainsPhrase(before, " should not configure to ")
            || ContainsPhrase(before, " should not configure to")
            || ContainsPhrase(before, " will not configure to ")
            || ContainsPhrase(before, " will not configure to")
            || ContainsPhrase(before, " would not configure to ")
            || ContainsPhrase(before, " would not configure to")
            || ContainsPhrase(before, " shall not configure to ")
            || ContainsPhrase(before, " shall not configure to")
            || ContainsPhrase(before, " should not mandate to ")
            || ContainsPhrase(before, " should not mandate to")
            || ContainsPhrase(before, " will not mandate to ")
            || ContainsPhrase(before, " will not mandate to")
            || ContainsPhrase(before, " would not mandate to ")
            || ContainsPhrase(before, " would not mandate to")
            || ContainsPhrase(before, " shall not mandate to ")
            || ContainsPhrase(before, " shall not mandate to")
            || ContainsPhrase(before, " should not apply to ")
            || ContainsPhrase(before, " should not apply to")
            || ContainsPhrase(before, " will not apply to ")
            || ContainsPhrase(before, " will not apply to")
            || ContainsPhrase(before, " would not apply to ")
            || ContainsPhrase(before, " would not apply to")
            || ContainsPhrase(before, " shall not apply to ")
            || ContainsPhrase(before, " shall not apply to")
            || ContainsPhrase(before, " will not enforce to ")
            || ContainsPhrase(before, " will not enforce to")
            || ContainsPhrase(before, " would not enforce to ")
            || ContainsPhrase(before, " would not enforce to")
            || ContainsPhrase(before, " shall not enforce to ")
            || ContainsPhrase(before, " shall not enforce to")
            || ContainsPhrase(before, " should not enforce to ")
            || ContainsPhrase(before, " should not enforce to")
            || ContainsPhrase(before, " should not provision to ")
            || ContainsPhrase(before, " should not provision to")
            || ContainsPhrase(before, " will not provision to ")
            || ContainsPhrase(before, " will not provision to")
            || ContainsPhrase(before, " would not provision to ")
            || ContainsPhrase(before, " would not provision to")
            || ContainsPhrase(before, " shall not provision to ")
            || ContainsPhrase(before, " shall not provision to")
            || ContainsPhrase(before, " will not maintain to ")
            || ContainsPhrase(before, " will not maintain to")
            || ContainsPhrase(before, " would not maintain to ")
            || ContainsPhrase(before, " would not maintain to")
            || ContainsPhrase(before, " shall not maintain to ")
            || ContainsPhrase(before, " shall not maintain to")
            || ContainsPhrase(before, " should not maintain to ")
            || ContainsPhrase(before, " should not maintain to")
            || ContainsPhrase(before, " should not ensure to ")
            || ContainsPhrase(before, " should not ensure to")
            || ContainsPhrase(before, " will not ensure to ")
            || ContainsPhrase(before, " will not ensure to")
            || ContainsPhrase(before, " shall not ensure to ")
            || ContainsPhrase(before, " shall not ensure to")
            || ContainsPhrase(before, " would not ensure to ")
            || ContainsPhrase(before, " would not ensure to")
            || ContainsPhrase(before, " cannot need to ")
            || ContainsPhrase(before, " cannot need to")
            || ContainsPhrase(before, " ought not require to ")
            || ContainsPhrase(before, " ought not require to")
            || ContainsPhrase(before, " ought not maintain to ")
            || ContainsPhrase(before, " ought not maintain to")
            || ContainsPhrase(before, " ought not ensure to ")
            || ContainsPhrase(before, " ought not ensure to")
            || ContainsPhrase(before, " ought not configure to ")
            || ContainsPhrase(before, " ought not configure to")
            || ContainsPhrase(before, " ought not mandate to ")
            || ContainsPhrase(before, " ought not mandate to")
            || ContainsPhrase(before, " ought not apply to ")
            || ContainsPhrase(before, " ought not apply to")
            || ContainsPhrase(before, " ought not enforce to ")
            || ContainsPhrase(before, " ought not enforce to")
            || ContainsPhrase(before, " ought not provision to ")
            || ContainsPhrase(before, " ought not provision to")
            || ContainsPhrase(before, " ought not need to ")
            || ContainsPhrase(before, " ought not need to")
            || ContainsPhrase(before, " should not need to ")
            || ContainsPhrase(before, " should not need to")
            || ContainsPhrase(before, " shall not need to ")
            || ContainsPhrase(before, " shall not need to")
            || ContainsPhrase(before, " will not need to ")
            || ContainsPhrase(before, " will not need to")
            || ContainsPhrase(before, " would not need to ")
            || ContainsPhrase(before, " would not need to")
            || ContainsPhrase(before, " need not need to ")
            || ContainsPhrase(before, " need not need to")
            || ContainsPhrase(before, " could not need to ")
            || ContainsPhrase(before, " could not need to")
            || ContainsPhrase(before, " could not require to ")
            || ContainsPhrase(before, " could not require to")
            || ContainsPhrase(before, " could not configure to ")
            || ContainsPhrase(before, " could not configure to")
            || ContainsPhrase(before, " could not mandate to ")
            || ContainsPhrase(before, " could not mandate to")
            || ContainsPhrase(before, " could not apply to ")
            || ContainsPhrase(before, " could not apply to")
            || ContainsPhrase(before, " could not enforce to ")
            || ContainsPhrase(before, " could not enforce to")
            || ContainsPhrase(before, " could not provision to ")
            || ContainsPhrase(before, " could not provision to")
            || ContainsPhrase(before, " could not maintain to ")
            || ContainsPhrase(before, " could not maintain to")
            || ContainsPhrase(before, " could not ensure to ")
            || ContainsPhrase(before, " could not ensure to")
            || ContainsPhrase(before, " couldn't configure to ")
            || ContainsPhrase(before, " couldn't configure to")
            || ContainsPhrase(before, " couldn't require to ")
            || ContainsPhrase(before, " couldn't require to")
            || ContainsPhrase(before, " cannot require ")
            || ContainsPhrase(before, " cannot need ")
            || ContainsPhrase(before, " cannot need");
    }

    private static bool ContainsPhrase(ReadOnlySpan<char> haystack, string phrase)
    {
        return haystack.IndexOf(phrase.AsSpan(), StringComparison.OrdinalIgnoreCase) >= 0;
    }

    private static bool IsWithoutPrefixedNegation(string haystack, int tokenIndex)
    {
        ReadOnlySpan<char> before = haystack.AsSpan(0, tokenIndex).TrimEnd();

        if (before.Length < 7)
            return false;

        return before.EndsWith("without", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("without-", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("without_", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("without.", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("without ", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsNonPrefixedNegation(string haystack, int tokenIndex)
    {
        ReadOnlySpan<char> before = haystack.AsSpan(0, tokenIndex).TrimEnd();

        if (before.Length < 3)
            return false;

        return before.EndsWith("non", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("non-", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("non_", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("non.", StringComparison.OrdinalIgnoreCase)
            || before.EndsWith("non ", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsNegatedPhraseSuffix(string haystack, int tokenIndex, int tokenLength)
    {
        ReadOnlySpan<char> after = haystack.AsSpan(tokenIndex + tokenLength).TrimStart();

        if (after.Length < 2)
            return false;

        if (after.StartsWith("not required", StringComparison.OrdinalIgnoreCase)
            || after.StartsWith("not needed", StringComparison.OrdinalIgnoreCase)
            || after.StartsWith("not necessary", StringComparison.OrdinalIgnoreCase)
            || after.StartsWith("is not required", StringComparison.OrdinalIgnoreCase)
            || after.StartsWith("is not needed", StringComparison.OrdinalIgnoreCase)
            || after.StartsWith("is not necessary", StringComparison.OrdinalIgnoreCase)
            || after.StartsWith("is unnecessary", StringComparison.OrdinalIgnoreCase)
            || after.StartsWith("isn't required", StringComparison.OrdinalIgnoreCase)
            || after.StartsWith("isn't needed", StringComparison.OrdinalIgnoreCase)
            || after.StartsWith("is optional", StringComparison.OrdinalIgnoreCase)
            || after.StartsWith("need not", StringComparison.OrdinalIgnoreCase))
            return true;

        return ContainsPhrase(after, " need not ");
    }

    private static string? NormalizeNegationText(string? haystack)
    {
        if (string.IsNullOrWhiteSpace(haystack))
            return haystack;

        if (haystack.IndexOf('\u2019') < 0
            && haystack.IndexOf('\u2018') < 0
            && haystack.IndexOf('\u2032') < 0)
            return haystack;

        return haystack
            .Replace('\u2019', '\'')
            .Replace('\u2018', '\'')
            .Replace('\u2032', '\'');
    }
}
