using ArchLucid.Core.Configuration;

namespace ArchLucid.Core.ProductLine;

/// <summary>Consumer-facing product labels for emails, exports, and clipboard artifacts.</summary>
public static class ProductLineConsumerNames
{
    public const string ArchitectureDefault = "ArchLucid";

    public const string SecurityDefault = "SecureNow";

    public static string DisplayName(ProductLineId productLine, ProductLineDisplayNamesOptions? options = null)
    {
        string? configured = productLine switch
        {
            ProductLineId.Architecture => options?.Architecture,
            ProductLineId.Security => options?.Security,
            _ => null,
        };

        if (!string.IsNullOrWhiteSpace(configured))
            return configured.Trim();

        return productLine == ProductLineId.Security ? SecurityDefault : ArchitectureDefault;
    }

    public static string GeneratedByLine(ProductLineId productLine, ProductLineDisplayNamesOptions? options = null) =>
        $"Generated by {DisplayName(productLine, options)}";

    public static string PoweredByLine(ProductLineId productLine, ProductLineDisplayNamesOptions? options = null) =>
        $"Powered by {DisplayName(productLine, options)}";

    public static string DefaultFooterAttributionTemplate(
        ProductLineId productLine,
        ProductLineDisplayNamesOptions? options = null) =>
        $"Prepared by {{FirmDisplayName}} using {DisplayName(productLine, options)}";
}
