<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ArchLucid.Notifications.Email.RazorLight</RootNamespace>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ArchLucid.Application.Tests" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="RazorLight" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Templates\*.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ArchLucid.Core\ArchLucid.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ArchLucid.Analyzers\ArchLucid.Analyzers.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
