using System.Text;

namespace ArchLucid.Cli.Commands;

/// <summary>Writes the starter policy-pack directory tree for <c>archlucid pack export-scaffold</c>.</summary>
internal static class PackExportScaffoldWriter
{
    internal const string PolicyPackFileName = "policy-pack.json";

    internal const string ComplianceRulesFileName = "compliance-rules.json";

    internal const string ReadmeFileName = "README.md";

    internal static IReadOnlyList<string> Write(string outputDirectory)
    {
        Directory.CreateDirectory(outputDirectory);

        string policyPackPath = Path.Combine(outputDirectory, PolicyPackFileName);
        string complianceRulesPath = Path.Combine(outputDirectory, ComplianceRulesFileName);
        string readmePath = Path.Combine(outputDirectory, ReadmeFileName);

        UTF8Encoding utf8NoBom = new(encoderShouldEmitUTF8Identifier: false, throwOnInvalidBytes: true);

        File.WriteAllText(policyPackPath, PolicyPackJson, utf8NoBom);
        File.WriteAllText(complianceRulesPath, ComplianceRulesJson, utf8NoBom);
        File.WriteAllText(readmePath, ReadmeMarkdown, utf8NoBom);

        return [policyPackPath, complianceRulesPath, readmePath];
    }

    private const string PolicyPackJson = """
        {
          "complianceRuleIds": [],
          "complianceRuleKeys": [
            "scaffold-ctrl-001",
            "scaffold-ctrl-002"
          ],
          "alertRuleIds": [],
          "compositeAlertRuleIds": [],
          "advisoryDefaults": {
            "severityFloor": "warning"
          },
          "metadata": {
            "author": "your-team",
            "packPurpose": "Replace with your internal control themes before import."
          }
        }
        """;

    private const string ComplianceRulesJson = """
        {
          "rulePackId": "custom-policy-pack-scaffold-v1",
          "name": "Custom policy pack — scaffold starter",
          "version": "1.0.0",
          "rules": [
            {
              "ruleId": "scaffold-ctrl-001",
              "controlId": "SCAFFOLD-001",
              "controlName": "Security baseline — replace with your control title",
              "appliesToCategory": "security",
              "requiredNodeType": "SecurityBaseline",
              "requiredEdgeType": "PROTECTS",
              "severity": "Warning",
              "description": "Sample rule: require an explicit security baseline node in the architecture graph context."
            },
            {
              "ruleId": "scaffold-ctrl-002",
              "controlId": "SCAFFOLD-002",
              "controlName": "Operational logging — replace with your control title",
              "appliesToCategory": "logging",
              "requiredNodeType": "PolicyControl",
              "requiredEdgeType": "APPLIES_TO",
              "severity": "Error",
              "description": "Sample rule: require tamper-evident logging for regulated data flows."
            }
          ]
        }
        """;

    private const string ReadmeMarkdown = """
        # Custom policy pack scaffold

        Generated by `archlucid pack export-scaffold`. Edit rule ids, descriptions, and metadata before importing into your tenant.

        ## Files

        | File | Role |
        |------|------|
        | `policy-pack.json` | **`PolicyPackContentDocument`** body — keys in `complianceRuleKeys` must match `ruleId` values in `compliance-rules.json`. |
        | `compliance-rules.json` | Sample file-based compliance rules for local authoring; import or register rules per your operate-mode pipeline. |

        ## Next steps

        1. Rename `scaffold-ctrl-*` rule ids and update both JSON files so keys stay aligned.
        2. Validate content: `archlucid policy-pack validate policy-pack.json`
        3. Create the pack via **`POST /v1/governance/policy-packs`** (Administrator; Standard tier).
        4. Publish a version and assign scope so pre-commit governance can reference the pack.

        ## Policy Pack Hub references (ArchLucid repo)

        - `docs/library/contributor-reference/GOVERNANCE.md` — create, publish, and assign flows
        - `docs/templates/policy-packs/README.md` — curl import templates and WAF analogue starter
        - `docs/library/PRE_COMMIT_GOVERNANCE_GATE.md` — wire packs into CI / pre-commit gates
        - `templates/policy-packs/` — vertical starter packs for inspiration

        _Do not treat this scaffold as certification against SOC 2, HIPAA, CIS, or cloud vendor frameworks without your own SME review._
        """;
}
