namespace ArchLucid.Core.Configuration;

public static partial class ConfigurationKeyCatalog
{
    private static void AddAgentExecution(List<ConfigurationKeyEntry> entries)
    {
        entries.AddRange(
        [
            E("ArchLucid", "ArchLucid:AgentOutput:QualityGate:Enabled", M("appsettings", "env"), "true", "—",
                "Enables quality gate for agent output.", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:AgentOutput:QualityGate:Mode", M("appsettings", "env"), "WarnOnly", "—",
                "WarnOnly (default) vs PilotStrict for citations/scores/pilot sponsor gates.", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:AgentOutput:QualityGate:StructuralWarnBelow", M("appsettings", "env"), "0.85",
                "—", "Quality gate warn threshold (structural).", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:AgentOutput:QualityGate:SemanticWarnBelow", M("appsettings", "env"), "0.65", "—",
                "Quality gate warn threshold (semantic).", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:AgentOutput:QualityGate:StructuralRejectBelow", M("appsettings", "env"), "0.7",
                "—",
                "Quality gate reject (structural); strict below this yields rejected outcome (EnforceOnReject gates blocking).",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:AgentOutput:QualityGate:SemanticRejectBelow", M("appsettings", "env"), "0.55",
                "—",
                "Quality gate reject (semantic). Pair with EnforceOnReject when runs must abort on reject.",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:AgentOutput:QualityGate:EnforceOnReject", M("appsettings", "env"), "false", "—",
                "When true, AgentOutputEvaluationRecorder throws on gate reject after metrics/logs.", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:AgentOutput:QualityGate:BlockRunOnReject", M("appsettings", "env"), "false", "—",
                "When true with EnforceOnReject, execute marks ExecutionCompletedQualityRejected and returns HTTP 409.",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:AgentOutput:QualityGate:PilotStrictMinStructuralCompleteness", M("appsettings", "env"),
                "0.9", "—",
                "PilotStrict: reject traces strictly below this structural completeness ratio.", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:AgentOutput:QualityGate:PilotStrictMinSemanticScore", M("appsettings", "env"), "0.55",
                "—", "PilotStrict: reject traces strictly below this semantic score.", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:AgentOutput:QualityGate:PilotStrictMinEvidenceRefCount", M("appsettings", "env"), "2",
                "—", "PilotStrict: require at least this many top-level evidenceRefs when value > 0.", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:AgentOutput:QualityGate:PilotStrictMinFaithfulnessSupportRatio",
                M("appsettings", "env"), "0.65", "—",
                "PilotStrict minimum aggregate explanation faithfulness ratio; config lint enforces on production-like hosting.",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:AgentOutput:QualityGate:PilotStrictMinAgentResultFaithfulnessSupportRatio",
                M("appsettings", "env"), "(unset)", "—",
        "PilotStrict: minimum AgentResult→evidence grounding ratio when an evidence package exists; required when Mode is PilotStrict (options validation).", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:AgentOutput:QualityGate:HeuristicEvaluatorTightenedThresholds",
                M("appsettings", "env"), "false", "—",
                "When true, heuristic semantic evaluator applies stricter length/overlap checks.", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:AgentOutput:QualityGate:PerAgentTypeFloors",
                M("appsettings", "env"), "(see AgentTypeQualityFloors)", "—",
                "Optional JSON dictionary of per-AgentType structural/semantic warn and reject floors.", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Agents:LlmJudge:Enabled", M("appsettings", "env"), "false", "—",
                "Opt-in LLM rubric judge (Topology+Critic). Shares LlmCompletionAccountingClient quotas/monthly cap with agents (no separate judge bucket).",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Agents:LlmJudge:DeploymentName", M("appsettings", "env"), "empty", "—",
                "Judge Azure OpenAI deployment; empty falls back to AzureOpenAI:DeploymentName.",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:AgentOutput:LlmSemanticJudge", M("appsettings", "env"), "(legacy)", "—",
                "Deprecated binding path for the same options type; prefer ArchLucid:Agents:LlmJudge. Agents section overrides overlapping keys.",
                ConfigKeyRequirementKind.None,
                ConfigurationKeyProductionProfileGuardKind.None,
                ConfigurationKeyDeprecationKind.DeprecatedBindingPath,
                AgentOutputLlmSemanticJudgeOptions.SectionPath),
            E("ArchLucid", "ArchLucid:AgentExecution:QualityGate:Judge", M("appsettings", "env"), "(legacy)", "—",
                "Deprecated judge budget binding path; prefer ArchLucid:Agents:LlmJudge:Budget. Canonical Agents section overrides overlapping keys.",
                ConfigKeyRequirementKind.None,
                ConfigurationKeyProductionProfileGuardKind.None,
                ConfigurationKeyDeprecationKind.DeprecatedBindingPath,
                "ArchLucid:Agents:LlmJudge:Budget"),
            E("ArchLucid", "ArchLucid:FallbackLlm:Enabled", M("appsettings", "env", "KeyVault"), "false", "When DR fallback on",
                "Enables secondary Azure OpenAI deployments on primary 429/5xx (see FallbackAgentCompletionClient). Pilot profile keeps disabled.",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:FallbackLlm:Endpoints", M("appsettings", "env", "KeyVault"), "[]", "When DR fallback on",
                "Ordered list of fallback Endpoint/ApiKey/DeploymentName rows tried after the primary fails.",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:FallbackLlm:Endpoint", M("appsettings", "env", "KeyVault"), "empty", "Legacy only",
                "Deprecated flat fallback endpoint; prefer ArchLucid:FallbackLlm:Endpoints[n]:Endpoint.",
                ConfigKeyRequirementKind.None,
                ConfigurationKeyProductionProfileGuardKind.None,
                ConfigurationKeyDeprecationKind.DeprecatedBindingPath,
                "ArchLucid:FallbackLlm:Endpoints"),
            E("ArchLucid", "ArchLucid:FallbackLlm:ApiKey", M("env", "KeyVault"), "empty", "Legacy only",
                "Deprecated flat fallback API key; prefer ArchLucid:FallbackLlm:Endpoints[n]:ApiKey.",
                ConfigKeyRequirementKind.None,
                ConfigurationKeyProductionProfileGuardKind.None,
                ConfigurationKeyDeprecationKind.DeprecatedBindingPath,
                "ArchLucid:FallbackLlm:Endpoints"),
            E("ArchLucid", "ArchLucid:FallbackLlm:DeploymentName", M("appsettings", "env"), "empty", "Legacy only",
                "Deprecated flat fallback deployment name; prefer ArchLucid:FallbackLlm:Endpoints[n]:DeploymentName.",
                ConfigKeyRequirementKind.None,
                ConfigurationKeyProductionProfileGuardKind.None,
                ConfigurationKeyDeprecationKind.DeprecatedBindingPath,
                "ArchLucid:FallbackLlm:Endpoints"),
            E("ArchLucid", "ArchLucid:Agents:Faithfulness:EmbeddingEnabled", M("appsettings", "env"), "false", "—",
                "When true, compute embedding-based AgentResult→evidence cosine alignment for API telemetry and OTEL (staging-first).",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Agents:Faithfulness:EmbeddingMaxChunkUtf16Length", M("appsettings", "env"), "512",
                "Optional tuning",
                "UTF-16 chunk size for claim/evidence text passed to the embedding model (clamped by host post-configure).",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Agents:Faithfulness:EmbeddingChunkOverlapUtf16", M("appsettings", "env"), "64",
                "Optional tuning", "Chunk overlap for embedding faithfulness (clamped vs max chunk length).",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Explanation:Aggregate:FaithfulnessFallbackEnabled", M("appsettings", "env"),
                "true", "—", "Allow fallback when faithfulness is low.", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Explanation:Aggregate:MinSupportRatioToTrustLlmNarrative",
                M("appsettings", "env"), "0.2", "—", "Minimum support ratio to trust the LLM narrative block.",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:MermaidCli:Enabled", M("appsettings", "env"), "false", "—",
                "Optionally render Mermaid with external CLI.", ConfigKeyRequirementKind.None),
            E("AgentExecution", "AgentExecution:Mode", M("appsettings", "env"), "Simulator", "—",
                "Simulator (offline) or Real (calls Azure OpenAI) — see validation rules.",
                ConfigKeyRequirementKind.None, ConfigurationKeyProductionProfileGuardKind.SoftGuard),
            E("AgentExecution", "AgentExecution:CompletionClient", M("appsettings", "env"), "omit or Azure", "—",
                "Echo to skip real LLM; see AgentExecution rules.", ConfigKeyRequirementKind.None,
                ConfigurationKeyProductionProfileGuardKind.SoftGuard),
            E("AgentExecution", "AgentExecution:LlmCostEstimation:Enabled", M("appsettings", "env"), "true", "—",
                "Token cost heuristics for telemetry.", ConfigKeyRequirementKind.None),
            E("AgentExecution", "AgentExecution:LlmCostEstimation:InputUsdPerMillionTokens", M("appsettings", "env"),
                "0.5", "—", "Cost model input (USD per 1M tokens).", ConfigKeyRequirementKind.None),
            E("AgentExecution", "AgentExecution:LlmCostEstimation:OutputUsdPerMillionTokens", M("appsettings", "env"),
                "1.5", "—", "Cost model output (USD per 1M tokens).", ConfigKeyRequirementKind.None),
            E("AgentExecution", "AgentExecution:TraceStorage:BlobPersistenceTimeoutSeconds", M("appsettings", "env"),
                "30", "—", "Timeout for writing trace chunks to durable storage.", ConfigKeyRequirementKind.None),
            E("AgentExecution", "AgentExecution:ReferenceEvaluation:Enabled", M("appsettings", "env"), "false", "—",
                "Reference case evaluation off by default in template.", ConfigKeyRequirementKind.None),
            E("AgentExecution", "AgentExecution:ReferenceEvaluation:ReferenceCasesPath", M("appsettings", "env"),
                "empty", "When reference eval on", "Path to reference case fixtures.", ConfigKeyRequirementKind.None),
            E("AgentExecution", "AgentExecution:Resilience:MaxConcurrentHandlers", M("appsettings", "env"), "8", "—",
                "Parallel agent/LLM handler limit.", ConfigKeyRequirementKind.None),
            E("AgentExecution", "AgentExecution:Resilience:PerHandlerTimeoutSeconds", M("appsettings", "env"), "900",
                "—", "Per job timeout.", ConfigKeyRequirementKind.None),
            E("AgentExecution", "AgentExecution:Resilience:LlmCallMaxRetryAttempts", M("appsettings", "env"), "3", "—",
                "LLM call retries.", ConfigKeyRequirementKind.None),
            E("AgentExecution", "AgentExecution:Resilience:LlmCallBaseDelayMilliseconds", M("appsettings", "env"),
                "500", "—", "Exponential backoff base (LLM).", ConfigKeyRequirementKind.None),
            E("AgentExecution", "AgentExecution:Resilience:LlmCallMaxDelaySeconds", M("appsettings", "env"), "10", "—",
                "Maximum delay between LLM retries.", ConfigKeyRequirementKind.None),
            E("AgentExecution", "AgentExecution:SchemaValidation:EnforceOnParse", M("appsettings", "env"), "true",
                "—",
                "When true, invalid AgentResult JSON fails fast in AgentResultParser; Staging/Production ship true.",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:ContentSafety:Enabled", M("appsettings", "env"), "false", "—",
                "When false on non-production-like hosts, NullContentSafetyGuard applies; Production/Staging always register Azure guard.",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:ContentSafety:Endpoint", M("appsettings", "env", "KeyVault"), "empty",
                "Production or Staging host",
                "Azure AI Content Safety HTTPS endpoint (required for production-like hosts; see ContentSafetyRules).",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:ContentSafety:ApiKey", M("appsettings", "env", "KeyVault"), "empty",
                "Production or Staging host",
                "Content Safety API key (secret; required for production-like hosts).",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:ContentSafety:BlockSeverityThreshold", M("appsettings", "env"), "4", "—",
                "Minimum Azure text severity (0/2/4/6) that blocks; default 4 blocks high and highest.",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:ContentSafety:FailClosedOnSdkError", M("appsettings", "env"), "true", "—",
                "When true, SDK/network failures block analysis; Staging/Production templates and host post-configure enforce fail-closed.",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:ContentSafety:AllowNullGuardInDevelopment", M("appsettings", "env"), "true", "—",
                "Non-production-like only: allow NullContentSafetyGuard when Enabled is false.",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:ContentSafety:EvaluateCompletionPromptAndResponse", M("appsettings", "env"),
                "true", "—",
                "When true, ContentSafetyEnforcingAgentCompletionClient runs input/output checks on LLM traffic.",
                ConfigKeyRequirementKind.None),
            E("AzureOpenAI", "AzureOpenAI:Endpoint", M("appsettings", "env", "KeyVault", "AZURE_OPENAI__Endpoint"),
                "empty", "When Real and not Echo", "Azure OpenAI resource endpoint (HTTPS).",
                ConfigKeyRequirementKind.WhenRealLlmNotEcho),
            E("AzureOpenAI", "AzureOpenAI:ApiKey", M("env", "KeyVault", "AZURE_OPENAI__ApiKey"), "empty",
                "When Real and not Echo", "Client credential for the Azure OpenAI resource (never log).",
                ConfigKeyRequirementKind.WhenRealLlmNotEcho),
            E("AzureOpenAI", "AzureOpenAI:DeploymentName", M("env", "AZURE_OPENAI__DeploymentName"), "empty",
                "When Real and not Echo", "Chat/Completion deployment name in Azure OpenAI.",
                ConfigKeyRequirementKind.WhenRealLlmNotEcho),
            E("AzureOpenAI", "AzureOpenAI:MaxCompletionTokens", M("appsettings", "env"), "0 (4096 default)", "—",
                "Upper bound; 0 uses product default (see agents pipeline).", ConfigKeyRequirementKind.None),
            E("AzureOpenAI", "AzureOpenAI:UseJsonSchemaResponseFormat", M("appsettings", "env"), "false", "—",
                "When true, agent completions request json_schema structured output from SchemaValidation:AgentResultSchemaPath; HTTP 400 falls back to json_object mode.",
                ConfigKeyRequirementKind.None),
            E("LlmDailyTenantBudget", "LlmDailyTenantBudget:Enabled", M("appsettings", "env"), "false", "—",
                "Enforce daily LLM token cap per tenant.", ConfigKeyRequirementKind.None),
            E("LlmDailyTenantBudget", "LlmDailyTenantBudget:HardCutoffTokensPerUtcDay", M("appsettings", "env"),
                "2000000", "When cap on", "Hard token budget per calendar UTC day.", ConfigKeyRequirementKind.None),
            E("LlmDailyTenantBudget", "LlmDailyTenantBudget:WarnFraction", M("appsettings", "env"), "0.8",
                "When cap on", "Warn when consumption crosses this fraction of cap.", ConfigKeyRequirementKind.None),
            E("LlmDailyTenantBudget", "LlmDailyTenantBudget:AssumedMaxTotalTokensPerRequest", M("appsettings", "env"),
                "65536", "When cap on", "Heuristic for reservation math.", ConfigKeyRequirementKind.None),
            E("AgentPrompts", "AgentPrompts:Versions:topology", M("appsettings", "env"), "v2026-04", "—",
                "Prompt set version: topology pack.", ConfigKeyRequirementKind.None),
            E("AgentPrompts", "AgentPrompts:Versions:cost", M("appsettings", "env"), "v2026-04", "—",
                "Prompt set version: cost pack.", ConfigKeyRequirementKind.None),
            E("AgentPrompts", "AgentPrompts:Versions:compliance", M("appsettings", "env"), "v2026-04", "—",
                "Prompt set: compliance pack.", ConfigKeyRequirementKind.None),
            E("AgentPrompts", "AgentPrompts:Versions:critic", M("appsettings", "env"), "v2026-04", "—",
                "Prompt set: critic pack.", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Agents:StagedCriticEnabled", M("appsettings", "env"), "false", "—",
                "When true, RealAgentExecutor runs non-Critic agents first, then Critic, injecting a bounded summary evidence note.",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Agents:StagedCriticOverlapEnabled", M("appsettings", "env"), "false", "—",
                "When true with staged Critic, runs Critic concurrently with phase-1 agents when quality posture allows (blocked under PilotStrict enforce/block).",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Agents:Phase1MaxConcurrentHandlers", M("appsettings", "env"), "0", "—",
                "Optional phase-1 admission cap during staged overlap (0 = reserve one bulkhead slot for Critic).",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Llm:RedactReasoningTrace", M("appsettings", "env"), "false", "—",
                "When true, merge provider reasoning into AgentResult.ReasoningTrace then run IPromptRedactor.RedactAlways before persistence.",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Agents:SummaryMaxTotalChars", M("appsettings", "env"), "12000", "—",
                "Upper bound on staged prior-agents summary body (normalized after bind).", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Agents:SummaryPerAgentMaxChars", M("appsettings", "env"), "4000", "—",
                "Upper bound per agent section inside the staged summary.", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Agents:MaxClaimsPerAgentIncluded", M("appsettings", "env"), "8", "—",
                "Max claim lines excerpted per prior agent in the staged summary.", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Agents:MaxClaimLineChars", M("appsettings", "env"), "240", "—",
                "Max characters per claim excerpt after redaction.", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Agents:MaxFindingTitlesPerAgent", M("appsettings", "env"), "5", "—",
                "Max finding titles listed per prior agent in the staged summary.", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Agents:MaxFindingTitleChars", M("appsettings", "env"), "100", "—",
                "Max characters per finding title excerpt.", ConfigKeyRequirementKind.None),
            E("SchemaValidation", "SchemaValidation:AgentResultSchemaPath", M("appsettings", "content"), "schemas/...",
                "—", "On-disk path to the agent result JSON schema.", ConfigKeyRequirementKind.None),
            E("SchemaValidation", "SchemaValidation:GoldenManifestSchemaPath", M("appsettings", "content"),
                "schemas/...", "—", "Golden manifest JSON schema file.", ConfigKeyRequirementKind.None),
            E("SchemaValidation", "SchemaValidation:EnableDetailedErrors", M("appsettings", "env"), "true", "—",
                "Verbose schema errors in early validation (dev).", ConfigKeyRequirementKind.None),
        ]);
    }
}
