namespace ArchLucid.Core.Configuration;

public static partial class ConfigurationKeyCatalog
{
    private static void AddDataRetentionAndEmail(List<ConfigurationKeyEntry> entries)
    {
        entries.AddRange(
        [
            E("ArchLucid", "ArchLucid:Retention:FunnelEventsDays", M("appsettings", "env"), "0", "—",
                "Max age (days) for FirstTenantFunnel SQL rows before archival/purge; 0 falls through to ArchLucid:FirstTenantFunnelRetentionDays when set, else Telemetry:FirstTenantFunnel:ArchivalRetentionDays, else 90.",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:FirstTenantFunnelRetentionDays", M("appsettings", "env"), "(omit)", "—",
                "When > 0, max age (days) for dbo.FirstTenantFunnelEvents SQL purge/archive rows (overrides Retention:FunnelEventsDays chain).",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Retention:FunnelEventsHardDeleteWithoutBlobArchive", M("appsettings", "env"),
                "true", "—",
                "When true and blob storage is absent, aged funnel rows delete from SQL only (no cold archive).",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Notifications:TrialLifecycle:Owner", M("appsettings", "env"), "Hosted", "—",
                "Who runs trial notification emails for this tenant class.", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:InternalCrossTenantAnalytics:RollupJobEnabled", M("appsettings", "env"), "true", "—",
                "Leader-elected worker that writes dbo.InternalCrossTenantRollupDaily.", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:InternalCrossTenantAnalytics:RollupIntervalHours", M("appsettings", "env"), "24",
                "—", "Hours between rollup passes (UTC calendar day).", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:InternalCrossTenantAnalytics:PseudonymizationSalt", M("appsettings", "env", "KeyVault"),
                "empty", "When SQL rollups run",
                "HMAC key material for AnalyticsTenantKey (never store raw tenant ids in rollup tables).",
                ConfigKeyRequirementKind.None),
            E("LlmPromptRedaction", "LlmPromptRedaction:Enabled", M("appsettings", "env"), "true", "—",
                "Redact prompts in logging/traces.", ConfigKeyRequirementKind.None,
                ConfigurationKeyProductionProfileGuardKind.SoftGuard),
            E("LlmPromptRedaction", "LlmPromptRedaction:ReplacementToken", M("appsettings", "env"), "[REDACTED]", "—",
                "Replacement for redacted span.", ConfigKeyRequirementKind.None),
            E("Demo", "Demo:Enabled", M("appsettings", "env"), "false", "—", "In-product demo / synthetic paths.",
                ConfigKeyRequirementKind.None),
            E("Demo", "Demo:SeedOnStartup", M("appsettings", "env"), "false", "—",
                "Seeds the Contoso path when demo is on (see ops guide).", ConfigKeyRequirementKind.None),
            E("DeveloperExperience", "DeveloperExperience:EnableApiExplorer", M("appsettings", "env"), "false", "—",
                "Exposes extra OpenAPI/Scalar in non-prod (see security note).", ConfigKeyRequirementKind.None),
            E("DataConsistency", "DataConsistency:OrphanProbeEnabled", M("appsettings", "env"), "true", "—",
                "Background data consistency scan.", ConfigKeyRequirementKind.None),
            E("DataConsistency", "DataConsistency:OrphanProbeIntervalMinutes", M("appsettings", "env"), "60", "—",
                "Orphan scan cadence.", ConfigKeyRequirementKind.None),
            E("DataConsistency", "DataConsistency:Enforcement:Mode", M("appsettings", "env"), "Warn",
                "ArchLucid.Api: Alert",
                "Off | Warn | Alert | Quarantine (see `DataConsistencyEnforcementMode`); reference Api appsettings.Production.json and appsettings.Staging.json ship Alert for orphan paging.",
                ConfigKeyRequirementKind.None),
            E("DataConsistency", "DataConsistency:Enforcement:MaxRowsPerBatch", M("appsettings", "env"), "500",
                "When enforced", "Safer cap per remediation batch.", ConfigKeyRequirementKind.None),
            E("DataConsistency", "DataConsistency:Enforcement:AlertThreshold", M("appsettings", "env"), "1", "—",
                "Orphan count threshold to page operators.", ConfigKeyRequirementKind.None),
            E("DataConsistency", "DataConsistency:Enforcement:AutoQuarantine", M("appsettings", "env"), "false", "—",
                "If true, auto quarantine (must be off until approved).", ConfigKeyRequirementKind.None),
            E("DataArchival", "DataArchival:PurgeArchivedAgentExecutionTracesAfterDays", M("appsettings", "env"), "0", "—",
                "Hard-delete SQL agent execution traces soft-archived longer than N days; 0 disables (Cosmos uses TTL).",
                ConfigKeyRequirementKind.None),
            E("DataArchival", "DataArchival:PurgeArchivedAgentExecutionTracesBatchSize", M("appsettings", "env"), "500",
                "When trace purge on",
                "DELETE TOP batch size per iteration (validated 1–10000 when purge enabled).",
                ConfigKeyRequirementKind.None),
            E("DataArchival", "DataArchival:PurgeUncommittedRunsAfterDays", M("appsettings", "env"), "0", "—",
                "Hard-delete non-Committed dbo.Runs older than N days; 0 disables (worker DataArchival loop).",
                ConfigKeyRequirementKind.None),
            E("DataArchival", "DataArchival:PurgeUncommittedRunsBatchSize", M("appsettings", "env"), "500",
                "When uncommitted run purge on",
                "Batch size per dbo.Archival_PurgeStaleUncommittedRunsBatch call (validated 1–10000).",
                ConfigKeyRequirementKind.None),
            E("AzureExtractor", "AzureExtractor:AutoPull:Enabled", M("appsettings", "env"), "false", "—",
                "Leader-only background pull for Azure cost/ARM extractor snapshots (Tier-2; scaffold until ingest ships).",
                ConfigKeyRequirementKind.None),
            E("AzureExtractor", "AzureExtractor:AutoPull:IntervalMinutes", M("appsettings", "env"), "360", "—",
                "Cadence between pull attempts when enabled; clamped 15–10080 in hosted service.",
                ConfigKeyRequirementKind.None),
            E("AzureDevOps", "AzureDevOps:Enabled", M("appsettings", "env"), "false", "—",
                "Enables work-item / PR status integration.", ConfigKeyRequirementKind.None),
            E("AzureDevOps", "AzureDevOps:Organization", M("appsettings", "env", "KeyVault ref"), "empty", "If ADO on",
                "DevOps org name (non-secret, still presence-checked).", ConfigKeyRequirementKind.None),
            E("AzureDevOps", "AzureDevOps:Project", M("appsettings", "env"), "empty", "If ADO on",
                "Project in Azure DevOps.", ConfigKeyRequirementKind.None),
            E("AzureDevOps", "AzureDevOps:PersonalAccessToken", M("env", "KeyVault"), "empty", "If ADO on",
                "PAT for the integration (secret).", ConfigKeyRequirementKind.None),
            E("Serilog", "Serilog:MinimumLevel:Default", M("appsettings", "env"), "Information", "—",
                "Serilog default minimum (host logging).", ConfigKeyRequirementKind.None),
            E("Logging", "Logging:LogLevel:Default", M("appsettings", "env"), "Information", "—",
                "Microsoft logger default (framework).", ConfigKeyRequirementKind.None),
            E("Email", "Email:Provider", M("appsettings", "env"), "Noop", "—",
                "Noop, Smtp, or Azure Communication Services (see `Email` namespace).", ConfigKeyRequirementKind.None),
            E("Email", "Email:AzureCommunicationServicesEndpoint", M("env", "KeyVault"), "empty",
                "If ACS for email in prod",
                "Azure Communication Services **Email** resource endpoint (HTTPS) when that provider is selected (see validation).",
                ConfigKeyRequirementKind.WhenAcsEmail),
            E("Email", "Email:SupportInbox", M("appsettings", "env"), "support@archlucid.net", "—",
                "Inbox for operator Report problem intake notifications (`POST /v1/support/problem-reports`).",
                ConfigKeyRequirementKind.None),
        ]);
    }
}
