namespace ArchLucid.Core.Configuration;

public static partial class ConfigurationKeyCatalog
{
    private static void AddAuthenticationAndBilling(List<ConfigurationKeyEntry> entries)
    {
        entries.AddRange(
        [
            E("ArchLucidAuth", "ArchLucidAuth:Mode", M("appsettings", "env"), "ApiKey", "—",
                "Default auth story for the template (dev API key, etc.).", ConfigKeyRequirementKind.None,
                ConfigurationKeyProductionProfileGuardKind.DeveloperBypass),
            E("ArchLucidAuth", "ArchLucidAuth:Authority", M("appsettings", "env"), "empty", "When OIDC in use",
                "Identity provider authority (OIDC) when that mode is enabled.", ConfigKeyRequirementKind.None,
                ConfigurationKeyProductionProfileGuardKind.SoftGuard),
            E("ArchLucidAuth", "ArchLucidAuth:JwtSigningPublicKeyPemPath", M("appsettings", "env"), "empty",
                "Non-production JWT PEM path",
                "Local JWT validation PEM path — disallowed on ASP.NET Core Production / ARCHLUCID_ENVIRONMENT=Production.",
                ConfigKeyRequirementKind.None, ConfigurationKeyProductionProfileGuardKind.SoftGuard),
            E("ArchLucidAuth", "ArchLucidAuth:Audience", M("appsettings", "env"), "empty", "When OIDC in use",
                "Token audience (OIDC).", ConfigKeyRequirementKind.None),
            E("ArchLucidAuth", "ArchLucidAuth:DevUserId", M("appsettings", "env"), "dev-user", "—",
                "Principal id for the development loop.", ConfigKeyRequirementKind.None),
            E("ArchLucidAuth", "ArchLucidAuth:DevUserName", M("appsettings", "env"), "Developer", "—",
                "Display name in dev default principal.", ConfigKeyRequirementKind.None),
            E("ArchLucidAuth", "ArchLucidAuth:DevRole", M("appsettings", "env"), "Admin", "—",
                "Default role in dev (see security docs).", ConfigKeyRequirementKind.None),
            E("Trial", "Trial:Lifecycle:IntervalMinutes", M("appsettings", "env"), "360", "—",
                "Trial state machine / email tick interval.", ConfigKeyRequirementKind.None),
            E("Trial", "Trial:Lifecycle:ReadOnlyAfterExpireDays", M("appsettings", "env"), "7", "—",
                "Days after expiry before read-only state.", ConfigKeyRequirementKind.None),
            E("Trial", "Trial:Lifecycle:ExportOnlyAfterReadOnlyDays", M("appsettings", "env"), "30", "—",
                "Transition to export-only after read-only for this many days.", ConfigKeyRequirementKind.None),
            E("Trial", "Trial:Lifecycle:PurgeAfterExportOnlyDays", M("appsettings", "env"), "60", "—",
                "Hard delete delay after export-only (policy).", ConfigKeyRequirementKind.None),
            E("Trial", "Trial:Lifecycle:HardPurgeMaxRowsPerStatement", M("appsettings", "env"), "5000", "—",
                "Purge batch size (data retention job).", ConfigKeyRequirementKind.None),
            E("Auth", "Auth:Trial:ExternalIdTenantId", M("appsettings", "env"), "empty", "When trial IdP",
                "B2C / external tenant id mapping for self-service sign-up.", ConfigKeyRequirementKind.None),
            E("Auth", "Auth:Trial:LocalIdentity:JwtPrivateKeyPemPath", M("appsettings", "env"), "empty",
                "When local IdP", "PEM for HS/RS local JWT signing (path).", ConfigKeyRequirementKind.None),
            E("Auth", "Auth:Trial:LocalIdentity:JwtIssuer", M("appsettings", "env"), "empty", "When local IdP",
                "Local JWT issuer string.", ConfigKeyRequirementKind.None),
            E("Auth", "Auth:Trial:LocalIdentity:JwtAudience", M("appsettings", "env"), "empty", "When local IdP",
                "Local JWT audience.", ConfigKeyRequirementKind.None),
            E("Auth", "Auth:Trial:LocalIdentity:AccessTokenLifetimeMinutes", M("appsettings", "env"), "60", "—",
                "Access token TTL for local auth.", ConfigKeyRequirementKind.None),
            E("Auth", "Auth:EmailOtp:Enabled", M("appsettings", "env"), "false", "—",
                "Enables passwordless email OTP sign-in endpoints.", ConfigKeyRequirementKind.None),
            E("Auth", "Auth:EmailOtp:CodeLifetimeMinutes", M("appsettings", "env"), "10", "—",
                "OTP code expiration in minutes.", ConfigKeyRequirementKind.None),
            E("Auth", "Auth:EmailOtp:MaxVerificationAttemptsPerChallenge", M("appsettings", "env"), "5", "—",
                "Failed verification attempts before challenge invalidation.", ConfigKeyRequirementKind.None),
            E("Auth", "Auth:EmailOtp:MaxCodeRequestsPerEmailPerHour", M("appsettings", "env"), "5", "—",
                "OTP challenge requests allowed per email per hour.", ConfigKeyRequirementKind.None),
            E("Auth", "Auth:EmailOtp:MaxCodeRequestsPerIpPerHour", M("appsettings", "env"), "20", "—",
                "OTP challenge requests allowed per client IP per hour.", ConfigKeyRequirementKind.None),
            E("Auth", "Auth:EmailOtp:ResendCooldownSeconds", M("appsettings", "env"), "45", "—",
                "Minimum seconds between OTP sends for the same email.", ConfigKeyRequirementKind.None),
            E("Cors", "Cors:AllowedOrigins:0", M("appsettings", "env", "Cors__*"), "http://localhost:3000", "—",
                "First allowed origin; additional indices use 1,2,… in JSON.", ConfigKeyRequirementKind.None),
            E("RateLimiting", "RateLimiting:Registration:PermitLimit", M("appsettings", "env"), "5", "—",
                "Throttling: registration path.", ConfigKeyRequirementKind.None),
            E("RateLimiting", "RateLimiting:Registration:WindowMinutes", M("appsettings", "env"), "60", "—",
                "Registration throttling window.", ConfigKeyRequirementKind.None),
            E("RateLimiting", "RateLimiting:EmailOtp:PermitLimit", M("appsettings", "env"), "10", "—",
                "HTTP rate limit for email OTP endpoints per IP.", ConfigKeyRequirementKind.None),
            E("RateLimiting", "RateLimiting:EmailOtp:WindowMinutes", M("appsettings", "env"), "15", "—",
                "HTTP rate limit window for email OTP endpoints.", ConfigKeyRequirementKind.None),
            E("RateLimiting", "RateLimiting:FixedWindow:PermitLimit", M("appsettings", "env"), "60", "—",
                "Default fixed window permit cap.", ConfigKeyRequirementKind.None),
            E("RateLimiting", "RateLimiting:FixedWindow:WindowMinutes", M("appsettings", "env"), "1", "—",
                "Fixed window length in minutes.", ConfigKeyRequirementKind.None),
            E("RateLimiting", "RateLimiting:EvidenceBulkUpload:PermitLimit", M("appsettings", "env"), "20", "—",
                "Bulk multipart evidence uploads per tenant window (policy evidenceBulkUpload).", ConfigKeyRequirementKind.None),
            E("RateLimiting", "RateLimiting:EvidenceBulkUpload:WindowMinutes", M("appsettings", "env"), "1", "—",
                "Window for bulk evidence upload throttling.", ConfigKeyRequirementKind.None),
            E("RateLimiting", "RateLimiting:EvidenceBulkUpload:QueueLimit", M("appsettings", "env"), "0", "—",
                "Queued upload requests after permit exhaustion (normally 0).", ConfigKeyRequirementKind.None),
            E("RateLimiting", "RateLimiting:EvidenceBulkUpload:Anomaly:Enabled", M("appsettings", "env"), "true", "—",
                "Z-score spike detection for bulk evidence uploads.", ConfigKeyRequirementKind.None),
            E("RateLimiting", "RateLimiting:EvidenceBulkUpload:Anomaly:ZScoreThreshold", M("appsettings", "env"), "3", "—",
                "Observation-window sum must exceed mean*n + Z*σ*√n to flag an anomaly.", ConfigKeyRequirementKind.None),
            E("RateLimiting", "RateLimiting:EvidenceBulkUpload:Anomaly:StricterPermitLimitMultiplier", M("appsettings", "env"), "0.25", "—",
                "Permit cap multiplier while a partition is throttled after a spike.", ConfigKeyRequirementKind.None),
            E("RateLimiting", "RateLimiting:EvidenceBulkUpload:Anomaly:ThrottleDurationMinutes", M("appsettings", "env"), "15", "—",
                "Minutes of stricter rate limiting after anomaly detection.", ConfigKeyRequirementKind.None),
            E("RateLimiting", "RateLimiting:Replay:Light:PermitLimit", M("appsettings", "env"), "60", "—",
                "Light replay throttling (see policies).", ConfigKeyRequirementKind.None),
            E("RateLimiting", "RateLimiting:Replay:Light:WindowMinutes", M("appsettings", "env"), "1", "—",
                "Window for light replay throttling.", ConfigKeyRequirementKind.None),
            E("RateLimiting", "RateLimiting:Replay:Heavy:PermitLimit", M("appsettings", "env"), "15", "—",
                "Heavy replay throttling (expensive paths).", ConfigKeyRequirementKind.None),
            E("RateLimiting", "RateLimiting:Replay:Heavy:WindowMinutes", M("appsettings", "env"), "1", "—",
                "Window for heavy replay throttling.", ConfigKeyRequirementKind.None),
            E("Authentication", "Authentication:ApiKey:Enabled", M("appsettings", "env"), "false", "—",
                "Static X-Api-Key authentication — see `Authentication` startup rules for key material.",
                ConfigKeyRequirementKind.None, ConfigurationKeyProductionProfileGuardKind.SoftGuard),
            E("Authentication", "Authentication:ApiKey:DevelopmentBypassAll", M("appsettings", "env"), "false", "—",
                "DANGER: only for dev — bypass key checks. Must be off in production.", ConfigKeyRequirementKind.None,
                ConfigurationKeyProductionProfileGuardKind.DeveloperBypass),
            E("Authentication", "Authentication:ApiKey:AdminKey", M("env", "KeyVault", "user secrets"),
                "null in template", "If enabled (see custom rule: at least one of Admin/Read keys)",
                "High-privilege API key value when `Enabled` (never print in CLI; presence only).",
                ConfigKeyRequirementKind.None),
            E("Authentication", "Authentication:ApiKey:ReadOnlyKey", M("env", "KeyVault", "user secrets"),
                "null in template", "If enabled (see at least one key rule)",
                "Read-tier API key when `Enabled` (secret).", ConfigKeyRequirementKind.None),
            E("Billing", "Billing:Provider", M("appsettings", "env"), "Stripe", "—",
                "Billing integrator: Stripe, marketplace, etc.", ConfigKeyRequirementKind.None),
            E("Billing", "Billing:Stripe:SecretKey", M("env", "KeyVault"), "empty", "Production billing",
                "Stripe live/test secret; required for paid flows in production.",
                ConfigKeyRequirementKind.WhenProduction),
            E("Billing", "Billing:Stripe:CheckoutSecretKey", M("env", "KeyVault"), "empty",
                "When using Stripe checkout",
                "Optional restricted Stripe key (rk_) for Checkout Session creation; falls back to SecretKey.",
                ConfigKeyRequirementKind.None),
            E("Billing", "Billing:Stripe:WebhookSigningSecret", M("env", "KeyVault"), "empty", "Production",
                "Validates `Stripe-Signature` on the webhook path.", ConfigKeyRequirementKind.WhenProduction),
            E("Billing", "Billing:Stripe:SubscriptionWebhookSigningSecret", M("env", "KeyVault"), "empty",
                "When using Stripe subscriptions",
                "Signing secret for `POST /v1/billing/webhooks/stripe/subscriptions`; falls back to WebhookSigningSecret.",
                ConfigKeyRequirementKind.None),
            E("Billing", "Billing:Stripe:WalletWebhookSigningSecret", M("env", "KeyVault"), "empty",
                "When using Stripe wallet top-ups",
                "Signing secret for `POST /v1/billing/webhooks/stripe` (payment_intent.*); falls back to WebhookSigningSecret.",
                ConfigKeyRequirementKind.None),
            E("Billing", "Billing:Stripe:PublishableKey", M("appsettings", "env", "KeyVault"), "empty",
                "When checkout UI in app", "Publishable key (non-secret but still not echoed by CLI in raw form here).",
                ConfigKeyRequirementKind.None),
            E("Billing", "Billing:Stripe:PriceIdTeam", M("appsettings", "env"), "empty", "When using Stripe",
                "Default price for Team SKU.", ConfigKeyRequirementKind.None),
            E("Billing", "Billing:Stripe:PriceIdArchitect", M("appsettings", "env"), "empty", "When using Stripe",
                "Default price for Architect SKU.", ConfigKeyRequirementKind.None),
            E("Billing", "Billing:Stripe:PriceIdPro", M("appsettings", "env"), "empty", "When using Stripe",
                "Default price for Pro SKU.", ConfigKeyRequirementKind.None),
            E("Billing", "Billing:Stripe:PriceIdEnterprise", M("appsettings", "env"), "empty", "When using Stripe",
                "Default price for Enterprise SKU.", ConfigKeyRequirementKind.None),
            E("Billing", "Billing:AzureMarketplace:LandingPageUrl", M("appsettings", "env"), "empty",
                "When marketplace GA in prod", "Azure marketplace landing (production checks when GA).",
                ConfigKeyRequirementKind.WhenProduction),
            E("Billing", "Billing:AzureMarketplace:MarketplaceOfferId", M("appsettings", "env"), "empty",
                "When marketplace GA in prod", "Commercial marketplace offer id.",
                ConfigKeyRequirementKind.WhenProduction),
        ]);
    }
}
