namespace ArchLucid.Core.Configuration;

public static partial class ConfigurationKeyCatalog
{
    private static void AddHostingAndCore(List<ConfigurationKeyEntry> entries)
    {
        entries.AddRange(
        [
            E("Hosting", "Hosting:LogStartupConfigurationSummary", M("appsettings", "env"), "true", "—",
                "Log effective configuration on startup (host).", ConfigKeyRequirementKind.None),
            E("Hosting", "Hosting:Role", M("appsettings", "env"), "Combined", "—",
                "Api, Worker, or Combined host process.", ConfigKeyRequirementKind.None),
            E("ProductionValidation", "ProductionValidation:RequireTelemetryExport", M("appsettings", "env"), "false", "—",
                "When true on production-profile hosts, require OTLP, Application Insights, or Prometheus export.",
                ConfigKeyRequirementKind.None, ConfigurationKeyProductionProfileGuardKind.SoftGuard),
            E("Metering", "Metering:Enabled", M("appsettings", "env"), "false", "—", "Feature metering toggle.",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Secrets:Provider", M("appsettings", "env", "KeyVault ref"), "EnvironmentVariable",
                "—", "How secrets (connection strings, API keys) are loaded.", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Secrets:KeyVaultUri", M("appsettings", "env", "KeyVault"), "empty",
                "If Key Vault routing", "Azure Key Vault base URI when the secrets provider needs it.",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:Secrets:KeyVaultCacheSeconds", M("appsettings", "env"), "300", "—",
                "Secret cache duration for Key Vault access.", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:StorageProvider", M("appsettings", "env"), "Sql", "—",
                "InMemory (tests) or Sql; unset defaults to Sql in product rules.", ConfigKeyRequirementKind.None),
            E("ConnectionStrings", "ConnectionStrings:ArchLucid", M("appsettings", "env", "KeyVault", "user secrets"),
                "see default dev", "When SQL is active",
                "Primary SQL connection string (required when using Sql storage).",
                ConfigKeyRequirementKind.WhenDefaultSqlStorage),
            E("ArchLucid", "ArchLucid:PublicSite:BaseUrl", M("appsettings", "env"), "https://archlucid.net", "—",
                "Public marketing / operator link base for emails and exports.", ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:KnowledgeGraph:ProjectionCache:Backend", M("appsettings", "env"), "Memory", "—",
                "Memory (per-process IMemoryCache) vs Distributed (IDistributedCache / Redis via host composition).",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:KnowledgeGraph:ProjectionCache:RedisConnectionString", M("appsettings", "env"),
                "empty", "Distributed Backend",
                "Optional Redis connection for projection cache; falls back to LLM / hot-path Redis when unset.",
                ConfigKeyRequirementKind.None),
            E("ArchLucid", "ArchLucid:KnowledgeGraph:ProjectionCache:AbsoluteExpirationSeconds", M("appsettings", "env"),
                "300", "Enabled projection cache",
                "TTL (seconds) for cached graph snapshot projections.",
                ConfigKeyRequirementKind.None),
            E("CosmosDb", "CosmosDb:ConnectionString", M("appsettings", "env", "KeyVault"), "empty",
                "When using Cosmos", "Optional Cosmos connection when the deployment uses it.",
                ConfigKeyRequirementKind.None),
            E("CosmosDb", "CosmosDb:DatabaseName", M("appsettings", "env"), "ArchLucid", "—",
                "Cosmos database name when enabled.", ConfigKeyRequirementKind.None),
            E("CosmosDb", "CosmosDb:GraphSnapshotsEnabled", M("appsettings", "env"), "false", "—",
                "Store graph snapshots in Cosmos when enabled.", ConfigKeyRequirementKind.None),
            E("CosmosDb", "CosmosDb:AgentTracesEnabled", M("appsettings", "env"), "false", "—",
                "Store agent traces in Cosmos when enabled.", ConfigKeyRequirementKind.None),
            E("CosmosDb", "CosmosDb:AuditEventsEnabled", M("appsettings", "env"), "false", "—",
                "Stream audit to Cosmos if configured.", ConfigKeyRequirementKind.None),
            E("HotPathCache", "HotPathCache:Enabled", M("appsettings", "env"), "true", "—", "Hot path cache on/off.",
                ConfigKeyRequirementKind.None),
            E("HotPathCache", "HotPathCache:Provider", M("appsettings", "env"), "Auto", "—",
                "Cache backend selection (e.g. Redis, memory, auto).", ConfigKeyRequirementKind.None),
            E("HotPathCache", "HotPathCache:ExpectedApiReplicaCount", M("appsettings", "env"), "1", "—",
                "Expected number of API replicas (cache coherency hint).", ConfigKeyRequirementKind.None),
            E("HotPathCache", "HotPathCache:AbsoluteExpirationSeconds", M("appsettings", "env"), "60", "—",
                "Absolute cache TTL in seconds for hot path entries.", ConfigKeyRequirementKind.None),
            E("HotPathCache", "HotPathCache:RedisConnectionString", M("appsettings", "env", "KeyVault"), "empty",
                "When using Redis for cache", "Redis when Provider selects Redis/Auto+Redis discoverable.",
                ConfigKeyRequirementKind.None),
            E("Observability", "Observability:Otlp:Enabled", M("appsettings", "env"), "false", "—",
                "Export OpenTelemetry to OTLP collector (host).", ConfigKeyRequirementKind.None,
                ConfigurationKeyProductionProfileGuardKind.SoftGuard),
            E("Observability", "Observability:Otlp:Endpoint", M("env", "KeyVault"), "empty", "If OTLP enabled",
                "OTLP base URL; required when `Observability:Otlp:Enabled` is true.",
                ConfigKeyRequirementKind.WhenOtlpEnabled, ConfigurationKeyProductionProfileGuardKind.SoftGuard),
            E("Observability", "Observability:AzureMonitor:ApplicationInsightsConnectionString", M("env", "KeyVault"),
                "empty", "When App Insights export",
                "Application Insights connection string under Observability:AzureMonitor (host OTel wiring).",
                ConfigKeyRequirementKind.None, ConfigurationKeyProductionProfileGuardKind.SoftGuard),
            E("Observability", "Observability:Prometheus:Enabled", M("appsettings", "env"), "false", "—",
                "Expose Prometheus scrape endpoint on /metrics (trusted network only).", ConfigKeyRequirementKind.None,
                ConfigurationKeyProductionProfileGuardKind.SoftGuard),
            E("ApplicationInsights", "ApplicationInsights:ConnectionString", M("env", "KeyVault"), "empty",
                "When telemetry export",
                "Application Insights connection string (appsettings or Key Vault reference).",
                ConfigKeyRequirementKind.None, ConfigurationKeyProductionProfileGuardKind.SoftGuard),
            E("Environment", "APPLICATIONINSIGHTS_CONNECTION_STRING", M("env"), "empty", "When telemetry export",
                "Azure Application Insights connection string env var (preferred on Azure App Service).",
                ConfigKeyRequirementKind.None, ConfigurationKeyProductionProfileGuardKind.SoftGuard),
        ]);
    }
}
