global using ArchLucid.Contracts.Governance.ComplianceDrift;
global using ArchLucid.Contracts.Governance.PolicyPacks;
global using ArchLucid.Contracts.Governance.Resolution;

global using ComplianceDriftFindingsBucketCounts = ArchLucid.Contracts.Governance.ComplianceDrift.ComplianceDriftFindingsBucketCounts;
global using ComplianceDriftFindingsTrendAuditTypes = ArchLucid.Core.Governance.ComplianceDrift.ComplianceDriftFindingsTrendAuditTypes;
global using ComplianceRulePack = ArchLucid.Contracts.Compliance.ComplianceRulePack;
global using ComplianceRulePackGovernanceFilter = ArchLucid.Core.Governance.PolicyPacks.ComplianceRulePackGovernanceFilter;
global using GovernanceScopeLevel = ArchLucid.Contracts.Governance.Resolution.GovernanceScopeLevel;
global using IComplianceDriftFindingsTrendReader = ArchLucid.Core.Persistence.Ports.IComplianceDriftFindingsTrendReader;
global using IEffectiveGovernanceLoader = ArchLucid.Core.Persistence.Ports.IEffectiveGovernanceLoader;
global using IPolicyPackAssignmentRepository = ArchLucid.Core.Persistence.Ports.IPolicyPackAssignmentRepository;
global using IPolicyPackCatalogRepository = ArchLucid.Core.Persistence.Ports.IPolicyPackCatalogRepository;
global using IPolicyPackChangeLogRepository = ArchLucid.Core.Persistence.Ports.IPolicyPackChangeLogRepository;
global using IPolicyPackRepository = ArchLucid.Core.Persistence.Ports.IPolicyPackRepository;
global using IPolicyPackVersionRepository = ArchLucid.Core.Persistence.Ports.IPolicyPackVersionRepository;
global using PolicyPack = ArchLucid.Contracts.Governance.PolicyPacks.PolicyPack;
global using PolicyPackAssignment = ArchLucid.Contracts.Governance.PolicyPacks.PolicyPackAssignment;
global using PolicyPackCatalogEntryDetail = ArchLucid.Contracts.Governance.PolicyPacks.PolicyPackCatalogEntryDetail;
global using PolicyPackCatalogListItem = ArchLucid.Contracts.Governance.PolicyPacks.PolicyPackCatalogListItem;
global using PolicyPackGovernanceFilter = ArchLucid.Core.Governance.PolicyPacks.PolicyPackGovernanceFilter;
global using PolicyPackStatus = ArchLucid.Contracts.Governance.PolicyPacks.PolicyPackStatus;
global using PolicyPackType = ArchLucid.Contracts.Governance.PolicyPacks.PolicyPackType;
global using PolicyPackVersion = ArchLucid.Contracts.Governance.PolicyPacks.PolicyPackVersion;
global using IComplianceRulePackLoader = ArchLucid.Core.Persistence.Ports.IComplianceRulePackLoader;
global using IComplianceRulePackProvider = ArchLucid.Core.Persistence.Ports.IComplianceRulePackProvider;
global using TenantCuratedComplianceRulePackMerger = ArchLucid.Core.Governance.PolicyPacks.CuratedRules.TenantCuratedComplianceRulePackMerger;
