global using ArchLucid.Contracts.Advisory.Delivery;
global using ArchLucid.Contracts.Advisory.Learning;
global using ArchLucid.Contracts.Advisory.Scheduling;
global using ArchLucid.Contracts.Advisory.Workflow;

global using AdvisoryScanExecution = ArchLucid.Contracts.Advisory.Scheduling.AdvisoryScanExecution;
global using AdvisoryScanSchedule = ArchLucid.Contracts.Advisory.Scheduling.AdvisoryScanSchedule;
global using ArchitectureDigest = ArchLucid.Contracts.Advisory.Scheduling.ArchitectureDigest;
global using DigestDeliveryAttempt = ArchLucid.Contracts.Advisory.Delivery.DigestDeliveryAttempt;
global using DigestDeliveryChannelType = ArchLucid.Contracts.Advisory.Delivery.DigestDeliveryChannelType;
global using DigestDeliveryPayload = ArchLucid.Contracts.Advisory.Delivery.DigestDeliveryPayload;
global using DigestDeliveryStatus = ArchLucid.Contracts.Advisory.Delivery.DigestDeliveryStatus;
global using DigestSubscription = ArchLucid.Contracts.Advisory.Delivery.DigestSubscription;
global using IAdvisoryScanExecutionRepository = ArchLucid.Core.Persistence.Ports.IAdvisoryScanExecutionRepository;
global using IAdvisoryScanScheduleRepository = ArchLucid.Core.Persistence.Ports.IAdvisoryScanScheduleRepository;
global using IArchitectureDigestRepository = ArchLucid.Core.Persistence.Ports.IArchitectureDigestRepository;
global using IDigestDeliveryAttemptRepository = ArchLucid.Core.Persistence.Ports.IDigestDeliveryAttemptRepository;
global using IDigestDeliveryChannel = ArchLucid.Core.Persistence.Ports.IDigestDeliveryChannel;
global using IDigestDeliveryDispatcher = ArchLucid.Core.Persistence.Ports.IDigestDeliveryDispatcher;
global using IDigestSubscriptionRepository = ArchLucid.Core.Persistence.Ports.IDigestSubscriptionRepository;
global using IRecommendationFeedbackAnalyzer = ArchLucid.Core.Persistence.Ports.IRecommendationFeedbackAnalyzer;
global using IRecommendationLearningProfileRepository = ArchLucid.Core.Persistence.Ports.IRecommendationLearningProfileRepository;
global using IRecommendationRepository = ArchLucid.Core.Persistence.Ports.IRecommendationRepository;
global using IRecommendationWorkflowService = ArchLucid.Core.Persistence.Ports.IRecommendationWorkflowService;
global using ImprovementPlan = ArchLucid.Contracts.Advisory.Models.ImprovementPlan;
global using ImprovementRecommendation = ArchLucid.Contracts.Advisory.Models.ImprovementRecommendation;
global using RecommendationActionRequest = ArchLucid.Contracts.Advisory.Workflow.RecommendationActionRequest;
global using RecommendationActionType = ArchLucid.Contracts.Advisory.Workflow.RecommendationActionType;
global using RecommendationLearningProfile = ArchLucid.Contracts.Advisory.Learning.RecommendationLearningProfile;
global using RecommendationOutcomeStats = ArchLucid.Contracts.Advisory.Learning.RecommendationOutcomeStats;
global using IImprovementAdvisorService = ArchLucid.Core.Persistence.Ports.IImprovementAdvisorService;
global using IRecommendationLearningService = ArchLucid.Core.Persistence.Ports.IRecommendationLearningService;
global using RecommendationRecord = ArchLucid.Contracts.Advisory.Workflow.RecommendationRecord;
global using RecommendationStatus = ArchLucid.Contracts.Advisory.Workflow.RecommendationStatus;
