namespace ArchLucid.Contracts.Governance;

/// <summary>AI-generated curated rule JSON plus mandatory human-review disclaimer.</summary>
public sealed class DraftPolicyPackRuleResponse
{
    public const string DefaultDisclaimer =
        "This draft was generated by AI and requires human review before activation. "
        + "Validate severity, evidence hints, and framework mappings against your governance program.";

    public string Disclaimer
    {
        get;
        set;
    } = DefaultDisclaimer;

    /// <summary>Single curated rule object JSON (not a full pack document).</summary>
    public string DraftRuleJson
    {
        get;
        set;
    } = "";
}
