namespace ArchLucid.ArtifactSynthesis.Layout;

/// <summary>
/// Formats inventory node labels for content-sized diagram canvases. Full names remain in
/// accessibility titles and outline tables; this type only shapes on-canvas text.
/// </summary>
public static class DiagramInventoryNodeCanvasLabelFormatter
{
    public static IReadOnlyList<string> FormatLines(
        string resourceName,
        IReadOnlyList<string> peerResourceNames,
        DiagramForestLayoutOptions options,
        int? textColumnMaxWidthPx = null)
    {
        if (string.IsNullOrWhiteSpace(resourceName))
        {
            return [string.Empty];
        }

        string trimmed = resourceName.Trim();
        int maxWidthPx = textColumnMaxWidthPx ?? ResolveInnerLabelWidthPx(options);
        int maxChars = ResolveMaxChars(maxWidthPx, options.CharacterWidth);

        if (trimmed.Length <= maxChars)
        {
            return [trimmed];
        }

        if (DiagramInventoryAutoGeneratedResourceName.LooksAutoGenerated(trimmed))
        {
            return [TruncateAutoGenerated(trimmed, peerResourceNames, maxChars)];
        }

        return DiagramLabelLineWrapper.Wrap(trimmed, maxWidthPx, options.CharacterWidth);
    }

    public static int ResolveInnerLabelWidthPx(DiagramForestLayoutOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);

        return Math.Max(
            48,
            options.MaxNodeWidth - (options.NodePaddingX * 2) - options.PictogramSize - options.IconToLabelGap);
    }

    private static int ResolveMaxChars(int maxWidthPx, double characterWidth)
    {
        return Math.Max(8, (int)Math.Floor(maxWidthPx / Math.Max(1.0, characterWidth)));
    }

    private static string TruncateAutoGenerated(
        string resourceName,
        IReadOnlyList<string> peerResourceNames,
        int maxChars)
    {
        int minimumUniquePrefixLength = ComputeMinimumUniquePrefixLength(resourceName, peerResourceNames);

        for (int length = resourceName.Length; length >= minimumUniquePrefixLength; length--)
        {
            string candidate = length >= resourceName.Length
                ? resourceName
                : $"{resourceName[..length]}...";

            if (candidate.Length <= maxChars)
            {
                return candidate;
            }
        }

        int keepLength = Math.Max(minimumUniquePrefixLength, Math.Min(resourceName.Length, maxChars - 3));

        return $"{resourceName[..keepLength]}...";
    }

    private static int ComputeMinimumUniquePrefixLength(
        string resourceName,
        IReadOnlyList<string> peerResourceNames)
    {
        int minimumUnique = resourceName.Length;

        foreach (string peer in peerResourceNames)
        {
            if (string.Equals(peer, resourceName, StringComparison.Ordinal))
            {
                continue;
            }

            int commonPrefixLength = CommonPrefixLength(resourceName, peer);
            minimumUnique = Math.Min(minimumUnique, commonPrefixLength + 1);
        }

        return Math.Max(1, minimumUnique);
    }

    private static int CommonPrefixLength(string left, string right)
    {
        int limit = Math.Min(left.Length, right.Length);
        int index = 0;

        while (index < limit && left[index] == right[index])
        {
            index++;
        }

        return index;
    }
}
