using System.Text.RegularExpressions;

namespace ArchLucid.ArtifactSynthesis.Layout;

/// <summary>
/// Heuristic detector for Azure-style auto-generated resource names on diagram canvases.
/// </summary>
public static partial class DiagramInventoryAutoGeneratedResourceName
{
    [GeneratedRegex(@"-\d{1,5}$", RegexOptions.CultureInvariant)]
    private static partial Regex TrailingHyphenDigits();

    [GeneratedRegex(
        @"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        RegexOptions.CultureInvariant)]
    private static partial Regex GuidSegment();

    [GeneratedRegex(@"(?<![0-9a-fA-F])[0-9a-fA-F]{12,}(?![0-9a-fA-F])", RegexOptions.CultureInvariant)]
    private static partial Regex LongHexRun();

    public static bool LooksAutoGenerated(string resourceName)
    {
        if (string.IsNullOrWhiteSpace(resourceName))
        {
            return false;
        }

        string trimmed = resourceName.Trim();

        if (GuidSegment().IsMatch(trimmed))
        {
            return true;
        }

        if (LongHexRun().IsMatch(trimmed))
        {
            return true;
        }

        if (TrailingHyphenDigits().IsMatch(trimmed))
        {
            return true;
        }

        return false;
    }
}
